### ISSUE TITLE
Documentation redirect should open new tab

### ISSUE THREAD

**Issue by RajGM** [keploy/keploy#100]
On page http://localhost:8081/testlist/ 
We have hyperlink: [For help, please visit documentation](https://github.com/keploy/keploy)

It should open the tab in new windows, as opposed to current window.

**Comment by himanshu007-creator** [comment]
Hey!
i would like to work on this issue

**Comment by nehagup** [comment]
@himanshu007-creator please feel free to take this up. 👍

**Comment by Akshit42-hue** [comment]
Hey @RajGM Can I work on this issue

**Comment by nehagup** [comment]
Hey @Akshit42-hue Yes!

**Comment by Akshit42-hue** [comment]
Hey @nehagup can you please tell me in which file I need to change, I have been searching in keploy-ui repo but can't able to need find any leads can you please provide any leads

**Comment by nehagup** [comment]
Hey @Akshit42-hue This is present in a global component. 
You can find it https://github.com/keploy/ui/blob/e4e7ee48b3071e3a5f14dd9d468c7c37c6b1f057/src/components/global/empty.tsx#L46 

Hope this helps! :)

**Comment by Akshit42-hue** [comment]
Thanks for the lead @nehagup

**Comment by Akshit42-hue** [comment]
Hey @nehagup, can you please shift this issue in keploy-ui so I can raise PR

**Comment by nehagup** [comment]
> Hey @nehagup, can you please shift this issue in keploy-ui so I can raise PR

Hi @Akshit42-hue There are 2 ways we can go about this : 
1. Create a replica issue to the UI Repo and add the PR. 
2. Add the PR to UI repo and link this issue. 

Let me know if you'd need any help :)

**Comment by Akshit42-hue** [comment]
1st option sounds good to me

**Comment by nehagup** [comment]
Linked to https://github.com/keploy/ui/issues/42
