### ISSUE TITLE
[feature]: change .keploy-config to .keploy

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#1001]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

There was a proposal to change name of keploy-config to just keploy. Detailed discussion should be done and implemented

### Why should this be worked on?

code quality

### Repository

keploy

**Comment by sambhavgupta0705** [comment]
@charankamarapu can I work on this issue??

**Comment by charankamarapu** [comment]
It is already assigned to one of the maintainers.

**Comment by officialasishkumar** [comment]
Is this issues still need to be worked on? 

If yes, then are you referring keploy-config to the config file we geneate with the `keploy generate-config` command?

**Comment by PranshuSrivastava** [comment]
Done [here](https://github.com/keploy/keploy/pull/1203)
