### ISSUE TITLE
[feature]: add debugger guide for keploy in dev guide and keploy repo

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#1002]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Developer always find it difficult to debug Keploy . Need proper debugger guide.

### Why should this be worked on?

customer enhancement

### Repository

keploy

**Comment by charankamarapu** [comment]
Like in vs code we have to write a launch.json for running keploy in debugger mode. We need better document it and show it in dev guide.

**Comment by 9520prashant** [comment]
> Like in vs code we have to write a launch.json for running keploy in debugger mode. We need better document it and show it in dev guide.

Ok

**Comment by AkashKumar7902** [comment]
Hey @charankamarapu 
Is anyone actively working on this issue ?

**Comment by charankamarapu** [comment]
This issue is open . This guide should be in a section of dev guide in keploy website.
