### ISSUE TITLE
[bug]: Incomplete data in recordTestAndMocks event

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We don't send mocks in recordTestAndMocks, need to send mocks too. But we need a connection between mocks and testcases to complete this task.

### Steps to reproduce

1. Use keploy

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by shivamsouravjha** [comment]
Seems like recordTestAndMocks has been removed, closing the issue, feel free to reopen if issue is still relevant
