### ISSUE TITLE
[feature]: add more sample apps using postgreSql as their dependency 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1013]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Currently there are only 2 samples app one in golang and other in Java which uses postgres as their database 
- We can add few samples for Python as well Javascript (Node Js ) as well , to showcase the keployV2 capabilities to the user .

### Why should this be worked on?

This will help user to try out samples related to postgres as their main db , and will give a wide range of samples to choose upon !

### Repository

keploy

**Comment by AKACHI-4** [comment]
hey @Sarthak160 can I work on this issue under hf'23 .. can u elaborate it more..

**Comment by Sarthak160** [comment]
Hey @AKACHI-4 , We have some sample repo for different languages to showcase the capabilities of keploy like record and replay. These are simple APIs which are integrated with keploy and have some instructions to capture and test the recorded testcases. Currently for postgres we have only for [Java](https://github.com/keploy/samples-java) and [Golang](https://github.com/keploy/samples-go/tree/main/echo-sql) . So you can contribute to https://github.com/keploy/samples-python and https://github.com/keploy/samples-typescript to showcase the same

**Comment by 0xVikasRushi** [comment]
Hello @Sarthak160!

I've been working on this issue and using typescript + postgres + typeorm (progress- [0xVikasRushi:samples-typescript](https://github.com/0xVikasRushi/samples-typescript))

![image](https://github.com/keploy/keploy/assets/88543171/7862a209-f561-472f-97c2-10e2e9d611b1)

**locally API works fine with a Docker PostgreSQL instance.** 


However, when deploying with Keploy,
```
$ docker compose up -d
$ docker build -t postgresstypeorm:0.1 .
$ docker run -p 3000:3000 --name postgresRestApiTest --network keploy-network postgresstypeorm:0.1
```

![image](https://github.com/keploy/keploy/assets/88543171/2dac9a35-db66-4784-9b8e-bcd26165ad25)
### I'm encountering  this error and it seems to be related to  configuration related to  [postgres DockerFile](https://github.com/0xVikasRushi/samples-typescript/blob/main/postgres-typeorm/Dockerfile).

**Comment by 0xVikasRushi** [comment]
Hi @Sarthak160. 


i have been working on postgres + typescript with typeORM and build REST API. currently test are getting recorded with keploy
![image](https://github.com/keploy/keploy/assets/88543171/ecafdb47-993f-49e6-a826-994602c454f5)


but I'm not sure why running test case are getting failed 

Code - [0xVikasRushi:main](https://github.com/0xVikasRushi/samples-typescript)


![image](https://github.com/keploy/keploy/assets/88543171/0d7cf3be-9082-43f0-bd10-0e9cab9aefb1)

**Comment by Sonichigo** [comment]
@Sarthak160 can you help @0xVikasRushi ?

**Comment by Sarthak160** [comment]
Yes @Sonichigo trying to replicate the same issue in my local environmet

**Comment by SohamRatnaparkhi** [comment]
> Hey @AKACHI-4 , We have some sample repo for different languages to showcase the capabilities of keploy like record and replay. These are simple APIs which are integrated with keploy and have some instructions to capture and test the recorded testcases. Currently for postgres we have only for [Java](https://github.com/keploy/samples-java) and [Golang](https://github.com/keploy/samples-go/tree/main/echo-sql?rgh-link-date=2023-10-14T19%3A08%3A08Z) . So you can contribute to [keploy/samples-python](https://github.com/keploy/samples-python) and [keploy/samples-typescript](https://github.com/keploy/samples-typescript) to showcase the same

Hey @Sarthak160 
Can should I add REST API with following tools:
1. Nest JS (for backend) + Typescript
2. Prisma as ORM
3. PostgreSQL as DB

in the [keploy/samples-typescript](https://github.com/keploy/samples-typescript)  to showcase the working of Keploy with these tools?

Thank you!

**Comment by Sarthak160** [comment]
@SohamRatnaparkhi Yes, sure !
