### ISSUE TITLE
[chore]: rename the container in docker-compose

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#102]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Rename the container in the docker-compose file from `web1` to `keploy`

### Why should this be worked on?

`web1` is not the apt name

**Comment by EdwinWalela** [comment]
I would like to work on this if noone has picked it yet. 

Should the container be renamed on debug and dev docker-compose files as well?

**Comment by nehagup** [comment]
@EdwinWalela Sure, you can take this up. Yes, changing the same in debug and dev docker-compose will be a good idea as well! 😄
