### ISSUE TITLE
[feature]: Nest.JS + PostgreSQL integration example

### ISSUE THREAD

**Issue by SohamRatnaparkhi** [keploy/keploy#1021]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

As stated in #1013 , there is a need of samples using TypeScript and PostgreSQL REST API apps to show Keploy integration with the tech-stack, I can add a simple CRUD app in [keploy/samples-typescript](https://github.com/keploy/samples-typescript) and then show integration of testcases using Keploy.
I am planning to use the following tech-stack:
- Nest JS + Typescript for backend backbone
- PostgreSQL as DB
- Prisma as ORM

### Why should this be worked on?

Currently the repository has no examples using Nest JS along with PostgrSQL as the database to show Keploy test integration. 

### Repository

samples-typescript

**Comment by Sonichigo** [comment]
Hey @SohamRatnaparkhi !! Any progress that you can share regarding the issue ?

**Comment by SohamRatnaparkhi** [comment]
Hi @Sonichigo 
I have drafted a PR for it with all the code. Actually, I am facing a problem while Keploy record. 
PR - [link](https://github.com/keploy/samples-typescript/pull/25)

Attached below are screenshots and logs related to the problem I am facing.

![image](https://github.com/keploy/keploy/assets/92905626/ebd92e25-7e3b-45b0-ab1c-3ab4ef13a3e3)
![image](https://github.com/keploy/keploy/assets/92905626/9ee9e25b-10e2-4989-94b4-57cf1f6ad2c8)
![image](https://github.com/keploy/keploy/assets/92905626/154ee3cc-4b01-400e-bcac-23be57ee5c24)

How to proceed further?
Thank you!

**Comment by Sonichigo** [comment]
@Sarthak160 can you help out @SohamRatnaparkhi ?

**Comment by gouravkrosx** [comment]
@SohamRatnaparkhi I've tried replicating your issue and getting it only when keploy-network is not present locally. Can you please try it once again? since you have got the keploy-network now.

**Comment by SohamRatnaparkhi** [comment]
> @SohamRatnaparkhi I've tried replicating your issue and getting it only when keploy-network is not present locally. Can you please try it once again? since you have got the keploy-network now.

Tried it.
Facing the same issue.

**Comment by charankamarapu** [comment]
You can confirm if you have the keploy-network using this command `docker network ls`. Can you confirm it once again because this error will never occur when keploy-network is present..?

**Comment by SohamRatnaparkhi** [comment]
> @SohamRatnaparkhi You can confirm if you have the keploy-network using this command `docker network ls`. Can you confirm it once again because this error will never occur when keploy-network is present..?

Yep. Checked it.
I'm having keploy network.
![image](https://github.com/keploy/keploy/assets/92905626/1689d5a4-1d0a-4464-9b9d-4d6b43441dae)

**Comment by charankamarapu** [comment]
Can you mentioned the alias that is used for keploy..?
