### ISSUE TITLE
[bug]: add correct version in sentry

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#1032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently a hardcoded version is injected into telemetry . Need to inject correct keploy version

### Steps to reproduce

1. View telemetry events

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by EraKin575** [comment]
Please assign this to me!

**Comment by AniketNS** [comment]
Hey @charankamarapu, Can I work on this issue?

**Comment by PranshuSrivastava** [comment]
Hey @AniketNS, this issue was urgent so it was assigned to me. Please check if the issue is not assigned to anyone before asking to work on it.

**Comment by AniketNS** [comment]
Sure @PranshuSrivastava. Thanks for the advice.
