### ISSUE TITLE
[feature]: move duplicate functions from different parser into single utility file 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1033]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Since keploy V2 has different parser for different protocols , they also contain some utility function such as - `func JaccardSimilarity`, `func CreateShingles`, `func AdaptiveK` etc .  which are exact duplicates of each other . As they are implemented in a generic way . 
- So instead of them keeping them int individual packages , them can be moved to common utils package inside proxy package, i.e - `util/util.go` .

### Why should this be worked on?

This can be done to improve the code quality of the keploy codebase so that future contributors not face any issues .
It also removes repetitive code which is not a good practice . 

### Repository

keploy

**Comment by Anushka-Bhowmick** [comment]
can i be assigned this issue?

**Comment by EraKin575** [comment]
@Sarthak160 please review the PR
