### ISSUE TITLE
[docs]: update macOS documentation for changing alias

### ISSUE THREAD

**Issue by 0xVikasRushi** [keploy/keploy#1037]
## Issue Description

When using the alias created during the macOS installation, as described in the [installation documentation](https://keploy.io/docs/server/macos/installation/) on the Keploy website, I encountered an issue. The alias, as currently provided, does not include the `--pull always` flag. Consequently, users do not automatically receive the latest version of Keploy when utilizing the provided alias.

![Screenshot](https://github.com/keploy/keploy/assets/88543171/eca3e99c-18ac-4488-a38c-7a4ac392f220)

**Suggested Fix**

To ensure that macOS users consistently obtain the latest version of Keploy, by adding the `--pull always` flag to the alias in the documentation. 

### Where is this stated?

<img width="841" alt="Screenshot 2023-10-21 at 11 46 07 AM" src="https://github.com/keploy/keploy/assets/88543171/bf47f217-668e-4625-98b4-fec5f2dbc988">

### Repository

docs

**Comment by Sekhar-Kumar-Dash** [comment]
@0xVikasRushi  please assignme this issue
