### ISSUE TITLE
[feature]: Move server to sdk communication to gRPC

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#104]
### Is there an existing feature request for this?

- [x] I have searched the existing issues

### Summary

Add support for migrating the HTTP APIs (in the `http/regression` folder) to gRPC. 

### Why should this be worked on?

since we'll have SDKs written in multiple programming languages, using gRPC can help us standardize the client communication between the servers and SDKs. This could also help improve performance because lots of binaries are also exchanged.

**Comment by petergeorgas** [comment]
I'm game... let's see how this goes!

**Comment by Sarthak160** [comment]
closes with #127
