### ISSUE TITLE
[bug]: binary not found for integration with go unit tests

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I run the go test cmd to observe the code coverage, then the cmd fails with the error `no such file or directory: /home/ritikjain.linux/keploy-workspace/keploy/keploy`. This should not be the behaiviour since, i have installed the keploy binary in my machine.

### Steps to reproduce

1. Install the `keploy` binary according to your path.
2. Then, integrate the go-sdk for code coverage.
3. And run the go test cmd to capture the code coverage.

### Environment

None

### Version

Local

### Repository

go-sdk

**Comment by EraKin575** [comment]
I would like to work on this issue

**Comment by EraKin575** [comment]
![image](https://github.com/keploy/keploy/assets/100225222/cae5ff73-90db-485d-96b4-df58325bae6b)
I ran the gin-mongo app with the test cases as guiided in [this](https://github.com/keploy/go-sdk/pull/194) and then ran `go test`  . It seemed to run successfully without giving errors

**Comment by re-Tick** [comment]
Closing the issue, since it is fixed in [this](https://github.com/keploy/go-sdk/pull/198) PR
