### ISSUE TITLE
[feature]: add option for storing tests and mocks in a DB instead of yaml 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1043]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Since we are using Yamls for storing testcases and mocks it can be cumbersome if their are large number of tests or if user is capturing from any live environment . 
- Also it includes lot of I/O operations which can lead to delay in test creation , even if all the requests are completed .
- So we should add , New Interfaces in keploy codeBase for insertion in a DataBase - In my opionion we can use MongoDb for this purpose as its is used for large, unstructured data due to its NoSQL, schemaless, and document-oriented design, scalability, high performance, geospatial support, and flexible query capabilities.
- If you have any other DB in mind we can have a discussion in the comments .

### Why should this be worked on?

This will be very helpful for the user who wants to capture from a real traffic and doesn't bother much about editing tests and mocks in the yamls .

### Repository

keploy

**Comment by rajesh604** [comment]
Hi @Sarthak160 can i work on this issue ?

**Comment by IllTamer** [comment]
Hey @Sarthak160 , I'm very interested in this issue. I have experience in upgrading storage methods from YAML to database support and am familiar with architecture design . If you need to implement this feature, please let me know and I will be happy to provide a relevant design document : )

**Comment by charankamarapu** [comment]
Closing this issue as this is a feature of enterprise
