### ISSUE TITLE
add automatic port change if the port is busy

### ISSUE THREAD

**Issue by EraKin575** [keploy/keploy#1051]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

since test and record mode run at same port, it will be beneficial to add a automatic port changing feature so both modes can be run at same time

### Why should this be worked on?

..

### Repository

keploy

**Comment by EraKin575** [comment]
@charankamarapu can I have a hacktoberfest label on this?😁

**Comment by charankamarapu** [comment]
Hi @EraKin575 we already have an option to change the port using --proxyport flag. So if some one wants to change the port in some mode like record or test they can change it using that flag . So I dont think there is any issue here. If you are satisfied with the answer we can close the issue.

**Comment by EraKin575** [comment]
@charankamarapu I am actually talking about automatically changing port if the port is busy

**Comment by charankamarapu** [comment]
Oh okay, then I guess we can take that up.  But you can change the description of the issue because if someone want to run test and record they can use proxyport flag and do that, so we are not solving that problem. We are solving the problem which mentioned in the above comment.

**Comment by EraKin575** [comment]
Thanks @charankamarapu

**Comment by nakulbh** [comment]
what is the default port that test and records run on ?

**Comment by charankamarapu** [comment]
The default port is 16789

**Comment by EraKin575** [comment]
@charankamarapu Please review on my PR

**Comment by EraKin575** [comment]
thanks @AkashKumar7902

**Comment by nakulbh** [comment]
@charankamarapu @EraKin575, I believe that simply incrementing the port won't resolve the issue. I've made some changes that I think are better suited to address this. Please review and share your thoughts on these modifications

**Comment by charankamarapu** [comment]
I guess there is some misunderstanding here, before raising a PR please ask to assign the issue to you. Right now there are two PRs and according to hackboterfest we decided to go by first come first serve. So @EraKin575 Pr will be reviewed . @nakulbh @EraKin575 please ask to assign before working on the issue. @nakulbh you choose some other issue. If this issue is not resolved even after completely reviewing after multiple revisions then I will consider @nakulbh PR.

**Comment by charankamarapu** [comment]
> thanks @AkashKumar7902

🤔

**Comment by nakulbh** [comment]
@charankamarapu why my PR is closed

**Comment by charankamarapu** [comment]
Like I mentioned above only one PR will be merged out of both which are submitted. PR submitted by @EraKin575 is about to merge. So I have to close yours.
