### ISSUE TITLE
[bug]: test fails for API making mongo calls with error logs in the OpMsg Section

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I record the testcases and mocks for a node app, then the tests fails for the mongo testcases saying that the connection is not established with the mongo server. error:
```
🐰 Keploy: 2023-11-01T16:57:59+05:30    ERROR   mongoparser/operation.go:503    failed to unmarshal the recorded document string of OpMsg       {"Client IP Address": "192.168.0.23:60856", "Client ConnectionID": 2, "Destination IP Address": "127.0.0.1:27017", "Destination ConnectionID": 3, "error": "end of input in JSON string"}
```

### Steps to reproduce

1. Use a node-mongo API which querying to createIndexes in the server initialisation.
2. Record the testcases and mongo mocks.
3. Run the testcases in record mode.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by charankamarapu** [comment]
Closing the issue as it is resolved.
