### ISSUE TITLE
[feature]: Add option to configure recording of test cases

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1059]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Right now there is no option in the keploy to record or eliminate certain test cases. We can add some kind of regex to filter out the recording of test cases. 

### Why should this be worked on?

- When users try to record test cases for their application from a live environment using Keploy, it may end up capturing numerous test cases and mocks.
- To address this, users can configure Keploy to specify which test cases to record and which to omit.

### Repository

keploy

**Comment by Hermione2408** [comment]
Can I work on this issue?

**Comment by gouravkrosx** [comment]
Sure @Hermione2408
