### ISSUE TITLE
[bug]: Make docker compose startup time configurable

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- For docker-compose files which take more than 30 seconds to build, keploy fails to find the application container and crashes.
- It should not happen because many docker-compose files can take more than 30 seconds to build and run. 
- So this listening time should be configurable rather than the hardcoded 30 seconds.

### Steps to reproduce

1. Set up keploy locally.
2. Take a docker-compose file that takes more than 30 seconds to run.
3. Try this compose file with keploy to record test cases for your application.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by EraKin575** [comment]
@gouravkrosx  would adding a waiting time flag to modes do the job?

**Comment by gouravkrosx** [comment]
Yes

**Comment by EraKin575** [comment]
OKay. C

**Comment by EraKin575** [comment]
@gouravkrosx you can assign it to someone else. My exams are about to commence, I won't be able to help for some time

**Comment by IllTamer** [comment]
Hey @gouravkrosx . I'm learning the code of keploy, and I thought this issue would be a good starting point. Could you please assign this issue to me? I will try my best to fix it. 😊

**Comment by gouravkrosx** [comment]
Hey @IllTamer , This issue is open to all so you can make a PR for this issue.
