### ISSUE TITLE
[bug]: Design inconsistency in website

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The boxes in the site are inconsistent, some of them don't have any border-radius while others have rounded corners. I want to make all of the boxes with the same border radius for design consistency.

### Steps to reproduce

Here, the boxes have rounded corners:<br>
![image](https://github.com/keploy/keploy/assets/121167506/119bdfe2-cbe5-42b3-b0e1-2efc30fa8080)
<br>
But, here the boxes have sharp corners: <br>
![image](https://github.com/keploy/keploy/assets/121167506/f2f158e8-08d1-40df-8278-a14a6d87f3b0)

### Environment

Release

### Version

Cloud

### Repository

keploy

**Comment by Swpn0neel** [comment]
I want to work on this issue, so please kindly assign me @fahurox @jeff1010322 @thunderboltsid @testwill !!

**Comment by nehagup** [comment]
Hi @Swpn0neel currently the website is not open source and we're planning to make it open source soon. Please pick another issue.

**Comment by nehagup** [comment]
@aniketbamotra fyi
