### ISSUE TITLE
[docs]: MongoDB Support section is not well explained

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#1079]
### What do you want to add to the docs? (please state reasons if any)

I want to re-work the whole MongoDB support section so that it can help the developers to use it more efficiently.

### Where is this stated?

It needs to updated because it's not well explained and a bit vague.

### Repository

docs

**Comment by nehagup** [comment]
@Swpn0neel can you please tell us how it is vague and what exactly do you want to change?

**Comment by Swpn0neel** [comment]
Hey @nehagup, only the "How it works?" section is currently mentioned in the MongoDB support section, but I think it would be better to add a small section on wire messages and a demonstration section at the end with an example of how developers can set up MongoDB with Keploy. <br>
Currently, only this much is present: <br>
![image](https://github.com/keploy/keploy/assets/121167506/da96be8b-7f47-425c-99c4-8a71f97020b7)

**Comment by nehagup** [comment]
@Swpn0neel that's a good idea to add. Please feel free to add an example.

**Comment by Swpn0neel** [comment]
Kindly assign me to this issue, I'll be happy to start working on it!! @nehagup
