### ISSUE TITLE
[docs]: add documentation for config file

### ISSUE THREAD

**Issue by AkashKumar7902** [keploy/keploy#1101]
### What do you want to add to the docs? (please state reasons if any)
Add a detailed documentation for config file 

### Repository

docs

**Comment by AniketNS** [comment]
Hey @AkashKumar7902, Can I work on this issue?

**Comment by AkashKumar7902** [comment]
Hey @AniketNS 
I have already started working on this issue. You may take another issue.

Happy coding!

**Comment by AniketNS** [comment]
Ohh ok

**Comment by charankamarapu** [comment]
Hey @AkashKumar7902 just to be clear this has to be done in keploy website and not in the ReadMe. We will just add a link in the readme to the keploy webiste where we specify config documentation.

**Comment by charankamarapu** [comment]
This issue is resolved.
