### ISSUE TITLE
[bug]: failure in handling TLS connection in python

### ISSUE THREAD

**Issue by Shashwat79802** [keploy/keploy#1107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While creating a new Python-Twilio sample application (https://github.com/Shashwat79802/twilio-python-sms) and integrating keploy into it, this issue occurred.

### Steps to reproduce

Run this application - https://github.com/Shashwat79802/twilio-python-sms
Follow the steps mentioned in the README.md to start this app, and make the request and you'll be able to reproduce this issue.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by EraKin575** [comment]
I would like to work on this issue

**Comment by officialasishkumar** [comment]
@Shashwat79802 Can you send the screenshot or the log of the error that you are facing?

**Comment by Shashwat79802** [comment]
> I would like to work on this issue

@EraKin575 issue assigned to you!!

**Comment by Shashwat79802** [comment]
> I would like to work on this issue

@EraKin575 It's open to all

**Comment by Shashwat79802** [comment]
> @Shashwat79802 Can you send the screenshot or the log of the error that you are facing?

![image](https://github.com/keploy/keploy/assets/63868528/3cb0c8bc-e653-446a-aa4f-f8881b7962cf)

**Comment by gouravkrosx** [comment]
This issue became urgent so we need to pick it. And has been resolved now. @Shashwat79802 Can you please try at your end and close it?
