### ISSUE TITLE
[bug]: keploy testcases not running because of recent changes to the model

### ISSUE THREAD

**Issue by AkashKumar7902** [keploy/keploy#1108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

the structure of noise has changed from []string to map[string][]string to cater to an improved noise detection and resolution system. Because of this change all the testcases file generated from the version before the improved noise, is failing.

### Steps to reproduce

NA

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by charankamarapu** [comment]
One of the issue is backward compatibility and other is when keploy is used in test mode without keploy-config there is this error `2023/11/13 18:45:11 assignment to entry in nil map`
