### ISSUE TITLE
[bug]: errors in keploy-config file should not stop keploy if cli flags are enabled

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently any kind of misconfiguration which leads to unmarshal error is forcing keploy to stop as it's returning errors from command line functions. -
version: 2-dev

```
🐰 Keploy: 2023-11-22T05:22:42Z         ERROR   test/match.go:16        cannot convert json string into json object     {"error": "unexpected end of JSON input"}
🐰 Keploy: 2023-11-22T05:22:42Z         ERROR   cmd/test.go:209         {"error": "failed to unmarshall the noise flag due to error: unexpected end of JSON input"}
🐰 Keploy: 2023-11-22T05:22:42Z         ERROR   cmd/root.go:225 failed to start the CLI.        {"error": "failed to unmarshall the noise flag due to error: unexpected end of JSON input"}
exit status 1
```
This can be not good experience as keploy-config file is an optional and comes after the priority of cli command.

### Steps to reproduce

1. Record bunch of testcases.
2. try to misconfigure any config-changes which can lead to unmarshal error .
3. Then run keploy on test mode , and you will see keploy shuts with exit status 1.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by EraKin575** [comment]
please assign me this
