### ISSUE TITLE
[docs]: Add Deduplication Algorithm Explanation to Glossary for Clarity in FAQ

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1125]
### Issue Summary
In our [FAQ section](https://keploy.io/docs/keploy-explained/faq/) section, the term `deduplication algorithm` is used extensively. While it provides valuable information for experienced users, it might be confusing for beginners. To enhance the accessibility and understanding for newcomers, I propose adding a detailed explanation of the term to our [Glossary](https://keploy.io/docs/concepts/general-glossary).

### Proposed Solution
Include a dedicated entry in the Glossary that explains the concept of `deduplication algorithm` in simple terms. This will serve as a reference point for beginners, providing them with the necessary information to understand the terms used in our documentation.

### Benefits
1. Improves overall documentation clarity.
2. Facilitates better understanding for beginners.
3. Enhances the user experience by providing quick and accessible explanations.

### Labels
- Documentation
- Beginner Friendly

### Repository

docs

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by aarishshahmohsin** [comment]
Can I get a reply?

**Comment by Sonichigo** [comment]
Hey @aarishshahmohsin assigned to you!

**Comment by aarishshahmohsin** [comment]
I have submitted a PR. Please look into it.
