### ISSUE TITLE
[feature]: Refactor the installation option in One Click Install

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1126]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

In the current flow when a user tries to install Keploy via [one click install](https://github.com/keploy/keploy#quick-installation), the user had to type the whole text to install Keploy(either ```Linux``` or ```Docker```. Instead of typing the whole text for the option, the input type should be updated as to accept single keys. (Pressing Enter/Return to install Keploy for Linux and Space for Keploy for Docker installation)

<img width="732" alt="image" src="https://github.com/keploy/keploy/assets/60891544/517ab9a3-7029-495f-a6e3-0c3959e5cb26">

### Why should this be worked on?

Easier and better user experience.

### Repository

keploy

**Comment by officialasishkumar** [comment]
Hey @shivamsouravjha, I have an alternative idea. Should I make a list to select the installation process?
![image](https://github.com/keploy/keploy/assets/87874775/341d2219-5566-4337-a8b0-109a7ce360a2)

**Comment by shivamsouravjha** [comment]
@officialasishkumar seems to be a better approach can proceed with it

**Comment by EraKin575** [comment]
Please assign me this issue

**Comment by gouravkrosx** [comment]
Closing as we currently have a single binary that can start docker and non-docker commands. hence the uniform installation guide.
