### ISSUE TITLE
update in the readme file

### ISSUE THREAD

**Issue by Akshit42-hue** [keploy/keploy#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There are two 'your' in the read me file

![Screenshot from 2022-04-16 17-34-22](https://user-images.githubusercontent.com/59443454/163674303-130d2655-18ef-4aab-b597-a57bb4b406fa.png)

**Comment by Akshit42-hue** [comment]
Hey @nehagup should I work on it

**Comment by nehagup** [comment]
@Akshit42-hue Yes sure :)
