### ISSUE TITLE
[docs]: Typo in Command for Capturing Test Cases in Samples-BunJS Documentation

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1134]
### What do you want to add to the docs? (please state reasons if any)

# **Description:**
In the documentation for the [sample bun.js](https://github.com/keploy/docs/blob/main/versioned_docs/version-2.0.0/quickstart/samples-bunjs.md), there is a typo in the command for capturing test cases. 

Currently, the command is shown as:

```bash
sudo -E env PATH=$PATH Keploy record -c 'bun run supabun.ts'
``` 

but it should be:

```shell
 sudo -E env PATH=$PATH keploy record -c 'bun run supabun.ts'
``` 
This correction is necessary because we have previously set the alias as "keploy." Please update the documentation to reflect the correct command.

![image](https://github.com/keploy/keploy/assets/109217591/c3becbdd-7cbf-4486-b45c-775ed25eb127)

### Repository

docs

**Comment by OlibhiaGhosh** [comment]
I would like to work on this

**Comment by aarishshahmohsin** [comment]
Can I be assigned this?

**Comment by nehagup** [comment]
@OlibhiaGhosh can you please confirm if you are working on this?

**Comment by OlibhiaGhosh** [comment]
@nehagup I have made the PR
