### ISSUE TITLE
[refactor]: samples java workflow needs to be refactor to do build checks inside the sample app directories.

### ISSUE THREAD

**Issue by Shashwat79802** [keploy/keploy#1142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Earlier there was only one sample application in the [samples-java](https://github.com/keploy/samples-java) repository and the maven build check was done in the parent directory itself because of the presence of the POM.xml file. But now adding a new sample app to the repo and creating subdirectories of each sample app causes build failure because the build check must now be performed inside of the subdirectories containing the POM.xml files. And for that, the workflow needs to be reconfigured so that the build check can be done correctly.

The following is the new structure of the repo now:
![image](https://github.com/keploy/keploy/assets/63868528/09f6c8a0-dc2a-4211-a02c-9f8e6f2063b9)

### Steps to reproduce

1. Navigate to this PR - https://github.com/keploy/samples-java/pull/52
2. Re-run the failing build check to see the error.

### Environment

None

### Version

Local

### Repository

samples-java

**Comment by IllTamer** [comment]
I've changed the project struct for temporary solution https://github.com/keploy/samples-java/pull/53 .
The idea is to use samples-java as the parent project of each sample project, so that each sub-project can be compiled normally in the workflow process. I don't know if this meets your expectations. If you have a better idea, please let me know. I also want to ask you to assign this issue to me.

**Comment by Shashwat79802** [comment]
> Hey @Shashwat79802 . I've changed the project struct for temporary solution [keploy/samples-java#53](https://github.com/keploy/samples-java/pull/53) . The idea is to use samples-java as the parent project of each sample project, so that each sub-project can be compiled normally in the workflow process. I don't know if this meets your expectations. If you have a better idea, please let me know. I also want to ask you to assign this issue to me. 😀

It'll still not work because there's no POM.xml file in the root dir where it'll do the build check, and the structure of the samples-java repo will be the same as that of all the other sample app repositories.

**Comment by Shashwat79802** [comment]
Checks has been removed which resolves the issue.
