### ISSUE TITLE
[bug]: Uncontrolled data used in path expression

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

pkg/platform/yaml/yaml.go:221 uses a user-provided value. Accessing files using paths constructed from user-controlled data can allow an attacker to access unexpected resources. This can result in sensitive information being revealed or deleted, or an attacker being able to influence behavior by modifying unexpected files.

### Steps to reproduce

```	_, err := os.Stat(path)```

This path depends on a user-provided value

```[pkg/service/serve/graph/schema.resolvers.go](https://github.com/keploy/keploy/blob/4fa8be8760931bc9bdef507fd74593b1f9754a08/pkg/service/serve/graph/schema.resolvers.go#L20-L20)
func (r *mutationResolver) RunTestSet(ctx context.Context, testSet string) (*model.RunTestSetResponse, error) {```

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by shivamsouravjha** [comment]
@aarishshahmohsin do you plan to pick this up?

**Comment by IllTamer** [comment]
> @aarishshahmohsin do you plan to pick this up?

Hey @shivamsouravjha , I'm interested in this issue, if @aarishshahmohsin doesn't have time to fix this bug, I'd be happy for you to assign this issue to me 😉

**Comment by aarishshahmohsin** [comment]
I am right now working on it.

**Comment by seipan** [comment]
Hello @shivamsouravjha !  Thank you for creating such a wonderful open-source software! It seems this issue hasn't been addressed yet, so I'm interested and wanted to comment. I believe I can solve this problem with the following approach

* By performing utils.ValidatePath before os.Stat the path, we can prevent unexpected access to directories.
* Alternatively, if you think we shouldn't accept a path as an argument in the first place, perhaps all paths should be overwritten with ys.TcsPath. (https://github.com/keploy/keploy/blob/main/pkg/platform/yaml/yaml.go#L228)
    
If these approaches are insufficient to solve this problem, I would like to reconsider it. Thank you.

**Comment by shivamsouravjha** [comment]
Hey @seipan exactly that's the direction to move in, we've implemented the first step across the repo, so sure you can work around that if interested

**Comment by seipan** [comment]
Hello, @shivamsouravjha. I am considering implementing a feature based on the approach used in the following implementation. If you think this direction is good, could you please assign me to this issue?
Here is the link to the implementation I would like to reference: https://github.com/keploy/keploy/blob/main/pkg/platform/yaml/yaml.go#L97-L99

**Comment by shivamsouravjha** [comment]
Assigned to you @seipan !

**Comment by Yaxhveer** [comment]
@seipan Are you working on this issue?

**Comment by seipan** [comment]
@Yaxhveer 
Yes!!!
