### ISSUE TITLE
[feature]: add custom timeout in colima status

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1144]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

In Keploy.sh when colima status is checked while installing keploy for docker, a timeout on colima status can help avoid one click install hanging .

### Why should this be worked on?

One click install hangs incase colima status isn't returned on time.

```  
if colima status | grep -q "Running"; then
      echo "colima is already running."
else
     colima start
 fi
 install_colima_docker
 return
```

### Repository

keploy

**Comment by officialasishkumar** [comment]
Hey @shivamsouravjha, what will be the timeout?

**Comment by shivamsouravjha** [comment]
5 Seconds would be fine.

Also before creating the PR ask the issue to be assigned

**Comment by officialasishkumar** [comment]
Please assign this issue to me
