### ISSUE TITLE
[bug]: GenerateConfig doesn't return after logging error

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The implementation of ```keploy/pkg/service/generateConfig/generateConfig.go``` doesn't return in case of error and is subject to nil memory exception.

### Steps to reproduce

After logging the error the value should be returned . 

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by charankamarapu** [comment]
This is due to new changes in the recent PR - https://github.com/keploy/keploy/pull/1146. Added comment in the PR related to this issue also.

**Comment by officialasishkumar** [comment]
Can you please assign this issue to me?
