### ISSUE TITLE
[docs]: add the documentation for keploy's example command

### ISSUE THREAD

**Issue by Shashwat79802** [keploy/keploy#1153]
### What do you want to add to the docs? (please state reasons if any)

Currently, there's no documentation about the example command of keploy including its flag --customSetup.

### Where is this stated?

The documentation needs to be added here just as the other commands are mentioned- https://keploy.io/docs/running-keploy/cli-commands/
To try the example command, install keploy, and run: keploy example --help

### Repository

docs

**Comment by jaimin001** [comment]
Can you please assign this issue to me?

**Comment by Shashwat79802** [comment]
> Can you please assign this issue to me?

Assigned it to you!!

**Comment by Shashwat79802** [comment]
Yup, running the example command with customSetup flag will output the commands to run keploy with different applications
