### ISSUE TITLE
[docs]: Typo in the MongoDB Connection String in Sample bunjs Docs

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1168]
### What do you want to add to the docs? (please state reasons if any)

# Description:
In the documentation for the [Sample bunjs + mongo ](https://keploy.io/docs/quickstart/samples-bunjs/) , there is a mistake in the MongoDB connection string. The current link provided is
```shell
mongodb://loacalhost:27017/keploy
``` 

But it should be 
```shell
mongodb://localhost:27017/keploy
``` 
 The typo in "loacalhost" is causing confusion and may lead users to encounter connection issues.

## Steps to Reproduce:

1. Visit [the Keploy documentation](https://keploy.io/docs/quickstart/samples-bunjs/).
2. Locate the MongoDB connection string in the documentation.
3. Observe the typo in "loacalhost."

## Expected Behavior:
The MongoDB connection string should be mongodb://localhost:27017/keploy instead of mongodb://loacalhost:27017/keploy.

## ScreenShot:

![image](https://github.com/keploy/keploy/assets/109217591/9ae0bd8b-eda5-4a9c-96a6-40e4dbefb272)

### Repository

docs

**Comment by Sonichigo** [comment]
Hi @OlibhiaGhosh this issue would be resolved by [PR](https://github.com/keploy/docs/pull/271).  You can take a look at some of other [GFI](https://github.com/keploy/keploy/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22)
