### ISSUE TITLE
[docs]: docs creation for new samples-java apps

### ISSUE THREAD

**Issue by Shashwat79802** [keploy/keploy#1175]
### What do you want to add to the docs? (please state reasons if any)

Create the docs for the new apps in samples-java:
1. https://github.com/keploy/samples-java/tree/main/spring-boot-mongo
2. https://github.com/keploy/samples-java/tree/main/user-manager

### Where is this stated?

Follow the documentation template of other sample apps mentioned in the [Keploy Docs Website](https://www.keploy.io/docs) and create the documentation for the new sample apps mentioned. Also, map those docs to the docs website in the [sidebar](https://keploy.io/docs/server/windows/installation/). 

### Repository

docs

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,please assign it to me @Shashwat79802

**Comment by Shashwat79802** [comment]
Assigned it to you, please start working on it.

**Comment by officialasishkumar** [comment]
Hey @Shashwat79802, Is this issues still needs to be worked on? I was writing the docs for https://github.com/keploy/samples-java/tree/main/spring-boot-mongo

**Comment by Sonichigo** [comment]
@karthiknadar1204 can you share your progress?

**Comment by karthiknadar1204** [comment]
I'll take up another issue some other time, have been under some medical treatment for a while so couldn't update anything.

Sorry for the delay,thank you

**Comment by Sonichigo** [comment]
Hope you get well soon @karthiknadar1204!!
 @officialasishkumar assigning you to!
