### ISSUE TITLE
[docs]: adding samples rust to docs website

### ISSUE THREAD

**Issue by Shashwat79802** [keploy/keploy#1177]
### What do you want to add to the docs? (please state reasons if any)

Add the [samples-rust](https://www.github.com/keploy/samples-rust) app and documentation to the [Keploy Docs Website](https://keploy.io/docs).

### Where is this stated?

Take reference from the other sample apps and their docs mentioned in the Keploy Docs website, and add the same for the application in the samples-rust repository. Make sure to follow the template for creation the documentation for the application to execute it using keploy.

### Repository

docs

**Comment by jaimin001** [comment]
Hey @Shashwat79802 , I want to work on this issue

**Comment by Sonichigo** [comment]
@jaimin001 great! Have assigned issue to you! Please Refer to the current styling of docs and sample app readme :- https://keploy.io/docs/quickstart/samples-gin/

**Comment by Sonichigo** [comment]
Closing the issue as a relevant PR has been merged.
