### ISSUE TITLE
[feature]: add support for arm64 docker images

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#118]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Add support for arm64 along with existing amd64 in docker build

### Why should this be worked on?

ARM64 systems are becoming popular, especially with people who are using M1 MacBooks or using AWS Graviton EC2 instances. Providing native ARM images will improve performance.

**Comment by ditsuke** [comment]
@slayerjain please assign this to me
