### ISSUE TITLE
[docs]: remove redundant lines from mux-postgres app guide in docs

### ISSUE THREAD

**Issue by Shashwat79802** [keploy/keploy#1184]
### What do you want to add to the docs? (please state reasons if any)

![image](https://github.com/keploy/keploy/assets/63868528/f89a97f4-323f-4ddf-99e4-e9d5dbbb7365)

Remove the redundant lines from the documentation

### Repository

docs

**Comment by Ghat0tkach** [comment]
Thank you @Shashwat79802 !

**Comment by Sonichigo** [comment]
This issue is closed since the a relevant PR as been merged and resolved the issue
