### ISSUE TITLE
[docs]: Incomplete Dependency Installation Command in Dev Guides Doc

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1185]
## **Description:**
In the [Dev Guides Doc](https://keploy.io/docs/keploy-explained/docs-dev-guide/) of Keploy, the command provided for installing dependencies is inaccurate. The documentation suggests using `yarn` for installation, but it should be `yarn install` instead.

![image](https://github.com/keploy/keploy/assets/109217591/c4ba3f84-8906-4b32-9e55-5b4e4ed3ff52)

**Expected Behavior:**
The correct command for installing dependencies should be `yarn install`.

**Steps to Reproduce:**
1. Navigate to the [Dev Guides Doc](https://keploy.io/docs/keploy-explained/docs-dev-guide/).
2. Locate the section related to dependency installation.
3. Observe that the documentation advises using `yarn` instead of the correct command `yarn install`.

### Repository

docs

**Comment by OlibhiaGhosh** [comment]
I would like to work on this!

**Comment by 404fixer** [comment]
This issue is not needed as `yarn` and `yarn install` does the same thing.
