### ISSUE TITLE
[bug]: ISSUE WHILE HOVERING THE BUTTONS

### ISSUE THREAD

**Issue by N0vice17** [keploy/keploy#1197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<b>While hovering the buttons on the website I noticed that they increased their width by a small amount in my opinion it is not looking that good and it's a bug.</b>

<b>I think you should do that if anyone hovers on the button then the text should glow or get bold or get a bigger font while maintaining the button's width.</b>

### Steps to reproduce

1. Go to the website 
2. Hover on any button
3. You will notice

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by nehagup** [comment]
@N0vice17 thanks for reporting! We're working on fixing this issue.

**Comment by N0vice17** [comment]
> @N0vice17 thanks for reporting! We're working on fixing this issue.

Can i work on this issue??

**Comment by nehagup** [comment]
@N0vice17 we've already picked this one. :)

**Comment by nehagup** [comment]
If you want to contribute on frontend - checkout improvements you can do on https://github.com/keploy/blog-website which is hosted on https://keploy.io/blog

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by nehagup** [comment]
@aarishshahmohsin this issue is already picked.

**Comment by bablysingh2409** [comment]
Can I work on this issue

**Comment by nehagup** [comment]
Hi @bablysingh2409 thanks for the initiative ,it's resolved! closing this.
