### ISSUE TITLE
[feature]: add passthroughHosts via CLI and config

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1198]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We pass through certain hosts in user applications that aren't needed in either record or testing phase for example telemetry calls for dotnet and etc.

### Why should this be worked on?

By making custom flags we can let through of certain http hosts.

### Repository

keploy

**Comment by Shubhrant05** [comment]
Can this issue be assigned to me ?

**Comment by Manvi1203** [comment]
@Shubhrant05, any updates on this issue?

**Comment by Shubhrant05** [comment]
> @Shubhrant05, any updates on this issue?

Work in progress, right now. Couldn't work much on it last week due to some issues.

**Comment by shashank-iitbhu** [comment]
Hey! @shivamsouravjha , Can I work on this issue?
@Shubhrant05 If you haven't made much progress on this issue, i would like to contribute.

**Comment by shashank-iitbhu** [comment]
From what i understand this issue can be solved by updating the Test and Record config structs and by updating the http parser functions to accept the config struct as a parameter. Also updating the test and record functions to accept the passThroughHosts parameter.
@shivamsouravjha Let me know if I can work on this, will try to open a draft PR asap.

**Comment by shivamsouravjha** [comment]
Hey @shashank-iitbhu I picked this issue as if was an internal requirement with more things you could see a separate PR for a similar issue under review
