### ISSUE TITLE
[bug]: remove dual commands for docker in keploy cli

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* Incase of Keploy cli there are dual occurrence of sample command for record and test. 
<img width="869" alt="image" src="https://github.com/keploy/keploy/assets/60891544/23d23cd2-cfc7-4779-8e25-894d666dfdca">
*incase of keploy example dual occurrence  of test but nothing for record
<img width="878" alt="image" src="https://github.com/keploy/keploy/assets/60891544/12a990c8-92fa-4486-8836-1cbe1904f274">

### Steps to reproduce

Expectations:
* Incase of Keploy command enhances indexing and removing the dual occurrence.
<img width="892" alt="image" src="https://github.com/keploy/keploy/assets/60891544/4329acc3-7bef-418e-86fa-30c5ff2616b5">
* Incase of keploy example adding the "<> " characters around generic names like ```containerName``` and etc for user clarification
<img width="895" alt="image" src="https://github.com/keploy/keploy/assets/60891544/09aa9b42-0b28-49a1-9b38-2e46441d8981">
* Removal of dual record and test in ```keploy example --customSetup true``` comand 
<img width="871" alt="image" src="https://github.com/keploy/keploy/assets/60891544/5d3b5e2f-09a6-4fab-99e4-5f20412ce78b">

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by aarishshahmohsin** [comment]
Can i be assigned this issue?
