### ISSUE TITLE
[bug]: remove unused directory and files 

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Files like ```pkg/hooks/keploy``` have directories like ```keploy```have files that have all commented codes which can be removed. 

### Steps to reproduce

* Removing unused code files.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?
