### ISSUE TITLE
[bug]: refactor delay flag log

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Incase of running Keploy test the delay flag logs come after the generate config log which shouldn't be the case. Refactoring the delay flag warning to the top is a better and more consistent log flow approach.
<img width="873" alt="image" src="https://github.com/keploy/keploy/assets/60891544/b7bb74bf-33bf-4ba8-a9c7-ad1d9d991005">

### Steps to reproduce

* Run keploy test -c <appcmd" to see the logs.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by charankamarapu** [comment]
The current approach is correct right..? delay flag can also be mentioned in the config file. Firstly we check config and if delay is not present in that too then we show how to use delay flag. As we check config first we need also say that we are continuing without config as config is not present.

**Comment by shivamsouravjha** [comment]
The logs for delay have example which seems out of context considering the logs around it.

SO either there can be a work around to refactor the warning logs to make them look more consistent.
<img width="890" alt="image" src="https://github.com/keploy/keploy/assets/60891544/b2f8d0b7-e78d-44ab-98d4-8235ef588a24">

or log the config file log afte the warning logs
