### ISSUE TITLE
[bug]: Fix indent

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* improve indent across the codebase.

### Steps to reproduce

* Code refactor style.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by shivamsouravjha** [comment]
Hey @aarishshahmohsin thanks for showing interest but I'm already working on this issue.

**Comment by aarishshahmohsin** [comment]
Ok.

**Comment by shivamsouravjha** [comment]
solves https://github.com/keploy/keploy/pull/1213
