### ISSUE TITLE
[refactor]: remove unused files 

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* Files like replay.go have just the package defined and serve no purpose, such files can be removed across the repo.

### Steps to reproduce

* Delete such files across repo.

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by shubham14bajpai** [comment]
Raised a new MR as there are still unused packages in the repository.
