### ISSUE TITLE
[docs]: Add Gitpod badge

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#122]
### What do you want to add to the docs? (please state reasons if any)

Add a GitPod badge to the readme. 

For example : https://img.shields.io/badge/Gitpod-ready--to--code-FFB45B?logo=gitpod 

### Where is this stated?

Currently, we're using Gitpod of a quick demonstration of Keploy with a sample application. Adding a badge would be easier navigation for visitors.

**Comment by khanjasir90** [comment]
@nehagup can i take this one!

**Comment by slayerjain** [comment]
@khanjasir90 please feel free to take this up and ask any questions :)

**Comment by khanjasir90** [comment]
@slayerjain @nehagup linked a PR pls go through it!
