### ISSUE TITLE
[docs]: Images Not Displaying on MongoDB Dependencies Page

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1221]
## **Issue:**
Images on [MongoDB Dependencies Page](https://keploy.io/docs/dependencies/mongo/) are not visible. The problem stems from using images in a private GitHub repo.

## **Proposed Solution:**
Move images to our public repository and update image addresses in the documentation.

## **Steps to Reproduce:**
1. Open [https://keploy.io/docs/dependencies/mongo/](https://keploy.io/docs/dependencies/mongo/)
2. Observe missing images.

## **Expected Behavior:**
Images should load correctly after migrating them to our public repository.

## Screenshot
![image](https://github.com/keploy/keploy/assets/109217591/15fb67a5-b998-4558-96d8-9d85ecd5ae5e)

### Repository

docs

**Comment by Swpn0neel** [comment]
I want to work on this issue!!

**Comment by Arindam200** [comment]
@Swpn0neel Go for it!
