### ISSUE TITLE
[feature]: Add Missing Repositories to Issue Templates

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1227]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Update the existing [issue templates ](https://github.com/keploy/keploy/tree/main/.github/ISSUE_TEMPLATE) to include repositories like blog-website and sample-rust in the dropdown options.

Currently, We only have these options:

      - keploy
      - java-sdk
      - samples-java
      - typescript-sdk
      - samples-typescript
      - docs
      - website
      - ui
      - python-sdk
      - go-sdk
      - samples-go

### Why should this be worked on?

To enhance the issue creation experience for contributors by providing a comprehensive list of destination repositories across all three templates.

### Repository

keploy

**Comment by thisisamandang** [comment]
Hi @Arindam200 i'd like to pick this

**Comment by Arindam200** [comment]
@thisisamandang  Go ahead!
