### ISSUE TITLE
[feature]: Improve Blog Website Header to Match Main Website

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1235]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

## **Description:**  
The header of our blog site doesn't match the main website's design, causing user confusion.
We need to align the blog header with the main website's header for a seamless user experience.

## Screenshot:

![image](https://github.com/keploy/keploy/assets/109217591/f5073a6f-c064-413a-b0a7-2f1407ada951)

### Why should this be worked on?

The current header on the blog website does not align with the design elements of the main website's header. This inconsistency may lead to user confusion, making it unclear that they are navigating within a sub-directory.

### Repository

blog-website

**Comment by Swpn0neel** [comment]
Hey, can I work on this issue?

**Comment by sahadat-sk** [comment]
Hey @Arindam200, Can I work on this issue?

**Comment by nehagup** [comment]
Sure @sahadat-sk

**Comment by sahadat-sk** [comment]
Hi @Arindam200, I've completed the website header development until this point. Could you let me know where I can find the code for the landing page? I'm unable to locate it in the docs repository and I need it to reference for the GitHub button.

https://github.com/keploy/keploy/assets/98450585/4f452126-a97e-415e-b124-7812b142677a

**Comment by Arindam200** [comment]
Hey @sahadat-sk , You can check this : https://github.com/keploy/website

**Comment by sahadat-sk** [comment]
Hey @Arindam200, @nehagup I've created a pull request, can you please review it?
