### ISSUE TITLE
[feature]: Enhance Home Page Design of Blog Website for Latest Posts Display

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1237]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

## Description

To improve user engagement and navigation, it's crucial to redesign the homepage of the blog website. Specifically, we need a layout that elegantly lists all the latest posts, making it easy for visitors to discover and access content.

### You can Take inspiration from this: 
![image](https://github.com/keploy/keploy/assets/109217591/077d7f32-2b0d-4109-b1c9-0f2392a4cdeb)

### Why should this be worked on?

The current design of the blog website's homepage does not effectively showcase the latest posts in an aesthetically pleasing and user-friendly manner.

### Repository

blog-website

**Comment by hubsMIT1** [comment]
@Arindam200  can i work on it?

**Comment by Arindam200** [comment]
Go Ahead @hubsMIT1 !

**Comment by sahadat-sk** [comment]
Hey @Arindam200 can I work on this issue?

**Comment by nehagup** [comment]
@sahadat-sk please feel free to pick this.

**Comment by Arindam200** [comment]
Feel free to make a PR @sahadat-sk !

**Comment by sahadat-sk** [comment]
Hey, sorry for the late reply. I have made some changes to the blog page, and here is a video of them. Could you review it? Then, I can create a pull request.

https://github.com/keploy/keploy/assets/98450585/08d915cf-d8bd-40e7-816b-1eccabd65a2a

**Comment by sahadat-sk** [comment]
> @sahadat-sk no worries, can you please open a PR, so that I can review the code changes?
> 
> Also, the issue is about changing the /blog page itself to showcase top blogs from /blog/technology and /blog/community - I don't see that in the video above.

Hi @nehagup, I've submitted a PR for your review. It includes layout changes for the /blog/technology and /blog/community pages. Additionally, I'm currently working on enhancing the /blog page to showcase the top blogs. Your feedback would be greatly appreciated. Thank you!.
