### ISSUE TITLE
[feature]: Standardize Single Blog Post Page Design

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1238]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

## Description

The current design of the single post page on our blog website lacks consistency and efficiency. The objective is to ensure that posts created in Gutenberg maintain a uniform appearance across all pages. By making adjustments to a single template, we should be able to update the design consistently across the platform.

You can take inspiration from the following design! 

### Inspiration:
![image](https://github.com/keploy/keploy/assets/109217591/8a4d3fd8-858f-40ed-ae0a-7c16105dcbfb)

### Why should this be worked on?

The inconsistency in the single post page design poses challenges for publishers aiming for a cohesive look and feel. Leveraging Gutenberg for content creation should align seamlessly with the design layout, ensuring that any changes made reflect uniformly across all post pages.

### Repository

blog-website

**Comment by Arindam200** [comment]
Go ahead! @satyamsaxena2001

**Comment by satyamsaxena2001** [comment]
Hey @Arindam200, had a few hiccups in setting-up on my local machine (will make changes in the setup - documentation). Just to give you an update I have identified the 'post files' in 'components' and will make changes in them soon. Sorry for the delay.

**Comment by LalitDeore** [comment]
Hey @Arindam200 , I am working on this issue.

**Comment by its-kunal** [comment]
Hey @LalitDeore , I have already started working on this issue. I will be raising a PR soon.

**Comment by PratikKhaire** [comment]
@its-kunal 
@LalitDeore  
Are you currently working on this problem? I would also like to share and contribute to it.

**Comment by its-kunal** [comment]
Yes @PratikKhaire I'm working on it, I will be raising a PR soon.

**Comment by its-kunal** [comment]
Hey @PratikKhaire I have raised a PR, if you want to contribute [PR Link](https://github.com/keploy/blog-website/pull/24)

**Comment by nehagup** [comment]
It is suggested to discuss the design and finalize it on "github discussions" before directly starting to code. We're open to all opinions.
