### ISSUE TITLE
[feature]: Ensure Consistent Font Usage Across Blog Website and Main Website

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1239]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

## Description
The blog website currently uses a different font than the main website, leading to a lack of visual consistency and brand alignment. To create a cohesive user experience and maintain brand identity, it is essential to use the same font across both platforms.

### Font Reference: 
![image](https://github.com/keploy/keploy/assets/109217591/3c5dda7f-ccce-4cea-960a-b3aec250420d)

### Why should this be worked on?

The discrepancy in font usage between the blog website and the main website can confuse users and diminish the overall brand image. By aligning the fonts, we aim to provide a seamless transition for users navigating between the two platforms while reinforcing brand consistency.

### Repository

blog-website

**Comment by Swpn0neel** [comment]
Hey, can I work on this issue?

**Comment by nehagup** [comment]
@Swpn0neel sure!

**Comment by Swpn0neel** [comment]
> @Swpn0neel sure!

Please sign me

**Comment by bablysingh2409** [comment]
Hy @nehagup ,can I work on this issue

**Comment by Arindam200** [comment]
@bablysingh2409 Go ahead

**Comment by srs-sudeep** [comment]
Hey @nehagup , can I work on this issue?
