### ISSUE TITLE
[feature]: Implement and Rectify Table of Contents for Blog Posts

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1240]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

A well-structured Table of Contents is essential for guiding readers through lengthy articles or posts, improving navigation, and enhancing the overall user experience. The inconsistencies and deficiencies in our current TOC implementation necessitate immediate attention to ensure content accessibility and engagement.

### References: 

![image](https://github.com/keploy/keploy/assets/109217591/13770b83-4146-4596-ba0e-94f64c5e7fb5)

![image](https://github.com/keploy/keploy/assets/109217591/5f2b2748-3a53-4182-a1fc-3c28f2739b9c)

### Why should this be worked on?

A well-structured Table of Contents is essential for guiding readers through lengthy articles or posts, improving navigation, and enhancing the overall user experience. The inconsistencies and deficiencies in our current TOC implementation necessitate immediate attention to ensure content accessibility and engagement.

### Repository

blog-website

**Comment by hubsMIT1** [comment]
Hi, @Arindam200 can i work on this issue?

**Comment by Arindam200** [comment]
Sure @hubsMIT1 !

**Comment by Arindam200** [comment]
Hey @hubsMIT1! This one Looks good!
