### ISSUE TITLE
[feature]: Rectify Broken Author Profile on Blog Page and Enhance Features

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1241]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

## Description

The author profile section on our blog page is currently broken, affecting the presentation and functionality of individual author details.

To provide readers with a comprehensive understanding of authors and enhance engagement, we need to fix the profile section by incorporating essential elements such as the author bio and links to social media profiles.

You can take reference from the following Screenshots

## Screenshot:
![image](https://github.com/keploy/keploy/assets/109217591/c72f2cc2-42a5-4f0f-9537-62e9a128bf7c)

### Why should this be worked on?

A well-curated author profile is crucial for establishing credibility, fostering community engagement, and enhancing the user experience on our blog page. The existing broken profile section detracts from these objectives and requires immediate attention to restore functionality and improve visual appeal.

### Repository

blog-website

**Comment by Skilldron** [comment]
Can I assign myself for this issue ?

**Comment by nehagup** [comment]
@Skilldron sure!

**Comment by professorabhay** [comment]
Hey, @Arindam200! Do you have any sample designs?
Or kindly provide me with something more that can help me to remake this.

**Comment by Akash-Singh04** [comment]
Hello there @Arindam200 ! I would love to work on this issue. I understand the assignment for the author page where we can encapsulate essential details such as author bio and links to social media profiles. Would love to get started as soon as i am assigned. Thank You!

**Comment by Arindam200** [comment]
Hey @Akash-Singh04 !

Are you still interested?

**Comment by Akash-Singh04** [comment]
Sure! Kindly assign me this issue and i will get started asap!

**Comment by Arindam200** [comment]
Go Ahead!

**Comment by Akash-Singh04** [comment]
This issue is being solved in https://github.com/keploy/blog-website/pull/7 by @Aditya-eddy
