### ISSUE TITLE
[feature]: Keploy test should throw non-zero exit code to notify the GitHub action

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1244]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, keploy test returns a zero exit code on test failure due to which the GitHub action is not notified for test run failure. Instead it can return 1 as exit code if the test run fails.

### Why should this be worked on?

This will notify the GitHub action in the CI of the user.

### Repository

keploy

**Comment by Akash-Singh04** [comment]
Hey there! I would love to pick up this issue. Can you provide more information regarding where the exit code returns 0? Thanks

**Comment by seipan** [comment]
Hello, @re-Tick. Regarding this issue, I believe it can be resolved by modifying t.tester.Test to return 1 when the bool return value is false. If this approach seems appropriate, I am ready to submit a pull request for your consideration. Thank you.

https://github.com/keploy/keploy/blob/main/cmd/test.go#L273"

**Comment by re-Tick** [comment]
> Hello, @re-Tick. Regarding this issue, I believe it can be resolved by modifying t.tester.Test to return 1 when the bool return value is false. If this approach seems appropriate, I am ready to submit a pull request for your consideration. Thank you.
> 
> https://github.com/keploy/keploy/blob/main/cmd/test.go#L273"

Yes @seipan, your approach is right. You can make the changes and open a PR
