### ISSUE TITLE
`keploy test` completes successfully in projects without test sets

### ISSUE THREAD

**Issue by milinddethe15** [keploy/keploy#1270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I tried `keploy test` cmd in a project which does not have any test sets from `keploy record`, it successfully completed the test. I think it should give some error.

### Steps to reproduce

- Run `keploy test -c "CMD_TO_RUN_APP" --delay 10` in a project which does not have keploy test sets

### Environment

None

### Version

Local

### Repository

keploy

**Comment by charankamarapu** [comment]
@milinddethe15 Why should the testRun show failed if there is no test case that is failed..? Its like the confusion matrix. My opinion is that False positive is better than False negative in this case.

**Comment by milinddethe15** [comment]
Why should the test run if there is no test-set

**Comment by charankamarapu** [comment]
Agreed but it should not be an error I guess. It should be just an info log thats it.

**Comment by milinddethe15** [comment]
I can't really understand why it shouldn't be error. I guess `keploy record` must be necessary for `keploy test`

**Comment by charankamarapu** [comment]
I mean error or failure in a command signifies that something is wrong either with the application or with keploy or the application cmd etc. But here it is just than user don't have test cases to run. We can just say no test cases found as a warn or info log and exit the cmd. `keploy record must be necessary for keploy test` this statement is not completely true because you can get test cases from someone who using the same app and just run the test cmd and it will work.

**Comment by milinddethe15** [comment]
Yes you are right.
By the Error I meant the same. It should log and exit.
Sorry for this confusion.

**Comment by charankamarapu** [comment]
no problem

**Comment by nehagup** [comment]
@milinddethe15 are you working on fixing this issue?

**Comment by milinddethe15** [comment]
Yes.. I am working on this.

**Comment by Akash-Singh04** [comment]
Hello @milinddethe15 if you are not currently working on this, i have a proposed solution to this issue.

Before executing the keploy test command,we should implement a check to verify if the project has any test sets recorded within keploy.
If no test sets are found, we can  provide an informative error message indicating that there are no test sets available for the project. This message should guide users on how to set up test sets or inform them about the absence of recorded tests.

very importantly, a documentation update would be necessary that includes information about the necessity of having test sets recorded for the keploy test command to function correctly.

I would love to get started on this issue asap, if i can be assigned the same! Thank You

**Comment by milinddethe15** [comment]
Hi @Akash-Singh04 , I am working on this and thinking the same approach.
Sorry I am taking time as im new to golang.
If you want you can make PR for the documentation updation.
Thanks for understanding!

**Comment by Akash-Singh04** [comment]
@nehagup If this issue has been resolved, Kindly close the issue. Otherwise i shall get started on this!

**Comment by nehagup** [comment]
@charankamarapu does this issue still persist?

**Comment by Akash-Singh04** [comment]
@nehagup @charankamarapu I just tested and it seems like the issue still persists, ```keploy test``` will successfully complete in projects without test sets. I will submit a PR fix for this as soon as possible.
