### ISSUE TITLE
[docs]: Incorrect language is specified for code blocks

### ISSUE THREAD

**Issue by epli2** [keploy/keploy#1275]
### What do you want to add to the docs? (please state reasons if any)

Incorrect language is specified for code blocks in the below docs. Currently specified to "go", but it should be "bash".
https://github.com/keploy/docs/blob/main/versioned_docs/version-2.0.0/server/sdk-installation/go-sdk.md#installation
https://github.com/keploy/docs/blob/main/versioned_docs/version-2.0.0/running-keploy/rename-testcases.md

### Repository

docs

**Comment by krrish-sehgal** [comment]
Hello,
I would like to assist with this issue, Kindly assign it to me.

**Comment by nehagup** [comment]
@krrish-sehgal I think it's been worked upon in the attached PR
