### ISSUE TITLE
[feature]: test command with coverage flag to serve command internally 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1292]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Currently in all other 3 languages except go we use serve command  for eg-
sudo -E keploy serve -c "python3 -m coverage run -m pytest test_keploy.py" --delay 10 
Also for Java - https://github.com/keploy/java-sdk/pull/159
- But from the user point of view it will be more relevant to use just one common command which can be of test only, so whenever user will give flag --coverage along with test command it will internally call serve method instead of actual test method . So the command can look like - 

`sudo -E keploy test -c "python3 -m coverage run -m pytest test_keploy.py" --coverage --delay 10`
- Also refactor the common methods which are duplicate in both test and serve command.

### Why should this be worked on?

To improve the user experience for using native frameworks for coverage purposes.

### Repository

keploy

**Comment by EraKin575** [comment]
please assign this to me
