### ISSUE TITLE
Typo: `gracfully` must be `gracefully`

### ISSUE THREAD

**Issue by milinddethe15** [keploy/keploy#1298]
In several places within the codebase, the term `gracfully` has been used instead of `gracefully` in comments.

**Comment by milinddethe15** [comment]
I will make PR fixing this.

**Comment by EraKin575** [comment]
@officialasishkumar please atleast ask once before submitting a PR and get it assigned to you

**Comment by milinddethe15** [comment]
Well good experience being a new contributor
