### ISSUE TITLE
[feature]: add update command to keploy cli

### ISSUE THREAD

**Issue by AkashKumar7902** [keploy/keploy#1303]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

we can include a command like `keploy update` which will update the keploy binary. Apart from this, we should notify our users that an update is available when they run any of our command. 

### Why should this be worked on?

traditional way of updating keploy is running one-click install again or add keploy binary to your system, this new feature will greatly improve user experience.

### Repository

keploy

**Comment by rharshit82** [comment]
Can you please assign me this?

**Comment by AkashKumar7902** [comment]
Hey @rharshit82 

Please provide an explanation of what your PR will do. If it looks good, we can assign you to this issue.

**Comment by Akash-Singh04** [comment]
Hello! I would love to pick up this issue. Here is what i plan to do to resolve it:

1.Update Command:
- Create a new command Keploy Update that checks for the latest version of keploy
-  Compare the installed version with the latest version available in the repository.
- If there's a newer version, prompt the user to confirm the update.
- If confirmed, Download and replace the current binary file

2.Update Notification
- Introduce a version check mechanism when any keploy command is run.
- If new version is available, prompt and notify the user

I can get started on the implementation of this right away, Kindly assign me this issue.

**Comment by AkashKumar7902** [comment]
Hey @Akash-Singh04, Thanks for your interest.

Can you please explain how you will notify the user if a update is available like if you intend to use the existing logger or be a bit fancy and follow what other OSS like sanity-cli uses to notify the user. You can copy the logs and make modifications to it just to clarify the design.

**Comment by Akash-Singh04** [comment]
The way we can approach this problem is via notifying the user about the new update whenever the keploy commands are run.

A sample log could look something like this:

sudo  keploy record -c "go run main.go handler.go"
[sudo] password for [user]: 

       ▓██▓▄
    ▓▓▓▓██▓█▓▄
     ████████▓▒
          ▀▓▓███▄      ▄▄   ▄               ▌
         ▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
       ▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
      ▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
       ▓▌                           ▐█▌                   █▌
        ▓

version: 2.0.0-alpha54

=================================================================
|                                                               |
|                    KeplOy CLI Update Available               |
|                                                               |
|  A new version of KeplOy CLI is available.                   |
|  Please consider updating for the latest features and fixes.  |
|                                                               |
|  Current Version: 2.0.0     Latest Version: x.y.z            |
|                                                               |
|  To update, run:                                             |
|  $ keploy update                                             |
|                                                               |
=================================================================



🐰 Keploy: 2024-01-08T10:52:50+05:30    INFO    continuing without configuration file because file not found
🐰 Keploy: 2024-01-08T10:52:50+05:30    INFO            {"keploy test and mock path": "/mnt/c/Users/USER/Desktop/samples-go/gin-mongo/keploy"}
🐰 Keploy: 2024-01-08T10:52:54+05:30    INFO    keploy initialized and probes added to the kernel.
🐰 Keploy: 2024-01-08T10:52:54+05:30    INFO    Proxy started at port:16789


We can use the existing logger for this as it can be seamlessly integrated whenever the user runs a keploy command. Let me know if any improvements can be made to this implementation

**Comment by AkashKumar7902** [comment]
Hey @Akash-Singh04 as the current version is always displayed at the beginning, we could omit that. 

/cc @charankamarapu

**Comment by Akash-Singh04** [comment]
Correct! An updated version would be:

```console
sudo  keploy record -c "go run main.go handler.go"
[sudo] password for [user]: 

       ▓██▓▄
    ▓▓▓▓██▓█▓▄
     ████████▓▒
          ▀▓▓███▄      ▄▄   ▄               ▌
         ▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
       ▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
      ▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
       ▓▌                           ▐█▌                   █▌
        ▓

version: 2.0.0-alpha54

=================================================================
|                                                               |
|                    KeplOy CLI Update Available               |
|                                                               |
|  A new version of KeplOy CLI is available. Latest Version: x.y.z |
|  Please consider updating for the latest features and fixes.  |
|                                                               |
|                                                               |
|  To update, run:                                             |
|  $ keploy update                                             |
|                                                               |
=================================================================



🐰 Keploy: 2024-01-08T10:52:50+05:30    INFO    continuing without configuration file because file not found
🐰 Keploy: 2024-01-08T10:52:50+05:30    INFO            {"keploy test and mock path": "/mnt/c/Users/USER/Desktop/samples-go/gin-mongo/keploy"}
🐰 Keploy: 2024-01-08T10:52:54+05:30    INFO    keploy initialized and probes added to the kernel.
🐰 Keploy: 2024-01-08T10:52:54+05:30    INFO    Proxy started at port:16789
```

Let me know if any improvements can be made to this implementation. If none, kindly assign me this issue

**Comment by AkashKumar7902** [comment]
@Akash-Singh04 

I think the update message should be short and informative. 

For example:
![image.png](https://github.com/keploy/keploy/assets/91385321/87d22481-30a5-436a-b5ab-0513c078e781)

You can research what others are following by installing older versions of popular npm packages. 

I am assigning this to you!

**Comment by charankamarapu** [comment]
According to my opinion, the above example will be good and I think we should remove the feature of showing the version every time users runs keploy. We can create a seperate command for version like `keploy --version` to display version. And regarding whenever a update is found , you guys are correct we need to show it as shown in the example above. Please add update feature in the new `keploy --version` cmd also

**Comment by AkashKumar7902** [comment]
@Akash-Singh04 

As this issue has more than one deliverables, you can make a draft PR after reaching a milestone!

Good luck

**Comment by Akash-Singh04** [comment]
Will get started on it immediately!

**Comment by Akash-Singh04** [comment]
@AkashKumar7902 Kindly look into my PR and let me know the corrections/updates to be made.
It only implements the update command as you said to make multiple pr's for this issue. Let me know if this is okay and if i should proceed onwards with the update notification functionality

**Comment by AkashKumar7902** [comment]
@Akash-Singh04 
No, Don't make multiple PRs. Continue adding commits to this PR only. And you can start working on the next milestone.

**Comment by AkashKumar7902** [comment]
@Akash-Singh04 
No, Don't make multiple PRs. Continue adding commits to this PR only. And you can start working on the next milestone.

**Comment by AkashKumar7902** [comment]
@Akash-Singh04 
Dont make multiple PRs. Add commits in one PR only.

**Comment by Akash-Singh04** [comment]
@AkashKumar7902 understood, can you look at this draft pr in that case? Meanwhile i will start implementing the update message

**Comment by Akash-Singh04** [comment]
> According to my opinion, the above example will be good and I think we should remove the feature of showing the version every time users runs keploy. We can create a seperate command for version like `keploy --version` to display version. And regarding whenever a update is found , you guys are correct we need to show it as shown in the example above. Please add update feature in the new `keploy --version` cmd also

@charankamarapu these seems like a great addition and i would love to work on it immediately. As i already worked on this issue and have implemented the version check and update commands this should be a task i am comfortable with and should be done easily. 

Kindly create a new issue for this feature request and assign me the same, Awaiting to get started!

**Comment by Akash-Singh04** [comment]
Update: PR is complete, kindly have a look at it
