### ISSUE TITLE
[feature]: Integrate keploy in wandb.ai

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#1310]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Intergrate in wandb.ai

### Why should this be worked on?

user requirement

### Repository

keploy

**Comment by shivamsouravjha** [comment]
1. wandb.ai makes grpc calls to internal server for all project related data.
2. Uses leveldb which is a on-disk key-value store in go written backend for the W&B SDK
3. Integrates with sqlite to download unsampled history  via public APIs.
4. Mysql can be used as an external Database store to connect to W&B server.
