### ISSUE TITLE
[feature]: update the code and readme for typescript sdk

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1312]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

The current TS SDK repo is outdated. We need to: 
1. Move current code and readme to a v1 folder. We also need to ensure that the old README in that folder has something like "This README is for keploy V1, which is now outdated" on top.
2. current code can be moved out and become something like `cli.ts` 

### Why should this be worked on?

README is outdated and code obsolete. 

### Repository

keploy

**Comment by shivamsouravjha** [comment]
Updated  the typescript-sdk. Decreasing the overall dependencies installed.
