### ISSUE TITLE
docs: change serve command usage to test with coverage flag in every readme and docs.

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1313]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Since we have now merged serve methods inside the test service only and now we are using test with coverage flags to trigger the graphQL server for keploy and performing mutations like running tests etc.
- Take reference from here https://github.com/keploy/keploy/issues/1292

### Why should this be worked on?

This should be done to provide better user experience to the new comers who want to try keploy to get coverage of their native unit tests.

### Repository

keploy

**Comment by slayerjain** [comment]
@EraKin575 Please check and update docs here - https://keploy.io/docs/server/sdk-installation/java/
