### ISSUE TITLE
[feature]: Add functional testing framework of keploy

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1315]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Implement a solid testing framework to find bugs and violations of backward compatibility.

### Why should this be worked on?

- Adding integration or end-to-end tests makes the program more trustworthy.
- Since Keploy is all about testing APIs, it should have a way to test itself.
- Testing helps catch problems early, making the software better.
- Users and potential users trust software with strong testing.

### Repository

keploy

**Comment by shivamsouravjha** [comment]
closing the issue as its solved
