### ISSUE TITLE
[bug]: keploy CLI logs error message when command is unknown

### ISSUE THREAD

**Issue by narharim** [keploy/keploy#1328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Current behavior:
when I run `keploy exampl` instead of `keploy example` it logs failed to start the CLI. 

```
version: 2.0.0-alpha56

Error: unknown command "exampl" for "keploy"

Did you mean this?
	example

Run 'keploy --help' for usage.
🐰 Keploy: 2024-01-10T16:15:03+05:30 	ERROR	failed to start the CLI.	{"error": "unknown command \"exampl\" for \"keploy\"\n\nDid you mean this?\n\texample\n"}

```
Expected behavior:

It should exit without logging.

### Steps to reproduce

Follow installation guide for [linux](https://keploy.io/docs/server/linux/installation/#manual-install) and run keploy

### Environment

None

### Version

Local

### Repository

keploy

**Comment by TheLazron** [comment]
Can I be assigned this issue please?

**Comment by heyyakash** [comment]
Hello. It seems the logger is logging out the error in root.go file before exiting. I have tried removing it on my local build and the output looks something like this? Is this what you are referring to?  If yes, then can I be assigned this issue?
![Screenshot from 2024-01-14 16-31-27](https://github.com/keploy/keploy/assets/85030597/54992877-5df3-4193-9b1e-b16eb039cb54)

**Comment by shivamsouravjha** [comment]
What do you think can be a solution for this @narharim ?  the correct log seems to be correct as the example subcommand has to be compiled and executed, since this isn't compiled the cli doesn't start

**Comment by PranshuSrivastava** [comment]
Sure @TheLazron you can go ahead and open a PR for it, if anyone else also opens one, it will be merged on a first come first serve basis

**Comment by varun7singh** [comment]
Hey @PranshuSrivastava i went through the Cobra docs and it returns an *error.errorString so the way i see it we can perform some string operations or regex to extract the type of error but am not too sure if that is the optimal way, will be opening a pr do let me know.
Thanks!!

**Comment by shivamsouravjha** [comment]
this issue seems to be resolved after the new update however a similar issue has surfaced. https://github.com/keploy/keploy/issues/1853
