### ISSUE TITLE
[bug]: Mounting the folder in keploy container on /files is creating problems

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The user workspace is mounted on `/files` inside the keploy container. This creates problems like changing the name of the containers or volumes when using docker compose. 

### Steps to reproduce

1. Try running any docker compose. `files` will be appended to it. 

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by slayerjain** [comment]
Potential fix: use `-v $(pwd):$(pwd) -w $(pwd)` in the docker alias.

**Comment by slayerjain** [comment]
@charankamarapu let me know is this works

**Comment by charankamarapu** [comment]
Replicated the issue and tested the fix. The fix is working as expected.
<img width="1243" alt="Screenshot 2024-01-10 at 11 31 43 PM" src="https://github.com/keploy/keploy/assets/72094895/8d111ef4-7d00-457a-8df2-7ab794a856f5">

**Comment by charankamarapu** [comment]
We need to update this in alias in our website and one-click install etc. Assigning this to @AkashKumar7902 .

**Comment by slayerjain** [comment]
please also check why `-v "$(pwd)":/files` is still required?
