### ISSUE TITLE
[bug]: error while extracting the OpMsg section in record

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to record test cases for the gin-mongo sample app. Then, the error occurs:
![Screenshot 2024-01-12 at 3 21 12 PM](https://github.com/keploy/keploy/assets/60597329/41a6f838-130f-48ec-ba63-ee7b54c07394)

### Steps to reproduce

1. Run the keploy record command with the gin-mongo sample.
2. Error will occur for the mongo dependency.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by re-Tick** [comment]
This will be occurring because the section of the OpMsg is a sectionSequence so the string starts with prefix `{ SectionSingle identifier:` [here](https://github.com/keploy/keploy/blob/be573ebcfaa99d55cdde1e41268eb051b7cefab4/pkg/proxy/integrations/mongoparser/scramAuth.go#L205C17-L205C17) and the [extractSectionSingle](https://github.com/keploy/keploy/blob/be573ebcfaa99d55cdde1e41268eb051b7cefab4/pkg/proxy/integrations/mongoparser/operation.go#L442) is not expecting that. So just need to add a switch case like [this](https://github.com/keploy/keploy/blob/be573ebcfaa99d55cdde1e41268eb051b7cefab4/pkg/proxy/integrations/mongoparser/operation.go#L478C2-L478C2).

**Comment by officialasishkumar** [comment]
I would like to work on this

**Comment by re-Tick** [comment]
I am assigning this to @charankamarapu, since this bug has became urgent. Thanks @officialasishkumar for your support.
