### ISSUE TITLE
[feature]: Reduce size of sample-go docker images

### ISSUE THREAD

**Issue by narharim** [keploy/keploy#1349]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Hello Team, I was exploring Keploy sample-go projects to get the hands on experience of the product. while doing that I came across that gin-mongo project, when I tried to build image from `Dockerfile` the image size was around 1.2GB, which is a huge size considering it's a sample project. 

### Why should this be worked on?

This will help developer save enough space on machine.

### Repository

samples-go

**Comment by narharim** [comment]
I have tried using multi state feature of docker and my final image was just ~`29MB`. I have tested the image on my linux machine works as expected.

**Comment by slayerjain** [comment]
@narharim Thats great. Please raise a PR for the multi state docker image :)
