### ISSUE TITLE
[docs]: Add missing file name and package in the Readme

### ISSUE THREAD

**Issue by littleironical** [keploy/keploy#135]
### What do you want to add to the docs? (please state reasons if any)

The section **Integration with native Go test framework** is missing 2 things:
1. It is not mentioned in which file we have to add the given code.
2. No package is added at the beginning which will give an error.

### Where is this stated?

Under the **Integration with native Go test framework** section in *README.md** file

**Comment by khanjasir90** [comment]
@littleironical i'll take this one!

**Comment by nehagup** [comment]
@khanjasir90 Yep, sure!

**Comment by littleironical** [comment]
@khanjasir90 are you still working on it?

**Comment by vish-han** [comment]
@littleironical I would love to work on this issue if its not being done yet....

**Comment by khanjasir90** [comment]
@vish-han go head! i just got busy with my college work. you could work on this

**Comment by littleironical** [comment]
@khanjasir90 have you started working on this?

**Comment by khanjasir90** [comment]
@vish-han was working on this! so i thought of working on some other issues.

**Comment by CypherpunkSamurai** [comment]
Hello Everyone, I've made a PR with the proposed changes

Please Review :)
