### ISSUE TITLE
[feature]: Test integration feasibility with Mattermost services

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1360]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Need to check if keploy can be integrate with any mattermost core services, record any existing flow from their test repo and increase the execution time. 

### Why should this be worked on?

Can help mattermost get quicker insight about service quality. 

### Repository

keploy

**Comment by charankamarapu** [comment]
Design of mattermost

1. Server Handlers Initialisation:
The server initialises various handlers for different endpoints, such as:
- /posts: Handling messaging-related actions within channels.
- /view: Fetching channel messages.
- /addMember: Adding a new member to a channel.
- /websocket: The most critical handler, used for sending messages to all members in a channel in real-time.



2. Channel Initialisation and WebSocket Connection:
- The server initializes structures representing channels, likely with details loaded from a database.
- These channel structures are connected to the websocket system, allowing for real-time communication capabilities.



3. Client Connection to WebSocket:
- When a client (user) starts, it establishes a connection to the websocket.
- This connection is maintained so the client can receive updates about channel activities or notifications in real-time.



4. Message Posting and Real-time Update:
- When a user posts a message in a channel, the message is sent to the /posts handler.
- The handler processes the message and triggers an update in the relevant channel structure.
- The update is then propagated through the websocket connection to all clients connected to that channel, ensuring real-time message delivery and notifications.



5. Handling Limitations in Testing Environments:
- Currently, Keploy does not support websocket testing.
- As a workaround, websocket calls can be bypassed or "passthrough" during testing, allowing other APIs to be tested without interruption.
