### ISSUE TITLE
[feature]: modularise, test and release python SDK

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1362]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to release the Pytest integration in the Python SDK for users. 

### Why should this be worked on?

This will make it easy for users to install python SDK for coverage. 

### Repository

keploy

**Comment by PranshuSrivastava** [comment]
Blocked currently because the pytest integration was not working correctly so cannot merge and release the sdk. Have informed the relevant person about the issues.

**Comment by gouravkrosx** [comment]
@PranshuSrivastava is this completed?

**Comment by PranshuSrivastava** [comment]
Yes done [here](https://github.com/keploy/python-sdk/commit/c2c50af1dec55a129db69e8202897a93b97f7cd9)
