### ISSUE TITLE
[feature]: Add MySQL sample application and documentation

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1364]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need MySQL sample application and documentation in docs.keploy.io

### Why should this be worked on?

High demand from user community

### Repository

keploy

**Comment by heyyakash** [comment]
I've had experience in creating CRUD apps with golang. I am confident that I work on this. Can I get this assignment?

**Comment by heyyakash** [comment]
will start right away

**Comment by EraKin575** [comment]
@heyyakash I have created a sample for go+mysql. Could you create a sample for JS+MySQL?

**Comment by heyyakash** [comment]
@EraKin575 I am almost done and will push the update in a while! sorry
