### ISSUE TITLE
[bug]: url field in HttpReq of a test case is always null 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

url field in HttpReq of a test case is always null that leads to data loss while capturing a test-case. 

### Steps to reproduce

1. Capture a test case 
2. Go to Network logs on  frontend or see the captured test case in MongoDB Compass 
3. Url field would be null 

### Environment

Deploy preview

### Version

Local

**Comment by nehagup** [comment]
Reference PR https://github.com/keploy/ui/pull/64

**Comment by khanjasir90** [comment]
@nehagup can I also look into this issue?

**Comment by nehagup** [comment]
@khanjasir90 Sure!

**Comment by nehagup** [comment]
@khanjasir90 This issue is being worked on by @re-Tick. Please pick a new one :)
