### ISSUE TITLE
[feature]: Pass Through for specific API end points in keploy test mode 

### ISSUE THREAD

**Issue by varma-shipsy** [keploy/keploy#1382]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Pass Through for specific API end points in keploy test mode
1. So keploy wont try to search and find the mocks for the api and result in failure 
2.  Like ignoring few endpoints tests in keploy test mode

### Why should this be worked on?

To Skip Health check failure logs in keploy as one usecase 

### Repository

keploy

**Comment by heyyakash** [comment]
Can you please elaborate this issue?

**Comment by slayerjain** [comment]
@heyyakash please ignore this issue. someone is already assigned and working on this :)
