### ISSUE TITLE
[feature]: Add basic linter to GitHub Actions

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1386]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need some basic Linter to Keploy CI. We also need to fix the issues reported but the linter. 

### Why should this be worked on?

This will help improve code quality. 

### Repository

keploy

**Comment by gouravkrosx** [comment]
closed by https://github.com/keploy/keploy/issues/1216
