### ISSUE TITLE
[bug]: many for loops have missing/incomplete stop conditions

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently test runs dont stop. This is likely due to missing exit conditions in for loops or race conditions.  Also need to fix the stopper error in test mode

We could use the ctx cancelled mechanism to fix this. 

### Steps to reproduce

1. Run keploy in test mode for a large test set. 
2. Try stopping once the test run is started.
3. Keploy doesn't and will hang.  

### Environment

None

### Version

Local

### Repository

keploy

**Comment by charankamarapu** [comment]
This has been fixed along with refactor changes. - https://github.com/keploy/keploy/pull/1684
