### ISSUE TITLE
[feature]: add example of filtering urls and headers in keploy config 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1389]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Currently if you use `keploy generate-config` there is a comment section below which have some basic examples showcasing the usability of keploy config features like global noise .
- But there is no example showing filtering of testcases and headers although we have a support for it .
- for eg -         
```
urlMethods: {
            "/petclinic/api/owners": ["GET", "POST"],
        }
```
- So we have to add example for the above as well as for headers .

### Why should this be worked on?

This issue makes keploy config experience better for the user .

### Repository

keploy

**Comment by narharim** [comment]
@Sarthak160, Happy to work on this

**Comment by shivamsouravjha** [comment]
closing the issue as its docs are added in config file
