### ISSUE TITLE
[docs]: Add jest documentation alongside Junit

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1390]
We need to add alongside other docs like JUnit here - https://keploy.io/docs/server/sdk-installation/java/

The current Experience of using the JS/TS SDK is also not very good. We should simplify it and make it cleaner.

**Comment by shivamsouravjha** [comment]
https://github.com/keploy/docs/pull/325

**Comment by shivamsouravjha** [comment]
https://keploy.io/docs/server/sdk-installation/typescript/
