### ISSUE TITLE
[bug]: fix race conditions in various flows within keploy

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We currently have race conditions when: 

1. Stop applications
2. Use TLS 
3. Maybe more

We need to fix these race conditions and also add GitHub Action to detect race conditions in PRs. 

### Steps to reproduce

1. build keploy with `-race` flag
2. Try stopping application or recording any application with TLS certificates. 

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by shashank-iitbhu** [comment]
found 2 more Data Race conditions while testing a web application using TLS.
`==================
WARNING: DATA RACE
Read at 0x00c000fca780 by main goroutine:
  go.keploy.io/server/pkg/hooks.(*Hook).StopUserApplication()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/loader.go:404 +0x105
  go.keploy.io/server/pkg/service/test.(*tester).RunTestSet.func1()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:573 +0xb8
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:477 +0x30
  go.keploy.io/server/pkg/service/test.(*tester).Test()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:236 +0xc35
  go.keploy.io/server/cmd.(*Test).GetCmd.func1()
      /home/shashank/Documents/Developer/keploy/cmd/test.go:273 +0x26b0
  github.com/spf13/cobra.(*Command).execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0xca5
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x617
  github.com/spf13/cobra.(*Command).Execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1104
  go.keploy.io/server/cmd.(*Root).execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:262 +0x1105
  go.keploy.io/server/cmd.Execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:176 +0x4d1
  main.main()
      /home/shashank/Documents/Developer/keploy/main.go:52 +0x469

Previous write at 0x00c000fca780 by goroutine 50:
  os/exec.(*Cmd).Start()
      /usr/local/go/src/os/exec/exec.go:693 +0xa57
  os/exec.(*Cmd).Run()
      /usr/local/go/src/os/exec/exec.go:587 +0x26
  go.keploy.io/server/pkg/hooks.(*Hook).runApp()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/launch.go:524 +0x9c4
  go.keploy.io/server/pkg/hooks.(*Hook).LaunchUserApplication()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/launch.go:252 +0x2b7e
  go.keploy.io/server/pkg/service/test.(*tester).InitialiseRunTestSet.func1()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:354 +0x16d

Goroutine 50 (running) created at:
  go.keploy.io/server/pkg/service/test.(*tester).InitialiseRunTestSet()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:353 +0x18b6
  go.keploy.io/server/pkg/service/test.(*tester).RunTestSet()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:559 +0x4e7
  go.keploy.io/server/pkg/service/test.(*tester).Test()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:236 +0xc35
  go.keploy.io/server/cmd.(*Test).GetCmd.func1()
      /home/shashank/Documents/Developer/keploy/cmd/test.go:273 +0x26b0
  github.com/spf13/cobra.(*Command).execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0xca5
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x617
  github.com/spf13/cobra.(*Command).Execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1104
  go.keploy.io/server/cmd.(*Root).execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:262 +0x1105
  go.keploy.io/server/cmd.Execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:176 +0x4d1
  main.main()
      /home/shashank/Documents/Developer/keploy/main.go:52 +0x469
==================
==================
WARNING: DATA RACE
Read at 0x00c000c675c0 by main goroutine:
  go.keploy.io/server/pkg/hooks.(*Hook).StopUserApplication()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/loader.go:419 +0x747
  go.keploy.io/server/pkg/service/test.(*tester).RunTestSet.func1()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:573 +0xb8
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:477 +0x30
  go.keploy.io/server/pkg/service/test.(*tester).Test()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:236 +0xc35
  go.keploy.io/server/cmd.(*Test).GetCmd.func1()
      /home/shashank/Documents/Developer/keploy/cmd/test.go:273 +0x26b0
  github.com/spf13/cobra.(*Command).execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0xca5
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x617
  github.com/spf13/cobra.(*Command).Execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1104
  go.keploy.io/server/cmd.(*Root).execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:262 +0x1105
  go.keploy.io/server/cmd.Execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:176 +0x4d1
  main.main()
      /home/shashank/Documents/Developer/keploy/main.go:52 +0x469

Previous write at 0x00c000c675c0 by goroutine 50:
  os.newProcess()
      /usr/local/go/src/os/exec.go:29 +0x729
  os.startProcess()
      /usr/local/go/src/os/exec_posix.go:63 +0x78f
  os.StartProcess()
      /usr/local/go/src/os/exec.go:111 +0x71
  os/exec.(*Cmd).Start()
      /usr/local/go/src/os/exec/exec.go:693 +0xa35
  os/exec.(*Cmd).Run()
      /usr/local/go/src/os/exec/exec.go:587 +0x26
  go.keploy.io/server/pkg/hooks.(*Hook).runApp()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/launch.go:524 +0x9c4
  go.keploy.io/server/pkg/hooks.(*Hook).LaunchUserApplication()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/launch.go:252 +0x2b7e
  go.keploy.io/server/pkg/service/test.(*tester).InitialiseRunTestSet.func1()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:354 +0x16d

Goroutine 50 (running) created at:
  go.keploy.io/server/pkg/service/test.(*tester).InitialiseRunTestSet()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:353 +0x18b6
  go.keploy.io/server/pkg/service/test.(*tester).RunTestSet()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:559 +0x4e7
  go.keploy.io/server/pkg/service/test.(*tester).Test()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:236 +0xc35
  go.keploy.io/server/cmd.(*Test).GetCmd.func1()
      /home/shashank/Documents/Developer/keploy/cmd/test.go:273 +0x26b0
  github.com/spf13/cobra.(*Command).execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0xca5
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x617
  github.com/spf13/cobra.(*Command).Execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1104
  go.keploy.io/server/cmd.(*Root).execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:262 +0x1105
  go.keploy.io/server/cmd.Execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:176 +0x4d1
  main.main()
      /home/shashank/Documents/Developer/keploy/main.go:52 +0x469
==================`

**Comment by shashank-iitbhu** [comment]
Found 2 more data race conditions while testing a web application using TLS.
```==================
WARNING: DATA RACE
Read at 0x00c000fca780 by main goroutine:
  go.keploy.io/server/pkg/hooks.(*Hook).StopUserApplication()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/loader.go:404 +0x105
  go.keploy.io/server/pkg/service/test.(*tester).RunTestSet.func1()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:573 +0xb8
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:477 +0x30
  go.keploy.io/server/pkg/service/test.(*tester).Test()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:236 +0xc35
  go.keploy.io/server/cmd.(*Test).GetCmd.func1()
      /home/shashank/Documents/Developer/keploy/cmd/test.go:273 +0x26b0
  github.com/spf13/cobra.(*Command).execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0xca5
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x617
  github.com/spf13/cobra.(*Command).Execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1104
  go.keploy.io/server/cmd.(*Root).execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:262 +0x1105
  go.keploy.io/server/cmd.Execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:176 +0x4d1
  main.main()
      /home/shashank/Documents/Developer/keploy/main.go:52 +0x469

Previous write at 0x00c000fca780 by goroutine 50:
  os/exec.(*Cmd).Start()
      /usr/local/go/src/os/exec/exec.go:693 +0xa57
  os/exec.(*Cmd).Run()
      /usr/local/go/src/os/exec/exec.go:587 +0x26
  go.keploy.io/server/pkg/hooks.(*Hook).runApp()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/launch.go:524 +0x9c4
  go.keploy.io/server/pkg/hooks.(*Hook).LaunchUserApplication()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/launch.go:252 +0x2b7e
  go.keploy.io/server/pkg/service/test.(*tester).InitialiseRunTestSet.func1()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:354 +0x16d

Goroutine 50 (running) created at:
  go.keploy.io/server/pkg/service/test.(*tester).InitialiseRunTestSet()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:353 +0x18b6
  go.keploy.io/server/pkg/service/test.(*tester).RunTestSet()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:559 +0x4e7
  go.keploy.io/server/pkg/service/test.(*tester).Test()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:236 +0xc35
  go.keploy.io/server/cmd.(*Test).GetCmd.func1()
      /home/shashank/Documents/Developer/keploy/cmd/test.go:273 +0x26b0
  github.com/spf13/cobra.(*Command).execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0xca5
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x617
  github.com/spf13/cobra.(*Command).Execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1104
  go.keploy.io/server/cmd.(*Root).execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:262 +0x1105
  go.keploy.io/server/cmd.Execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:176 +0x4d1
  main.main()
      /home/shashank/Documents/Developer/keploy/main.go:52 +0x469
==================
==================
WARNING: DATA RACE
Read at 0x00c000c675c0 by main goroutine:
  go.keploy.io/server/pkg/hooks.(*Hook).StopUserApplication()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/loader.go:419 +0x747
  go.keploy.io/server/pkg/service/test.(*tester).RunTestSet.func1()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:573 +0xb8
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:477 +0x30
  go.keploy.io/server/pkg/service/test.(*tester).Test()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:236 +0xc35
  go.keploy.io/server/cmd.(*Test).GetCmd.func1()
      /home/shashank/Documents/Developer/keploy/cmd/test.go:273 +0x26b0
  github.com/spf13/cobra.(*Command).execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0xca5
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x617
  github.com/spf13/cobra.(*Command).Execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1104
  go.keploy.io/server/cmd.(*Root).execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:262 +0x1105
  go.keploy.io/server/cmd.Execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:176 +0x4d1
  main.main()
      /home/shashank/Documents/Developer/keploy/main.go:52 +0x469

Previous write at 0x00c000c675c0 by goroutine 50:
  os.newProcess()
      /usr/local/go/src/os/exec.go:29 +0x729
  os.startProcess()
      /usr/local/go/src/os/exec_posix.go:63 +0x78f
  os.StartProcess()
      /usr/local/go/src/os/exec.go:111 +0x71
  os/exec.(*Cmd).Start()
      /usr/local/go/src/os/exec/exec.go:693 +0xa35
  os/exec.(*Cmd).Run()
      /usr/local/go/src/os/exec/exec.go:587 +0x26
  go.keploy.io/server/pkg/hooks.(*Hook).runApp()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/launch.go:524 +0x9c4
  go.keploy.io/server/pkg/hooks.(*Hook).LaunchUserApplication()
      /home/shashank/Documents/Developer/keploy/pkg/hooks/launch.go:252 +0x2b7e
  go.keploy.io/server/pkg/service/test.(*tester).InitialiseRunTestSet.func1()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:354 +0x16d

Goroutine 50 (running) created at:
  go.keploy.io/server/pkg/service/test.(*tester).InitialiseRunTestSet()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:353 +0x18b6
  go.keploy.io/server/pkg/service/test.(*tester).RunTestSet()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:559 +0x4e7
  go.keploy.io/server/pkg/service/test.(*tester).Test()
      /home/shashank/Documents/Developer/keploy/pkg/service/test/test.go:236 +0xc35
  go.keploy.io/server/cmd.(*Test).GetCmd.func1()
      /home/shashank/Documents/Developer/keploy/cmd/test.go:273 +0x26b0
  github.com/spf13/cobra.(*Command).execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0xca5
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x617
  github.com/spf13/cobra.(*Command).Execute()
      /home/shashank/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1104
  go.keploy.io/server/cmd.(*Root).execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:262 +0x1105
  go.keploy.io/server/cmd.Execute()
      /home/shashank/Documents/Developer/keploy/cmd/root.go:176 +0x4d1
  main.main()
      /home/shashank/Documents/Developer/keploy/main.go:52 +0x469
==================```

**Comment by shivamsouravjha** [comment]
@shashank-iitbhu this deals with the record flow at the moment. For TLS, how did you came across it?  is the app open sourced to check ?

**Comment by shivamsouravjha** [comment]
1. Race condition is happening because of process state being read in stopuserapplication and written in runapp, this process state can't be ignored as it informs about the state of application (to avoid closing an already closed application).
2. The issue states that value is read before it's written in case of exec command, removing isn't possible, so the race condition in unavoidable

**Comment by shivamsouravjha** [comment]
1. Tried looking at the solutions mentioned in [issue](https://github.com/golang/go/issues/28461) the solution linked aren't possible as one of solution was specific to windows library, and upon looking more closely it wasn't solving the error as it would start the execution and move ahead instead of waiting.
2. Similarly other solution still was prone to the error [Code Snippet](https://github.com/cirruslabs/cirrus-ci-agent/blob/3809e608477d33ffd49c116d566fe87155a53d2e/internal/executor/shell.go#L57).
3. Upon trying the mutex solution too we face deadlock condition as the wait would be blocking the process and keploy won't be able to terminate program.

**Comment by shivamsouravjha** [comment]
Race conditions were fixed after the revamp https://github.com/keploy/keploy/pull/1684
