### ISSUE TITLE
[feature]: Not requiring superuser

### ISSUE THREAD

**Issue by tomtastico** [keploy/keploy#1394]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It's not great that to run keploy it asks for superuser access. Feels like overkill for a testing system.

I understand this might be necessary to properly proxy requests, but would be great to find some way to not need superuser privileges.

### Why should this be worked on?

Requiring superuser privileges is a security issue that might hinder adoption (specially in enterprise)

### Repository

keploy

**Comment by slayerjain** [comment]
@tomtastico thanks for creating the issue. Keploy V2 uses eBPF to enable code-less instrumentation of application. This requires elevated privileges on most linux systems. 

A way to bypass this could be to run Keploy and the application in a VM or isolated docker container. Eg: Docker on windows or macOS runs on a separate VM and should allow keploy to run in docker mode without needing privileges over the entire system. 

What do you think?

**Comment by tomtastico** [comment]
I see, yes the docker option is a good alternative then to not require root directly in the host machine. Thanks for clarifying!
