### ISSUE TITLE
[feature]: Add capability to compress the mocks for particular test-set

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1395]
### Is there an existing feature request for this?

- [x] I have searched the existing issues

### Summary

Currently the mocks.yaml could become extremely huge, and so compressing them could reduce the size for git repos. 

### Why should this be worked on?

Current file sizes can make the git repos extremely big. 

### Repository

keploy

**Comment by gouravkrosx** [comment]
@slayerjain is this issue still relevant?

**Comment by slayerjain** [comment]
I think no longer relevant since we are planning to release mock registry
