### ISSUE TITLE
[docs]: update missing information in the flask+mongo python sample

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1399]
### What do you want to add to the docs? (please state reasons if any)

here are some issues I saw while trying for macOS:
1. Keploy no longer requires colima for macos. 
2. Creating Docker Volume is also no longer required for macos
3. keploy record command is incorrect.
4. POST request is incorrect
5. Command to build the application docker container is missing.
6. The application docker commands should also include `--rm` so that the containers can be reused. 

It would also be good to try and see if there are also inconsistencies in windows and linux guides. 

### Where is this stated?

https://keploy.io/docs/quickstart/samples-flask/

### Repository

keploy

**Comment by Akash-Singh04** [comment]
https://github.com/keploy/docs/pull/324

I made a PR for this, Kindly look into it

**Comment by Akash-Singh04** [comment]
@nehagupta  The PR has been merged, if there aren't any more deliverables this issue can be closed,

**Comment by shivamsouravjha** [comment]
closing the issue as its solved
