### ISSUE TITLE
[docs]: Incorrect Naming in Side Navbar for Mux and MongoDB Sample App

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1402]
## Description
The side navbar of the [Mux and MongoDB sample app](https://keploy.io/docs/quickstart/samples-mux/) currently displays the name as "MUX+ Postgres," which is inaccurate. The correct representation should be "MUX + MongoDB." This discrepancy may cause confusion for users.

### Solution
Update the side navbar to accurately reflect the technologies used in the app.

### Screenshots
![image](https://github.com/keploy/keploy/assets/109217591/b05ffd0f-0cde-4498-bed1-90e2f4b1e4ac)

### Repository

docs

**Comment by Sonichigo** [comment]
The issue isn't correct! Since the sample app is MUX-SQL app itself, so the side navbar is correct and needs no changes!
