### ISSUE TITLE
[docs]:  add README for spring petclinic

### ISSUE THREAD

**Issue by PranshuSrivastava** [keploy/keploy#1416]
### What do you want to add to the docs? (please state reasons if any)

So that people can easily use the petclinic application and seamlessly integrate keploy with it. 

### Where is this stated?

The documentation currently doesn't exist, it needs to be added.

### Repository

keploy

**Comment by PranshuSrivastava** [comment]
Done [here](https://github.com/keploy/samples-java/pull/62)

**Comment by shivamsouravjha** [comment]
closing as this issue is solved
