### ISSUE TITLE
[feature]: remove extra steps from macos and linux startup

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1417]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We can remove redundant conditions: 

1. macOS: remove different steps for colima and docker. 
2. macOS: remove sudo
3. Linux: remove docker condition after its no longer required. 

### Why should this be worked on?

Will improve installation UX. 

### Repository

keploy

**Comment by gouravkrosx** [comment]
This issue has been resolved. Now, the new installation is uniform and handles all the mentioned scenarios.
