### ISSUE TITLE
[bug]: parsers throw random errors when connections are closed

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There are many junk errors which are thrown when keploy stops. We need to avoid logging unnecessary errors for different parsers. 

Please list the errors from each parser once you handle them during exit. 

### Steps to reproduce

1. Start application in record mode.
2. Stop keploy and see random junk errors. 

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by slayerjain** [comment]
We need to gracefully stop the TCP connections instead of ignoring connection errors during shutdown.

**Comment by gouravkrosx** [comment]
This issue has been resolved and no longer exists.
