### ISSUE TITLE
[feature]: Improve the API for the JUnit integration

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1422]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to have cleaner user facing APIs for the JUnit Java integration library to work with keploy v2.  Need to document on docs.keploy.io along with example. 

### Why should this be worked on?

Current approach requires putting too much code to copy-paste by the user. 

### Repository

keploy

**Comment by slayerjain** [comment]
@Sarthak160 please add the PR and documentation link here.

**Comment by Sarthak160** [comment]
https://github.com/keploy/java-sdk/pull/163#issue-2111583413

**Comment by shivamsouravjha** [comment]
closing the issue as solved
