### ISSUE TITLE
[feature]: create test summary aggregate for multiple tests

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1424]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to ensure we have an aggregate test summary when there multiple test-sets run in keploy-test

### Why should this be worked on?

Important to provide summary to the user 

### Repository

keploy

**Comment by officialasishkumar** [comment]
Hey @slayerjain,

#1326  solves this

**Comment by gouravkrosx** [comment]
solved by #1326
