### ISSUE TITLE
[feature]: add race condition check in the test bench

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1427]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be good to check if there are any race conditions introduced by any PR. 

### Why should this be worked on?

Race conditions are hard to detect and lead to unexpected/random behaviour during runtime. 

### Repository

keploy

**Comment by gouravkrosx** [comment]
@shivamsouravjha Did you add the `race` flag in each of the test pipelines?

**Comment by shivamsouravjha** [comment]
Have added the same
