### ISSUE TITLE
[bug]: navbar broken for larger screens in keploy-docs

### ISSUE THREAD

**Issue by cu8code** [keploy/keploy#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when i make the website full screen(1920 x 1200) it break the navbar in the docs.

https://github.com/keploy/keploy/assets/109351887/941f7b35-bbcc-421b-8ca0-22fe32559ed1

### Steps to reproduce

1. open the docs in the browser
2. full screen the browser
3. it breaks

### Environment

Production

### Version

Cloud

### Repository

docs

**Comment by cu8code** [comment]
i would like to work on this issue.

**Comment by vr-varad** [comment]
@cu8code are u working on it could I give it a try?

**Comment by cu8code** [comment]
I already made a PR

**Comment by nehagup** [comment]
Thanks for reporting @cu8code ! Please give it a try.

**Comment by vr-varad** [comment]
@nehagup can i give it a try??

**Comment by cu8code** [comment]
@nehagup @vr-varad I am busy with something else.

**Comment by Akash-Singh04** [comment]
![image](https://github.com/keploy/keploy/assets/114267538/03aecd53-1fec-4462-9b5a-f01021b14fdd)


Hey, i am unable to reproduce this issue, Does it happen specifically on some browsers? 
Kindly close the issue if this is resolved, Thanks

**Comment by nehagup** [comment]
This issue has been resolved, closing!
