### ISSUE TITLE
[feature]: download all generated test cases

### ISSUE THREAD

**Issue by luudis** [keploy/keploy#143]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- download all the generated test cases
- place them into original code and works with go test

### Why should this be worked on?

All tech teams demand high test coverage of all programs. We use bamboo to run pipeline of unit tests. Maybe we can download the test cases generated by kepoly and use them in bamboo pipelines. If this works , it can save lots of time of writing unit test code.

**Comment by slayerjain** [comment]
@luudis thanks for creating the feature request :)

We are working on the design of code export feature.  

For now, have you tried the `go test` integration which you could use with bamboo? - https://github.com/keploy/keploy#integration-with-native-go-test-framework

Its also available in the sample application - https://github.com/keploy/samples-go/blob/main/echo-sql/main_test.go

This should allow you to run keploy tests along with your existing units tests with `go test` anywhere including bamboo.

**Comment by anirudhjain75** [comment]
This would be great to have.

**Comment by slayerjain** [comment]
We've started working on this.

Tests will be exported as yaml and be editable by the user. Mocks will also be exported separately and can be used in isolation.

**Comment by luudis** [comment]
@slayerjain I am glad to hear this. It will be an awesome feature for us!

**Comment by Sarthak160** [comment]
Done by #175
