### ISSUE TITLE
Add a timer to the keploy recorder

### ISSUE THREAD

**Issue by heyyakash** [keploy/keploy#1434]
###  Is there an existing feature request for this?
- [x]  I have searched the existing issues
### Summary
Add a timer to the keploy recorder to gracefully stop and exit the recorder when the timer ends
### Why should this be worked upon
This can be useful in scenarios where you want to limit the testing time, especially in continuous integration (CI) pipelines or automated testing environments.
### Repository
keploy

**Comment by EraKin575** [comment]
@heyyakash are you working on this issue?

**Comment by officialasishkumar** [comment]
😐

**Comment by heyyakash** [comment]
> @heyyakash are you working on this issue?

Yes
