### ISSUE TITLE
[bug]: Test mode for spring-pet-clinic is failing due to Postgres

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#1443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

1. In test mode spring-pet-clinic outputs 7-9 test failures out of 50-60

### Steps to reproduce

1. Record 50-60 test cases for spring-pet-clinic
2. Run test mode

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by gouravkrosx** [comment]
This issue has been resolved after custom matching of the Postgres parser.
