### ISSUE TITLE
[bug]: Bug in display of differences for a object response  

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* If the response is a map and the value is an array and the order is changed for response a very non helpful difference log appears.
<img width="749" alt="image" src="https://github.com/keploy/keploy/assets/60891544/7e44a1bc-c6af-45dc-bceb-7e801117e15d">
* Also elements missing from response in map. as this was the actual response 
<img width="247" alt="image" src="https://github.com/keploy/keploy/assets/60891544/c75bd8b8-ff78-4f66-99c7-0c063c48eeab">

### Steps to reproduce

```
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]]; // Swap elements
    }
}
router.get('/get', async (req, res) => {
    try {
        const mixedArray = [
            "String element",
            { key: "Object element" },
            [[1, 2], [3, 4]], // Array of arrays
            { numbers: [1, 2, 3, 4, 5] }, // Array in an object
            {}, // Empty object
            12345, // Number
            true // Booleanxw
        ]
        
        shuffleArray(mixedArray)
        console.log(mixedArray);
        res.status(200).json({"dsf":1,"sda":mixedArray});
    }
    catch (err) {
        res.status(400).send(`Failed to fetch req details as ${err}`);
    }
})```

In express-mongoose replace the get router with this, record and test for this endpoint

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by gouravkrosx** [comment]
@shivamsouravjha is this resolved? if yes please close this issue.

**Comment by shivamsouravjha** [comment]
This is linked in another issue.
