### ISSUE TITLE
[feature]: Dynamically include Keploy's custom CA in the application container.

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1461]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, to enable TLS with Keploy in Docker, we need to [modify](https://keploy.io/docs/running-keploy/docker-tls/#heading) the application's Dockerfile. This involves adding Keploy's custom CA to the appropriate root CA path for different languages. To simplify this process, Keploy can dynamically add its custom CA upon container startup, utilizing the `overlayfs` concept to access the container's filesystem from the host.

### Why should this be worked on?

This enhancement will enhance user experience by eliminating the need for manual Dockerfile modifications. Everything will occur seamlessly in the background without user intervention.

### Repository

keploy

**Comment by starvader13** [comment]
@Swpn0neel This seems like an interesting idea to work on. Could you assign this to me?

Also, as far as I understood, I need to go through the overlayfs and then create a custom CA using Bash Scripting. And make sure that this script runs at startup.

Questions:
1. Is there any reference or documentation to help me build a custom CA? This is new to me.
2. What steps or modifications are needed in the Keploy setup to integrate this functionality?

**Comment by Swpn0neel** [comment]
Yes @starvader13 Go ahead!! @gouravkrosx can help you more about the issue, and also feel free to ask any questions in our sleack #dev channel!

**Comment by gouravkrosx** [comment]
@starvader13 You can maybe work on the below issue. Since our earlier assumption was that it would work, but the mentioned approach won't work, you can just refer to the new issue for a better understanding of why it would not work.
https://github.com/keploy/keploy/issues/2080

Meanwhile I am closing this issue.
