### ISSUE TITLE
[feature]: race flag in CI pipeline

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1467]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

* While building Keploy use the race flag to build the binary to know the race conditions.

### Why should this be worked on?

* Helps identify race conditions prior to merge the build.

### Repository

keploy

**Comment by Akash-Singh04** [comment]
Hey, I would like to work on this!

**Comment by Akash-Singh04** [comment]
Hey @shivamsouravjha , I assume this issue still needs help. 
Do you have any specific requirements or preferences regarding the implementation of the race flag feature? Any form of elaboration/context on which CI pipeline is being referred to and where the race flag is present would be of great assistance!

**Comment by shivamsouravjha** [comment]
1. Yes this still needs to be taken up.
2. This is Keploy's pipeline.
3. If we just add the flag it won't be of big help as race flags just logs and doesn't throw any error(we don't want errors too as there are pre-existing conditions which are in process of being solved). Probably a way where a workflow collects race logs from all other workflow and notifies if a new is added.
