### ISSUE TITLE
[bug]: only add sudo to docker alias for linux if required

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

By default docker requires using `sudo` in most linux distros. There are ways to avoid adding the sudo flag everytime. Keploy should check if docker is executable without `sudo` and use the alias (used during installation accordingly"  

### Steps to reproduce

1. install keploy on linux select docker using -  curl -O https://raw.githubusercontent.com/keploy/keploy/main/keploy.sh && source keploy.sh
2. keploy will ask for sudo everytime. can be verified with `alias docker`

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by Akash-Singh04** [comment]
Hey, I would like to work on this!

**Comment by Akash-Singh04** [comment]
@slayerjain Kindly review the PR!
