### ISSUE TITLE
DCO integration

### ISSUE THREAD

**Issue by Akshit42-hue** [keploy/keploy#147]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Can we integrate DCO to Keploy ?
WDYT// @slayerjain @nehagup 

### Why should this be worked on?

The DCO is a per-commit sign-off made by a contributor stating that they agree to the terms published at https://developercertificate.org/ for that particular contribution.

**Comment by nehagup** [comment]
Thanks @Akshit42-hue it'll be a good addition!

**Comment by khanjasir90** [comment]
is anyone working on this or can I take this one up!

**Comment by nehagup** [comment]
@khanjasir90 feel free to take this up. 🙂

**Comment by khanjasir90** [comment]
Actually @nehagup , It would require to Log in as user with Owner rights to a GitHub organization and then configure the dco from this https://github.com/apps/dco.

**Comment by nehagup** [comment]
@khanjasir90 I've configured the same. :)
