### ISSUE TITLE
[refactor]: samples-go to fix linter errors

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1474]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

* After the addition of golint for samples-go numerous linter issues surfaced because of which pipeline fails.

### Why should this be worked on?

* Improve code quality for sample go-apps

### Repository

samples-go

**Comment by Yaxhveer** [comment]
@shivamsouravjha I would like to work on this issue.
