### ISSUE TITLE
[feature]: use struct instead of passing in individual flags in record and test command

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1482]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

* In capture traffic we have different flags that are passed from command layer to service layer.
* As more flags are introduced there might be too much alterations in different files and merge conflicts too.
* Instead of passing all values in `CaptureTraffic` rather define a struct, assign values from flags and pass it into the `CaptureTraffic`.
* `getTestConfig` can be made global.
* `getTestConfig` and `GetRecordConfig` can be passed the struct instead of passing each param.

### Why should this be worked on?

* Better coding practice and less merge conflicts.

### Repository

keploy

**Comment by Akash-Singh04** [comment]
Hey, Will get to work on this. Kindly assign it, Thanks!

**Comment by Akash-Singh04** [comment]
@shivamsouravjha  Kindly Review this PR at your earliest convenience!
