### ISSUE TITLE
[feature]: Add java SDK

### ISSUE THREAD

**Issue by Arushisingh23** [keploy/keploy#149]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Include Java and well-known framework support so that Java application developers may use Keploy.

### Why should this be worked on?

I received several requests to add Java support from Reddit, LinkedIn, and YouTube. It's also one of the languages that businesses utilize the most frequently.

**Comment by nehagup** [comment]
@Arushisingh23 This is a duplicate issue. Please check this one - https://github.com/keploy/keploy/issues/52 

If this is related to something else please feel to add more details and re-open.
