### ISSUE TITLE
[bug]: sorting order of test cases wrong 

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If there are large number of testcases recorded (5-10) every second. Then keploy would sort the testcases wrong, which could result in weird behaviour because the order of the mocks could change. 

This happens because tests are sorted on the `created` field, which has upto 1 second accuracy (eg: `1707070012`. So every testcase recorded in the same second will have the same `created` timestamp field value. 

We should instead sort it on the req timestamp, which has accuracy upto nsecs (eg: `2024-02-04T23:36:51.888317999+05:30`)

### Steps to reproduce

1. Use some generator to record the test cases (which can generate at least 5 tests/sec). 
2. Try running keploy in test mode, and check the order of execution. 

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by Yaxhveer** [comment]
@slayerjain I would like to work on this issue.

**Comment by slayerjain** [comment]
Please feel free to try :)

**Comment by Akash-Singh04** [comment]
@slayerjain Kindly review the PR and let me know if the bug persists
