### ISSUE TITLE
[bug]: Replacement for the links in community and blog pages in blog website.

### ISSUE THREAD

**Issue by Aditya-eddy** [keploy/keploy#1502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I go to the community or Blog (technology)  page. and choose a post and click on the author. It redirects us to https://keploy.io/wp/author/ritik-jain/. But if we have a authors page which list all the authors and Indivisual author's page It should link to that.
![Screenshot from 2024-02-06 11-10-01](https://github.com/keploy/keploy/assets/70089590/7869d2fc-0586-4726-ae3d-18368516435e)

### Steps to reproduce

1. Select any post.
2. Press on the author and view all posts.
3. redirects us to the https://keploy.io/wp/author/ritik-jain/

### Environment

None

### Version

Cloud

### Repository

blog-website

**Comment by Aditya-eddy** [comment]
Hey @Sonichigo  can this issue can be included in  [keploy/issue/7](https://github.com/keploy/blog-website/pull/7) ?

**Comment by Sonichigo** [comment]
Let's keep this separate, this can be a good first issue for the folks looking to contribute
