### ISSUE TITLE
[bug]: fix social preview of blog posts

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we share the blog on social, the Social Preview Image is same for all blogs, instead of their own featured images (Header Image).

for example: - https://keploy.io/blog/community/securing-data-protocols-tls-application

**_Here, the acutal header image is different then what's being shown, as well as the blog name, it's description are also different._**
<img width="431" alt="image" src="https://github.com/keploy/keploy/assets/53110238/3a3f180e-c18a-4fba-950e-7005a7dee712">

### Steps to reproduce

1. go to twitter/slack/linkedin/other SM
2. Post the blog https://keploy.io/blog/community/securing-data-protocols-tls-application

### Environment

Deploy preview

### Version

Cloud

### Repository

blog-website

**Comment by Aditya-eddy** [comment]
Hey @Sonichigo  can you assign me this issue. Thanks!!

**Comment by Aditya-eddy** [comment]
Hey @Sonichigo i have created a pr [issue](https://github.com/keploy/blog-website/pull/9). Please checkout when you get to it. Thanks!!.
