### ISSUE TITLE
[feature]: Improve the Test Summary Output result for PR

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1506]
Right now, only test summary result will show if there are multiple testset or test suites because the logic being used searches for 4 lines and append them to file `KEPLOY_REPORT`. 
```
  TESTRUN SUMMARY. For testrun with id: "test-set-0"
	Total tests: 0
	Total test passed: 0
	Total test failed: 0
```
This logic fails if we have more than 1 test-set as in that case only last test-set summary will be saved and output to the PR.  It's better to update this logic based on the this PR result https://github.com/keploy/keploy/pull/1326 .

**Comment by Akash-Singh04** [comment]
Working on this, Submitting a PR soon!

**Comment by Akash-Singh04** [comment]
@Sonichigo Kindly check the Pull request for this issue. #1326 Needs to be merged first if i am not wrong

**Comment by Akash-Singh04** [comment]
@Sonichigo This issue can be closed now i suppose
