### ISSUE TITLE
[bug]: the Body is empty in github/action script

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1507]
Create issue/pr comment is not working as expected anymore. this is because the `actions/github-script@v6` has field : - `body: process.env.KEPLOY_REPORT` which is blank, implying that the testrun summary is not getting saved to the file in the previous step.

```
RequestError [HttpError]: Validation Failed: {"resource":"IssueComment",
"code":"unprocessable","field":"data","message":"Body cannot be blank"}
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:6842:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 422,
```

This results to GitHub Action Check Failing. Here we maybe also need error handling, so that in unexpected cases users can debug the problems faster and easily.

**Comment by Aditya-eddy** [comment]
Working on this @Sonichigo will be submitting a pr soon. Thanks!!

**Comment by Akash-Singh04** [comment]
@Aditya-eddy Are you still working on this?

**Comment by Aditya-eddy** [comment]
@Akash-Singh04 you can work on this issue!!
