### ISSUE TITLE
[feature]: Implement custom matching for postgres parser 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1508]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Currently, Postgres is using generic fuzzy match which is based on binary matching. 
- Since we have seen there are lot of cases where it can give false positive, like in case of exact same preparedstatements.
- This has been replicated in samples-java/petclinic app , create more than 30 testcases and it will result in either mismatch or JPA transaction error .
- Along with custom matching we have to implement a n internal map of each prepared statement for connection . 

 

### Why should this be worked on?

This should be done to make psql parser more robust and stable .

### Repository

keploy

**Comment by gouravkrosx** [comment]
Closing as it is already integrated in main.
