### ISSUE TITLE
feat: option to disable ANSI color codes

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently when we are logging to places where ANSI color codes are not supported eg: piping to a file - the output is not readable. We use ANSI color codes to show colors in terminals, but they are not supported in log files and CI. 

We should provide an option to disable ANSI color codes. 

### Steps to reproduce

1. Record tests for any application with keploy. 
2. run testmode by pipping to a file. eg:`keploy test -c "some app command" &> log.txt`
3. You will see random charaters appened instead of colors. 

eg: 

```
  TESTRUN SUMMARY. For testrun with id: [31m[1m"[0m[31mtest-set-0[0m[31m[1m"[0m
	Total tests: [34m[1m79[0m
	Total test passed: [34m[1m66[0m
	Total test failed: [34m[1m13[0m
	```

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by Akash-Singh04** [comment]
I think we can add a CLI flag and a config flag to do this, Working on the implementation right away

**Comment by Akash-Singh04** [comment]
@slayerjain PR has been made, along with relevant screenshots to satisfy the flag is working as intended. Kindly check it and let me know if any changes are required
