### ISSUE TITLE
[feature]: redirect the incoming traffic for user app to proxy in macos

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1521]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Redirect the incoming traffic to the Keploy proxy in order to add the support for macOs native. And forward the traffic to the actual application to capture the request and response. Just log the incoming payloads for the Proxy.

### Why should this be worked on?

This can be used to record/test the responses of the APIs.

### Repository

keploy

**Comment by re-Tick** [comment]
Can take reference from the [mitm transparent proxy](https://docs.mitmproxy.org/stable/howto-transparent/#macos)

**Comment by Swpn0neel** [comment]
is this issue still active @re-Tick ?

**Comment by re-Tick** [comment]
@Sonichigo what is the update on this. Please check.

**Comment by charankamarapu** [comment]
Tracking this feature in other issue.
