### ISSUE TITLE
[feature]: filter the incoming traffic for the user app in macos

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1522]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently incoming traffic is filtered according to the process id of the application, similarly to add support for macOs native the network traffic should be filtered and only requests for the user application should be redirected to the Keploy proxy.

### Why should this be worked on?

This will add option to configure the user application dynamically from the CLI command.

### Repository

keploy

**Comment by shubham-sonthalia** [comment]
Hi @re-Tick , can I work on this issue?

**Comment by re-Tick** [comment]
Hi @shubham-sonthalia, the issue is open for all. And the task is to redirect the external network calls from the app to the keploy proxy. In linux, we use processId filter to redirect only the network calls from the target user application.

**Comment by shubham-sonthalia** [comment]
Okay, I am working on this.

**Comment by distrowar** [comment]
Hey @re-Tick can you explain on how process id is filtered for linux? 

And where macos implementation starts?

**Comment by re-Tick** [comment]
The filtering is done by having the process id of target application started by keploy and the process id of the program which called the ebpf hook.

**Comment by thebigbone** [comment]
One question: Is it not possible to simply use the unix TCP/UDP socket for capturing the network traffic instead of using eBPF?

**Comment by slayerjain** [comment]
@thebigbone can you please explain how you will capture TCP/UDP socket traffic transparently?

**Comment by Swpn0neel** [comment]
is this issue still active @slayerjain ?

**Comment by charankamarapu** [comment]
Tracking this feature in other issue.
