### ISSUE TITLE
[feature]: redirect the outgoing traffic for the user app in macOs native

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1523]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Redirect the network traffic of the user app to the Keploy proxy, which is outgoing calls from the app. This will add support for mocking the external calls. And just log the request/response of the network call in the proxy.

### Why should this be worked on?

This will help in adding support for the mocking in the proxy.

### Repository

keploy

**Comment by re-Tick** [comment]
Can take reference from the [mitm transparent proxy](https://docs.mitmproxy.org/stable/howto-transparent/#macos)

**Comment by officialasishkumar** [comment]
I would like to work on this

**Comment by Sonichigo** [comment]
Hey @officialasishkumar just checking-in if you are still working on this ?

**Comment by officialasishkumar** [comment]
Hey @re-Tick, can you please add some more context on this issue? I'm unable to figure out the task.

**Comment by re-Tick** [comment]
Hi @officialasishkumar, currently the ebpf hooks are used to redirect the network traffic for a target user application by using the processId of the user app. Similarly, in macOs support the traffic can be redirected using the [pf](https://en.wikipedia.org/wiki/PF_(firewall)) like the [mitm](https://docs.mitmproxy.org/stable/howto-transparent/#macos) proxy support.

**Comment by Sonichigo** [comment]
@slayerjain is this issue active ?

**Comment by charankamarapu** [comment]
Tracking this feature in other issue.
