### ISSUE TITLE
[feature]: Implement JavaScript Script for Automated Keploy Updates

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1524]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Objective:
Create a JavaScript script to automatically download and update the latest Keploy binary from GitHub. Additionally, ensure platform-specific updates, such as Docker images for users employing Docker. 
For now you can make that script inside the main keploy repo only later we might migrate to another repo for the vs code extension.

Features:

- Fetches the latest Keploy release from GitHub.
- Checks for updates and replaces older binaries.
- Provides platform-specific updates (e.g., docker for mac, colima, wsl2, linux native).
Expected Behavior:

Script checks for updates and replaces older versions.
Handles platform-specific updates seamlessly.

### Why should this be worked on?

This can be the foundation for integrating keploy via vs code extenstions

### Repository

keploy

**Comment by Akash-Singh04** [comment]
Hey there, could you provide some more insight into this issue? Why is this feature required when ```keploy update``` command already exists?

**Comment by Akash-Singh04** [comment]
Working on this in this Repo: https://github.com/Akash-Singh04/KeployVScodeExtension

Currently the [Vscode extension](https://marketplace.visualstudio.com/items?itemName=Akash-Singh04.heykeploy) has a version function that gets the latest version. Working on integrating a script for updatiing keploy here

**Comment by Akash-Singh04** [comment]
Hey there! The [Vscode Extension](https://marketplace.visualstudio.com/items?itemName=Akash-Singh04.heykeploy) now supports  Keploy Update Command!

Working on refining the script  even further to support platform-specific updates

**Comment by Akash-Singh04** [comment]
@Sarthak160 Super excited to inform you that  [Keploy Extension](https://marketplace.visualstudio.com/items?itemName=Akash-Singh04.heykeploy) now provides platform-specific updates!

The script:
Script checks for updates and replaces older versions.
Handles platform-specific updates seamlessly.

However, there was an interesting limitation i found in the VSCode Extensions API, Which i have documented here: [Limitation](https://github.com/Akash-Singh04/KeployVScodeExtension?tab=readme-ov-file#limitations).

Let me know how this can be improved further. Had a lot of fun!

**Comment by Akash-Singh04** [comment]
@Sonichigo Now that GSoC has begun and this was a qualifier task, I think this issue can be closed to avoid redundance.
