### ISSUE TITLE
[feature]:  Implement GitHub Actions Workflow for VS Code Extension Publishing

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1525]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

**Objective:**
Create a GitHub Actions workflow to automate publishing Visual Studio Code extensions to the Marketplace.

**Features:**
- Sets up Node.js environment.
- Installs dependencies.
- Packages extension into .vsix file.
- Publishes extension to the Marketplace using provided access token.

**Acceptance Criteria:**
- Workflow successfully packages and publishes the extension upon release.
- It should be well tested by making a sample dummy extension and deploying to marketplace
- Workflow tested for reliability and error handling.

**Note:** This task is a good first issue for contributors interested in GitHub Actions and automation.

### Why should this be worked on?

This can be the foundation for integrating keploy via vs code extenstions.

### Repository

keploy

**Comment by Aditya-eddy** [comment]
Hey @Sarthak160 I have a question. Do we have to create our own repo and then share here? Thanks!!

**Comment by Akash-Singh04** [comment]
Hey there @Sarthak160  I have created a VScode Extension [HeyKeploy](url) that fetches the latest version of keploy and displays it on the KeployVersion command

I have implemented automated github actions workflow for deploying it to Vscode marketplace

Here is the repository link: https://github.com/Akash-Singh04/KeployVScodeExtension/

**Comment by Sarthak160** [comment]
> Hey @Sarthak160 I have a question. Do we have to create our own repo and then share here? Thanks!!

Hey @Aditya-eddy, yes you have to create a sample extension on your own!

**Comment by Sonichigo** [comment]
@Sarthak160 can you please review the @Akash-Singh04 submission!!

**Comment by Sonichigo** [comment]
@Aditya-eddy check-in to know if you are working on the issue ?

**Comment by olawoyinsamson** [comment]
Hi @Sarthak160 ,I'm interested in working on this issue,  will like to give this task a try and this is how i intended to resolve this issue. I will branch (new branch for the issue resolution github-actions) out of main branch  in the keploy/keploy repo and then implement the following Github Action workflow for packing a sample extension and published via the market place.

**Comment by Sonichigo** [comment]
hi @olawoyinsamson !! Sounds good, you can pick up the task of building keploy vscode extentsion to try out the workflow!

**Comment by Sonichigo** [comment]
> Yes I have created a VScode publishing extension. But since it was just a dummy vscode extension I did'nt comment. But I did successfully created the Github Action WorkFlow for it which publishes the extension. Here's the link to my repo:-- 1.[My runKeploy Repo](https://github.com/Aditya-eddy/runKeploy) It was first time working with github Action Workflow. And I had a good time. Thanks!!

Hey @Aditya-eddy, any progress on this ?

**Comment by Aditya-eddy** [comment]
Currently not! But will soon make pr for it!!

**Comment by Akash-Singh04** [comment]
@Sonichigo Now that GSoC has begun and this was a qualifier task, I think this issue can be closed to avoid redundance.

**Comment by Sonichigo** [comment]
Since this issue is not relevant for now closing it.
