### ISSUE TITLE
[feature]: add code syntax highlighting and copy button to blogs code blocks

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1527]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently in the code-blocks mentioned on any blog on https://keploy.io/blog doesn't have a code syntax highlighting. It'll be better to add - 

- Code syntax highlighting, maybe by using prisms or similar library 
- Add a Copy button to the code blocks 

 

### Why should this be worked on?

Improves blog understanding and reading. 

### Repository

blog-website

**Comment by Aditya-eddy** [comment]
@nehagup working on this issue will be submitting a pr soon.
