### ISSUE TITLE
[feature]: add copy block button in the docs website 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1530]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

we're using docusaurus in docs-website and the code-blocks should be easy to copy with a copy button. 

This was being worked at https://github.com/keploy/docs/pull/297 but the approach is not feasible to be copied to all code block, in order to keep it simple for the contributors to write in md format. 

### Why should this be worked on?

to save time copying code. 

### Repository

docs

**Comment by Aditya-eddy** [comment]
hey @nehagup working on it. Will be submitting a pr soon. Thanks!!
