### ISSUE TITLE
[bug]: remove explicit chmod commands from keploy codebase

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We currently have multiple `chmod` commands within the keploy codebase. This creates dependency on the library and so we must handle this programatically. 

Since keploy runs as root (using the sudo command), the files created by keploy are not editable by other users by default (even after setting broader file permission during create). The `chmod` command ensures that generated yamls are user editable. 

### Steps to reproduce

eg: https://github.com/keploy/keploy/blob/main/pkg/proxy/util/util.go

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by Akash-Singh04** [comment]
Working on this!

**Comment by shivamsouravjha** [comment]
Issue seems to be resolved after refactor.
