### ISSUE TITLE
[bug]: Hero Image Not Responsive on Mobile Devices

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#1537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

# Description:
The hero image on the website [writers.keploy.io](https://writers.keploy.io/) is not responsive in the mobile design, causing it to overlap with the text content. This issue persists across various devices and screen sizes, disrupting the user experience and readability.

### Additional Information:
- This issue affects the overall usability and aesthetics of the website on mobile platforms.
- Providing a responsive design for the hero image will enhance the mobile user experience and improve readability.
- This bug may require adjustments to the CSS styling or implementation of media queries to ensure proper responsiveness across different devices and screen resolutions.

## ScreenShot:

![image](https://github.com/keploy/keploy/assets/109217591/de5e031a-ee70-4211-bb14-6950ffba7bc4)

![image](https://github.com/keploy/keploy/assets/109217591/7b1b9eb1-03ee-43e5-88af-bed79f3f4a67)

### Steps to reproduce

1. Access the website [writers.keploy.io](https://writers.keploy.io/) on a mobile device or through a mobile browser.
2. Navigate to the homepage or any page where the hero image is displayed.
3. Notice that the hero image overlaps with the text content, making it difficult to read.

### Environment

None

### Version

Cloud

### Repository

writers-program

**Comment by jaiakash** [comment]
I check the website just now, its fixed yeah?

**Comment by fknemi** [comment]
this doesn't seem to have been fixed.... can this be assigned to me?

**Comment by fknemi** [comment]
@Arindam200  can this issue be assigned to me.... it is still there on [writers.keploy.io](https://writers.keploy.io/)

**Comment by Swpn0neel** [comment]
Does this issue still persist? @Sonichigo

**Comment by Sonichigo** [comment]
Yes

**Comment by shreyashrpawar** [comment]
I would like to work on this issue for KROC

**Comment by Swpn0neel** [comment]
Please go ahead! @shreyashrpawar

**Comment by shreyashrpawar** [comment]
https://github.com/keploy/writers-program/pull/10

Solved the issue pull request #10 at keploy/writer's program

**Comment by dakshmehta007** [comment]
@Arindam200  sir I recently check. your Issue was solved.
