### ISSUE TITLE
[bug]: Keploy fails with "docker start <container>" as user app command

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#1539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

1. Keploy is not build with considering this type of command, so it will be most probably fail this case. 
2. We need to test the behaviour of this command and make sure this works.
3. Need to deal with how we stop the container once we stop keploy. We need to make sure that we don't kill the container etc 

### Steps to reproduce

1. Run keploy in record mode and use a docker application and use docker start container command.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by Yaxhveer** [comment]
Working on this
