### ISSUE TITLE
[feature]: Ability to mock out sensitive information like secrets from tests cases

### ISSUE THREAD

**Issue by anirudhjain75** [keploy/keploy#154]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Would be great to have ability to remove sensitive information like keys, secrets, etc from generated testcases as some client calls also contains them. Incase the output of testcase is generated, sensitive fields in functions / rest api calls should be removed.

### Why should this be worked on?

This will improve the security of the applications as generated test files can be kept in repo without the secrets.

**Comment by charankamarapu** [comment]
hi @anirudhjain75 , In the databases which we support like mongo, oracle we need passwords and secrets etc. In these cases we never store the password as it is, passwords will be either encrypted or salted. If a database or API is using any encryption to hide those passwords or secrets, keploy will also use the same encryption methods and store the password in the yaml. When it comes to production scenarios where people use keploy in production, we are adding an option to store mocks and tests in mongoDb. So if someone is worried about their data being in repos they can use their mongo instances to store mocks and testcases.

If you still think there is a possibility that some password/secret in a particular case is not encrypted in yaml please provide an example. We are happy to take that and solve it.

**Comment by gouravkrosx** [comment]
@anirudhjain75 , is this still relevant for you? 

> hi @anirudhjain75 , In the databases which we support like mongo, oracle we need passwords and secrets etc. In these cases we never store the password as it is, passwords will be either encrypted or salted. If a database or API is using any encryption to hide those passwords or secrets, keploy will also use the same encryption methods and store the password in the yaml. When it comes to production scenarios where people use keploy in production, we are adding an option to store mocks and tests in mongoDb. So if someone is worried about their data being in repos they can use their mongo instances to store mocks and testcases.
> 
> If you still think there is a possibility that some password/secret in a particular case is not encrypted in yaml please provide an example. We are happy to take that and solve it.
