### ISSUE TITLE
[bug]: race condition in mongo parser

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* Race condition as read and write concurrently at `configRequests`, `logger` in decode , 
![image](https://github.com/keploy/keploy/assets/60891544/4f3fa930-6184-451a-9332-85e44c08433d)

![image](https://github.com/keploy/keploy/assets/60891544/b49c8424-6d2d-4dd2-9feb-cf346cbfaf46)

![image](https://github.com/keploy/keploy/assets/60891544/7d3c72cb-b2e0-494f-913d-2f3267b13b0d)

### Steps to reproduce

* can be solved by creating copies in case of logger.

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by heyyakash** [comment]
Can you tell how can this error be reproduced?

**Comment by shivamsouravjha** [comment]
* You can build the keploy binary with `-race` flag.
* Use keploy with mongo based project eg~express-mongoose.

**Comment by AhmedLotfy02** [comment]
Hey @shivamsouravjha 
I performed the following command as you said
`sudo -E env PATH=$PATH keploy -race -c 'node /home/ahmed/Desktop/GSOC/Keploy/Issues/samples-typescript/express-mongoose/src/app.js'`
but i got that the flag isn't found in keply:
![image](https://github.com/keploy/keploy/assets/76037906/8e76fd86-a020-40c2-9a2b-7618303f0bfd)

**Comment by shivamsouravjha** [comment]
Hey @AhmedLotfy02 this race flag is to be used while building the binary.

```go build -race -o keploybin && sudo mv keploybin /usr/local/bin ```

here assumption is keploy alias is `keploy='sudo -E env PATH="$PATH" keploybin'`

**Comment by shivamsouravjha** [comment]
Solved after V2 revamp
