### ISSUE TITLE
[GSoC]: Build an app with multiple services, demonstrating contract testing

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1543]
- This task involves building an application comprised of multiple services, each with its unique functionality. The focus is on implementing contract testing, ensuring that these services communicate effectively based on predefined agreements. By rigorously testing these interactions, we can check the reliability of the application's architecture.
- This task can give an idea about how contract testing works and how we can incorporate the concept in keploy.

**Comment by AhmedLotfy02** [comment]
Hi @gouravkrosx I would like to know more about this issue (talking in slack for example)
is this about building multiple services each independent localhost with spring boot and test keploy on it?

**Comment by gouravkrosx** [comment]
@AhmedLotfy02 This task isn't exactly about keploy, but you need to understand contract testing first to add similar support to keploy. You'll be creating several microservices using any programming language, not just Spring Boot. The goal is to demonstrate how contract testing helps keep these microservices working together smoothly.

**Comment by AhmedLotfy02** [comment]
I made an architecture and want to know if I'm on the right way
the architecture is inspired from pact , consumer creates the contract (consumer driven contract) then send it to a middle layer which store the contract in any kind of repository so the consumer can fetch it any time for verification , also provider fetches the contract from repo and uses these contracts to perform verification. 
![image](https://github.com/keploy/keploy/assets/76037906/926e1ab8-826b-4b58-93c6-e3a0c05f107c)

**Comment by Akash-Singh04** [comment]
This Looks like a fun task to work upon and learn about contract testing. Will get working on this!

**Comment by AhmedLotfy02** [comment]
# Building two services demonstrating **Contract Testing**

## Architecture
<ul>
<li>
Assume we have two microservices "Order" and "Product" for simplification they are sharing the same file system.
</li>
<li>
For simplicification, order service request for products from product service.
<hr>
<ul><li>
<a href="https://ibb.co/VtMYZ9Y"><img src="https://i.ibb.co/hy2Fj9F/arc.png" alt="arc" border="0"></a>
</li></ul>
</li>

</ul>

## Contract Structure
<ol>
<li>
The contract between two service must define the consumer, the provider and the interactions between them.
<hr>
    <ul>
    <li>
       <a href="https://ibb.co/1fG8jDg"><img src="https://i.ibb.co/d04GxdT/contract.png" alt="contract" border="0"></a>
    </li>
    </ul>
</li>

<li>
The consumer and provider must have an identifer for simplification now let's assume it's their port.
    <ul>
    <li>
    Data Structure:
    <hr>
    <a href="https://ibb.co/3N7L1Z9"><img src="https://i.ibb.co/jMT1hXP/participant.png" alt="participant" border="0"></a>
    </li>
    </ul>
</li>

<li>
    The third component is the interactions which will contain what happened between the two services.
    <ul>
    <li>
    Each interaction has a request, response and description.
    <hr>
    <ul>
    <li>
<a href="https://ibb.co/rwtLTLj"><img src="https://i.ibb.co/LZPqbqF/interaction.png" alt="interaction" border="0" /></a>    </li>
    </ul>
    </li>
    <li>
    Request Structure: It's a primary version some fields are to be added later.
    <hr>
        <ul>
            <li>
           <a href="https://ibb.co/9Z08jkT"><img src="https://i.ibb.co/Y0SRGFk/request.png" alt="request" border="0"></a>
            </li>    
        </ul>
    </li>
    <li>
    Response Structure: It's a primary version some fields are to be added later.
    <hr>
        <ul>
            <li>
           <a href="https://ibb.co/M5VV6L6"><img src="https://i.ibb.co/0VMMt3t/response.png" alt="response" border="0"></a>
            </li>    
        </ul>
    </li>
    </ul>
</li>
</ol>

## Flow:

## While Requesting (Record Mode):

### MODE 1:
#### When Order services request for products new interaction is created
<a href="https://ibb.co/ZNcwKLc"><img src="https://i.ibb.co/fQrKt1r/step1.png" alt="step1" border="0"></a>
<ul><li>
The contract is saved by name consumer_provider.json in our case it's 8085_8084.json

</li>
<li>
Check whether the contract exists or not, if it's exists append the interaction if not create the contract with this interaction
<hr>

```
public static void createContract(com.example.order.models.Response response, com.example.order.models.Request request,     String consumer,String provider) {
        // create the interaction
        com.example.order.models.Interaction interaction = new com.example.order.models.Interaction();
        interaction.setRequest(request);
        interaction.setResponse(response);
        interaction.setDescription("test interaction description");
        //check if the contract exists or not
        if(checkContractExist(consumer, provider)){
            com.example.order.models.Contract contract = loadContract(consumer, provider);
            contract.getInteractions().add(interaction);
            saveContract(contract);
        }
        else{
            // if the contract does not exist, create a new contract and add the interaction to it
            com.example.order.models.Contract contract = new com.example.order.models.Contract(); 
            contract.setConsumer(new com.example.order.models.Participant(consumer));
            contract.setProvider(new com.example.order.models.Participant(provider));
            List<com.example.order.models.Interaction> interactions = new ArrayList<com.example.order.models.Interaction>();
            interactions.add(interaction);
            contract.setInteractions(interactions);
            // save the contract
            saveContract(contract);
        }
    }

public static Boolean checkContractExist(String consumer, String provider) {
        File file = new File("./"+consumer+"_"+provider+".json");
        return file.exists();
}

```
</li>
<li>
Save contract as a json file:
<hr>
<a href="https://ibb.co/FJ4DG7s"><img src="https://i.ibb.co/P4G6BCT/step2.png" alt="step2" border="0"></a>
<hr>

```
 public static Boolean saveContract(com.example.order.models.Contract contract) {
        // Create an ObjectMapper to save class into it
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.enable(SerializationFeature.INDENT_OUTPUT);

        try {
            // Convert the Contract object to a JSON string
            String contractJson = objectMapper.writeValueAsString(contract);
            // Write the JSON string to a file using try-with-resources
            try (FileWriter fileWriter = new FileWriter("./" + contract.getConsumer().getName() + "_" + contract.getProvider().getName() + ".json")) {
                fileWriter.write(contractJson);
            }   
        
        } catch (IOException e) {
            // Handle the exception according to your needs
            e.printStackTrace();
            return false;
        }
        return true;

    }
```

</li>

</ul>

### MODE 2:
#### Testing Consumer (Test Mode)
<ul>
<li>
For simplicity we will test "Get products"
</li>
<li>
When Order service test no need for product service to be up, just the contract is need.
<hr>
<a href="https://ibb.co/mzSPPmm"><img src="https://i.ibb.co/6sNqq22/step3.png" alt="step3" border="0"></a>
</li>
<li>
So we will load all contracts where we are consumer on them (for simplicity we will load one contract):
<hr>

```
 public static com.example.order.models.Contract loadContract(String consumer, String provider) {
        // Create an ObjectMapper to read the class from the file
        ObjectMapper objectMapper = new ObjectMapper();
        com.example.order.models.Contract contract = null;
        try{
            String workingDirectory = System.getProperty("user.dir");
            System.out.println("Current working directory: " + workingDirectory);
            File jsonFile = new File("/home/ahmed/Desktop/GSOC/Keploy/Issues/issue1541/8085_8084.json");
            
            if (jsonFile.exists()) {
                // Read the content of the file and deserialize it into Contract class
                contract = objectMapper.readValue(jsonFile, com.example.order.models.Contract.class);
                System.out.println("Contract loaded successfully from: " + jsonFile.getAbsolutePath());
            } else {
                System.out.println("File not found: " + jsonFile.getAbsolutePath());
            }
        }
        catch (IOException e) {
            // Handle the exception according to your needs
           e.printStackTrace();
        }
        return contract;
    }
```
</li>
<li>
Test it by get the contract and getting the needed interactions based on our tests.
<hr>
<a href="https://ibb.co/Btj3kVJ"><img src="https://i.ibb.co/6mbwQRS/step4.png" alt="step4" border="0"></a>
<hr>

```
 public static com.example.order.models.Response test(String consumer,String url,String method){
        // load the contract
        com.example.order.models.Contract contract = loadContract(consumer,"");
        // get the interactions
        List<com.example.order.models.Interaction> interactions = contract.getInteractions();
        // loop through the interactions
        com.example.order.models.Response actualResponse = null;
        for (com.example.order.models.Interaction interaction : interactions) {
            // get the request
            com.example.order.models.Request request = interaction.getRequest();
            // get the response
            com.example.order.models.Response response = interaction.getResponse();
            // log the request and response
            System.out.println("Request: " + request);
            System.out.println("Response: " + response);
            if (request.getURL().equals(url)&& request.getMethod().equals(method)){
                actualResponse = response;
                break;
            }
        }
        return actualResponse;
    }
```

</li>

</ul>

#### Verify Provider (Test Mode)
<ul>
<li>
We don't need order service to be up to verify APIs of product service just the contract.
</li>
<li>
Load the contract as mentioned before:
<hr>
<a href="https://ibb.co/Hrf4PRV"><img src="https://i.ibb.co/P5vjWJN/step5.png" alt="step5" border="0"></a>

</li>
<li>
Get all contracts where product service is a provider (for simplicity we will load one contract)

</li>
<li>
Make requests to product service APIs which exist in contract and compare it with response from the contract also.
<hr>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/K6BmNKK/step6.png" alt="step6" border="0"></a>

<hr>

```
 public static Boolean verify(String port){
        com.example.product.models.Contract contract = loadContract("",port);
        // get the interactions
        if(contract==null || ! contract.getProvider().getName().equals(port)){
            return false;
        }
        // //make a map that takes string and string  
        // Map<String, String> contractRequest = new HashMap<>();

        // // Loop over the interactions
        // for (com.example.product.models.Interaction interaction : contract.getInteractions()) {
            
        //     contractRequest.put(interaction.getRequest().getMethod().toString(), interaction.getRequest().getURL());
        // }
        String expectedBody="hello";
        ResponseEntity<String> testResponse= makeReq(contract.getInteractions().get(0).getRequest().getMethod().getValue(), "http://localhost:8084/products/");
        if(testResponse.getBody().equals(expectedBody)){
            return true;
        }
        return false;
    }
    public static ResponseEntity<String> makeReq(String method,String url){
        if(method.equals("get")){
           return  restTemplate.getForEntity(url, String.class);
        }
        return null;
    }
```

</li>
> Note: some logic are hard-coded as we demonstrating the contract testing other things will be added later.
</ul>

### That's it!

**Comment by gouravkrosx** [comment]
@AhmedLotfy02 Will try to review this by EOD.

**Comment by gouravkrosx** [comment]
@AhmedLotfy02 , providing a sample repo rather than images of code snippets is better. Here, you have the gist of contract testing. But as you've referred to Pact for this, it will be good if you build the app and demonstrate contract testing using Pact.

**Comment by AhmedLotfy02** [comment]
@gouravkrosx Done, can you check the pull request linked with this issue
# Sample Pact to demonstrate Contract Testing (SpringBoot)


## Architecture
<ul>
<li>
Assume we have three microservices "Customer" and "Product" (Consumer) and Retailer which is Provider.
</li>

<li>
<a href="https://ibb.co/gD40BHH"><img src="https://i.ibb.co/4j1b599/arc2.png" alt="arc2" border="0"></a>
</li>

</ul>

## Flow:

## While Product Service test against Mock Provider:


### Using Mockito to mock the services.
#### Contract is Created and published to pact broker


<ul><li>
Contract is published but not verified by retailer service (provider):
<hr>
<a href="https://ibb.co/gD51vS2"><img src="https://i.ibb.co/P57pTcL/publishnotverified.png" alt="publishnotverified" border="0"></a></li>

<li>
Retailer then verify the contract in the test:

<hr>
<a href="https://ibb.co/FhdqnHg"><img src="https://i.ibb.co/zmtHN6G/verified.png" alt="verified" border="0"></a>
</li>

<li>
Assume we change any field name in provider test will cause the contract to be unverifed <hr>
<a href="https://ibb.co/pRVBS11"><img src="https://i.ibb.co/nndNFww/afterparamchange.png" alt="afterparamchange" border="0"></a>
<hr>
<a href="https://ibb.co/z488rTZ"><img src="https://i.ibb.co/tJZZ4TD/changed-Param.png" alt="changed-Param" border="0"></a>

</li>

</ul>

#### Same steps can be done with customer services and contract created then verifed by retailer
<ul>

<li>
<hr>
<a href="https://ibb.co/J21gBj5"><img src="https://i.ibb.co/vmFRw4Z/customer.png" alt="customer" border="0"></a></li>

</ul>

### That's it!

**Comment by gouravkrosx** [comment]
@AhmedLotfy02 , This task was only related to understanding how contract testing works. The Linked PR can't be merged because this sample app is not related to keploy.

**Comment by AhmedLotfy02** [comment]
@gouravkrosx I  wonder whether my output is the desired or not? or i must integrate pact with Keploy's code?

**Comment by hp77-creator** [comment]
@gouravkrosx are you planning to add this app into sample app repo?

**Comment by gouravkrosx** [comment]
@AhmedLotfy02 , your output seems correct.

**Comment by gouravkrosx** [comment]
@hp77-creator, Not really because this task was to understand the current limitation of keploy for contract testing.

**Comment by gouravkrosx** [comment]
This was related to the GSoC qualification task, since the proposal period has been closed, I am closing the issue. Thanks everyone for the contribution.
