### ISSUE TITLE
Create a dockerfile for the gql-mongo to build and run docker image

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1544]
Write a Dockerfile to build and run the image of the gql-mongo application.

**Comment by varun7singh** [comment]
Hey @re-Tick could you elaborate a bit?
Thanks !!

**Comment by re-Tick** [comment]
Currently the application can run natively in linux. But there should be a way to start the application in a docker container. For that you can write a dockerfile to build an application image and run it in a container.

**Comment by Sonichigo** [comment]
hey @varun7singh are you working on this issue ?

**Comment by Sonichigo** [comment]
the issue is still relevant but needs to be updated with more details! Since it's been stale for a long time closing this. @Swpn0neel please create a new issue based on the this one.

**Comment by Swpn0neel** [comment]
> the issue is still relevant but needs to be updated with more details! Since it's been stale for a long time closing this. @Swpn0neel please create a new issue based on the this one.

I need more info to create a new issue regarding this, otherwise it would be indifferent!
