### ISSUE TITLE
[feature]: Add popular mentions on the blog-website

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1552]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Idea is to add a section to /blog with can show 10-15 popular tweets/linkedin post of people sharing their experience about Keploy or any blog read from this website. 

If you're picking this issue please feel free to discuss design. 

### Why should this be worked on?

Appreciates the community spreading a word.

### Repository

blog-website

**Comment by Aditya-eddy** [comment]
Hey @nehagup I would love to discuss the design. We can a create a tab contents with different social media as tabs and showing the popular contents on their website. And just to confirm we will creating this at the homepage.. "/blog" Thanks.!!

**Comment by nehagup** [comment]
> Hey @nehagup I would love to discuss the design. We can a create a tab contents with different social media as tabs and showing the popular contents on their website. 
I'm open to more thoughts, however, I explored a few trending project landing pages and found these good. 
<img width="1461" alt="Screenshot 2024-02-13 at 11 21 09 PM" src="https://github.com/keploy/keploy/assets/15074229/9d82719f-3063-49a4-b322-0b3dd2f4e6f4">

<img width="1325" alt="Screenshot 2024-02-13 at 11 20 28 PM" src="https://github.com/keploy/keploy/assets/15074229/48bb1a2b-0df0-4d9e-b01b-168601fb437a">

<img width="1504" alt="Screenshot 2024-02-13 at 11 18 40 PM" src="https://github.com/keploy/keploy/assets/15074229/e5016e65-1ac2-486f-aa81-5ddf9ed6c9bb">

> And just to confirm we will creating this at the homepage.. "/blog" Thanks.!!
Yes, you're right!

**Comment by Aditya-eddy** [comment]
Yes I think the above design would be more appropiate to the website. Would start working on it today. Will present you the v1 for it and from there we can start improving it. Thanks!!

**Comment by Aditya-eddy** [comment]
Hey @nehagup I have attached the screenshot can you review the design? I have currently implemented for twitter. Will be waiting on the feedback.
![Screenshot from 2024-02-15 13-04-42](https://github.com/keploy/keploy/assets/70089590/212c642f-87a1-40d0-afb5-ce02e1ce7d72)
Thanks!!

**Comment by sahadat-sk** [comment]
Hi @nehagup, I'm also interested in this issue. Can I submit my design too?

**Comment by Swpn0neel** [comment]
Hey @nehagup I have designed this, if you like it I can go for implementing it on the site... or if you have any other design recommendations, I can work on that too!!

![image](https://github.com/keploy/keploy/assets/121167506/a87dff0a-3845-4397-9e33-1d4737d38abc)

**Comment by nehagup** [comment]
> Hey @nehagup I have designed this, if you like it I can go for implementing it on the site... or if you have any other design recommendations, I can work on that too!!

I think this is cleaner, just need to make it compatible with the layout, maybe 3-4 in a row.

**Comment by Swpn0neel** [comment]
> I think this is cleaner, just need to make it compatible with the layout, maybe 3-4 in a row.

Yeah, that can be done easily, no issues!! Feel free to assign me.

**Comment by nehagup** [comment]
@Swpn0neel please raise the PR.

**Comment by Swpn0neel** [comment]
Sure!! But can please provide me the tweets that you want to display?? @nehagup

**Comment by nehagup** [comment]
@Swpn0neel you can take any tweet links right now, will share the list once we have a working PR.

**Comment by Swpn0neel** [comment]
> @Swpn0neel you can take any tweet links right now, will share the list once we have a working PR.

Ok!! I'm working on the issue

**Comment by Swpn0neel** [comment]
Hey @nehagup, Kindly check my PR and let me know!!
