### ISSUE TITLE
[feature]: add more stories to blog website as a suggestion at the end of the blog

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1553]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

right now there are only 2 stories at the end of each blog as "More Stories", minimum 8

### Why should this be worked on?

so that readers can see and choose from more options

### Repository

blog-website

**Comment by Aditya-eddy** [comment]
Hey @nehagup working on it will publish a pr soon.
