### ISSUE TITLE
[bug]: Sort test suite names for complete summary

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* In `test.go` testSuiteNames are sorted as string using `sort.Strings(testSuiteNames)`.
* 
<img width="674" alt="image" src="https://github.com/keploy/keploy/assets/60891544/6474a7f4-625a-4b1c-84dd-09da663a7602">

### Steps to reproduce

* Instead of sorting as string it should be sorted as number.

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by officialasishkumar** [comment]
A possible fix is to store the numbers after "test-set-" in a slice of integers and then sort it.
