### ISSUE TITLE
[bug]: Uncontrolled data used in path expression

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* We've a function like `util.ValidatePath` that checks the path to avoid Uncontrolled data issue.
* `pkg/platform/yaml/testReport.go:100` have a similar Uncontrolled data used in path expression issue which can be fixed by validating the path.

### Steps to reproduce

* Validate the path before using OS operation on filepath.

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by Ajeett01** [comment]
I would like to work on this issue. I would write code that validates the path before file operation, then would pass the validated path to it.

**Comment by shivamsouravjha** [comment]
Sure @Ajeett01 ! this task is open to all. Feel free to work on a PR.
