### ISSUE TITLE
[bug]: mockTest is failing while using go test 

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I change keploy mode to test from record in my go unit test, 

```bash
err := keploy.New(keploy.Config{
	Mode: keploy.MODE_TEST,
	Name: "<stub_name/mock_name>"
	Path: "<local_path_for_saving_mock>",
	MubeKeployLogs: false,
	delay: 10,
})
```
keploy goes into the infinite loop

```bash
🐰 Keploy: 2024-02-15T06:43:30Z 	[33mWARN[0m	yaml/yaml.go:387	request timestamp is missing for 
go.keploy.io/server/pkg/platform/yaml.(*Yaml).ReadTcsMocks
	/home/runner/work/keploy/keploy/pkg/platform/yaml/yaml.go:387
go.keploy.io/server/pkg/service/mocktest.(*mockTester).MockTest
	/home/runner/work/keploy/keploy/pkg/service/mocktest/mocktest.go:66
go.keploy.io/server/cmd.(*MockTest).GetCmd.func1
	/home/runner/work/keploy/keploy/cmd/mocktest.go:80
github.com/spf13/cobra.(*Command).execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.keploy.io/server/cmd.(*Root).execute
	/home/runner/work/keploy/keploy/cmd/root.go:262
go.keploy.io/server/cmd.Execute
	/home/runner/work/keploy/keploy/cmd/root.go:176
main.main
	/home/runner/work/keploy/keploy/main.go:52
runtime.main
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/proc.go:267
```

Since I'm creating mocks from my unit-test file, I don't have request timestamps which the keploy is searching for.

### Steps to reproduce

1. Use `go-sdk` in `_test.go` to generate mocks for unit-tests.
2. Keep Keploy Mode to record and run the `go test` command
3. Now change the Mode to test and run the command again.
4. The Keploy goes to the infinite loop, with the error mentioned in above behaviour.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by charankamarapu** [comment]
Identified two regression bugs which is causing error in mock commands:
1. https://github.com/keploy/keploy/blob/80d9f7f9ce64fb563c1cb4865b6be490691ebbbd/pkg/platform/yaml/yaml.go#L361
2.https://github.com/keploy/keploy/blob/80d9f7f9ce64fb563c1cb4865b6be490691ebbbd/pkg/service/mocktest/mocktest.go#L72

**Comment by gouravkrosx** [comment]
After refactoring, this feature has been removed temporarily.
