### ISSUE TITLE
[docs]: Update keploy logo in the dashboard

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#157]
### What do you want to add to the docs? (please state reasons if any)

The Keploy logo is updated now, but the Keploy console still has old logo.  
<img width="70" alt="Screenshot 2022-08-10 at 12 57 18 AM" src="https://user-images.githubusercontent.com/15074229/183747467-3cc53e1d-3dfd-4e6d-a0b1-47d93cb81380.png">

### Where is this stated?

https://avatars.githubusercontent.com/u/92252339?s=200&v=4

**Comment by karnatisrinivas** [comment]
Hello, can I work on this?

**Comment by nehagup** [comment]
@karnatisrinivas Sure.

**Comment by ShivamTyagi12345** [comment]
> Hello, can I work on this?

Hey @karnatisrinivas Will you kindly share any updates :)

**Comment by karnatisrinivas** [comment]
Hello @ShivamTyagi12345 , Please go ahead

**Comment by CypherpunkSamurai** [comment]
Hello, this issue has been stale for a while, can i work on this?

It will be an easy fix.

**Comment by nehagup** [comment]
@CypherpunkSamurai thanks for the support however I just noticed this has been fixed. https://github.com/keploy/ui/pull/88/files
