### ISSUE TITLE
[docs]: adding env path in debugger

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1574]
### What do you want to add to the docs? (please state reasons if any)

* https://keploy.io/docs/keploy-explained/debugger-guide/ here an "env" field is to be added which is the path to go binary.
```
            "name": "Record",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "asRoot": true,
            "console": "integratedTerminal",
            "program": "main.go",
            "args": ["record", "-c", "<path_to_executable>"]
            "env": {
                "PATH": "<path to Go binary>"
            }
```

Path to go binary can be found via `echo $PATH`.

### Where is this stated?

* Via adding this, the error ```(exec: "go": executable file not found in $PATH)``` will be solved while running debugger.

### Repository

docs

**Comment by AhmedLotfy02** [comment]
Can i be assigned to this issue?
