### ISSUE TITLE
[feature]: hide complete test summary in case of application not run 

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1577]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

* In case Keploy test doesn't run (due to error) or no test cases were recorded its better to not show complete test summary.
<img width="771" alt="image" src="https://github.com/keploy/keploy/assets/60891544/5c2a8818-e422-48cd-b004-4707b6b6f91a">

### Why should this be worked on?

* Better UX

### Repository

keploy

**Comment by AhmedLotfy02** [comment]
Can I be assigned this issue or it's closed?

**Comment by officialasishkumar** [comment]
Hey @AhmedLotfy02, I already have an open PR.

**Comment by shivamsouravjha** [comment]
Hey @officialasishkumar multiple folks can work on a PR in parallel the most suitable would be merged.
