### ISSUE TITLE
[feature]: Colorise keploy's logo in terminal

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1579]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

* Currently Keploy's logo is monochromatic, it can be colourised in gradient.
<img width="698" alt="image" src="https://github.com/keploy/keploy/assets/60891544/0399b410-ced6-4d11-b0d9-5913c755db3e".

* A snippet like this would create the below image

```
var gradientColors = []string{
	"\033[38;5;202m", // Red
	"\033[38;5;202m", // Orange-Red
	"\033[38;5;208m", // Orange
	"\033[38;5;214m", // Yellow-Orange
	"\033[38;5;220m", // Yellow
}
if binaryToDocker := os.Getenv("BINARY_TO_DOCKER"); binaryToDocker != "true" {
		// ANSI escape code to reset color
		const reset = "\033[0m"

		// Print each line of the logo with a different color from the gradient
		lines := strings.Split(logo, "\n")
		for i, line := range lines {
			color := gradientColors[i%len(gradientColors)]
			fmt.Println(color, line, reset)
		}
	}
```
<img width="638" alt="image" src="https://github.com/keploy/keploy/assets/60891544/4039b545-c7f3-4043-b1d1-d891a2b65757">.

* The above gradient can be modified to look exactly like 
<img width="191" alt="image" src="https://github.com/keploy/keploy/assets/60891544/e9b270a3-fcba-45a4-8254-ee14a5e3e710">

### Why should this be worked on?

* Helps better UI experience for user.

### Repository

keploy

**Comment by AhmedLotfy02** [comment]
Do you want something like that?
![image](https://github.com/keploy/keploy/assets/76037906/1f2f2505-bb2b-4c76-99f5-a8ee39636a6e)

**Comment by shivamsouravjha** [comment]
I tried looking but it can be made more closer to the logo, in the keploy image the gradients go from dark orange to light yellow. you can break the text into parts and colourise each of the part to be more close to source image.

**Comment by AhmedLotfy02** [comment]
@shivamsouravjha I made these two which is better or do something else?
(1)
![image](https://github.com/keploy/keploy/assets/76037906/ac4bc393-2307-46e5-9789-23346a8cd9fd)
(2)
![image](https://github.com/keploy/keploy/assets/76037906/30c2bf7d-3277-4023-9c97-fb8b1e6bd6b6)

**Comment by AhmedLotfy02** [comment]
@shivamsouravjha Will do it now ^^
