### ISSUE TITLE
[bug]: Not able to go to next page because of overlapping chatbox

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The chatbox is overlapping with the table page navigation icons on the testlist page. 

### Steps to reproduce

Create >26 tests -> select page size as 25 -> try clicking on next(2nd page).
<img width="372" alt="Screenshot 2022-08-10 at 12 57 08 AM" src="https://user-images.githubusercontent.com/15074229/183747372-5e15f9be-d9ed-4f86-a60b-ae9580861579.png">
 

### Version

Local

**Comment by karnatisrinivas** [comment]
Hello, Can I work on this?

**Comment by nehagup** [comment]
@karnatisrinivas Sure!

**Comment by nehagup** [comment]
@karnatisrinivas are you still working on this?

**Comment by aakashgarg-19** [comment]
@nehagup can I work on this?

**Comment by ShivamTyagi12345** [comment]
> @nehagup can I work on this?

sure :+1:

**Comment by aakashgarg-19** [comment]
Thankyou @ShivamTyagi12345  I am working on it

**Comment by faraz16iqbal** [comment]
Is this issue still open? If yes, I would like to work on it! @nehagup

**Comment by nehagup** [comment]
@faraz16iqbal sure.

**Comment by Prasanta-mondal** [comment]
I am Interested to Solve this Task Please Assign Me .

**Comment by nehagup** [comment]
@Prasanta-mondal sure.
