### ISSUE TITLE
[bug]: correction required in doc quickstart

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've corrected Gin Mongo Sample URL shortner docs for refernce. https://keploy.io/docs/quickstart/samples-gin/ 

Since Keploy just needs one click installation, now instead of platform specific, quickstart guide needs to be for docker or non-docker ways. This issue is to run through the samples apps on the docs repo and correct the flow where it's breaking.

There are multiple apps so can be assigned to multiple folks comfortable in different languages. Heres' the list -

**Java**
- [ ] https://keploy.io/docs/quickstart/pet-clinic/
- [ ] https://keploy.io/docs/quickstart/samples-java/
- [ ] https://keploy.io/docs/quickstart/java-spring-boot-mongo/

**Go**
- [x] https://keploy.io/docs/quickstart/samples-mux/
- [x] https://keploy.io/docs/quickstart/samples-echo/
- [x] https://keploy.io/docs/quickstart/samples-redis/
- [x] https://keploy.io/docs/quickstart/samples-mysql/

**Python**
- [x] https://keploy.io/docs/quickstart/samples-django/
- [x] https://keploy.io/docs/quickstart/samples-flask/
- [x] https://keploy.io/docs/quickstart/samples-fastapi/
- [x] https://keploy.io/docs/quickstart/samples-fastapi-twilio/

**JavaScript/Node**
- [ ] https://keploy.io/docs/quickstart/samples-bunjs/
- [ ] https://keploy.io/docs/quickstart/samples-nodejs/

**Rust**
- [ ] https://keploy.io/docs/quickstart/samples-rust/

Please feel free to connect with me if you need more info.
 

### Steps to reproduce

Not all users can follow docs currently since keploy installation has become one click.

### Environment

Production

### Version

Cloud

### Repository

docs

**Comment by Ajeett01** [comment]
I would like to work on JavaScript. Can you give me a small idea , from which file should I start in docs repo.
@nehagup

**Comment by hp77-creator** [comment]
Hi @nehagup I will raise a MR for echo-sql, I have documented the issues that I faced and will send a PR to fix the issues that I faced.
Issues: https://gist.github.com/hp77-creator/04d2eedb7bd1856673dde8b9ac69e192

**Comment by nehagup** [comment]
**Rust documentation** for docs website is still open, it is just done on the Readme (https://github.com/keploy/samples-rust/tree/main/CRUD-rust-mongo ) by @Ajeett01 

This needs to be replicated to docs website with better code snippets/code-blocks. Use snapify in case of code images or code blocks for commands that needs to be copied.
