### ISSUE TITLE
[bug]: some logs don't work

### ISSUE THREAD

**Issue by nnnkkk7** [keploy/keploy#1588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Some logs are not printed where they should be.

### Steps to reproduce

When I run some functions in local machine, they don't print the logs.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by gouravkrosx** [comment]
This issue has been addressed through refactoring changes, so closing this PR.
