### ISSUE TITLE
[feature]: tags filter on blog-website

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1591]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently the tags are just displayed at the end of the post on the the blog website. These need better formatting so that they look like tags.

On clicking one tag, it should redirect to page listing all blogs with that tag. Just like it happens for an author right now.

Examples https://keploy.hashnode.dev/tag/testing?source=tags_bottom_blogs

### Why should this be worked on?

easy to find similar blogs for better interest 

### Repository

blog-website

**Comment by its-kunal** [comment]
@nehagup, is this issue still available, because following merged PR is been reverted back.
