### ISSUE TITLE
[perf]: improve mobile performance issues for blog website

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Need to fix all issues for keploy.io/blog for mobile - https://pagespeed.web.dev/analysis/https-keploy-io-blog/a3ryo78tg6?form_factor=mobile 

<img width="987" alt="Screenshot 2024-02-17 at 5 54 32 PM" src="https://github.com/keploy/keploy/assets/15074229/ecd5af43-6804-4545-8842-13dbe19349aa">

### Steps to reproduce

better seo

### Environment

Production

### Version

Cloud

### Repository

blog-website

**Comment by its-kunal** [comment]
Hey @nehagup, can I work on this issue?
