### ISSUE TITLE
[perf]: improve mobile performance issues for docs website

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1593]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Need to fix all issues for keploy.io/blog for mobile - https://pagespeed.web.dev/analysis/https-keploy-io-docs/tkgmgmeiho?form_factor=mobile 

<img width="974" alt="Screenshot 2024-02-17 at 5 57 40 PM" src="https://github.com/keploy/keploy/assets/15074229/c1c311bc-1911-4e37-8b14-e33d0b5f1697">

### Why should this be worked on?

better seo

### Repository

docs

**Comment by PratikKhaire** [comment]
@nehagup Can I work on this issue? Please assign it to me.

**Comment by nehagup** [comment]
> @nehagup Can I work on this issue? Please assign it to me.

@PratikKhaire the first best PR will be merged, please feel free to open a PR
