### ISSUE TITLE
[chore]: blog website seo improvements

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- [x] Keploy logo in our blog articles lacks an alt attribute.
- [x]  inconsistencies in the title casing of our blog articles, some titles are not following the standard title case format - it should all be titlecase
- [x] **View All Posts** text needs to be cleaner and more subtle
- [x] Need to show author bio - profile description, images to improve credibility of the blog with author

<img width="955" alt="Screenshot 2024-02-17 at 5 36 22 PM" src="https://github.com/keploy/keploy/assets/15074229/968abef1-ccfc-4283-84d4-362578840ee5">

### Steps to reproduce

better seo

### Environment

Production

### Version

Cloud

### Repository

blog-website

**Comment by Swpn0neel** [comment]
Hey, I can work on these issues, but can you please elaborate the third and fourth requirement??

**Comment by nehagup** [comment]
> Hey, I can work on these issues, but can you please elaborate the third and fourth requirement??

Hey @Swpn0neel the `view all post` button needs to be cleaner on design side. maybe remove the blue highlight and add arrow icon, you can decide. 

last point is to fetch the description, image and any other meta data of the author and show that on frontend.

**Comment by Swpn0neel** [comment]
Got it @nehagup, feel free to assign me... I would like to work on these issues!!

**Comment by nehagup** [comment]
@Swpn0neel please raise the PR

**Comment by Aditya-eddy** [comment]
Hey @Swpn0neel are you still working on the issue. Just checking-in!

**Comment by Swpn0neel** [comment]
> Hey @Swpn0neel are you still working on the issue. Just checking-in!

Yes

**Comment by shikhar2712** [comment]
Hey @Swpn0neel is the issue sorted or I want to contribute?

**Comment by Swpn0neel** [comment]
> Hey @Swpn0neel is the issue sorted or I want to contribute?
> 

This issue has some clarification problems which I have addressed in the Slack channel, but it isn't resolved yet

**Comment by its-kunal** [comment]
@nehagup Please review my PR, I would be a great help.
