### ISSUE TITLE
[feature]: read and write test runs to files

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#160]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to implement the ability to read and write test run data from files rather a database (currently MongoDB). than 

### Why should this be worked on?

Keploy needs to run without needing a database. All relevant data currently saved to DBs should be saved files. 

This will allow users to process these files for additional insights or analytics.

**Comment by charankamarapu** [comment]
Current keploy either v1 or v2 currently implements file storage as needed in this issue. Closing issue as issue is resolved.
