### ISSUE TITLE
[bug]: Keploy update command updates even on latest version 

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#1608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

1. install latest keploy and run keploy update , it will update again.
2. This is happening because the version we get in the binary is 2.x.x and in release tag we get v2.x.x.

### Steps to reproduce

1. install latest keploy and run keploy update , it will update again.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by AhmedLotfy02** [comment]
Hi @charankamarapu please check the opened PR for this issue
