### ISSUE TITLE
[feature]: exports tests as programmatic test files (go/js/other..)

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#161]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be really helpful if keploy can also export tests into programmatic files. For eg: it could be test files written in go or js.

### Why should this be worked on?

While exporting to json/yaml is useful, they are not as useful or customizable as programmatic code like go/js. It could for example enable more powerful custom assertions and integrations.

**Comment by Swpn0neel** [comment]
Is this issue still relevant @slayerjain @nehagup ?

**Comment by nehagup** [comment]
@Swpn0neel yes, if we go DSL approach in future.
