### ISSUE TITLE
[feature]: Keploy V2 refactor the hooks and proxy

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1624]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to make the hooks and proxy more modular and probably split it into the core package. 

### Why should this be worked on?

There is high coupling between the hooks and the proxy components. 

### Repository

keploy

**Comment by gouravkrosx** [comment]
closed by: https://github.com/keploy/keploy/pull/1684
