### ISSUE TITLE
[feature]: Keploy V2 refactor Manual testing and update test pipelines

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1626]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Need to manually test Keploy and update the test scripts.  

### Why should this be worked on?

Stability

### Repository

keploy

**Comment by charankamarapu** [comment]
Refactoring of keploy is done in this PR - https://github.com/keploy/keploy/pull/1684.  Manually is also done and merged the into main
