### ISSUE TITLE
[feature]: Keploy V2 refactor the cli 

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1630]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to complete cli package and hook all the keploy components using the cli package. 

### Why should this be worked on?

Complete V2 refactor. 

### Repository

keploy

**Comment by charankamarapu** [comment]
CLI Refactoring of keploy is done in this PR - https://github.com/keploy/keploy/pull/1684 and merged the into main.
