### ISSUE TITLE
[bug]: coverage.keploy is not generated for python code coverage

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I record testcases for the python API server with keploy, and run the testcases with pytest integration with keploy's python-sdk. The code coverage is not captured for the APIs.

### Steps to reproduce

1. Go to samples-python and clone locally
2. Record some testcases.
3. Copy the test_keploy.py and run the testcases.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by gouravkrosx** [comment]
Closing as it is fixed.
Users can follow https://keploy.io/docs/server/sdk-installation/python/#heading
