### ISSUE TITLE
[feature]:  Addition of version argument to installation script

### ISSUE THREAD

**Issue by anirudhjain75** [keploy/keploy#1639]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

I'd suggest adding version to installation script as there are cases where we use specific version of keploy cli to test

### Why should this be worked on?

Much needed improvement / enhancement

### Repository

keploy

**Comment by besasch88** [comment]
I believe it is a clone of https://github.com/keploy/keploy/issues/1958, just fixed!

**Comment by gouravkrosx** [comment]
Thanks @besasch88 , yes it is fixed.

**Comment by gouravkrosx** [comment]
It can be used via : `curl --silent -O -L https://keploy.io/install.sh && source install.sh -v <version-tag>`
