### ISSUE TITLE
[bug]: testcase fails due to unmatched external http mock

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I record a testcase for an API which is making an external call to the public network, and run the testcase in test mode. The test-run fails due to unmatched http mock for the external call by the recorded API testcase and mock.

### Steps to reproduce

1. Create an API which is making an http external.
2. Record a testcase for that API
3. Run the testcase/mock in test mode.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by gouravkrosx** [comment]
Unable to reproduce after keploy v2 refactoring.
