### ISSUE TITLE
[bug]: panic when make api request in multiple goroutines

### ISSUE THREAD

**Issue by luudis** [keploy/keploy#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i make api call with goroutines in keploy `record` mode, the program panics at the time keploy send that duplicate request.
The stacktrace is as follows:
`panic: runtime error: index out of range [0] with length 0

goroutine 6693 [running]:
github.com/keploy/go-sdk/keploy.ProcessDep({0x15452e0, 0xc00123d2f0}, 0x149c91f, 0xc00123d320, {0xc000c87990, 0x2, 0x980f8a8})
        /Users/ludashuai3/WorkSpace/demo-api/vendor/github.com/keploy/go-sdk/keploy/utils.go:91 +0xe34
github.com/keploy/go-sdk/integrations/khttpclient.Interceptor.RoundTrip({{0x1539640, 0xc002349180}, 0xc00084d320, 0xc001721500}, 0xc00396d100)
        /Users/ludashuai3/WorkSpace/demo-api/vendor/github.com/keploy/go-sdk/integrations/khttpclient/httpClient.go:162 +0xd49
net/http.send(0xc00396d100, {0x1539320, 0xc0008a5540}, {0x1481f40, 0x1, 0x0})
        /usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00123d200, 0xc00396d100, {0xc00396d100, 0xc003c79ba0, 0x0})
        /usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00123d200, 0xc00396d100)
        /usr/local/go/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
main.callLucy({0x15452e0, 0xc000c50b70})
        /Users/ludashuai3/WorkSpace/demo-api/main.go:109 +0x9b
main.main.func4.1()
        /Users/ludashuai3/WorkSpace/demo-api/main.go:57 +0xff
created by main.main.func4
        /Users/ludashuai3/WorkSpace/demo-api/main.go:53 +0x65

Process finished with exit code 2
`

### Steps to reproduce

**Setup gin server**

1. Create an empty project with IDE. eg. GoLand.
2. Init project with go mod. `go mod init demo`
3. Copy following code into project . Execute `go mod tidy` and `go mod vendor` if need.
4. Run the program and test with curl `curl -L -X GET 'http://127.0.0.1:9900/test'` several times (maybe 5 or 6 times).

**Example code**
`package main

import (
	"context"
	"encoding/json"
	"github.com/gin-gonic/gin"
	"github.com/keploy/go-sdk/integrations/kgin/v1"
	"github.com/keploy/go-sdk/integrations/khttpclient"
	"github.com/keploy/go-sdk/keploy"
	"io/ioutil"
	"net/http"
	"sync"
)

func main() {
	port := "9900"

	router := gin.Default()

	k := keploy.New(keploy.Config{
		App: keploy.AppConfig{
			Name: "demo-api",
			Port: port,
		},
		Server: keploy.ServerConfig{
			URL: "http://localhost:8081/api",
		},
	})

	kgin.GinV1(k, router)

	// router here
	router.GET("/jack", func(c *gin.Context) {
		j := jack{JackName: "my name is jack"}
		c.JSON(200, j)
	})
	router.GET("/tom", func(c *gin.Context) {
		j := tom{TomName: "my name is tom"}
		c.JSON(200, j)
	})
	router.GET("/lucy", func(c *gin.Context) {
		j := lucy{LucyName: "my name is lucy"}
		c.JSON(200, j)
	})

	router.GET("/test", func(c *gin.Context) {
		println("test begin")

		// call api in goroutines
		wg := sync.WaitGroup{}
		wg.Add(20)
		for i := 0; i < 20; i++ {
			go func() {
				defer wg.Done()
				callJack(c.Request.Context())
				callTom(c.Request.Context())
				callLucy(c.Request.Context())
			}()
		}
		wg.Wait()

		println("test finish")
		c.JSON(200, "success")
	})

	router.Run(":" + port)
}

type jack struct {
	JackName string `json:"jackName"`
}
type tom struct {
	TomName string `json:"tomName"`
}
type lucy struct {
	LucyName string `json:"lucyName"`
}

func callJack(ctx context.Context) {
	client := getHttpClient(ctx)
	request, _ := http.NewRequest(http.MethodGet, "http://localhost:9900/jack", nil)
	resp, _ := client.Do(request)
	defer resp.Body.Close()
	body, _ := ioutil.ReadAll(resp.Body)

	jack := new(jack)
	err := json.Unmarshal([]byte(string(body)), jack)
	if err != nil {
		println("jack err: ", err)
	}
}

func callTom(ctx context.Context) {
	client := getHttpClient(ctx)
	request, _ := http.NewRequest(http.MethodGet, "http://localhost:9900/tom", nil)
	resp, _ := client.Do(request)
	defer resp.Body.Close()
	body, _ := ioutil.ReadAll(resp.Body)

	tom := new(tom)
	err := json.Unmarshal([]byte(string(body)), tom)
	if err != nil {
		println("tom err: ", err)
	}
}
func callLucy(ctx context.Context) {
	client := getHttpClient(ctx)
	request, _ := http.NewRequest(http.MethodGet, "http://localhost:9900/lucy", nil)
	resp, _ := client.Do(request)
	defer resp.Body.Close()
	body, _ := ioutil.ReadAll(resp.Body)

	lucy := new(lucy)
	err := json.Unmarshal([]byte(string(body)), lucy)
	if err != nil {
		println("lucy err: ", err)
	}
}

func getHttpClient(ctx context.Context) *http.Client {
	interceptor := khttpclient.NewInterceptor(&http.Transport{})

	interceptor.SetContext(ctx)
	client := &http.Client{Transport: interceptor}
	return client
}
`

**The stacktrace is as follows:**
`panic: runtime error: index out of range [0] with length 0

goroutine 6693 [running]:
github.com/keploy/go-sdk/keploy.ProcessDep({0x15452e0, 0xc00123d2f0}, 0x149c91f, 0xc00123d320, {0xc000c87990, 0x2, 0x980f8a8})
        /Users/ludashuai3/WorkSpace/demo-api/vendor/github.com/keploy/go-sdk/keploy/utils.go:91 +0xe34
github.com/keploy/go-sdk/integrations/khttpclient.Interceptor.RoundTrip({{0x1539640, 0xc002349180}, 0xc00084d320, 0xc001721500}, 0xc00396d100)
        /Users/ludashuai3/WorkSpace/demo-api/vendor/github.com/keploy/go-sdk/integrations/khttpclient/httpClient.go:162 +0xd49
net/http.send(0xc00396d100, {0x1539320, 0xc0008a5540}, {0x1481f40, 0x1, 0x0})
        /usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00123d200, 0xc00396d100, {0xc00396d100, 0xc003c79ba0, 0x0})
        /usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00123d200, 0xc00396d100)
        /usr/local/go/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
main.callLucy({0x15452e0, 0xc000c50b70})
        /Users/ludashuai3/WorkSpace/demo-api/main.go:109 +0x9b
main.main.func4.1()
        /Users/ludashuai3/WorkSpace/demo-api/main.go:57 +0xff
created by main.main.func4
        /Users/ludashuai3/WorkSpace/demo-api/main.go:53 +0x65

Process finished with exit code 2
`

### Version

Local

**Comment by slayerjain** [comment]
@luudis this seems to be working fine with the latest keploy server (v0.5.0) and SDK (v0.5.1). can you please try again and verify?

I'm also attaching the logs that I got.

 
[log.txt](https://github.com/keploy/keploy/files/9431973/log.txt)

**Comment by GopinathRakkiyannan** [comment]
@nehagup Could you please confirm whether this issue still persists. If yes, I would like to work on it.

Please update your inputs. Thanks in advance

**Comment by GopinathRakkiyannan** [comment]
@nehagup Even I have tested as per your steps. I am not able to see the failure. I have run the curl more than 30 times.

NOTE: I am using go 1.18.3

**Comment by nehagup** [comment]
@GopinathRakkiyannan thanks for confirming. Closing this issue since it's not replicable anymore. @luudis please feel free to re-open it in-case you see it again.
