### ISSUE TITLE
[bug]: the diff viewer shows all of the trailing body as difference rather than being specific to the diff chars

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This majorly happens for array of object. 
![Screenshot 2024-03-05 at 7 00 53 PM](https://github.com/keploy/keploy/assets/15074229/fff7593c-a102-4b77-9f09-4d4436b841a5)

### Steps to reproduce

try breaking any api in java sample pet clinic app.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by shivamsouravjha** [comment]
This error seems to be related to a pre-existing issue
https://github.com/keploy/keploy/issues/1496

the summary of which was that the library dependency used to show the diff doesn’t handle arrays well.


I was testing few probable alternatives to the current json diff viewer dependency

**Comment by shivamsouravjha** [comment]
https://github.com/keploy/keploy/issues/1738 is similar hence closing this issue.
