### ISSUE TITLE
[docs]: Slack Invite Link possibly expired - Getting Started

### ISSUE THREAD

**Issue by mehulambastha** [keploy/keploy#1653]
### What do you want to add to the docs? (please state reasons if any)

**Issue**
New contributors like myself are arriving at the Github repo, and the [Getting Started](https://github.com/keploy/gsoc/tree/main/2024) page recommends joining the Slack Community. The invite link for to join the slack channel doesn't work and has possibly expired.

**Relevant Proof**
1. Click Link
![image](https://github.com/keploy/keploy/assets/47669806/5504bd69-bc2f-476a-8ad7-e2d18ac52bbc)
2. Try to log in (with personal as well as educational - college email accounts)
![image](https://github.com/keploy/keploy/assets/47669806/54145fec-a8f6-4fd7-a286-3421f63aab78)
3. Greeted with error
![image](https://github.com/keploy/keploy/assets/47669806/55125cff-1e9d-4386-b720-97f588d00978)
4. Google search leads to [this](https://github.com/JohnSnowLabs/spark-nlp/issues/2063) issue outlining that an expired invite link can cause this behaviour.

**Possible Outcomes**
A new contributor unable to join the slack channel (which is recommended as the first step) might feel demotivated and give up. This might not be the ideal way of welcoming new contributors to our project.

**Possible Fixes**
README.md should be updated with a new, valid invite link (might try generating a new link, valid for 30 days)

### Where is this stated?

Invalid link present at https://github.com/keploy/gsoc/edit/main/2024/README.md , line 7
![image](https://github.com/keploy/keploy/assets/47669806/946123c7-2f69-410d-95e4-9b7a137fa907)

### Repository

keploy

**Comment by jaiakash** [comment]
Hi @mehulambastha the links on gsoc pages do ask for the keploy.io email id. Can you check this and let me know if you join from this link https://join.slack.com/t/keploy/shared_invite/zt-23foxf3k0-zcsxyOHLMt40K1RCUsefkA

This is from github.com/keploy page.
