### ISSUE TITLE
[bug]  Command built from user-controlled sources

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1661]
The code snippet
 ```
	cmd := exec.Command("sudo", "chmod", "-R", "777", keployPath)
```
* Insufficient sanitization of keploypath needs to be fixed. 

* File `pkg/proxy/util/util.go:94`

**Comment by hyyhyf7** [comment]
Can I take this issue?

**Comment by hyyhyf7** [comment]
How can I check if I sanitized keploypath sufficiently?

**Comment by shivamsouravjha** [comment]
you can try using validate like used in other functions,

**Comment by gouravkrosx** [comment]
@shivamsouravjha is this issue still relevant?

**Comment by shivamsouravjha** [comment]
closing the issue as this is solved
