### ISSUE TITLE
[feature]: add animations to blog website

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1664]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Few good animation examples are https://webflow.com/interactions-animations 

This is an open ended task basis on contributors creativity. I'm happy to discuss more around what animations can be added to what components. Here are few of my suggestions 

- [x]  Progress bar to individual posts as user scrolls

- [ ] load action animations (fade in, slide in etc..) on loading pages and blog preview cards
- [ ] grow animation on hovering over table of content items

### Why should this be worked on?

To make the blog website more interactive and appealing animations can be added. 

### Repository

blog-website

**Comment by ankitjangidx** [comment]
hey @nehagup I'd like to work on this issue. I've explored the animations showcased on [https://webflow.com/interactions-animations](webflow) and got a clear idea of what you're aiming for. I'll be focusing on implementing animations like **progress bars** for individual posts as users scroll, **loading action** animations, and **grow** animations. Additionally, I suggest incorporating transition delays on button hover and scale effects on card hover. I have several other design and animation ideas to discuss further.

**Comment by ankitjangidx** [comment]
and considering the current layout, I've noticed a significant amount of blank white space on the blog page. Furthermore, the placement of the open-source image seems off; it should ideally be positioned above the 'Keploy blog' heading, as per my suggestion. @nehagup  What are your thoughts on addressing these layout concerns?

### Currently
![image](https://github.com/keploy/keploy/assets/100501722/dce4f2d0-a5ca-4238-9f19-0086f324491e)

### Something like this
![image](https://github.com/keploy/keploy/assets/100501722/4961294a-8c43-40f2-8de2-c9fdeeee756b)

**Comment by nehagup** [comment]
> and considering the current layout, I've noticed a significant amount of blank white space on the blog page. Furthermore, the placement of the open-source image seems off; it should ideally be positioned above the 'Keploy blog' heading, as per my suggestion. @nehagup What are your thoughts on addressing these layout concerns?
> 
> ### Currently
> ![image](https://private-user-images.githubusercontent.com/100501722/311528009-dce4f2d0-a5ca-4238-9f19-0086f324491e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDM4ODEsIm5iZiI6MTcxMDM0MzU4MSwicGF0aCI6Ii8xMDA1MDE3MjIvMzExNTI4MDA5LWRjZTRmMmQwLWE1Y2EtNDIzOC05ZjE5LTAwODZmMzI0NDkxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNTI2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGI0YmMyYjM1MTZlMzE0ZTNiODI3NTZiODZmMzc4NTBjOTJlYTRlNDI5YjgzZDEzOWYyN2I1ZGU0ZDcwYTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EJGHEyGcCqNYjpBkmhIPLGE_CSwSPRVKGOFoMgr3g9Y)
> 
> ### Something like this
> ![image](https://private-user-images.githubusercontent.com/100501722/311528063-4961294a-8c43-40f2-8de2-c9fdeeee756b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDM4ODEsIm5iZiI6MTcxMDM0MzU4MSwicGF0aCI6Ii8xMDA1MDE3MjIvMzExNTI4MDYzLTQ5NjEyOTRhLThjNDMtNDBmMi04ZGUyLWM5ZmRlZWVlNzU2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNTI2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDNjOTg4MDdhMzgyNTYyZDM3NmNlYjg0OGI4NjBiNzg3ODQwZmQxOWVlNzYyYjU1YzExZWQ4NGYyY2Q0NmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wCsXgg7IVmuYTbWr7GnK2dfi2d2REC_acqEU6wThP10)


@ankitjangidx this can be positioned on the background layer to parah and buttons with decreased opacity. IMO it's better to have first text of the page as banner title.

**Comment by sahadat-sk** [comment]
Hi @nehagup, I've made a loading animation for page transition. Take a look and tell me what you think. I'll be adding more animations soon.

https://github.com/keploy/keploy/assets/98450585/759527c3-b293-4074-8942-6aa781887403

**Comment by its-kunal** [comment]
Hey @nehagup, I have raised a pull request for this issue please review it. [PR Link](https://github.com/keploy/blog-website/pull/31)

**Comment by nehagup** [comment]
Hi @sahadat-sk please make a PR. @its-kunal thanks, will review

**Comment by its-kunal** [comment]
hey @nehagup, @Hermione2408 can you please provide a reference related to this task?

>  load action animations (fade in, slide in etc..) on loading pages and blog preview cards
