### ISSUE TITLE
[feature]: add newsletter subscription section to blog website 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1665]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Add a form on the right empty space of the individual posts after user has scrolled 50% of the post with fade in/slide in animation that collects Full Name, Company, Email address.

Use an Github env variable $SUBSCRIPTION_URL to access the fetch URL in the code. 

### Why should this be worked on?

To send new blog posts and newsletter via email to subscribers. 

### Repository

blog-website

**Comment by its-kunal** [comment]
Hey, @nehagup and contributors,
I have designed this sample prototype and want to discuss more about design and layout.

https://github.com/keploy/keploy/assets/92196937/a75cb8f5-b954-4460-bd03-5b2e8341a3d8

**Comment by nehagup** [comment]
@its-kunal this should contain a form taking Full Name, Company, Email address.

**Comment by its-kunal** [comment]
@nehagup created a PR, please review
