### ISSUE TITLE
[bug]: disable record keploy by default

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We use keploy to test keploy. When using keploy directly via the binary, the testing mode is enabled. This tried to send test cases to [https://api.keploy.io](https://api.keploy.io/regression/testcase). This should be disabled by default at the binary level. 

### Steps to reproduce

1. download keploy binary and connect to mongo
2. try recording any test case.

### Environment

Deploy preview

### Version

Local

**Comment by nehagup** [comment]
@Prasanta-mondal the issue is closed.
