### ISSUE TITLE
[refactor]: Star us on github button 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1670]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Current Github Star buttons utilise the Github API but due to the bug in the implementation, number doesn't update in real-time. Animation effects can also be added to this button - something like https://github.com/dillionverma/llm.report/blob/main/components/site-header.tsx 

### Why should this be worked on?

To correct github star numbers 

### Repository

website

**Comment by professorabhay** [comment]
I think that API not returning real-time data - 
Data Returned by API -
![image](https://github.com/keploy/keploy/assets/76243309/13c06bf3-d043-41d6-8798-1b8950918b66)
Real - 
![image](https://github.com/keploy/keploy/assets/76243309/3ac333f9-ce1e-4410-9a30-f02d97e0f9f3)

**Comment by sk0618054** [comment]
I fix this please check my pull request :- [929aa58](https://github.com/keploy/website/pull/2/commits/929aa58034b141e75c3ac8aed2c0a11ad47bf193)
![Screenshot 2024-03-10 191730](https://github.com/keploy/keploy/assets/139760052/bdd4e293-125d-4108-83bf-4b4193886df5)

**Comment by its-kunal** [comment]
Does this issue still exist? 
I think the [commit](https://github.com/keploy/website/commit/55770148c1cc8c38ec8a80fd6a4dbdf14e0b675f) has already solved it.
