### ISSUE TITLE
[feature]: add twitter mentions on keploy website

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1673]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Idea to replicate the same sectional concept to keploy website. 

https://github.com/keploy/keploy/issues/1552 

### Why should this be worked on?

Appreciates the community spreading a word.

### Repository

website

**Comment by professorabhay** [comment]
Hey @nehagup, Do we need to create a similar design or something different will also work?

**Comment by nehagup** [comment]
@professorabhay please feel free to suggest any new designs. Same design also works which fits in the color scheme.

**Comment by Aditya-eddy** [comment]
Working it will submit a pr soon!
