### ISSUE TITLE
[feature]: Refactor feature section with parallax effect 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1674]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

currently users are not able to identify that the feature section has 3 tabs and they can click on them. 

So the feature sections needs to be expanded within 3 sub-sections divided in 2 parts. With feature heading and description on one side and image on the other.  I personally like how appsmith has implemented it under "Dev-first workflows" section with parallax effect. 

### Why should this be worked on?

better UX

### Repository

website

**Comment by professorabhay** [comment]
Hey @nehagup, Can you please explicitly mention that section? 
I'm not able to find that feature section on the website of keploy!

**Comment by nehagup** [comment]
haha.. @professorabhay that's the problem. The feature section is "keploy for developers" section that has 3 tabs with different GIFs

**Comment by professorabhay** [comment]
Kind of treasure hunting! 

![image](https://github.com/keploy/keploy/assets/76243309/d12f09a8-b160-41b4-a6a9-b5518d1d7aa4)
