### ISSUE TITLE
[feature]: add infinite loop and fade in effect to Trusted by section

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1675]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Add “Trusted by” and “dependencies” section with infinite loop and fade in at the ends. I personally liked how stepci has done it 

<img width="674" alt="Screenshot 2024-03-08 at 6 45 39 PM" src="https://github.com/keploy/keploy/assets/15074229/3a598d2f-986b-4075-8c9e-8a09beeaa250">

### Why should this be worked on?

for cleaner look

### Repository

website

**Comment by professorabhay** [comment]
So, we have to implement that fade functionality in this trusted section, and similar to this we need a dependency section?
Is that white circle highlighting on the left side a kind of implementation bug? 🤔

![image](https://github.com/keploy/keploy/assets/76243309/188e6625-3e81-4d47-9a01-42caf13e9554)
