### ISSUE TITLE
[feature]: add command line tutorial section to website

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1676]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Liked the concept of implementation by stepci. Keploy has simple 3 step running guide, one-click installation command, record and replay. 

<img width="337" alt="Screenshot 2024-03-08 at 6 47 42 PM" src="https://github.com/keploy/keploy/assets/15074229/b98f6328-66f9-4fb3-832d-cd7a20cb863c">

### Why should this be worked on?

easy access for users to try out keploy just when they are exploring website.

### Repository

website

**Comment by Aditya-eddy** [comment]
Will be working on this submitting a pr soon!!
