### ISSUE TITLE
[feature]: Prettify code blocks on blog-website

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1685]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Prettify code blocks is required, currently all the code blocks are left aligned. Adding tabs-formatting according to language will enhance the readability.

### Why should this be worked on?

better UX - enhances the readability and understandability of the code snippet

### Repository

blog-website

**Comment by its-kunal** [comment]
Hey @nehagup, I'll be working on this, submitting a PR soon

**Comment by ankitjangidx** [comment]
> Hey @nehagup, I'll be working on this, submitting a PR soon

For this issue, I think setting up Prettier would be better option so that the same code formatting settings will be used consistently across all code blocks. This will streamline the process and ensure code consistency throughout the website.
