### ISSUE TITLE
[feature]: dark mode for the website

### ISSUE THREAD

**Issue by khareyash05** [keploy/keploy#1694]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Hey a dark mode for the website wil be great. Since Tailwind is being used and thus it will be easy to switch to dark mode.

I can work on that

### Why should this be worked on?

Enhanced user experience

### Repository

website

**Comment by harshsbhat** [comment]
Can I work on this

**Comment by khareyash05** [comment]
> Can I work on this
> 

Hey @harshsbhat I actually opened up the PR for myself. Could you please look for other issues. Thanks

**Comment by its-kunal** [comment]
Hey @nehagup, can I work on this issue?

**Comment by harshsbhat** [comment]
Hey @khareyash05  I can see you have not completed this in 2 months. Can I work on this?

**Comment by khareyash05** [comment]
Yeah. Please give it a go!

**Comment by harshsbhat** [comment]
Is it approved by the maintainers to work on?
