### ISSUE TITLE
[bug]: TestResult summary overlap issue at certain media sizes

### ISSUE THREAD

**Issue by hanzili** [keploy/keploy#1698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On a certain media size(width 768-1005px), the TestResult summary overlap with other components on the page.  I expect the summary to be clearly visible and not obscured by any other elements on the page, regardless of the media size or screen resolution.

### Steps to reproduce

a. Adjust the browser to a specific media size (width 768-1005px).
b. Navigate to the home page where the TestResult summary is displayed.
c. Observe that the summary is overlapping with other components on the page.<img width="566" alt="image" src="https://github.com/keploy/keploy/assets/96609857/56a3b507-f91f-4abe-ab1e-5b630acc0390">

### Environment

None

### Version

Cloud

### Repository

website

**Comment by nehagup** [comment]
Thanks for creating issue @hanzili It can be solved with https://github.com/keploy/keploy/issues/1672

**Comment by ethanwater** [comment]
@nehagup submitted a simple fix, had to redo since I forgot to sign.

**Comment by hanzili** [comment]
![image](https://github.com/keploy/keploy/assets/96609857/1fb078e9-ef08-4176-977a-0b5c7c0950db)


lots of component are overlapped in current version

**Comment by nehagup** [comment]
> ![image](https://private-user-images.githubusercontent.com/96609857/318286899-1fb078e9-ef08-4176-977a-0b5c7c0950db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDk1MjUsIm5iZiI6MTcxMTkwOTIyNSwicGF0aCI6Ii85NjYwOTg1Ny8zMTgyODY4OTktMWZiMDc4ZTktZWYwOC00MTc2LTk3N2EtMGI1YzdjMDk1MGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE4MjAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyOGQ2NWQ0MTc4NDE2OTNiOTdhMTQ4YTFiM2VmZTIxNzdjMWNjZDEyZTY4MTNiOTFiOTU2MGEwYTdmMGEwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KELN8lOX5yhp0b0s6yDoO4g-A1Af6T5WLYv248JOKRk)
> 
> lots of component are overlapped in current version

@hanzili can you please share which screen size are you testing this on? I checked all screen sizes on chrome, couldn't replicate the SS you shared.

**Comment by hanzili** [comment]
> > ![image](https://private-user-images.githubusercontent.com/96609857/318286899-1fb078e9-ef08-4176-977a-0b5c7c0950db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDk1MjUsIm5iZiI6MTcxMTkwOTIyNSwicGF0aCI6Ii85NjYwOTg1Ny8zMTgyODY4OTktMWZiMDc4ZTktZWYwOC00MTc2LTk3N2EtMGI1YzdjMDk1MGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE4MjAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyOGQ2NWQ0MTc4NDE2OTNiOTdhMTQ4YTFiM2VmZTIxNzdjMWNjZDEyZTY4MTNiOTFiOTU2MGEwYTdmMGEwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KELN8lOX5yhp0b0s6yDoO4g-A1Af6T5WLYv248JOKRk)
> > lots of component are overlapped in current version
> 
> @hanzili can you please share which screen size are you testing this on? I checked all screen sizes on chrome, couldn't replicate the SS you shared.

https://github.com/keploy/keploy/assets/96609857/3a654cd0-50af-46d8-b24a-5fbf8e825a2c


Yes, the width of the screen is around 740px. I just tested using Chrome and observe the same behavior
