### ISSUE TITLE
[bug]: keploy hangs if proxy port is already in use

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- If the Proxy port is already in use, keploy fails to clean up and gracefully exit and also hangs even after hitting `ctrl + c`.
<img width="1428" alt="Screenshot 2024-03-18 at 12 40 17 PM" src="https://github.com/keploy/keploy/assets/44055698/4275bfc9-1838-4962-96a6-01416f3d126c">

### Steps to reproduce

1. Start keploy in record mode.
2. And another terminal, again run keploy.
3. `{"error": "listen tcp :16789: bind: address already in use"}` will be thrown and `ctrl + c` won't work 

### Environment

None

### Version

Local

### Repository

keploy

**Comment by Swpn0neel** [comment]
Any update on this? @gouravkrosx

**Comment by AhmedLotfy02** [comment]
@gouravkrosx working on this.
