### ISSUE TITLE
[bug]: copy button doesn't copy to clipboard for Safari

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#1706]
### What do you want to add to the docs? (please state reasons if any)

The copy command button on the docs website doesn't copy the script on Safari, it could be for other browsers as well. For chrome, it works. 

### Where is this stated?

docs website

### Repository

docs

**Comment by Ajeett01** [comment]
Solving!

**Comment by outoflaksh** [comment]
Hi, I was tinkering around with the code from the docs repo. Found a static js file that takes care of the copy to clipboard feature. I added some code that could work with Safari but any of the changes I made aren't reflected in the local dev server. Is the codebase fetching the static js files from a separate external URL? If so, can you point me to where I can change such a setting? Thanks!

**Comment by Ajeett01** [comment]
I faced the similar problem when I edited code-block-buttons.js, I was trying to figure out what may be the reason.

**Comment by Aditya-eddy** [comment]
Copy to Clipboard button is handled by MDX tag. Which is provided by the docusaurus. Maybe we need to update the browsers in the config file.

**Comment by nehagup** [comment]
@Aditya-eddy can you please pick this up, we see no other PR for now.

**Comment by Swpn0neel** [comment]
Are you still working on it @Aditya-eddy ?

**Comment by Aditya-eddy** [comment]
hey @Swpn0neel i think this issue has been fixed by upgrading the docusaurus to v3. But please if the issue still persists you can go on with it.
