### ISSUE TITLE
[feature]: React UI Console for Test Generation

### ISSUE THREAD

**Issue by athul-22** [keploy/keploy#1709]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Project Overview:
The goal is to develop a straightforward UI console using React, demonstrating Keploy's test generation capabilities. This console will enable users to record and replay tests while highlighting Keploy's automatic test generation feature.

Goals & Ideas:
Simple Interface: I'll create an intuitive layout in collaboration with mentors, ensuring easy navigation for users.
Record and Replay: I'll implement functionality for users to record actions and replay them as tests, making test creation straightforward.
Automatic Test Generation: I'll showcase Keploy's ability to automatically generate tests based on user interactions, emphasizing its efficiency.
Interactive Demo: Users will engage with the demo, experiencing firsthand how Keploy simplifies test generation.
Documentation: I'll provide clear documentation within the UI console to guide users through the demo and explain Keploy's benefits.
Responsive Design: I'll ensure the UI console is responsive across devices, using TailwindCSS for seamless functionality.

Skills and Experience:
I'm proficient in React, Typescript, Next.js, and TailwindCSS, with prior experience in building user-friendly interfaces and integrating complex functionalities.
Github:  http://github.com/athul-22

**Comment by PranshuSrivastava** [comment]
Hey, @athul-22 thanks for proposing this idea. We will discuss the usecase of this project with the mentors and get back to you.
