### ISSUE TITLE
[docs]: Add glossary describing complex terms.

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/keploy#172]
### What do you want to add to the docs? (please state reasons if any)

Create a glossary page that will describe all the complex terms beginners find difficult to understand when they walkthrough the documentation, for example, in the [Keploy features](https://docs.keploy.io/docs/concepts/what-are-keploy-features) section:
1. ***Automatically mock Mutations***: This feature description involves the word **idempotency**, so, explain the term w.r.t API.
1. ***Accurate Noise Detection***: This part involves the reference to noisy field, please add a short description explaining what **noisy field** is and why it needs to be neglected.
2. ***Native Interoperability***: Add what **native interoperability** refers to and break down the description of How Keploy contributes to it.

### Where is this stated?

These updates will help beginners to gain a clear understanding of basic terms and concepts, which in turn will be useful for them in learning advanced topics.

**Comment by mahinperwaiz** [comment]
is it done or still needs some improvements?

**Comment by SanskritiHarmukh** [comment]
Created a [pull request](https://github.com/keploy/docs/pull/36) solving this issue, but was unable to link it to this issue directly, may be because I already used it in the previous PR. @mahinperwaiz you can do improvements once @nehagup review the new pull request.
