### ISSUE TITLE
[feature]: Explore integration with Tyk

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1730]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to explore if key can add value after being integrated with Tyk. 

### Why should this be worked on?

Can ease testing of the Tyk project. 

### Repository

keploy

**Comment by charankamarapu** [comment]
### ABOUT TYK
TYK is an API Gateway which can be installed and users can register APIs to the TYK Gateway and the TYK gateway will acting as gateway to the API. TYK supports many frameworks like REST, GraphQl and protocols like HTTP, GRPC etc.

### Challenges in Integrating TYK with Keploy
After registering the API using this [way](https://tyk.io/docs/getting-started/create-api/). The configuration of the API is stored in a file and when ever it TYK is restarted It will fetch config from it and stores in Redis and uses it. As TYK is storing configuration in file system, it is not possible to replay the test cases properly.

**Comment by charankamarapu** [comment]
PR in tyk repo - https://github.com/TykTechnologies/tyk/pull/6197
