### ISSUE TITLE
[bug]:  incorrect routing on blog website 

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Rigth now, if the blog is present on community for example top 5 cypress alternative blog is present under `/community`, on keploy.io/blog. 

Original URL:- https://keploy.io/blog/community/top-5-cypress-alternatives-for-web-testing-and-automation
<img width="1752" alt="image" src="https://github.com/keploy/keploy/assets/53110238/f6e6be5c-3087-43e6-b8db-04c4dd4879be">

But if we change community to technology, then also the url is working, which shouldn't be the case it should show 404 as the blog is hosted on community website.

Canonical URL:- https://keploy.io/blog/technology/top-5-cypress-alternatives-for-web-testing-and-automation

### Steps to reproduce

1. go to https://keploy.io/blog/community/
2. open any blog.
3. change `community` to `technology` in the URL/

### Environment

None

### Version

Cloud

### Repository

blog-website

**Comment by ethanwater** [comment]
It's worth noting that the same bug can be reproduced vice versa. If we change technology to community in the url for any technology posts, the same error will occur.

**Comment by kanugurajesh** [comment]
@Sonichigo can you assign me the issue I have found the reason

**Comment by Aditya-eddy** [comment]
hey @Sonichigo made a pr please check!
