### ISSUE TITLE
[feature]: update all the frameworks logo on landing page

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1734]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

right now only four language are mentioned on the landing page. 
<img width="1329" alt="image" src="https://github.com/keploy/keploy/assets/53110238/39f58b49-88e3-4362-b0d7-c6a16e1cc241">

But keploy supports more languages such as rust, csharp, etc..

### Why should this be worked on?

This would help the first time discovererd user who are coming on main website to know more about the supports that keploy provide

### Repository

website

**Comment by kanugurajesh** [comment]
@Sonichigo can you assign this issue to me I will fix it soon

**Comment by Aditya-eddy** [comment]
hey @Sonichigo does the background png available or we have to make our own?

**Comment by Sonichigo** [comment]
You take the pngs from net!

**Comment by nehagup** [comment]
> hey @Sonichigo is the background png available or we have to make our own?

@Aditya-eddy this task doesn't require that background PNG, since it's about adding more languages support. 

However, if you're planning to add any frameworks, please use this. 

![bg-pg](https://github.com/keploy/keploy/assets/15074229/285cc397-85a3-42b1-9aa2-a2056b9d32ee)

**Comment by Aditya-eddy** [comment]
I was asking about this background only. thanks
