### ISSUE TITLE
[feature]: Add code coverage data to keploy test report

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1735]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to add code coverage info to the test reports in a generic format. 

### Why should this be worked on?

This will help users leverage the coverage information to get better understanding of keploy test execution and visualization via keploy dashboard. 

### Repository

keploy

**Comment by AkashKumar7902** [comment]
Currently, only coverage data for go applications can be accessed programmatically. 

Also, in case of go applications, the overall coverage data is collected, the code which does this resides in printSummary function of replay.go, which means it is outside the scope of individual test-set and test report is concluded for each test-set run.
