### ISSUE TITLE
[feature]: log error in case of invalid flags

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1747]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

* Incase of running invalid flags keploy doesn't specifically tells the error just stops.
* 
<img width="626" alt="image" src="https://github.com/keploy/keploy/assets/60891544/c91a3a68-3ecc-4e7b-b8ef-e90c14b9ae2a">

### Why should this be worked on?

* Incase if an invalid flag is provided, it should be logged as well for the user

### Repository

keploy

**Comment by ethanwater** [comment]
Gonna give this a look. 👍

**Comment by ethanwater** [comment]
@shivamsouravjha This bug has been fixed. The errors were being explicitly silenced.
