### ISSUE TITLE
[bug]: Author Profile image looks different in the single post page

### ISSUE THREAD

**Issue by its-kunal** [keploy/keploy#1752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

view for an author profile image in the single post page

![image](https://github.com/keploy/keploy/assets/92196937/4290a04b-a00b-411d-a94d-54b320f10c7c)

![image](https://github.com/keploy/keploy/assets/92196937/ce88b6dc-5fd0-43d7-8b5e-505e3b2065ef)

For different authors, it does not maintain the proper design pattern

### Steps to reproduce

Link for the above posts are - [Link 1](https://keploy.io/blog/community/why-i-love-end-to-end-e2e-testing) [Link 2](https://keploy.io/blog/community/understand-the-role-of-continuous-testing-in-ci-cd)

### Environment

Production

### Version

Cloud

### Repository

blog-website

**Comment by Aditya-eddy** [comment]
Hey @its-kunal how is it looking different ?

**Comment by its-kunal** [comment]
@Aditya-eddy, height and width of author profile image

**Comment by Aditya-eddy** [comment]
okay please go ahead then.
