### ISSUE TITLE
[feature]: automatically add test reports folder to gitignore 

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1775]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We should maybe create a gitignore if possible in the keploy folder that adds the test report folder and prevents it from accidentally being commited. 

More ideas to accomplishing this is also welcome. 

### Why should this be worked on?

Some users have been accientially commiting the reports folder present in the keploy folder to git. This can unnecessarily polute the git history. 

### Repository

keploy

**Comment by ethanwater** [comment]
I assume we can just create a gitignore file, and write the report path to it? much like how it's done in Rust using cargo

**Comment by Akash-Singh04** [comment]
@slayerjain Kindly review this and let me know if this implementation works!

**Comment by ayush3160** [comment]
@Swpn0neel , Can you please assign this to me.
Thanks

**Comment by Swpn0neel** [comment]
Go ahead! @ayush3160
