### ISSUE TITLE
[bug]: nil pointer MySQL parser exceptions 

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There seems to be multiple nil pointer excpetions reported on the slack channel. We need to replicate them and fix, to make it useable. 

### Steps to reproduce

1. make an application with MySQL database. 
2. First conenction should fail with keploy reporting a nil pointer exception. 

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by slayerjain** [comment]
We should explore using https://kaitai.io for reimplementation of the mysql parser.

**Comment by gouravkrosx** [comment]
This bug has been resolved. MySQL is working as intended.
