### ISSUE TITLE
[feature]: Dedicated parser for Redis

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1778]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

So far the redis parser has been using the generic parser, but I feel it might be better to have a deicated parser. 

### Why should this be worked on?

It might help with use experience. 

### Repository

keploy

**Comment by shivamsouravjha** [comment]
Redis has a dedicated parser, we can close this issue.
