### ISSUE TITLE
fix: automatic generation of github action workflow for keploy should be configurable

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1780]
- Since, right now it is not configurable, in the testing pipeline, we are unnecessarily making this workflow file.
- It should be configurable (default: true) but in the testing pipeline, it should be false.

**Comment by Akash-Singh04** [comment]
Will look into this!

**Comment by Akash-Singh04** [comment]
We can add in a flag to enable or disable the generation of this github actions file
