### ISSUE TITLE
[feature]: move middleware code to v2

### ISSUE THREAD

**Issue by EraKin575** [keploy/keploy#1797]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Move middleware code to v2 folder and set coverage function code independently

### Why should this be worked on?

--

### Repository

java-sdk

**Comment by Swpn0neel** [comment]
PR has problem, and the issue is currently stale @Sonichigo

**Comment by gouravkrosx** [comment]
@Sarthak160 Please check whether this issue is relevant or not.
