### ISSUE TITLE
[bug]: use of Image tag instead of img tag.

### ISSUE THREAD

**Issue by its-kunal** [keploy/keploy#1799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the following files - 
- components\language.tsx
- components\trustedBy.tsx
- components\tweets.tsx

`img` tag is used.

### Steps to reproduce

Go to files -
- components\language.tsx
- components\trustedBy.tsx
- components\tweets.tsx

Here, `img` tag is used, while the use of `Image` tag will leverage the full potential of Next.js

### Environment

Deploy preview

### Version

Local

### Repository

website

**Comment by anuanu0-0** [comment]
Can I take up this issue if no one is working on it?
