### ISSUE TITLE
[feature]: check if the linux kernel version is lower than 5.15

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1811]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We should automically check, log and return if the kernel version is less than 5.15, since keploy only supports above that version. 

We can create compatibility check before performing record or test during flag validation. 

### Why should this be worked on?

It can create confusion to the users when keploy doens't work due to lower kernel versions such as - https://github.com/keploy/keploy/issues/984

### Repository

keploy

**Comment by Aryakoste** [comment]
Hello @slayerjain @nehagup. I would like to work on this issue.

**Comment by slayerjain** [comment]
@Aryakoste sure! Please try and raise a PR:)

**Comment by suvanbanerjee** [comment]
@slayerjain should we check this in installer ? like if kernel version is lower than 5.15 then don't let the user install keploy and show error message am i interpreting correctly.

**Comment by slayerjain** [comment]
@suvanbanerjee I think better to check the kernel version when keploy starts

**Comment by suvanbanerjee** [comment]
@slayerjain if i am not wrong i have to modify `main.go` entry point for keploy

**Comment by slayerjain** [comment]
@suvanbanerjee I think it should be part of the validation logic present in various cli `cmds`. Not all `cmds` require using ebpf. So the ones where we are loading ebpf, we should add to the validation logic.

**Comment by slayerjain** [comment]
we have the `ValidateFlags` for flags, we should likely rename this to just `Validate` and have internal methods for Flag and compatibility validation. @gouravkrosx please guide here

**Comment by gouravkrosx** [comment]
@suvanbanerjee , We can just add a new method to the interface called Validate() which can internally call ValidateFlags. Majorly, record and test cmd require eBPF, you can check the kernel version in the Validate function and then call ValidateFlags.

**Comment by Akash-Singh04** [comment]
Will work on this
Also hello there @suvanbanerjee :D

**Comment by slayerjain** [comment]
@Akash-Singh04 please allow @suvanbanerjee to solve this issue if he wants to solve it.

**Comment by suvanbanerjee** [comment]
> @Akash-Singh04 please allow @suvanbanerjee to solve this issue if he wants to solve it. 

@slayerjain I have having so trouble to run keploy locally due to delayed update in fedora. Thus @Akash-Singh04 you make a PR.

**Comment by Akash-Singh04** [comment]
@slayerjain @gouravkrosx Kindly check the implementation and let me know if it works!
