### ISSUE TITLE
[feature]: log time in the cli results after a test run 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1826]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Its good to log the time taken by keploy to test the application.
We can calculate the time taken by each test run, and maintain a list structure.
Final summary could look like.

`  COMPLETE TESTRUN SUMMARY. 
        Total tests: 7
        Total test passed: 1
        Total test failed: 6

        Test Suite Name         Total Test      Passed          Failed       Time taken 

        "test-set-3"            7               1               6               1:00 min

### Why should this be worked on?

I It will give the idea that how long it took for a complete test run.

### Repository

keploy

**Comment by Swpn0neel** [comment]
Stale issue, the PR has conflicts @Sonichigo

**Comment by debayangg** [comment]
@Swpn0neel can I work on this issue for kROC?

**Comment by Swpn0neel** [comment]
Go ahead @debayangg!!

**Comment by debayangg** [comment]
This is the current preview of this feature. Should I create a PR?
![image](https://github.com/user-attachments/assets/f44873ce-27ca-4c3a-9583-08fc2c0229c7)

**Comment by Swpn0neel** [comment]
LGTM! @shivamsouravjha any feedback?

**Comment by debayangg** [comment]
How do I test the new keploy binary?

**Comment by debayangg** [comment]
@Swpn0neel I have merged a PR for this issue
