### ISSUE TITLE
[feature]: adding reviewed by section in the blogs

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1830]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Google SEO has updated and now focus put the posts on higher rank. Where it focus on content and author of the blog.

### Why should this be worked on?

It will help in the increasing traffic and visitors.

### Repository

website

**Comment by Swpn0neel** [comment]
This issue is currently stale @Sonichigo

**Comment by Sonichigo** [comment]
@Swpn0neel the PR is in review now!
