### ISSUE TITLE
[bug]: routing redirect error on the keploy blog

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i click on the blog :- https://keploy.io/blog/community/write-clean-and-efficient-unit-tests-in-go

It redirects me to keploy technology blog. This behavior is for the blog specified above as it the latest blog released after the fix of #1733  (https://github.com/keploy/keploy/issues/1733)

### Steps to reproduce

1. Go to https://keploy.io/blog/community 
2. Click on:- https://keploy.io/blog/community/write-clean-and-efficient-unit-tests-in-go
3. You will be redirected to the keploy.io/blog/technology

### Environment

Production

### Version

Cloud

### Repository

blog-website

**Comment by Sonichigo** [comment]
The Issue is with keploy.io/blog/technology as well! The new tech blogs redirects to /community, just vice-a-versa of the issue mentioned above.

**Comment by Sonichigo** [comment]
a pr fixed the issue on temporary basis:- #keploy/docs

**Comment by its-kunal** [comment]
I'll be working on this issue and raise a PR soon.

**Comment by Sonichigo** [comment]
hi @its-kunal ! The PR raised by @aditya-eddy has fixed the issue! You can take a look at other issues revolving around keploy website :- https://github.com/keploy/keploy/issues?q=is%3Aopen+is%3Aissue+label%3Awebsite
