### ISSUE TITLE
[feature]: Make mock data compress-decompress while writing it into yaml

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#184]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently mock export feature of keploy is wiriting mocks into yaml.  
Mock for a test ID looks like - 

<img width="1691" alt="Screenshot 2022-10-03 at 1 35 25 PM" src="https://user-images.githubusercontent.com/50234097/193542557-35ebdba9-151a-4b2d-a9b3-d82d65d5014e.png">

- Mock object's data is displayed as base64 encoded string . There are some cases where size of string can be very large like above example .
- So we can use some compressing tools which can compress the byte string while writing and can decompress them back at the time of test runs .
- Some of them are - compress/gzip which take Base64OutputStream and converts it into gzipped format 

### Why should this be worked on?

- This can be very fuzzy to see such large ByteString in code base .
- This is making reading testcases unreadable for the user .

**Comment by Shivansh-yadav13** [comment]
@Sarthak160 I would like to contribute

**Comment by nehagup** [comment]
@Shivansh-yadav13 I've assigned the issue.
