### ISSUE TITLE
[bug]: Content Overlap on Medium Screen Sizes

### ISSUE THREAD

**Issue by Hermione2408** [keploy/keploy#1843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On medium screen sizes, there is an overlap of the gif of native integration and content for it 
![Screenshot from 2024-04-22 11-33-28](https://github.com/keploy/keploy/assets/78696767/ee39439e-dd8f-479a-9174-2f7d44f7cafa)

### Steps to reproduce

1. Open the website on a medium screen device.
2. Navigate to the keploy for developer section 
3. Observe the overlap between the text content and the code block for native integration GIF .

### Environment

None

### Version

Local

### Repository

website

**Comment by Swpn0neel** [comment]
I want to work on this issue!!

**Comment by nehagup** [comment]
@Swpn0neel please check, issue is still not resolved.

**Comment by Swpn0neel** [comment]
See, it's working fine @nehagup... I just checked it from the deployment </br>
![image](https://github.com/keploy/keploy/assets/121167506/33688b72-a85c-417a-b1c1-de854ea4d3b0)

**Comment by nehagup** [comment]
Looks good! Thanks @Swpn0neel 👏
