### ISSUE TITLE
[docs]: Link not working in PyTest documentation

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#1844]
### What do you want to add to the docs? (please state reasons if any)

The actual addressable link to the "this" word, which is currently not working
![image](https://github.com/keploy/keploy/assets/121167506/f205550e-dfe4-446e-babd-11b9bf37a001)

### Where is this stated?

This is confusing for someone who is looking for a potential solution to the problem

### Repository

docs

**Comment by Swpn0neel** [comment]
I want to work on this issue

**Comment by Sonichigo** [comment]
@Swpn0neel assigned to you!
