### ISSUE TITLE
[bug]: race condition in keploy record

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* testCount is concurrently written and read in case of keploy record.

### Steps to reproduce

* Build the binary with `go build -race -tags=viper_bind_struct -o keploybin . && sudo mv keploybin /usr/local/bin/keploybin`
* Try running express-mongoose in record.
* While closing race condition occurs

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by dxtym** [comment]
Hi! May I give this a try?

**Comment by shivamsouravjha** [comment]
sure @dxtym  you can work on the issue!
