### ISSUE TITLE
[bug]: no log incase of wrong commands

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* in case of wrong command, no log is shown for sample commands.
<img width="598" alt="image" src="https://github.com/keploy/keploy/assets/60891544/89dc1996-633b-4558-b58b-56fb54547243">

### Steps to reproduce

* Run keploy exmaple or any wrong command.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by ADTmux** [comment]
I would like to work on this!

**Comment by shivamsouravjha** [comment]
sure @ADTmux you can work on the issue
