### ISSUE TITLE
[bug]: python in docker workflow fails 

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* Python in docker fails due to build error in flask-mongo
<img width="980" alt="image" src="https://github.com/keploy/keploy/assets/60891544/9830dc0d-ce03-4a34-b053-3f32a2fd0254">

### Steps to reproduce

* Pipelines are failing

### Environment

None

### Version

Cloud

### Repository

samples-python

**Comment by PranshuSrivastava** [comment]
Fixed by resetting irrelevant commits in the sample app.
