### ISSUE TITLE
[bug]: not able to start keploy with docker

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="1449" alt="image" src="https://github.com/keploy/keploy/assets/53110238/8d3c1775-91a9-4f21-9171-9b7f0b664a86">

I am using my application with keploy and docker : - 
```
keploy record -c "docker compose up" --containerName "bunSqlApp" --buildDelay 50s
```

Afer one-click, keploy alias variable is set as below
```
alias keploy='docker run --pull always --name keploy-v2 -p 16789:16789 --privileged --pid=host -it -v $(pwd):$(pwd) -w $(pwd) -v /sys/fs/cgroup:/sys/fs/cgroup -v debugfs:/sys/kernel/debug:rw -v /sys/fs/bpf:/sys/fs/bpf -v /var/run/docker.sock:/var/run/docker.sock -v /Users/sonichigi/.keploy:/root/.keploy --rm ghcr.io/keploy/keploy'

```

### Steps to reproduce

1. I used one-click installation `curl -O https://raw.githubusercontent.com/keploy/keploy/main/keploy.sh && source keploy.sh`
2. run keploy with docker
3.
```
🐰 Keploy: 2024-05-07T09:30:35Z         ERROR   failed to attach the kretprobe hook on tcp_v4_connect   {"error": "creating tracefs event (arch-specific fallback for \"tcp_v4_connect\"): creating probe entry on tracefs: checking trace event ebpf_0e10d539f465b608/tcp_v4_connect: neither debugfs nor tracefs are mounted"}
🐰 Keploy: 2024-05-07T09:30:35Z         ERROR   failed to load hooks    {"error": "creating tracefs event (arch-specific fallback for \"tcp_v4_connect\"): creating probe entry on tracefs: checking trace event ebpf_0e10d539f465b608/tcp_v4_connect: neither debugfs nor tracefs are mounted"}
🐰 Keploy: 2024-05-07T09:30:35Z         ERROR   failed to start the hooks and proxy     {"error": "failed to hook into the app"}
```

### Environment

Release

### Version

Local

### Repository

keploy

**Comment by charankamarapu** [comment]
Hi @Sonichigo latest release is working fine for me with samples-go repo and gin-mongo application. Can you try with latest release? I suggest you to try first with gin-mongo and then with your sample app where you faced the error.

**Comment by Sonichigo** [comment]
Hi @charankamarapu yep tried with latest release installed from one and with gin-mongo itself, still not working.

**Comment by besasch88** [comment]
@Sonichigo Please try with `docker volume rm debugfs` and `docker volume create --driver local --opt type=debugfs --opt device=debugfs debugfs`.

**Comment by Swpn0neel** [comment]
Is this issue still active @Sonichigo?

**Comment by Sonichigo** [comment]
This issue is resolved
