### ISSUE TITLE
[feature]: add test pipeline for testing `MySQL` parser using different applications

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1869]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Currently, there's a test pipeline for the gin-mongo application, which is a combination of Golang and MongoDB, aimed at testing the Mongo parser. ([1](https://github.com/keploy/keploy/blob/44109632096744c364a1ec081261c01d02e6d830/.github/workflows/build_stage.yml#L23)), ([2](https://github.com/keploy/keploy/blob/44109632096744c364a1ec081261c01d02e6d830/.github/workflows/build_stage.yml#L27))
- Likewise, we aim to establish pipelines for all supported languages using MySQL as the database to test the MySQL parser.
- You can contribute to this effort by referring to our documentation on how to extend coverage for Keploy or understand its self-testing approach.
- Docs Link: https://keploy.io/docs/keploy-explained/testing-guide/

### Why should this be worked on?

- This initiative will enhance Keploy's coverage and benefit all users by supporting its testing capabilities through the concept of Keploy testing Keploy.
- It will promote confidence in reviewing pull requests, particularly those involving changes to the MySQL parser, by ensuring thorough testing and validation.

### Repository

keploy

**Comment by RISHIKESHk07** [comment]
@gouravkrosx could I try this as a beginner?

**Comment by gouravkrosx** [comment]
@RISHIKESHk07 
Yes, you can try, if you face any problems while following the docs, please let us know.

**Comment by RISHIKESHk07** [comment]
@gouravkrosx it the above the correct approach , or i am missing additional knowledge ?
