### ISSUE TITLE
[bug]:  preview image is incorrect on landing page

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Right now while sharing the any https://keploy.io/ url except the blog or docs, the preview image is by default the image with largest size present in the page.

<img width="349" alt="image" src="https://github.com/keploy/keploy/assets/53110238/6db46b16-2627-4550-a3b2-fe09cd86a200">
<img width="371" alt="image" src="https://github.com/keploy/keploy/assets/53110238/e3254aea-25ce-40df-adc6-6d5feff7c12d">

### Steps to reproduce

1. Share the https://keploy.io/ on any social media platform like google chats, slack, twitter to preview the Page.
<img width="349" alt="image" src="https://github.com/keploy/keploy/assets/53110238/8e748c61-e39e-4e7e-8ca2-4e66d968d2d0">

### Environment

Production

### Version

Cloud

### Repository

website

**Comment by ShashankGarg24** [comment]
Hey, Can i work on this issue?

**Comment by chintanpuggalok** [comment]
I am just seeing a blank can you please attach more screenshots?
<img width="1728" alt="image" src="https://github.com/keploy/keploy/assets/55681139/9d554575-51c0-4df7-be36-36c081aebc6e">

**Comment by Sonichigo** [comment]
hi @chintanpuggalok ! Seems like the preview image is showing up only on chats and not on any other social medias such as linkedin, slack, or even twitter. I suspect this could be because there isn't any preview image set by default and what google chat is doing, it's taking the image for preview based on the size of the image and resolution by it self.

**Comment by chintanpuggalok** [comment]
so what do we actually want like any specific image that should be out view image?

**Comment by Sonichigo** [comment]
yes, the image should be keploy logo.

**Comment by rohitmondal03** [comment]
@Sonichigo if this issue is still open, can I work on this ?

**Comment by Sonichigo** [comment]
hi @rohitmondal03 yes it's up for grabs

**Comment by rohitmondal03** [comment]
Will work on it @Sonichigo

**Comment by Sonichigo** [comment]
Hey @rohitmondal03 any updates?

**Comment by yaten2302** [comment]
Hey @Sonichigo, if this issue is still open, then may I work on it? I just tried to send [this](https://keploy.io/) url to myself on slack, it's not showing any image?

![image](https://github.com/keploy/keploy/assets/129659514/660e3044-c82a-4a9f-a630-f0be1826dfc0)

**Comment by Sonichigo** [comment]
> Hey @Sonichigo, if this issue is still open, then may I work on it? I just tried to send [this](https://keploy.io/) url to myself on slack, it's not showing any image?
> 
> ![image](https://private-user-images.githubusercontent.com/129659514/343640094-660e3044-c82a-4a9f-a630-f0be1826dfc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzM4MTYsIm5iZiI6MTcxOTQ3MzUxNiwicGF0aCI6Ii8xMjk2NTk1MTQvMzQzNjQwMDk0LTY2MGUzMDQ0LWM4MmEtNGE5Zi1hNjMwLWYwYmUxODI2ZGZjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwNzMxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDZiOTU5MDk4YzdlY2I5NjM5ZDc5Y2VhYjFjNTM5ZTk1ZWUxNzRmZjExYTBmZWQ0ZDk4NjY5YTE5MGJmYzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JMUGaOXnlGV3kaTI1H2l2o4xZGr481-FMIcJK_HYB0g)

Hey @yaten2302 yes, this issue still up for grabs!

**Comment by Sonichigo** [comment]
yes @yaten2302

**Comment by yaten2302** [comment]
> yes @yaten2302

@Sonichigo  should I use [this logo](https://github.com/keploy/website/blob/main/components/ui/logo.tsx)?

**Comment by yaten2302** [comment]
I've create a PR for this @Sonichigo, could you please review that and LMK if any changes are required?
