### ISSUE TITLE
[bug]: outdated blog URL on docs main page

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1886]
The New keploy blog website is hosted on https://keploy.io/blog. But on docs page it still points to the old keploy hashnode blog page. Therefore, it needs to be and point to right and latest blog website.

<img width="1116" alt="image" src="https://github.com/keploy/keploy/assets/53110238/c2ba1ce1-8f50-4b73-996e-5bc6ec0b7752">

**Comment by anshjain16** [comment]
@Sonichigo can i solve this issue

**Comment by anshjain16** [comment]
I found the page where the link is located, i just need to know what icon to place instead of the hashnode one
![image](https://github.com/keploy/keploy/assets/137677212/9c8a51d0-ac84-4494-80d0-c17fc236b418)

**Comment by Sonichigo** [comment]
Hey @anshjain16, you can use the icon of keploy instead of hashnode

**Comment by anshjain16** [comment]
Done it!!
![image](https://github.com/keploy/keploy/assets/137677212/5b9c7f4c-90bd-420d-8082-da02fbe91880)
Can you check the title , it should be blogs or blog
Also the pr should be raised in the docs repo itself right?

**Comment by anshjain16** [comment]
Hey @Sonichigo I created a pull request on the docs repo, can you review it

**Comment by Sonichigo** [comment]
Closing since fix is merged:- https://github.com/keploy/docs/pull/398
