### ISSUE TITLE
[docs]: add nested fields example in config file

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1892]
### What do you want to add to the docs? (please state reasons if any)

Currently, adding deeply nested JSON fields in the configuration file, such as in the global noise section, is somewhat tricky. While adding fields with a single level of nesting is manageable, handling multiple levels of nesting can be more complex. Therefore, we need additional examples in the **_Keploy configuration comments_** and **_documentation_** to better illustrate how to add these nested fields.

### Where is this stated?

Lets say we have this token field inside the response body.
```json
{"data":{"signUp":{"id":"100","email":"keploy@test.com","firstName":"keploy","lastName":"keploy","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImNyZWF0ZWRBdCI6IjIwMjQtMDUtMjJUMTA6NDk6MjIuNjI0WiIsImlkIjoxMDAsImZpcnN0TmFtZSI6InNhZ2FyIiwibGFzdE5hbWUiOiJ0b21hciIsImVtYWlsIjoic2FnYXJAdGVzdC5jb20iLCJwYXNzd29yZCI6IjU1ZjQ1MTg2OWI3OTZlMmFlZmU3ODA2ZjA0YTJlMzBkIiwidXBkYXRlZEF0IjoiMjAyNC0wNS0yMlQxMDo0OToyMi4wMzlaIiwiZGVsZXRlZEF0IjpudWxsfSwiaWF0IjoxNzE2Mzc0OTYyLCJleHAiOjE3MTY0NjEzNjJ9.21A-gz8QLnbx2bhpzMcezENjTGWKhBfwU4o2paFuEVM","createdAt":"2024-05-22T10:49:22.624Z","deletedAt":null,"updatedAt":"2024-05-22T10:49:22.039Z"}}}
```
How can I use it in the config file? refer [this](https://keploy.io/docs/running-keploy/configuration-file/#global-noise).

### Repository

docs

**Comment by gouravkrosx** [comment]
This is working:
<img width="318" alt="Screenshot 2024-05-23 at 6 02 13 PM" src="https://github.com/keploy/keploy/assets/44055698/304cfcfa-62e3-4293-bdb8-5e5e6ae4632b">

**Comment by khareyash05** [comment]
This also works
```
"body":{
      "data.login.token": [],
      "data.login.refreshToken":[]
}
```

**Comment by piyush182004** [comment]
I want to contribute to this doc part. I have already prepared several examples that demonstrate how to handle deeply nested JSON fields in both the global noise and test-set noise sections. Here are some sample configurations: 
GLOBAL NOISE EXAMPLE
globalNoise:
  global:
    body:
      data:
        signUp:
          token: []
    header:
      Date: []

TEST NOISE EXAMPLE 

test-sets:
  test-set-1:
    body:
      data:
        signUp:
          token: []
    header:
      User-Agent: ["PostmanRuntime/7.34.0"]

**Comment by shivamsouravjha** [comment]
sure @piyush182004 you can feel free to work on the changes and raise the PR.

**Comment by GauriBhandari** [comment]
@Swpn0neel I would like to work on this issue as the part of kROC!

**Comment by GauriBhandari** [comment]
@Swpn0neel could you please help signing(guiding) about the CLA  ?

**Comment by Swpn0neel** [comment]
> @Swpn0neel could you please help signing(guiding) about the CLA ?

You've failed the DCO check. Kindly do that! You've to first configure Docusaurus in your system and then use "-s" while committing!

**Comment by GauriBhandari** [comment]
@shivamsouravjha so we want to add documentation for the same right , just i did before but in docs repo, or we have to change any config file? Could you please help

**Comment by khareyash05** [comment]
> @shivamsouravjha so we want to add documentation for the same right , just i did before but in docs repo, or we have to change any config file? Could you please help

Not needed, just add it in the docs
