### ISSUE TITLE
[bug]: check for mock kind in parsers

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* Incase of filtered and unfiltered mocks, the fetched mocks  from mockdb should also be filtered on kind inorder to avoid extra mocks during matching
* Happens in Generic,mongo and mysql parsers 

### Steps to reproduce

* search for kind in decodeor match
* better to implement in decode of files.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by anshjain16** [comment]
Hey @shivamsouravjha can i work on this issue

**Comment by shivamsouravjha** [comment]
sure @anshjain16 you can work on this

**Comment by anshjain16** [comment]
@shivamsouravjha can you please provide some more details about this issue

**Comment by anshjain16** [comment]
![image](https://github.com/keploy/keploy/assets/137677212/4ececbba-a34f-4827-a5c5-3c86aa7fa74b)
should the mocks that are being fetched should again be filtered on the basis of kind of mock

**Comment by shivamsouravjha** [comment]
yes @anshjain16  the mocks fetched from filtered and unfiltered mockdb functions are to be filtered again in the parsers.

**Comment by anshjain16** [comment]
is it solved?

**Comment by shivamsouravjha** [comment]
yes @anshjain16  the changes fixed the issue, you can look out for other open issues.
