### ISSUE TITLE
[bug]: keploy update not working on debian

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have installed keploy via one-click, i was on `version: 2.1.0-alpha16`, and tried to bump up version by using `keploy update` command, but getting the below error message : 

<img width="1043" alt="image" src="https://github.com/keploy/keploy/assets/53110238/651b8fc6-0f98-40db-b9eb-e2c727553459">

### Steps to reproduce

1. Open the terminal
2. Use the command - `keploy update`

Keploy will throw the error

```sh
🐰 Keploy: 2024-06-04T16:00:37+05:30    ERROR   failed to update        {"error": "alias path /usr/local/bin/keploy does not exist"}
```

### Environment

Release

### Version

Local

### Repository

keploy

**Comment by Akash-Singh04** [comment]
It is fixed in #1486 , caused due to the incorrect alias path
