### ISSUE TITLE
[feature]: Add husky to the project

### ISSUE THREAD

**Issue by Ameerjafar** [keploy/keploy#1956]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

currently in our project we don't have husky if we add the husky in our project we can easily formatting the code before the contributor make the commit make the code cleaner 

### Why should this be worked on?

we can easily formatting the code the contributor don't worry this thing by using pre commit in the husky 

### Repository

keploy

**Comment by Ameerjafar** [comment]
@fahurox can you assign me this issue i really wanted to work on this enhancement man.

**Comment by slayerjain** [comment]
@Ameerjafar please raise a PR. I’m interested in seeing how it can help us.

**Comment by Ameerjafar** [comment]
sorry sir we have another method to implement the github hook so there is no need of husky @slayerjain
