### ISSUE TITLE
[feature]: Add a button to copy the code all at once.

### ISSUE THREAD

**Issue by ShivamTyagi12345** [keploy/keploy#198]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently the Keploy UI shows us this.
![image](https://user-images.githubusercontent.com/60812924/193864107-cdd365c1-1cb4-4d69-a8bc-099b7d60256d.png)

Inorder to copy the code we use traditional way of selecting and dragging the cursor. It would be convenient to have a button in order to copy these lines of code at once 

### Why should this be worked on?

This issue when resolved shall be a Convenient developer experience

**Comment by devXprite** [comment]
Hii @ShivamTyagi12345, I want to work on this Issue

**Comment by ShivamTyagi12345** [comment]
> Hii @ShivamTyagi12345, I want to work on this Issue

Awesome. Assigning this right away :+1:

**Comment by Sarthak160** [comment]
@ShivamTyagi12345   I guess this issue is already resolved by existing [PR in UI repo ](https://github.com/keploy/ui/pull/74)
Sorry @devXprite , You can look for any other issue .

**Comment by ShivamTyagi12345** [comment]
thanks for letting me know.Closing the duplicate-issue.Thanks @devXprite . Other issues can be found [here](https://github.com/keploy/keploy/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
