### ISSUE TITLE
feat: add support for finding the given docker-compose file in the command.

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1986]
- Right now, If the user wants to run a separate docker-compose file, keploy will still find the default pattern i.e: `filenames := []string{"docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"}`
- It should also consider taking the file provided by the user. eg: `docker compose -f keploy-docker-compose.yml up`.
- Right now, this is creating problems and keploy will only consider the file with the given patterns.

**Comment by Aryakoste** [comment]
Hello @gouravkrosx I would like to work on this issue.

**Comment by gouravkrosx** [comment]
Go ahead! But this issue is urgent and important and should be solved by tomorrow's EOD. So it will be closed soon.
