### ISSUE TITLE
[bug]: goCoverage not working

### ISSUE THREAD

**Issue by khareyash05** [keploy/keploy#1989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

coverage percentage not showing on using `--goCoverage` in `keploy test` / --putting `goCoverage` to true in the config file

### Steps to reproduce

Run an application with --goCoverage

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by yaten2302** [comment]
Hey @Sonichigo @Sonichigo, I would like to work on this issue, may I give it a try?

**Comment by Sonichigo** [comment]
Hey @yaten2302 sure!

**Comment by yaten2302** [comment]
@Sonichigo, I wanted to ask that for implementing the goCoverage, we've to make changes in the `keloy/cli/test.go` file, am I right?
Actually, I'm learning Go side by side, so if I've any doubt I'll surely ask about it 👍

**Comment by yaten2302** [comment]
Hi @Sonichigo @khareyash05, I was trying to understand the `cli/test.go` file. But, I'm facing some issues, in it, it's written `RunE`, which means that it'll always return an error, so will it actually return the coverage percentage?

Forgive me if it's a silly question 🙏 , actually, I'm a first time contributor to keploy and currently I'm trying to get familiar with the codebase

**Comment by gouravkrosx** [comment]
@yaten2302, Please follow the [docs](https://keploy.io/docs/server/sdk-installation/go/) and understand the expected flow. The `goCoverage` used to work but somehow it stopped working. You don't need to implement whole thing, just need to debug what has gone wrong.
> so will it actually return the coverage percentage?

No, it will just return the error from the replay flow. And the current coverage will be logged like this.
```
🐰 Keploy: 2023-12-07T08:53:14Z         INFO    test/test.go:261
        test-app-url-shortener          coverage: 78.4% of statements
```

**Comment by khareyash05** [comment]
Linked PR https://github.com/khareyash05/go-template/pull/1
