### ISSUE TITLE
[feature]: Allow keploy to be run on debian 11 with Kernel version 5.10

### ISSUE THREAD

**Issue by kingster** [keploy/keploy#2003]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Today while trying to run on deb11, the process fails with

```
Keploy: 2024-06-27T19:18:19+05:30 	ERROR	detected linux kernel version5.10.0-28-amd64. Keploy requires linux kernel version 5.15 or above. Please upgrade your kernel or docker version.
```

Is there any way to run on deb11?

### Why should this be worked on?

This would allow keploy to be run on deb11 boxes.

### Repository

keploy

**Comment by slayerjain** [comment]
@kingster `BPF_FUNC_task_pt_regs` doesn't seem to be used anymore, so I just needed to update the compatibility check and seem to be working on my Debian 11 VM :)

Cgroup v2 is a crucial requirement, but Debian 11 seems to support that too.
