### ISSUE TITLE
[feature]: support performance testing

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2017]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Test cases be converted to performance scripts for load testing  that can be run on Keploy and other tools

### Why should this be worked on?

Performance testing is a critical need for products.

### Repository

keploy

**Comment by Indranil0603** [comment]
Hi @Swpn0neel I would like to work on this. I feel like this requires some research to implement would be great if I could get any leads on it.

**Comment by Swpn0neel** [comment]
Go ahead @Indranil0603 !!

**Comment by charankamarapu** [comment]
duplicate issue.
