### ISSUE TITLE
[bug]: GIFs seems grainy/pixelated when switched to dark mode

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2020]
### What is the problem? (please state reasons if any)

I went through the [keploy docs](https://docs.keploy.io/docs/keploy-explained/how-keploy-works/) with dark mode turned on. I was not able to understand what the gif provided on the page. Gifs were grainy and pixelated [refer fig:1]. 

**Note:** This issue is present only in dark mode
![fig:1](https://github.com/keploy/keploy/assets/58633735/e35dd395-3d82-4739-9b81-a175f8552b12)

### Repository

docs

**Comment by HasanZaigam** [comment]
@Swpn0neel I am interested to contribute on these issues.

**Comment by starvader13** [comment]
@Swpn0neel I would like to collaborate on the issue. What say @HasanZaigam

**Comment by Swpn0neel** [comment]
Go ahead!!

**Comment by starvader13** [comment]
@Swpn0neel  @HasanZaigam You guys can have a look at the PR.

**Comment by HasanZaigam** [comment]
I can not see your PR.
