### ISSUE TITLE
[feature]: Add mux-elastic sample app

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2030]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Create a Go sample app using Mux and Elastic that can perform basic CRUD operations.

### Why should this be worked on?

There is currently no sample apps for Mux-Elastic.

### Repository

samples-go

**Comment by sagnik3788** [comment]
@Swpn0neel, can you assign me? I would like to work on this issue .

**Comment by Swpn0neel** [comment]
Yes, go ahead @sagnik3788!!

While preparing make sure to create proper documentation by taking reference from the other sample apps, because after making the app, you would also have to create the docs for our documentation site! So, it's better to keep it prepared from beforehand, while you're building the app.

I'll create the documentation issue and assign it to you, once you've completed this PR!

**Comment by Sonichigo** [comment]
Hey @sagnik3788 any updates/progress on this issue?

**Comment by sagnik3788** [comment]
@Sonichigo not working on it you can unassign me

**Comment by ayush3160** [comment]
@Swpn0neel , Can you assign this to me I would like to work on this.
Thanks

**Comment by Swpn0neel** [comment]
Go ahead @ayush3160!

**Comment by varunsh17** [comment]
Hi @ayush3160 You working on it currently ?

**Comment by ayush3160** [comment]
Hi @varunsh17 , Yes I am working on this.
