### ISSUE TITLE
[feature]: add support to disable coverage preview

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2033]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

* For a user an option to disable the preview of coverage should be added

### Why should this be worked on?

* Better UX for a user.
* Example in case of node this nyc coverage disable option can be given as a flag.
<img width="901" alt="image" src="https://github.com/keploy/keploy/assets/60891544/711fedf6-6803-4d4f-96e3-bee47c62baa2">

### Repository

keploy

**Comment by debayangg** [comment]
Can I work on this issue @shivamsouravjha?

**Comment by debayangg** [comment]
I tried to replicate the cases where code coverage is displayed by keploy for golang and typescript by running the samples. I was able to generate a coverage report with keploy in golang application when the app is built with -cover flag. In case of golang, only a confirmation that the code coverage report is generated is given, line by line coverage is not displayed.

For the typescript sample using express-mongoose, I was not able to generate it using npm start.

Can you provide some context when the display of coverage report occurs?

**Comment by shivamsouravjha** [comment]
This is  a language specific dependency thus for different languages it can be different and the task was to check the behaviour for different languages supported by Keploy. 

In case of express-mongoose it 
https://github.com/user-attachments/assets/aa1deffa-e81a-473b-8c6d-f1d730fd3474

**Comment by debayangg** [comment]
okay i'll investigate this for the given sample app and that specific version of keploy. Also will check into other languages to the best of my abilities.

**Comment by debayangg** [comment]
For some reason in my keploy.yml ,skipCoverage was set to true. After setting it to false, I was able to replicate the above behaviour. 

Also after going through the keploy cli docs, I came across the --skip-coverage flag which can be used to skip code coverage previews. In case of express-mongoose, this was the result :

https://github.com/user-attachments/assets/8868ab60-5e51-45bc-9740-d6b464beb633

Since this already exists as a flag we can give to keploy to skip code coverage, do you think I should continue to work on this issue?

**Comment by debayangg** [comment]
@shivamsouravjha any updates?

**Comment by shivamsouravjha** [comment]
Yes it is still relevant , it can be called as skip preview and it shows coverage percent but not the line by line preview

**Comment by debayangg** [comment]
okay got it, so the feature is a flag that can be passed to the keploy cli which will skip the line by line coverage preview but show the coverage percent, and should be applicable to all languages currently supported by keploy.

![image](https://github.com/user-attachments/assets/01afcab4-8951-4022-9a56-571259274dc0)
Just to further confirm, the behaviour of using this flag should be similar to above image right.

**Comment by debayangg** [comment]
I have written the code for a --skip-preview flag which works as follows:

https://github.com/user-attachments/assets/78b725cc-e381-45eb-90ed-17156e7f97ba

Should I go ahead with a PR?

**Comment by debayangg** [comment]
@shivamsouravjha should I go ahead and create a PR?

**Comment by shivamsouravjha** [comment]
looks great go ahead @debayangg  also do add this flag in the documentation and attach the link of docs PR in the PR you will raise in keploy repo.

**Comment by shivamsouravjha** [comment]
The is similar to https://github.com/keploy/keploy/issues/2056
