### ISSUE TITLE
[bug]: keploy gives error for gin mongo when recorded with docker compose

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* Tried running docker compose up in gin-mongo faced this error~ 
<img width="1372" alt="image" src="https://github.com/keploy/keploy/assets/60891544/5113eadb-2a48-4b15-a429-c6a0baacfc92">

### Steps to reproduce

* keploy record in gin-mongo.
* Doesn't happen in other sample apps.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by sagnik3788** [comment]
@Swpn0neel i want to work on this issue . can you  please assign me ?

**Comment by Swpn0neel** [comment]
Please go ahead @sagnik3788 !!

**Comment by shivamsouravjha** [comment]
the reason for this bug is the indocker flag, it shouldn't be present, removing indocker from https://github.com/keploy/keploy/blob/main/config/default.go should do the job.
