### ISSUE TITLE
[feature]: add cli flag to override keploy server port

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#204]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We should have a CLI flag to override the keploy server port. 

### Why should this be worked on?

Having a flag such as `keploy -p9000` can be useful to quickly change the keploy port when using keploy locally

**Comment by gauravgahlot** [comment]
@slayerjain I'm unsure of your plan wrt the CLI. However, I would just considering [Cobra](https://github.com/spf13/cobra) for writing an easy to maintain CLI.

If so, I would be happy to help with that.

**Comment by slayerjain** [comment]
@slayerjain Cobra looks really good. I think it would be cool to use it for our cli commands :)

**Comment by gauravgahlot** [comment]
Okay. This is the only command https://github.com/keploy/keploy/tree/main/cmd/server I see. 
From the description I see the name of the CLI should be `keploy`. Could you still confirm it?

**Comment by slayerjain** [comment]
That's the command to run. We need to add the CLI params to that same binary. Currently, if you install keploy you just need to run `keploy` and it would start the server automatically. We just need to add flags to that.

**Comment by charankamarapu** [comment]
This is implemeted in keploy v2. Closing as this issue is resolved in keploy v2.
