### ISSUE TITLE
[feature]: flag to remove line by line coverage

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2056]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

* Incase of different languages an option to remove line by line coverage should be given however the cumulative coverage should be displayed.

### Why should this be worked on?

* this is a language dependent change, like for node line by line preview can be disable by nyc configuration

### Repository

keploy

**Comment by sratslla** [comment]
Hi, I would like to work on this!

**Comment by shivamsouravjha** [comment]
sure feel free to work on it.

**Comment by Ishaanj18** [comment]
Hey Shubh would like to collaborate with you !

**Comment by sratslla** [comment]
Sure! I will DM you on Slack!!

**Comment by Sonichigo** [comment]
hey @sratslla @Ishaanj18 any updates?

**Comment by sratslla** [comment]
Hi @Sonichigo 
Yes, Me and Ishaan had a talk and were studying the code base to find the relevant files. You can expect a PR by tomorrow.
