### ISSUE TITLE
[feature]: enable version command for the keploy binary

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#206]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Keploy needs to provide a version flag (eg: `keploy version` which outputs the binary version. The version needs to be consistent with the git tag which was used to build that version. This might require passing git tag (which is the version) as a build argument during the build process and outputting that via the version subcommand within keploy. 

### Why should this be worked on?

This would help users check for their version of keploy, which is particularly helpful during debugging.

**Comment by PankhudiB** [comment]
Hello @slayerjain ,
I am interested to contribute on this.

**Comment by PankhudiB** [comment]
I understood the part of injecting the version value information during go build.
But from what I understood by roughly going through the repo, is keploy is running as server and not as a cli , so where does the version subcommand come into picture ? (or how do we exactly want to show the version). Can you kindly clarify.

**Comment by slayerjain** [comment]
@PankhudiB thanks for your interest. You're absolutely right that keploy is a server so we can do 2 things: 

1. Log the keploy server version while keploy starts, similar to how various servers like apache, nginx, etc. This should be the most useful. 
2. It would be good to have a version subcommand, which would just log the version instead of starting the server. This can be useful if keploy fails to start for some reason.

**Comment by gauravgahlot** [comment]
@PankhudiB FYI, I'm working on creating a CLI for Keploy as part of the issue #204. Glad I came across this issue, else I was going to add version as well. 😄

**Comment by PankhudiB** [comment]
@slayerjain makes sense.
@gauravgahlot great ! you can integrate the cli , I ll add subcommand to it.

**Comment by ShivamTyagi12345** [comment]
> @PankhudiB FYI, I'm working on creating a CLI for Keploy as part of the issue #204. Glad I came across this issue, else I was going to add version as well. smile

@gauravgahlot  woud you like to be assigned with this task then?

**Comment by gauravgahlot** [comment]
No. Since @PankhudiB is interested in doing so. Let's keep it that way only.

**Comment by PankhudiB** [comment]
Hey @slayerjain , I got it running in my local with ldflags and passing some dummy version :) 
In case of building the executable in github action shall I use short value of the git SHA ?

**Comment by slayerjain** [comment]
@PankhudiB in real-build pipelines, it would be good to provide both commit hashes and also git tags (if present). The git tag variable would be available in the GitHub actions pipeline.
