### ISSUE TITLE
[feature]: revamp the navbar on keploy landing page

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#2068]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently the navbar has below fields:- 
<img width="543" alt="image" src="https://github.com/user-attachments/assets/7d5f060c-4cbe-40e8-8c2e-465b35febde3">

The new navbar should have below tabs and structure
![image](https://github.com/user-attachments/assets/872b3053-bb7b-4a25-a819-1993bba8233f)

### Why should this be worked on?

Since now keploy has different pillar pages and resources it would be good to have proper structure so first time visitor or even regular visitor can easily navigate to page or resource they are looking for.

### Repository

website

**Comment by PranavBarthwal** [comment]
I would like to work on this issue @Sonichigo.
Please assign.

**Comment by Pratik772846** [comment]
Hi @Sonichigo ,I would like to work on this issue.

**Comment by vaishnavi192** [comment]
since it's level 3 i would also like to collaborate on this issue @Sonichigo

**Comment by yaten2302** [comment]
@Sonichigo sir, I'm familiar with the teach stack of Keploy's website, may I also collaborate on this issue?

**Comment by Sonichigo** [comment]
Before i assign it. @PranavBarthwal @yaten2302 @vaishnavi192 @Pratik772846  can you guys discuss first on what items would you guys work and how will you collaborate? I would suggest to open up a GitHub Discussion and then break down the components on discussion.

**Comment by yaten2302** [comment]
@Sonichigo sir, I've created a discussion and gave my approach there, others also kindly review if it's looking good, then we can start working on it together 👍 

Also, I've a doubt, can we do like 1 of us can create a fork and the others can fork their repo and then only that 1 folk will create the PR for this or separate PRs have to be made by each one of us?

**Comment by yaten2302** [comment]
Ig I forgot to provide the link of the discussion, here it's - https://github.com/orgs/keploy/discussions/2079
You'll can give your views here  @PranavBarthwal @vaishnavi192 @Pratik772846

**Comment by harshsbhat** [comment]
Hey @Sonichigo can you assign me this task? Or should I work without an assignment?

**Comment by yaten2302** [comment]
@Sonichigo @Swpn0neel sir, I've made a prototype of the navbar, could you please review that if it's looking good then we can start working on it today 👍 <br>
![image](https://github.com/user-attachments/assets/b05eb23e-cedb-4685-9934-04ede9d6da87)

**Comment by Sonichigo** [comment]
> @Sonichigo @Swpn0neel sir, I've made a prototype of the navbar, could you please review that if it's looking good then we can start working on it today 👍 ![image](https://private-user-images.githubusercontent.com/129659514/349368969-b05eb23e-cedb-4685-9934-04ede9d6da87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTg5NTcsIm5iZiI6MTcyMTE5ODY1NywicGF0aCI6Ii8xMjk2NTk1MTQvMzQ5MzY4OTY5LWIwNWViMjNlLWNlZGItNDY4NS05OTM0LTA0ZWRlOWQ2ZGE4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwNjQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWZiYjk5NGRiMTJmZTQzMDQyODZmMTBkZTgzMTkzZTMwZjBiMWQ5M2YxMTFiZDdhZjZiMWZlNThmOTc4N2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0_GhAMwXR5z9638h3iZpaBFt21ULAFjWjj6dMNvSo8s)

Hey, before actually starting on the code aspect, it would be great you can finalize the UI on Figma.

**Comment by yaten2302** [comment]
> > @Sonichigo @Swpn0neel sir, I've made a prototype of the navbar, could you please review that if it's looking good then we can start working on it today 👍 ![image](https://private-user-images.githubusercontent.com/129659514/349368969-b05eb23e-cedb-4685-9934-04ede9d6da87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTg5NTcsIm5iZiI6MTcyMTE5ODY1NywicGF0aCI6Ii8xMjk2NTk1MTQvMzQ5MzY4OTY5LWIwNWViMjNlLWNlZGItNDY4NS05OTM0LTA0ZWRlOWQ2ZGE4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwNjQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWZiYjk5NGRiMTJmZTQzMDQyODZmMTBkZTgzMTkzZTMwZjBiMWQ5M2YxMTFiZDdhZjZiMWZlNThmOTc4N2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0_GhAMwXR5z9638h3iZpaBFt21ULAFjWjj6dMNvSo8s)
> 
> Hey, before actually starting on the code aspect, it would be great you can finalize the UI on Figma.

May i share the figma prototype here?

**Comment by Sonichigo** [comment]
> > > @Sonichigo @Swpn0neel sir, I've made a prototype of the navbar, could you please review that if it's looking good then we can start working on it today 👍 ![image](https://private-user-images.githubusercontent.com/129659514/349368969-b05eb23e-cedb-4685-9934-04ede9d6da87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTg5NTcsIm5iZiI6MTcyMTE5ODY1NywicGF0aCI6Ii8xMjk2NTk1MTQvMzQ5MzY4OTY5LWIwNWViMjNlLWNlZGItNDY4NS05OTM0LTA0ZWRlOWQ2ZGE4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwNjQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWZiYjk5NGRiMTJmZTQzMDQyODZmMTBkZTgzMTkzZTMwZjBiMWQ5M2YxMTFiZDdhZjZiMWZlNThmOTc4N2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0_GhAMwXR5z9638h3iZpaBFt21ULAFjWjj6dMNvSo8s)
> > 
> > 
> > Hey, before actually starting on the code aspect, it would be great you can finalize the UI on Figma.
> 
> May i share the figma prototype here?

Yes sure!

**Comment by yaten2302** [comment]
> > > > @Sonichigo @Swpn0neel sir, I've made a prototype of the navbar, could you please review that if it's looking good then we can start working on it today 👍 ![image](https://private-user-images.githubusercontent.com/129659514/349368969-b05eb23e-cedb-4685-9934-04ede9d6da87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTg5NTcsIm5iZiI6MTcyMTE5ODY1NywicGF0aCI6Ii8xMjk2NTk1MTQvMzQ5MzY4OTY5LWIwNWViMjNlLWNlZGItNDY4NS05OTM0LTA0ZWRlOWQ2ZGE4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwNjQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWZiYjk5NGRiMTJmZTQzMDQyODZmMTBkZTgzMTkzZTMwZjBiMWQ5M2YxMTFiZDdhZjZiMWZlNThmOTc4N2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0_GhAMwXR5z9638h3iZpaBFt21ULAFjWjj6dMNvSo8s)
> > > 
> > > 
> > > Hey, before actually starting on the code aspect, it would be great you can finalize the UI on Figma.
> > 
> > 
> > May i share the figma prototype here?
> 
> Yes sure!

Here's the figma link - https://www.figma.com/design/n3BO0caZntCqDLe8CFCi3f/Keploy-NavBar?node-id=0-1&t=JFO7QnVRxbio7Uvw-1

**Comment by Sonichigo** [comment]
@yaten2302 the UI of platform isn't correct in figma. It will be similar to one mentioned in the issue description.

Some references: - 
<img width="950" alt="image" src="https://github.com/user-attachments/assets/5f63c267-57fb-45bf-bfae-350d46a05f44">

**Comment by yaten2302** [comment]
Okay @Sonichigo sir, so it has to be wide enough, right? Like it should cover the complete page?
I'll redesign it 👍

**Comment by Sonichigo** [comment]
> Okay @Sonichigo sir, so it has to be wide enough, right? Like it should cover the complete page? I'll redesign it 👍

Before you redesign, i think it would be great to explore other websites which has these. I think design perspective is missing right now.

**Comment by yaten2302** [comment]
> > Okay @Sonichigo sir, so it has to be wide enough, right? Like it should cover the complete page? I'll redesign it 👍
> 
> Before you redesign, i think it would be great to explore other websites which has these. I think design perspective is missing right now.

Yes, sure 👍 I'll explore some websites with similar design and then I'll incorporate somethin like that in this navbar 👍

**Comment by yaten2302** [comment]
> @yaten2302 the UI of platform isn't correct in figma. It will be similar to one mentioned in the issue description.
> 
> Some references: -
> 
> <img alt="image" width="950" src="https://private-user-images.githubusercontent.com/53110238/349530190-5f63c267-57fb-45bf-bfae-350d46a05f44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzc3MTIsIm5iZiI6MTcyMTI3NzQxMiwicGF0aCI6Ii81MzExMDIzOC8zNDk1MzAxOTAtNWY2M2MyNjctNTdmYi00NWJmLWJmYWUtMzUwZDQ2YTA1ZjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA0MzY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZDk5OGQ4ZTUyMGM4YWU4NjI5NDE2ODZjMGQ1YzhkMjMyNzE3MGI5YmU4ODViNTE2MjZjNDYzZGEyOTU2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cqeGlQpoIEUOO67OH7TdWNuN9VrqYuiQ6fK4rsaTyo">
> <img alt="image" width="1456" src="https://private-user-images.githubusercontent.com/53110238/349530514-3c5b52c8-dedb-48c3-9f24-3153bbffc22a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzc3MTIsIm5iZiI6MTcyMTI3NzQxMiwicGF0aCI6Ii81MzExMDIzOC8zNDk1MzA1MTQtM2M1YjUyYzgtZGVkYi00OGMzLTlmMjQtMzE1M2JiZmZjMjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA0MzY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiY2YzYmZmYmMyNTEzYjdlNzc1NWE5OGY0NGVlNDY4NWFmYzUyNDE5ZmVlNWU5N2FkNzljMDEwZWNiOTgzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e6eOkaD0MKirQb2Iw2j3k6GrUygRaqGB52NMeZtZZME">
> additionally, the social links section will be below and the rest product & solution and not in between.

@Sonichigo sir, I've redesigned the NavBar, could you please have a look and guide that is it looking good or it something needs to be changed?

**Comment by yaten2302** [comment]
Yes, @vaishnavi192 , but before starting, kindly wait for the NavBar design to be approved, and then we'll start. Everything will be discussed in the discussion open for this issue👍 so no worries 😀

**Comment by Sonichigo** [comment]
> @Sonichigo Under blogs i have to make 2 sections in one page about technology and community right?

yes!

**Comment by yaten2302** [comment]
@Sonichigo @Swpn0neel sir, I've made the changes for the "Platform" part, here's a screenshot, could you please review that are the changes looking good or do I've to change something in this? <br>
![image](https://github.com/user-attachments/assets/fc07d717-9da4-47bf-8592-ee8c0a19d13b)
<br>
![image](https://github.com/user-attachments/assets/257beb59-98fd-4fc8-9fa7-69f5d7656313)

In here, some of the icons are same, actually, I wasn't able to find some good icons related to the headings, could you please guide what type of icons should come here?

**Comment by yaten2302** [comment]
@Sonichigo @Swpn0neel sir, could you please review [this PR](https://github.com/keploy/website/pull/65) and LMK if any changes are required in the "Platform" section.

Also, @vaishnavi192 @PranavBarthwal , could you please confirm that are both working on the "Blogs" and the "About" section, since I haven't seen any fork on my repo

**Comment by TvisharajiK** [comment]
This issue is now continued in https://github.com/keploy/keploy/issues/2210
