### ISSUE TITLE
[docs]: code for irrelevant languages be removed from test coverage generation section

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2070]
### What do you want to add to the docs? (please state reasons if any)

* Either all the languages should be merged or documentation should be separate for all.
<img width="782" alt="image" src="https://github.com/user-attachments/assets/c17bc8f6-ac5b-4935-9d7e-d5b6818228fa">
* Javascript code shound't have:

```
Note: In case of java application, before running test subcommand, you need to clean the project by removing any previously generated file, and run install command.

mvn clean install -Dmaven.test.skip=true
```

* Similarly Javascript shouldn't have any unrelated code of Java and Go.
* Go shouldn't have MVN code cleanup.

### Where is this stated?

https://keploy.io/docs/server/sdk-installation/python/#graceful-shutdown

### Repository

keploy

**Comment by starvader13** [comment]
I would love to take up this issue. 

For starters, apart from the changes mentioned in the issue description, I can also see that this `Language Specific Requirement` should be separated for each case or moved to a new section independently.

![image](https://github.com/user-attachments/assets/9afa1730-fdf9-4f64-bdd2-c40a248ada96)

**Comment by Sonichigo** [comment]
@starvader13 i have assigned the issue to you! Lmk if you need any help :)

**Comment by shivamsouravjha** [comment]
Hey @starvader13 !
Yes along with that the not section has java code which is best suited in java usecase.
Similarly the graceful shutdown is a golang code, thus should only be present in Go code.

**Comment by starvader13** [comment]
> Yes along with that the not section has java code which is best suited in java usecase. Similarly the graceful shutdown is a golang code, thus should only be present in Go code.

I was thinking of adding a section of `Prerqisite` where we can put the Language Specific Requirements And `Introduction for Merge Unit Test Coverage Data` ?

WDYT? @shivamsouravjha

**Comment by shivamsouravjha** [comment]
would suggest that  Language Specific Requirements be just kept specific to language.
