### ISSUE TITLE
[bug]: year in footer still shows 2023

### ISSUE THREAD

**Issue by PranavBarthwal** [keploy/keploy#2072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

year in footer still shows 2023.
I would like to fix this under kROC.
I'll use dynamic date instead of hardcoded value

![Screenshot (241)](https://github.com/user-attachments/assets/880965d0-6a82-4cc5-a31f-8ef7295ac7bc)

### Steps to reproduce

1. go to bottom of wesbite
2. see date in footer

### Environment

Deploy preview

### Version

Cloud

### Repository

website

**Comment by Sonichigo** [comment]
hey @PranavBarthwal that's the copyright since we launched this website in 2023 that's why it is for 2023.

**Comment by PranavBarthwal** [comment]
> hey @PranavBarthwal that's the copyright since we launched this website in 2023 that's why it is for 2023.

Ahh, understood. Lemme close this issue then xD
