### ISSUE TITLE
[bug]: "Explore More" links not working in keploy.io

### ISSUE THREAD

**Issue by yaten2302** [keploy/keploy#2074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

# Issue
When we go to keploy.io and go on any "Explore More" link, it shows "404 This page doesn't exits".

# Solution
It should redirect the user to the actual link.

# Screenshots
![image](https://github.com/user-attachments/assets/fd96102b-45e0-4dfe-9b74-e907b1691308) <br>
![image](https://github.com/user-attachments/assets/4f6c5036-d16b-4cf2-823f-ce4bd7b13e94)

### Steps to reproduce

1. Go to keploy.io
2. Click on "Explore More" button under the "Keploy for developers" section
3. You'll see a 404 page.

### Environment

None

### Version

Cloud

### Repository

website

**Comment by yaten2302** [comment]
@Sonichigo sir, could you please assign this issue to me under kROC. I would like to work on this issue.

**Comment by Swpn0neel** [comment]
Go ahead @yaten2302

**Comment by yaten2302** [comment]
@Swpn0neel sir, could you please also provide the links which have to be added for these buttons? Or are these buttons meant to be removed?

**Comment by Sonichigo** [comment]
These button will be present there itself. They should right now on clicking open the pages on docs. 

1. Record Replay API Flows
Record and replay complex, distributed API flows as mocks and stubs. It's like time machine for tests!


2. Find Duplicate Tests
Find redundant tests that doesn't add to the test coverage. Automatically detect and remove duplicate tests, ideal for big-teams crowd-sourcing tests.

3. Works with JUnit, PyTest, Jest, Go-Test in CI/CD

Explore more -> https://keploy.io/docs/server/sdk-installation/go/

**Comment by yaten2302** [comment]
@Sonichigo sir, all the 3 links should redirect to this one - https://keploy.io/docs/server/sdk-installation/go/ , have I understood this correctly?

**Comment by harshsbhat** [comment]
I have fixed this issue @yaten2302 and @Sonichigo please check. Thank you!

**Comment by yaten2302** [comment]
Hey @harshsbhat , actually this issue was already assigned to me and I'm almost done with this and by today I'll create a PR for this.
@Sonichigo sir, could you please look into this.

**Comment by harshsbhat** [comment]
Hey @yaten2302 the solution was just 3 lines long. So I thought you probably gave up on this task. I'm really sorry I didn't know you were still working on this issue. As most of the repos work without the proper need for an assignment

**Comment by yaten2302** [comment]
@Sonichigo sir, ig my 1 PR was already open in the Keploy's website repo and changes related to this issue has also been pushed there, could you please have a look at it - https://github.com/keploy/website/pull/49/commits/621482b2a5f6d7c04c21b09f0e5eb47277d7be3f
Thanks

**Comment by Sonichigo** [comment]
> Hey @yaten2302 the solution was just 3 lines long. So I thought you probably gave up on this task. I'm really sorry I didn't know you were still working on this issue. As most of the repos work without the proper need for an assignment

Hey @harshsbhat , still would be great if you can check with the person assigned if he is working on the issue or not before making a PR 😃

**Comment by harshsbhat** [comment]
> > Hey @yaten2302 the solution was just 3 lines long. So I thought you probably gave up on this task. I'm really sorry I didn't know you were still working on this issue. As most of the repos work without the proper need for an assignment
> 
> Hey @harshsbhat , still would be great if you can check with the person assigned if he is working on the issue or not before making a PR 😃

Yep! As I said I'm sorry. I won't do this again. 😃

**Comment by Sonichigo** [comment]
> > > Hey @yaten2302 the solution was just 3 lines long. So I thought you probably gave up on this task. I'm really sorry I didn't know you were still working on this issue. As most of the repos work without the proper need for an assignment
> > 
> > 
> > Hey @harshsbhat , still would be great if you can check with the person assigned if he is working on the issue or not before making a PR 😃
> 
> Yep! As I said I'm sorry. I won't do this again. 😃

All great! 😊 There are multiple open issues without that you can pickup : - [Good first issues](https://github.com/keploy/keploy/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22), looking forward towards your contribution :)

**Comment by yaten2302** [comment]
@Sonichigo sir, may I close this issue now, the PR got merged ig?

**Comment by Swpn0neel** [comment]
> @Sonichigo sir, may I close this issue now, the PR got merged ig?

No, for tracking purpose we'll keep it open for now!
