### ISSUE TITLE
[bug]: Command box overflow in mobile view

### ISSUE THREAD

**Issue by suvanbanerjee** [keploy/keploy#2075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The installing command in Keploy's website is overflowing in mobile devices
![image](https://github.com/user-attachments/assets/129ddac6-08ca-4905-9151-43fed565e5fb)

### Steps to reproduce

1. open keploy.io on a mobile device
2. Scroll down to Getting Started section

### Environment

None

### Version

Cloud

### Repository

website

**Comment by suvanbanerjee** [comment]
@Sonichigo Can you assign it to me under KRoC

**Comment by Sonichigo** [comment]
hey @suvanbanerjee we are refactoring this section and replacing with react-console. pr- https://github.com/keploy/website/pull/42
