### ISSUE TITLE
[feature]: add linter for go dependencies

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2077]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

* A linter that can go through all the go dependencies and warn about the dependencies that are depreceated.

### Why should this be worked on?

* Makes sure we don't have unsupported dependencies.

### Repository

keploy

**Comment by sratslla** [comment]
I would like to pick this one up.

**Comment by shivamsouravjha** [comment]
sure feel free to work on it.

**Comment by sratslla** [comment]
Hi! golangci-lint does not have a built-in linter specifically for deprecated dependencies. We can create a custom Go script to check for deprecated dependencies and integrate this script with our golangci-lint workflow.
ref-https://github.com/golangci/golangci-lint/discussions/2598
