### ISSUE TITLE
[bug]: Add Email Check to Keploy Test Coverage Challenge

### ISSUE THREAD

**Issue by starvader13** [keploy/keploy#2082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When subscribing to the `Keploy test coverage Challenge`, the system accepts an empty value or random value upon hitting the subscribe button. This allows the user to submit without any arguments, which negatively impacts both backend performance and frontend user experience.

### Steps to reproduce

1. Go to the `Keploy test coverage Challenge` section.
2. Click on the subscribe button without entering an email or entering a random value.
3. Observe that the subscription is accepted and renders a message `Thanks for subscribing!`.

### Screenshots
![image](https://github.com/user-attachments/assets/d6b8bb17-66c9-483c-8a8e-0769fedc5e2f)

**Clicking Subscribe with Random / Empty Email**
![image](https://github.com/user-attachments/assets/f8843c18-34bb-449b-bc19-e0db1d39840c)

### Repository

website

**Comment by starvader13** [comment]
@swpn0neel Have a look..

### Proposed Solution 

**The solution could be broken into two sub-parts:**
1. Implement `Zod Validation` to ensure the email string is not empty and is a valid email format. 
2. Handle the render logic to provide a user-friendly message such as "The email entered needs to be a valid email."

**Comment by Swpn0neel** [comment]
> @Swpn0neel Have a look..
> 
> ### Proposed Solution
> **The solution could be broken into two sub-parts:**
> 
> 1. Implement `Zod Validation` to ensure the email string is not empty and is a valid email format.
> 2. Handle the render logic to provide a user-friendly message such as "The email entered needs to be a valid email."

LGTM! Please go ahead!

**Comment by PranavBarthwal** [comment]
Is this issue up for collaboration?

**Comment by Swpn0neel** [comment]
> Is this issue up for collaboration?

This is a solo issue!
