### ISSUE TITLE
[feature]: language icons on home page should directly lead to keploy docs on that language

### ISSUE THREAD

**Issue by debayangg** [keploy/keploy#2090]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be more intuitive if the language icons on the keploy would redirect to docs regarding how to use keploy with that language.

![image](https://github.com/user-attachments/assets/b58c2200-cb57-41c1-bc81-d6e287f2b01e)
Clicking on the icon of any language should lead to the default sample page for that language.

### Why should this be worked on?

Would make the UI for intuitive.

### Repository

website

**Comment by Swpn0neel** [comment]
Please go ahead @debayangg !!

**Comment by HasanZaigam** [comment]
@debayangg lets collaborate and start working on this together.

**Comment by debayangg** [comment]
> @debayangg lets collaborate and start working on this together.

I have mostly finished the PR, would recommend you to search for other issues for collaboration.

**Comment by HasanZaigam** [comment]
thanks @debayangg No problem I will find the other issue
