### ISSUE TITLE
[feature]: Supports cards on Keploy Documentation page should hover to make UI more intutive 

### ISSUE THREAD

**Issue by Aman172003** [keploy/keploy#2091]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Like other cards present on the website, the supports cards should hover when cursor is placed over it.
<img width="1440" alt="Screenshot 2024-07-18 at 1 20 19 AM" src="https://github.com/user-attachments/assets/3573acaa-45a8-459a-b9b7-4bd00083a4da">
 

### Why should this be worked on?

It will make UI more intutive

### Repository

docs

**Comment by Aman172003** [comment]
@Swpn0neel I would like to work on this under KROC

**Comment by Swpn0neel** [comment]
Go ahead @Aman172003

**Comment by Aman172003** [comment]
Hey @Swpn0neel , could you please review the PR.
