### ISSUE TITLE
[bug]: `jsxBracketSameLine` is Deprecated and should be Removed

### ISSUE THREAD

**Issue by starvader13** [keploy/keploy#2092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

As discussed https://github.com/keploy/docs/pull/417#issuecomment-2233785295 , the `jsxBracketSameLine` needs to be removed.

### Steps to reproduce

1. Run ` yarn prettier --write <path-to-file/filename>.md` 
2. Generates warning
![test](https://github.com/user-attachments/assets/27a6f0e8-86b9-488c-b9ee-2aeca09de552)

### Environment

None

### Version

Cloud

### Repository

docs

**Comment by starvader13** [comment]
@Swpn0neel Review Required!!

**Comment by Swpn0neel** [comment]
Send the PR 🙌 @starvader13
