### ISSUE TITLE
[docs]: Add instructions for using npm to run the Docusaurus site locally

### ISSUE THREAD

**Issue by GauriBhandari** [keploy/keploy#2094]
### What do you want to add to the docs? (please state reasons if any)

I would like to suggest adding documentation for running the Docusaurus site locally using `npm` 

### Where is this stated?

Currently, the documentation only includes instructions for using `yarn`, but providing alternatives like `npm` can help more contributors who may prefer or need these options.

### Repository

docs

**Comment by GauriBhandari** [comment]
@Swpn0neel and team if you find this issue helpful, please add the labels and assign it to me. I have created this issue under KROC.

**Comment by Swpn0neel** [comment]
> @Swpn0neel and team if you find this issue helpful, please add the labels and assign it to me. I have created this issue under KROC.

Under which section do you want to want to add this?

**Comment by GauriBhandari** [comment]
in the docs repo where contribution guide is mentioned , theirs a section referencing - 'How to set up the docs website locally?', their only given build with yarn. 

https://keploy.io/docs/keploy-explained/docs-dev-guide/

![image](https://github.com/user-attachments/assets/005d4b62-60c7-40d8-a1a3-ea5da6712c3d)

**Comment by Swpn0neel** [comment]
Great! Go ahead with this issue!

**Comment by GauriBhandari** [comment]
@Swpn0neel and team , i have made the necessary changes , could you please review it and let me know if further changes are needed , if not then could you please proceed with merging it !?

**Comment by Sonichigo** [comment]
Hi @GauriBhandari ! `yarn` section is mentioned because in the docs website build, test and deploy we use `yarn build`. Although above is a good to have, but not in terms of websites we have.

**Comment by GauriBhandari** [comment]
Hi @Sonichigo ,

Thanks for the feedback! I added the `npm` section to help users who might prefer it over `yarn`. While I understand `yarn` is the go-to for building, testing, and deploying, I thought having `npm` as an option could make things easier for a wider audience.

I've also tested the website locally using `npm`, and it works fine. If you think it's better, I can add a note saying `yarn` is preferred for these tasks but `npm` can also be used. Let me know your thoughts!

Thanks again!

**Comment by Sonichigo** [comment]
> Hi @Sonichigo ,
> 
> Thanks for the feedback! I added the `npm` section to help users who might prefer it over `yarn`. While I understand `yarn` is the go-to for building, testing, and deploying, I thought having `npm` as an option could make things easier for a wider audience.
> 
> I've also tested the website locally using `npm`, and it works fine. If you think it's better, I can add a note saying `yarn` is preferred for these tasks but `npm` can also be used. Let me know your thoughts!
> 
> Thanks again!

That can be done. In notes with bold that `yarn is preferred`

**Comment by Sonichigo** [comment]
This issue will be resolved by https://github.com/keploy/docs/pull/423.  The PR is in review
