### ISSUE TITLE
[docs]: add FAQs for unit test gen

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2095]
### What do you want to add to the docs? (please state reasons if any)

* Unit test gen has exposurre to chatgpt and this often arises question. Adding FAQs can help in clearing doubts.

### Where is this stated?

This conversation can be a good reference https://keploy.slack.com/archives/C035URHSGDQ/p1721297840351699

### Repository

keploy

**Comment by yaten2302** [comment]
May I work on this issue @shivamsouravjha ? Could you please guide that what all type of questions should be present in the docs?

**Comment by shivamsouravjha** [comment]
You can add it here~
https://keploy.io/unit-test-generator
https://github.com/keploy/keploy/blob/main/README-UnitGen.md
https://keploy.io/docs/running-keploy/unit-test-generator/. 

You can try framing questions based upon the conversation and refer to others questions.

**Comment by yaten2302** [comment]
Hey @shivamsouravjha @Swpn0neel , could you please guide that are these FAQs relevant?

1. Does Keploy send any data somewhere else?
No, Keploy does not send any user code to remote systems, except when using the unit test generation feature.
2. What data is sent when using the unit test generation (UT gen) feature?
When using the UT gen feature, both the source code and the unit test code will be sent to the Large Language Model (LLM) you are using.
3. Which LLM is used by Keploy by default?
By default, Keploy uses - `litellm` to support vast number of LLM backends.
4. Can I use a private LLM with Keploy?
Yes, if your organization has its own LLM(a private one), you can use it with Keploy. This ensures that data is not sent to any external systems.

**Comment by Swpn0neel** [comment]
> Hey @shivamsouravjha @Swpn0neel , could you please guide that are these FAQs relevant?
> 
> 1. Does Keploy send any data somewhere else?
>    No, Keploy does not send any user code to remote systems, except when using the unit test generation feature.
> 2. What data is sent when using the unit test generation (UT gen) feature?
>    When using the UT gen feature, both the source code and the unit test code will be sent to the Large Language Model (LLM) you are using.
> 3. Which LLM is used by Keploy by default?
>    By default, Keploy uses - `litellm` to support vast number of LLM backends.
> 4. Can I use a private LLM with Keploy?
>    Yes, if your organization has its own LLM(a private one), you can use it with Keploy. This ensures that data is not sent to any external systems.

Merge the 4 questions into one:

Does Keploy send your private data to any cloud server for test generation?
-> No, Keploy does not send any user code to remote systems, except when using the unit test generation feature. When using the UT gen feature, both the source code and the unit test code will be sent to the Large Language Model (LLM) you are using. By default, Keploy uses - litellm to support vast number of LLM backends. Yes, if your organization has its own LLM(a private one), you can use it with Keploy. This ensures that data is not sent to any external systems.

(Rephrase the answer a bit)

**Comment by yaten2302** [comment]
@Swpn0neel @shivamsouravjha , in these 2 links - https://github.com/keploy/keploy/blob/main/README-UnitGen.md
https://keploy.io/docs/running-keploy/unit-test-generator/ , there's no FAQ section give, so do I've to create a new FAQ section and then add all the FAQs present here as well as this one? <br>
![image](https://github.com/user-attachments/assets/3564fb7e-6382-4fec-9179-b713497e08ef)

**Comment by shivamsouravjha** [comment]
yes go ahead with that.

**Comment by Swpn0neel** [comment]
> @Swpn0neel @shivamsouravjha , in these 2 links - https://github.com/keploy/keploy/blob/main/README-UnitGen.md https://keploy.io/docs/running-keploy/unit-test-generator/ , there's no FAQ section give, so do I've to create a new FAQ section and then add all the FAQs present here as well as this one? ![image](https://private-user-images.githubusercontent.com/129659514/350242930-3564fb7e-6382-4fec-9179-b713497e08ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzQxODYsIm5iZiI6MTcyMTM3Mzg4NiwicGF0aCI6Ii8xMjk2NTk1MTQvMzUwMjQyOTMwLTM1NjRmYjdlLTYzODItNGZlYy05MTc5LWI3MTM0OTdlMDhlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNzI0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTMwYmEwZGRmY2E2MjE3YTBkZWEyNWI0YTIxOTFkZTRmMTQ3NzU5ZmUzZmQxZmFkYzk1OGRjNDlhYWQzNTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aIduwiw1Drc4t9nY0lCGy-JksU2bF1k8ya8e9CkHcLk)

Add it here as well, because this is our main FAQ section. You'll find it inside our `docs` repo

**Comment by yaten2302** [comment]
@Swpn0neel sir, ig there are some issues in this PR - https://github.com/keploy/website/pull/58 , I'll recreate this, sorry for inconvenience.

**Comment by yaten2302** [comment]
@Swpn0neel sir, I've made the changes for this - https://keploy.io/unit-test-generator. Ig separate PRs have to be created for different links, since they are present in different repos. I'll create the PR in other repos too 👍

**Comment by yaten2302** [comment]
@Swpn0neel sir, I've created all the 3 PR's to fix this issue and 1 has ben merged, could you please have a look at the other 2 as well.

**Comment by yaten2302** [comment]
@Swpn0neel sir, ig now all the PRs are approved, may I create a PR in the leaderboard for this issue?

**Comment by Swpn0neel** [comment]
Go ahead @yaten2302, but first fix the DCO checks!
