### ISSUE TITLE
[bug]: Subscribe button enabled with no email entered

### ISSUE THREAD

**Issue by GauriBhandari** [keploy/keploy#2099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The "Subscribe" button is enabled even when no email is entered in the subscription form.

### Steps to reproduce

1. Go to the subscription form on the Keploy test coverage challenge page (https://keploy.io/#0).
2. Without entering any email, click on the "Subscribe" button.
3. Notice that the button is enabled and can be clicked, even though no email is provided.

### Environment

None

### Version

Cloud

### Repository

website

**Comment by GauriBhandari** [comment]
@Swpn0neel and team if you find this issue helpful, please add the labels and assign it to me. I have created this issue under KROC.

**Comment by Swpn0neel** [comment]
@Sonichigo Can you please check this?

**Comment by Sonichigo** [comment]
Hi @GauriBhandari this is an duplicate issue. And PR is work in progess: -https://github.com/keploy/website/pull/55
