### ISSUE TITLE
[bug]: Correct CNCF Link and Ensure Images Open Link In New Tab 

### ISSUE THREAD

**Issue by starvader13** [keploy/keploy#2103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Current behavior

In our application's footer section is a segment labelled "Find us on CNCF Landscape" containing two images with links. Currently, these links exhibit the following issues:

1. The CNCF link is incorrect.
2. Clicking on the images opens the links in the same tab.

## Steps to reproduce
1. Navigate to the Footer. Scroll down to the footer section of the application.
2. Locate the CNCF Landscape Section. Find the section labelled "Find us on CNCF Landscape" which contains the relevant images.
3. Click on the Images. Click on the images within this section.
4. Observe Link Behavior:
    - Notice that the links open in the same tab instead of a new tab.
    - Confirm that the CNCF link points to an incorrect URL.

### Environment

None

### Version

Cloud

### Repository

website

**Comment by starvader13** [comment]
@Swpn0neel WDYT? 

This seems a bug to me.

**Comment by Swpn0neel** [comment]
@starvader13 Kindly fix that, and @Sonichigo can you please provide the correct link?

**Comment by starvader13** [comment]
> Clicking on the images opens the links in the same tab.

@Swpn0neel, should we apply the same changes to the `Twitter` and `GitHub` Logo in the footer? If necessary, I can extend this issue to include those links as well.

**Comment by nehagup** [comment]
@starvader13 yes that sounds good.

**Comment by starvader13** [comment]
@nehagup @Swpn0neel I have made all the changes. You can have a look at it.

**Comment by starvader13** [comment]
@Swpn0neel I think this issue can be closed as there is no further changes required and the MRs are merged.
