### ISSUE TITLE
[docs]: Add Blogs in Engineering Blogs repository

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2104]
Add all the PRs from https://github.com/kilimchoi/engineering-blogs/pulls in this repository https://github.com/keploy/engineering-blogs

**Comment by starvader13** [comment]
Hey @Swpn0neel Are we talking about the Open PRs or Closed Ones?

**Comment by Swpn0neel** [comment]
Only the open ones!

**Comment by BHAV0207** [comment]
hey @Swpn0neel  I would like to work on this issue as my first issue, can you please assign me this issue

**Comment by we-kash** [comment]
Hey @Swpn0neel,

I would like to collaborate with @BHAV0207 on the 111 PRs. I believe we can handle them more efficiently if we work together.

Thanks!

**Comment by Swpn0neel** [comment]
Sure, go ahead @we-kash

**Comment by BHAV0207** [comment]
hey @Swpn0neel  can I also be assigned to this issue as @we-kash  mentioned above if we both work together it will done more efficiently

**Comment by Swpn0neel** [comment]
> hey @Swpn0neel can I also be assigned to this issue as @we-kash mentioned above if we both work together it will done more efficiently

Go ahead, and divide the tasks among yourselves!

**Comment by starvader13** [comment]
@we-kash @BHAV0207 Hey guys, if you haven't joined Slack yet, Join it soo that we can divide the task over there only.

**Comment by starvader13** [comment]
Hey @Swapnoneel,

Regarding this issue, instead of addressing each issue individually, which can be slow, we could consider a more efficient approach.

Proposal:

1. Use keploy/engineering-blogs as the origin repository and engineering-blogs as the upstream repository.
2. Fetch PRs from the upstream repository.
3. Integrate these PRs into a dedicated branch in the origin repository.
4. This process will streamline the integration of PRs and make the process more efficient.

WDYT? @Swpn0neel @we-kash @BHAV0207

**Comment by we-kash** [comment]
> Hey @Swapnoneel,
> 
> Regarding this issue, instead of addressing each issue individually, which can be slow, we could consider a more efficient approach.
> 
> Proposal:
> 
> 1. Use keploy/engineering-blogs as the origin repository and engineering-blogs as the upstream repository.
> 2. Fetch PRs from the upstream repository.
> 3. Integrate these PRs into a dedicated branch in the origin repository.
> 4. This process will streamline the integration of PRs and make the process more efficient.
> 
> WDYT? @Swpn0neel @we-kash @BHAV0207
@starvader13 
Ok I think this will ease out the iterative work, let me look into it

**Comment by Swpn0neel** [comment]
That would be better @starvader13!

**Comment by BHAV0207** [comment]
@Swpn0neel !!  many PR's were partially verified, leading to some checks getting failed.

**Comment by Swpn0neel** [comment]
ok, no issues!!

**Comment by we-kash** [comment]
@starvader13 and @Swpn0neel I have raised a PR for the same. Please review my changes in PR  https://github.com/keploy/engineering-blogs/pull/2

**Comment by starvader13** [comment]
@Swpn0neel This issue can be closed as the MRs are merged
