### ISSUE TITLE
[bug]: Incorrect Redirection When Clicking on Version 2.0.0 Navbar Dropdown Item on Documentation Website

### ISSUE THREAD

**Issue by ayush3160** [keploy/keploy#2106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we click on version 2.0.0 from the version dropdown, it incorrectly redirects to the Windows installation page (route: /docs/server/windows/installation/). This behavior is incorrect as it should redirect to the Keploy introduction page, similar to the redirection when we click on version 1.0.0 option.

![Screenshot from 2024-07-21 03-11-45](https://github.com/user-attachments/assets/fd141452-647c-4f87-bf90-df133e0c428c)

### Steps to reproduce

1. Go to home page.
2. Open the version drop-down . Click on 2.0.0 option.
3. See it redirects to keploy windows installation page.

### Environment

None

### Version

Cloud

### Repository

docs

**Comment by ayush3160** [comment]
@Swpn0neel, @Sonichigo, could you please verify if this is a bug or intended behavior? If it's a bug, I'll raise a PR to fix it. Thank you!

**Comment by Sonichigo** [comment]
@ayush3160 thanks for pointing out! It isn't expected behaviour. On clicking `2.0.0` it should show up the page :- https://keploy.io/docs/server/installation/
