### ISSUE TITLE
[feature]: Create a sample app using Flask and Redis

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2112]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

A Flask-based application using Redis for caching and REST API for client-server communication. It needs to come with proper documentation!

### Why should this be worked on?

There's currently no such sample app with us.

### Repository

samples-python

**Comment by sammaji** [comment]
I would like to work on this.

**Comment by Swpn0neel** [comment]
Please go ahead @sammaji!!

**Comment by Aman172003** [comment]
> I would like to work on this.

Hey @sammaji , would you like to collaborate on this.

**Comment by sammaji** [comment]
Hi @Aman172003 
Sorry, I am almost done with it.

**Comment by sammaji** [comment]
@Aman172003 

I'm working on the code part.

If you want you can take up the documentation part.

**Comment by Aman172003** [comment]
> @Aman172003 
> 
> I'm working on the code part.
> 
> If you want you can take up the documentation part.

I have already worked on flask and redis in the past, if you need any type of help then we could collaborate.

**Comment by Aman172003** [comment]
Hey @sammaji , are you still working on it?

**Comment by eagle1-7** [comment]
Hey @Swpn0neel , Can i work on it?

**Comment by sammaji** [comment]
I'm getting an issue with redis that I'm trying to fix rn.
