### ISSUE TITLE
Responsive Issue in Mobile Version - Collaboration Section Overlaps with GIFs

### ISSUE THREAD

**Issue by HasanZaigam** [keploy/keploy#2114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
In the mobile version of the website, the recent collaboration part goes behind the GIFs used in the feature section. This makes the collaboration part unreadable and affects the user experience.

## Expected Behavior
The collaboration part should be visible and not overlap with the GIFs.

## Actual Behavior
The collaboration part goes behind the GIFs, making it unreadable.

## Screenshots

for more understanding of the issue Please have a look at the Screenshots which I attached below:-

### In mobile Versio:-

![Screenshot 2024-07-22 093555](https://github.com/user-attachments/assets/2c765114-4785-4d37-9631-81d61fb773ad)

### In Laptop Version:-
![Screenshot 2024-07-22 100123](https://github.com/user-attachments/assets/d5a8c185-9ad1-4bf2-9da2-38b49c404d7d)

## Steps to Reproduce

1. Open the website on a mobile device.
2. Navigate to the feature section.
3. Observe that the recent collaboration part overlaps with the GIFs.

None

### Repository

keploy/website

**Comment by Swpn0neel** [comment]
Can you please name the devices in which they are breaking? So that we can reproduce it properly!

**Comment by HasanZaigam** [comment]
from dimension 420 X 725 to 768 X 725 it shows this issue.

**Comment by siddharthbaleja7** [comment]
Can you please assign this issue to me

**Comment by HasanZaigam** [comment]
@siddharthbaleja7  Yes, go ahead and start Contributing and for more details . Please reach to @Swpn0neel

**Comment by Swpn0neel** [comment]
Go ahead @siddharthbaleja7!

**Comment by siddharthbaleja7** [comment]
@Swpn0neel The PR is raised in the website Repo. Can you please review it?

**Comment by siddharthbaleja7** [comment]
Hi @Swpn0neel, I’ve addressed the requested fixes—could you please review the updated PR? Thanks!
