### ISSUE TITLE
[bug]: One of the code snippets on the landing page is overflowing in mobile version.

### ISSUE THREAD

**Issue by Aman172003** [keploy/keploy#2126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Mobile View
<img width="325" alt="Screenshot 2024-07-24 at 3 02 50 AM" src="https://github.com/user-attachments/assets/2f2afa5f-eb20-404a-a954-9104b90435eb">

## Desktop View
<img width="1440" alt="Screenshot 2024-07-24 at 3 11 45 AM" src="https://github.com/user-attachments/assets/9228c6c1-078a-4f74-924f-ec3fbb676e5e">

### Steps to reproduce

Visit https://keploy.io/ to see the code snippet overflow issue.

### Environment

None

### Version

Cloud

### Repository

website

**Comment by Aman172003** [comment]
@ Swpn0neel can i work on it under kROC?

**Comment by Swpn0neel** [comment]
Can you tell me the device name in which it's causing this issue?

**Comment by Aman172003** [comment]
> Can you tell me the device name in which it's causing this issue?

devices with the resolution below 581x903

**Comment by Swpn0neel** [comment]
But I can't reproduce it:

![image](https://github.com/user-attachments/assets/42d4b93a-ad8e-4475-9b21-7e48083cc4da)

**Comment by Aman172003** [comment]
@Swpn0neel my bad it's 485x903

**Comment by suvanbanerjee** [comment]
@Aman172003 Check #2075

**Comment by suvanbanerjee** [comment]
@Swpn0neel to replicate open in your real mobile device

**Comment by Swpn0neel** [comment]
As we are refactoring this section and replacing it with react-console, so it's currently not relevant for us!

**Comment by nehagup** [comment]
@Swpn0neel I think there's a confusion. I could see this error too, it's a valid issue. The new section we are adding is going to be seperate. @Aman172003 thanks for the initiative, please take this one. 
<img width="584" alt="Screenshot 2024-07-24 at 7 44 45 PM" src="https://github.com/user-attachments/assets/d9b5d342-5488-4901-af74-3258e009f9e5">
