### ISSUE TITLE
[feature]: seperate repo for shared go libs

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#213]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to create a separate repo for shared lib between keploy and the go SDK. If it makes sense we could also move the shared libs to the go SDK as well.  

### Why should this be worked on?

The go-sdk unnecessarily depends on the keploy repo which can create issues while making changes to the share libs and also if there are any problems with the keploy.io domain.

**Comment by charankamarapu** [comment]
This issue is related to keploy v1 and it is not relevant as keploy v2 as been lanuched,
