### ISSUE TITLE
[bug]: fix the GitHub actions generation feature

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#2133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently the GitHub actions is generated in the root folder - it should instead be in the current folder. We also need to validate the following: 

1. Ensure to only generate of the remote url in the repo is GitHub based. There's no point is generating GitHub actions pipeline for users with Gitlab, Bitbucket, Gerrit, etc.. 
2. Ensure that the generated actions actually works. 
3. Document the steps the user needs to take to make it work. 

This can be a powerful feature if works correctly. 

### Steps to reproduce

1. Record some tests with keploy
2. Run keploy test with `--generateGithubActions=true`. 

### Environment

None

### Version

Local

### Repository

keploy

**Comment by jaydee029** [comment]
Hey @slayerjain I have sufficient experience with github actions, I would like to take this up.
