### ISSUE TITLE
[feature]: Create a sample app using Express, PostgreSQL and Prisma

### ISSUE THREAD

**Issue by starvader13** [keploy/keploy#2136]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

An Express-based application utilizing PostgreSQL as the database and Prisma as the ORM for client-server communication. It needs to come with proper documentation!

### Why should this be worked on?

Express with PostgreSQL is widely used in modern web development. Incorporating Prisma as an ORM enhances the development experience by simplifying database interactions and ensuring efficient client-server communication. This would be a good SDK to have.

### Repository

typescript-sdk

**Comment by Sonichigo** [comment]
@starvader13 How do you planning to work on resolving this issue?

**Comment by Swpn0neel** [comment]
> @Swpn0neel As discussed, I have created an issue, Can you assign this to me?

Go ahead!!

**Comment by starvader13** [comment]
> @starvader13 How do you planning to work on resolving this issue?

@Sonichigo  I’m planning to create a basic CRUD application using Express.js. I’ll set up PostgreSQL locally using Docker and Prisma as the ORM. Additionally, I plan to write API documentation using Swagger.

Here are a few ideas for basic CRUD applications:

1. **Task Manager**
   - **Description:** An application to manage personal or team tasks.
   - **Features:** Add, view, update, and delete tasks. Each task can have a title, description, due date, and status (e.g., pending, in-progress, completed).

2. **Event Planner**
   - **Description:** A tool to manage events and appointments.
   - **Features:** Add, view, update, and delete events. Each event can have a title, date, time, location, and description.

3. **Blog Management**
   - **Description:** A platform to manage blog posts.
   - **Features:** Add, view, update, and delete blog posts. Each post can have a title, content, author, and publication date.

WDYT? Do you have any suggestions on which one I should choose, or any other ideas to add?

**Comment by Sonichigo** [comment]
> > @starvader13 How do you planning to work on resolving this issue?
> 
> @Sonichigo I’m planning to create a basic CRUD application using Express.js. I’ll set up PostgreSQL locally using Docker and Prisma as the ORM. Additionally, I plan to write API documentation using Swagger.
> 
> Here are a few ideas for basic CRUD applications:
> 
> 1. **Task Manager**
>    
>    * **Description:** An application to manage personal or team tasks.
>    * **Features:** Add, view, update, and delete tasks. Each task can have a title, description, due date, and status (e.g., pending, in-progress, completed).
> 2. **Event Planner**
>    
>    * **Description:** A tool to manage events and appointments.
>    * **Features:** Add, view, update, and delete events. Each event can have a title, date, time, location, and description.
> 3. **Blog Management**
>    
>    * **Description:** A platform to manage blog posts.
>    * **Features:** Add, view, update, and delete blog posts. Each post can have a title, content, author, and publication date.
> 
> WDYT? Do you have any suggestions on which one I should choose, or any other ideas to add?

All are great suggestion. I would suggest to go for either  the task manager or event planner. Since blog management CRUD is already present in nextjs-postgres

**Comment by starvader13** [comment]
> > > @starvader13 How do you planning to work on resolving this issue?
> > 
> > 
> > @Sonichigo I’m planning to create a basic CRUD application using Express.js. I’ll set up PostgreSQL locally using Docker and Prisma as the ORM. Additionally, I plan to write API documentation using Swagger.
> > Here are a few ideas for basic CRUD applications:
> > 
> > 1. **Task Manager**
> >    
> >    * **Description:** An application to manage personal or team tasks.
> >    * **Features:** Add, view, update, and delete tasks. Each task can have a title, description, due date, and status (e.g., pending, in-progress, completed).
> > 2. **Event Planner**
> >    
> >    * **Description:** A tool to manage events and appointments.
> >    * **Features:** Add, view, update, and delete events. Each event can have a title, date, time, location, and description.
> > 3. **Blog Management**
> >    
> >    * **Description:** A platform to manage blog posts.
> >    * **Features:** Add, view, update, and delete blog posts. Each post can have a title, content, author, and publication date.
> > 
> > WDYT? Do you have any suggestions on which one I should choose, or any other ideas to add?
> 
> All are great suggestion. I would suggest to go for either the task manager or event planner. Since blog management CRUD is already present in nextjs-postgres

Great then I would be going with the `Task Manager` one.
