### ISSUE TITLE
[docs]: contribution guide page

### ISSUE THREAD

**Issue by jaiakash** [keploy/keploy#2139]
### What do you want to add to the docs? (please state reasons if any)

https://keploy.io/docs/keploy-explained/contribution-guide/#keploy-operates-in-three-modes
<img width="901" alt="Screenshot 2024-07-26 at 6 19 03 PM" src="https://github.com/user-attachments/assets/f227ca0d-1cfb-4414-88f2-d8eed8faf243">

### Where is this stated?

In ss there are 3 modes mentioned, but actually its two right? First one being record and second one being test mode.

### Repository

docs

**Comment by debayangg** [comment]
Technically there's also keploy gen for unit tests generation.

**Comment by jaiakash** [comment]
Same thing was discussed in slack too with @Sonichigo 
He told gen ai mode is for generating test.

**Comment by poojatalele** [comment]
I would like to work on this issue.

**Comment by Sonichigo** [comment]
@jaiakash are you working on this issue ?

**Comment by jaiakash** [comment]
Yeah i would like to take it up.

**Comment by jaiakash** [comment]
Hi, I have made the PR; please check it.  I have one more suggestion for docs, which I have mentioned in PR.
