### ISSUE TITLE
[feature]: Remove sudo usage from keploy codebase

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2142]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be good to remove `sudo` usage from keploy codebase.

### Why should this be worked on?

This would make it easy to run keploy in systems were root user is not a sudoer.

### Repository

keploy

**Comment by Swpn0neel** [comment]
Depends on #2131

**Comment by SYSHIL** [comment]
Hi @Swpn0neel, could I pick this up as my first issue?

**Comment by Swpn0neel** [comment]
What is your approach to solve this issue?

**Comment by SYSHIL** [comment]
I had the opportunity to explore the tool itself yesterday. Today, I plan to set up the binary and run Keploy locally on my machine. Following that, I will review the codebase to understand how everything is set up. While I don't yet have an approach to solve the issue itself, I was wondering if this would be a good first issue to work on?

**Comment by Swpn0neel** [comment]
> I had the opportunity to explore the tool itself yesterday. Today, I plan to set up the binary and run Keploy locally on my machine. Following that, I will review the codebase to understand how everything is set up. While I don't yet have an approach to solve the issue itself, I was wondering if this would be a good first issue to work on?

You can try and let us know!

**Comment by SYSHIL** [comment]
Sure, Thank you so much @Swpn0neel !
