### ISSUE TITLE
[feature]: Add custom themes for Dark and Light mode users in Keploy Vscode Extension

### ISSUE THREAD

**Issue by SkySingh04** [keploy/keploy#2143]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Repository : https://github.com/keploy/vscode-extension

The current version of the vscode extension lacks customization options for Dark and Light modes. Instead, it has a standard theme for both light and dark mode users. This feature request proposes the addition of custom themes that automatically adapt to the user's VSCode theme settings, providing a more consistent and visually appealing experience.

#### Deliverables
- Implement custom themes for both Dark and Light mode users.
- Automatically detect the user's VSCode theme setting and apply the corresponding Keploy extension theme.
- Ensure all UI elements, including text, icons, buttons, and backgrounds, are styled appropriately for both Dark and Light modes.
- Provide a seamless transition between themes when the user switches VSCode modes.
ive and polished development environment.

### Why should this be worked on?

Improvements to UI/UX for Keploy extension users.

### Repository

keploy

**Comment by Aman172003** [comment]
i would like to work on this

**Comment by Akash-Singh04** [comment]
@Aman172003 Sure, give it a try!

**Comment by Akash-Singh04** [comment]
Sure thing! Feel free to give it a try! We will merge the first good PR that solves the issue! @yaten2302

**Comment by sanjay-xdr** [comment]
I have successfully setup the tailwind in the project and its working now 
Currently working on changing css to tailwind classes 
regarding this isssue 
do we have something specific for theme changes?
or just basic stuff like changing text color etc
Thanks

**Comment by Akash-Singh04** [comment]
Thats amazing @sanjay-xdr ! For the tailwind themings and guidelines, you can refer to #2145! Ideally, we would want to minimise the plain css in svelte files and sidebar.css to tailwind code as much as possible!

**Comment by sanjay-xdr** [comment]
gotta work on sidebar.css and theme now
thanks

**Comment by Akash-Singh04** [comment]
@sanjay-xdr Yes! Some elements are being created dynamically. Its better we keep a separate css file for those elements and add the rest of them using tailwind. Also, kindly go through the sidebar.css file and purge any styles that are not being applied!
