### ISSUE TITLE
[bug]: Current test pipelines are not showing logs when all tests are passed .

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#2156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Current test pipelines are not showing logs when all tests are passed but in case of failed tests or Error logs.

### Steps to reproduce

1) See the logs of the testbench for eg - https://github.com/keploy/keploy/actions/runs/10161943079/job/28101545615
2) Since all the testsets are passed, its not showing the logs.

### Environment

Production

### Version

Cloud

### Repository

keploy

**Comment by Deepakchowdavarapu** [comment]
I can Work on this Issue , Please Assign it to me

**Comment by Deepakchowdavarapu** [comment]
#2173 please review this @Sarthak160

**Comment by gouravkrosx** [comment]
@Sarthak160 Please look into this.

**Comment by shivamsouravjha** [comment]
closing the issue as it is linked to keploy binary return 1 and nothing can be done in this regard
