### ISSUE TITLE
[feature]: style the "star on github" button on landing page 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#2157]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We're planning to integrate magicui https://magicui.design/docs and the button design inspiration can be taken from the docs page of magicUI itself. 

<img width="256" alt="Screenshot 2024-07-30 at 7 44 39 PM" src="https://github.com/user-attachments/assets/345011c2-42ac-4b21-b4da-15dc4bc9997f">

Bonus: 
You can https://magicui.design/docs/components/cool-mode with stars as the object

### Why should this be worked on?

improved design

### Repository

website

**Comment by BHAV0207** [comment]
hey @nehagup  i would like to work on this issue

**Comment by nehagup** [comment]
Sure @BHAV0207 , please create a PR.

**Comment by nehagup** [comment]
@BHAV0207 are you still working on this?

**Comment by Sonichigo** [comment]
hey @BHAV0207 are you still working on it ?

**Comment by akshat99812** [comment]
I would like to work on this can this be assigned to me

**Comment by nehagup** [comment]
@akshat99812 sure.

**Comment by dakshmehta007** [comment]
@nehagup should we have to give style to whole button?
