### ISSUE TITLE
[feature]: add marquee animation to list of supported dependencies in the landing page

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#2160]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Add marquee effect https://magicui.design/docs/components/marquee to the "Replicate data from any source  " section of keploy landing page. 

### Why should this be worked on?

better design

### Repository

website

**Comment by Aman172003** [comment]
i would like to work on this

**Comment by nehagup** [comment]
@Aman172003  are you still working on this?

**Comment by Aman172003** [comment]
yes
