### ISSUE TITLE
[feature]: add neon gradient behind the CTA buttons on the landing page

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#2161]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Idea is to add https://magicui.design/docs/components/neon-gradient-card neon gradient effect behind the main call-to-action buttons. 

### Why should this be worked on?

better design

### Repository

keploy

**Comment by abhinav26966** [comment]
Hey @nehagup , I would like to work on this issue.

**Comment by nehagup** [comment]
@abhinav26966 are you still working on this?

**Comment by abhinav26966** [comment]
> @abhinav26966 are you still working on this?

Yes @nehagup , I'm still working on this issue, will be opening PR soon.

**Comment by abhinav26966** [comment]
Hey, can you help me a bit. 
Actually I can't identify the call-to-action buttons, can you please help me with some examples and follow ups on the issue as I couldn't find some good matches for call-to-action buttons in the [website](https://github.com/keploy/website) repo.

**Comment by abhinav26966** [comment]
Hey, @nehagup 
Can you help please about the issue details?

**Comment by abdulghous** [comment]
Had anyone contributed this issue? I am a new developer and I can contribute in this issue if no one had done.
