### ISSUE TITLE
[feature]: add particles in the hero section of the landing page

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#2162]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

add https://magicui.design/docs/components/particles in the background of hero section of landing page

### Why should this be worked on?

better design

### Repository

website

**Comment by BHAV0207** [comment]
@nehagup  I would like to work on this issue

**Comment by nehagup** [comment]
@suvanbanerjee If you want you can pick this up, @BHAV0207  has been assigned 2 other issues.

**Comment by suvanbanerjee** [comment]
@nehagup Sure assign it to me

**Comment by suvanbanerjee** [comment]
@nehagup Should we add the specific MagicUI framework to the Keploy website and then integrate the particle effect from MagicUI? Doing so would be a major PR and might require significant testing. Alternatively, should I just focus on adding the particle effect without using MagicUI, simply taking inspiration from it?

**Comment by harshsbhat** [comment]
I have implemented something similar to this in my Portfolio. Would love to work on this @nehagup
