### ISSUE TITLE
[bug]: UI not optimized for videos or gif

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#2163]
### Steps to reproduce

1. Go to https://keploy.io/blog/technology/revolutionising-unit-test-generation-with-llms
2. Scroll down to where the gif present.

https://github.com/user-attachments/assets/1a1ce8ae-3c6b-4da5-83ec-f540a0c04be3

### Expected Behaviour

1. It should behave in a manner  similiar to image.

**Comment by suvanbanerjee** [comment]
@Sonichigo can i take this one?

**Comment by Sonichigo** [comment]
Yeah sure!

**Comment by suvanbanerjee** [comment]
@Sonichigo can you share an example page where gif are not scaled properly

**Comment by Sonichigo** [comment]
> @Sonichigo can you share an example page where gif are not scaled properly

Please refer to this - > https://keploy.io/blog/technology/revolutionising-unit-test-generation-with-llms
