### ISSUE TITLE
[docs]: add sse-svelte sample application on documentation website

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#2164]
### What do you want to add to the docs? (please state reasons if any)

Quickstart Guide to run [SSE-Svelte](https://github.com/keploy/samples-go/tree/main/sse-svelte) application on Documentation under `golang` language.

### Repository

docs - https://github.com/keploy/docs

**Comment by Ishaanj18** [comment]
I will take this one up!

**Comment by Sonichigo** [comment]
@Ishaanj18 go ahead! lmk if you are stuck any where?
