### ISSUE TITLE
[docs]: add fasthttp-postgres sample app guide on documentation website

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#2166]
### What do you want to add to the docs? (please state reasons if any)

Quickstart Guide to run [fasthttp-postgres](https://github.com/keploy/samples-go/tree/main/fasthttp-postgres) application on Documentation under golang language.

### Repository

docs

**Comment by mastersans** [comment]
I'll work on this.

**Comment by Sonichigo** [comment]
sure @mastersans ! Lmk if you need any help :)

**Comment by mastersans** [comment]
@Sonichigo i have opened a PR for this one https://github.com/keploy/docs/pull/437 can you take a look at that.
