### ISSUE TITLE
[bug]: Remove internal config params while generating config in vscode extension

### ISSUE THREAD

**Issue by ayush3160** [keploy/keploy#2168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Repo :- https://github.com/keploy/vscode-extension
While setting up the config through vscode-extension it adds internal params to keploy.yml file. For more reference see [#issue2076](https://github.com/keploy/keploy/issues/2076).

### Steps to reproduce

1. Start by setting up keploy config file.
2. Check keploy.yml file.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by Sonichigo** [comment]
This issue is depended on the https://github.com/keploy/keploy/issues/2076 ! Since keploy.yml generated via keploy itself in by keploy vscode-extension, it's an issue with keploy. I noticed that you already have raised the pr for the fix, it will fix the issue in vscode as well

**Comment by ayush3160** [comment]
I thought it is using the [handleInitializeKeployConfigFile](https://github.com/keploy/vscode-extension/blob/main/src/Config.ts#L53) function to initialize the config file.

**Comment by Sonichigo** [comment]
My bad, yeah, we need to fix there as well. Would you like to work on this issue ?

**Comment by ayush3160** [comment]
Yes , Working on it
