### ISSUE TITLE
[docs]: incorrect bash command in README.md of samples-python/fastapi-twilio

### ISSUE THREAD

**Issue by sratslla** [keploy/keploy#2171]
### What do you want to add to the docs? (please state reasons if any)

The bash command in the readme has trailing commas in the JSON, which will result in incorrect Query and 422 Unprocessable Entity in our case. Also, there are some minor updates that can made.

### Repository

samples-python

**Comment by sratslla** [comment]
I would like to work on this under KROC.

**Comment by Sonichigo** [comment]
this issue is resolved by the pr - https://github.com/keploy/samples-python/pull/25
