### ISSUE TITLE
[docs]: Improve Glossary Styling for Dark/Light Modes and List Alignment

### ISSUE THREAD

**Issue by abhishekkushwaha-tm** [keploy/keploy#2187]
### What do you want to add to the docs? (please state reasons if any)

![image](https://github.com/user-attachments/assets/43009c4f-db9b-43c3-bb75-32704ca38db3)

- Dark/Light Mode Consistency
- Standardize the alignment of glossary terms across all letter sections

### Where is this stated?

https://keploy.io/docs/concepts/reference/glossary/

### Repository

docs

**Comment by Abbhiishek** [comment]
Raised a Pull Request here: https://github.com/keploy/docs/pull/441
