### ISSUE TITLE
CodeQL queries

### ISSUE THREAD

**Issue by aaaayush-n** [keploy/keploy#2204]
Hello, 
I want to know where I can find the CodeQL queries that run in the github workflow.
Please provide me with a link to these queries.

**Comment by shivamsouravjha** [comment]
This would be the one https://github.com/keploy/keploy/blob/main/.github/workflows/codeql.yml

you can see similar workflows via `.github.` folder inside which there are workflows.

**Comment by aaaayush-n** [comment]
@shivamsouravjha 
I want to see the queries being executed.
I want access to the .ql files ie. the queries that are running.

**Comment by shivamsouravjha** [comment]
If you refer to the workflow, 
```
- name: Perform CodeQL Analysis
  uses: github/codeql-action/analyze@v2

```
we've this imported for our CodeQL usage, and we don’t directly use .ql queries.
