### ISSUE TITLE
[feature]: Navbar Revamp Design (Follow up)

### ISSUE THREAD

**Issue by TvisharajiK** [keploy/keploy#2210]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

**The navbar of the Keploy website needs some revamping done :** 

There is a existing issue where the revamp has been discussed (Kindly refer for context) : https://github.com/keploy/keploy/issues/2068

Took some inspiration and created the figma to recreate : https://www.figma.com/design/F4malcwSfTY7tUhamWAGj1/Keploy-NavBar-Change-suggestions-(to-share)?node-id=0-1&t=FBl3wGXEL7gjJXKq-1

This is the color palette for reference : https://github.com/keploy/website?tab=readme-ov-file#brand-color-palette

### 🎤 Why should this be worked on?

Revamping the entire Navbar section to have more people visit and for ease of navigation as well 

### 💻 Repository

website

**Comment by TvisharajiK** [comment]
@yaten2302 Hey yaten, since that issue is closed. This was the new one created. Has all the figma link as well 
Let me know if you need anything else

**Comment by TvisharajiK** [comment]
Hey @yaten2302 are you working on this ?

**Comment by yaten2302** [comment]
Hey @TvisharajiK , yes, I'm working on this issue. I'll create a PR soon!
