### ISSUE TITLE
[feature]: add support of Go for VScode extension 

### ISSUE THREAD

**Issue by Hermione2408** [keploy/keploy#2250]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

add support of go in VSCode extension

### 🎤 Why should this be worked on?

Helps generate UT for go apps

### 💻 Repository

keploy

**Comment by ayesparshh** [comment]
I will work on this. Please provide references for support in other languages.
Thanks

**Comment by Akash-Singh04** [comment]
Is this referring to record and replay commands or is this for the UTG command? @Hermione2408

**Comment by Hermione2408** [comment]
PR- https://github.com/keploy/vscode-extension/pull/29
