### ISSUE TITLE
[feature]: The Docs Section Footer is not looking good , wants to work on this issue

### ISSUE THREAD

**Issue by rajputdivyanshu81** [keploy/keploy#2254]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

![Screenshot 2024-08-31 020443](https://github.com/user-attachments/assets/e9ddc23e-d9df-4787-b57f-ea81cfe718d3)
![Screenshot 2024-08-31 020711](https://github.com/user-attachments/assets/03f74b22-fd5a-4b0f-b2e3-e1a70befa6ec)
these footers styles looks old ,wanna upgrade it to the new one which looks better and more engaging UI.

### 🎤 Why should this be worked on?

UI should be good ..

### 💻 Repository

keploy

**Comment by rajputdivyanshu81** [comment]
Please assign me this issue

**Comment by Sonichigo** [comment]
@rajputdivyanshu81 can you share the scope of improvements and design reference, before we assign the issue?

**Comment by Shaileshsaravanan** [comment]
can you assign this to me, i would like to work on it

**Comment by MitanshuKumawat** [comment]
Pls assign me this

**Comment by rajputdivyanshu81** [comment]
This is good , so please close this issue , there is no need to add the animations over there ...before some time i thought to add some motion and animations over but that was not the right decision... hence this is resolved so requested to close this issue...
