### ISSUE TITLE
[feature]: The Home should also have an dark mode and light mode feature, as most of the developeres preferred to be work on the dark mode..

### ISSUE THREAD

**Issue by rajputdivyanshu81** [keploy/keploy#2256]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

making the dark theme in it so that user can switch the mode and go for what ever is comfortable with..

### 🎤 Why should this be worked on?

![image](https://github.com/user-attachments/assets/5d6ab16b-11f3-42de-9a1c-279ae7d42956)
Black background screen is more preferred to read ..... so website should have an dark mode and light mode theme ...

### 💻 Repository

keploy

**Comment by rajputdivyanshu81** [comment]
Please assign me this issue

**Comment by Sonichigo** [comment]
Hi @rajputdivyanshu81 closing this issue since it's a duplicate issue, please find the active one - https://github.com/keploy/keploy/issues/2039

**Comment by rajputdivyanshu81** [comment]
great
