### ISSUE TITLE
[bug]: Keploy is unable to record some mysql messages

### ISSUE THREAD

**Issue by sagar-t-97** [keploy/keploy#2268]
### 👀 Is there an existing issue for this?

- [X] I have searched and didn't find similar issue

### 👍 Current behavior

When I try keploy record with a node and mysql app, keploy fails to record the initial handshake packets with mysql. I am seeing this issue with this application https://github.com/wednesday-solutions/nodejs-hapi-template and using keploy enterprise 0.9.7
Here are the error logs generated by keploy:
```
🐰 Keploy: 2024-09-05T11:29:14Z         ERROR   failed to handle initial handshake      {"Client IP Address": "192.168.128.5:55780", "Client ConnectionID": "4", "Destination ConnectionID": "5", "error": "failed to handle auth switch request: failed to handle caching sha2 password: failed to get caching sha2 password mechanism: invalid caching_sha2_password mechanism"}
🐰 Keploy: 2024-09-05T11:29:14Z         ERROR   failed to encode the mysql message into the yaml        {"Client IP Address": "192.168.128.5:55780", "Client ConnectionID": "4", "Destination ConnectionID": "5", "error": "failed to handle auth switch request: failed to handle caching sha2 password: failed to get caching sha2 password mechanism: invalid caching_sha2_password mechanism"}
🐰 Keploy: 2024-09-05T11:29:14Z         ERROR   failed to record the outgoing message   {"error": "failed to handle auth switch request: failed to handle caching sha2 password: failed to get caching sha2 password mechanism: invalid caching_sha2_password mechanism"}
🐰 Keploy: 2024-09-05T11:29:14Z         ERROR   failed to handle the client connection  {"error": "failed to handle auth switch request: failed to handle caching sha2 password: failed to get caching sha2 password mechanism: invalid caching_sha2_password mechanism"}
```

### 👟 Steps to Replicate

1. git clone https://github.com/wednesday-solutions/nodejs-hapi-template.git
2. docker compose --env-file .env.docker build
3. keploy record -c 'docker compose --env-file .env.docker up' --containerName "nodejs-hapi-template-app-1"

### 💻 Operating system

MacOS

### 🎲 Version

I am using keploy enterprise 0.9.7

### 💻 Repository

keploy

**Comment by gouravkrosx** [comment]
@sagar-t-97 Can you please try again with the latest keploy oss release?

**Comment by sagar-t-97** [comment]
Thanks, its working now with version: 2.3.0-beta20
