### ISSUE TITLE
[feature]: update feature in vscode extension

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2277]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

* we should let users update their keploy on vscode

### 🎤 Why should this be worked on?

* helps users keep on latest version

### 💻 Repository

vscode-extension

**Comment by ayush3160** [comment]
This feature is already implemented in vscode-extension. 

![peek_1](https://github.com/user-attachments/assets/1148b42a-7c00-4d96-801f-a979300409f0)
