### ISSUE TITLE
[feature]: Create a sample app using Express and Redis

### ISSUE THREAD

**Issue by akshat99812** [keploy/keploy#2296]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

The application is a RESTful web service built on Express.js for client-server communication, utilizing Redis as an in-memory data store for caching frequently accessed data. The implementation aims to enhance the system’s performance by reducing latency and minimizing load on the primary data source (such as a database), especially for read-heavy operations.

### 🎤 Why should this be worked on?

This solution is suitable for high-performance web applications where optimizing read operations and ensuring low-latency responses are critical.
There's currently no such sample app with us.

### 💻 Repository

samples-typescript

**Comment by akshat99812** [comment]
Added a PR: [#65](https://github.com/keploy/samples-typescript/pull/65)

**Comment by Sonichigo** [comment]
@akshat99812 thanks for the contribution! It's in review!
