### ISSUE TITLE
[feature]: CI Pipelines for Go Sample Applications

### ISSUE THREAD

**Issue by khareyash05** [keploy/keploy#2317]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

There are CI pipelines for some of the existing applications in samples- go but not for all, adding them would be great

Also there are only linter pipelines, build pipelines are needed

### 🎤 Why should this be worked on?

To increase our applications tests

### 💻 Repository

samples-go

**Comment by MeenuyD** [comment]
Hello @khareyash05 I would like to ok on this feature could you please assign me

**Comment by khareyash05** [comment]
Sure go ahead @MeenuyD

**Comment by rishavmehra** [comment]
Hey @khareyash05,

I just raised a PR for the changes related to [issue #2317](https://github.com/keploy/keploy/issues/2317).

Could you please take a moment to review it? You can find the PR here: [PR #121](https://github.com/keploy/samples-go/pull/121).

Thank you!

**Comment by khareyash05** [comment]
Hey @rishavmehra, I wont be able to review this PR, because someone has been already assigned, will have to wait for sometime to review
