### ISSUE TITLE
[bug]: make one click install for mac backward compatible

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2327]
### 👀 Is there an existing issue for this?

- [X] I have searched and didn't find similar issue

### 👍 Current behavior

* When running one click install on mac latest binary isn't replaced in tmp folder

### 👟 Steps to Replicate

* Incase if old keploy folder is existent it won't be replaced leading to latest version no being installed on keploy
* Removing the pre-existent keploy folder in temp is the way to go 

### 💻 Operating system

Linux

### 🎲 Version

I am using the latest version of keploy

### 💻 Repository

keploy

**Comment by a1danw** [comment]
For mac I tried adding the following to both install_keploy_arm and install_keploy_amd but didn't seem to fix it
`rm -rf /tmp/keploy
mkdir -p /tmp/keploy`

**Comment by shivamsouravjha** [comment]
hey @a1danw its present in usr/local/bin by default, you should try removing the keploy folder from there.

**Comment by NishantBansal2003** [comment]
Is this issue resolved with respect to the PR [#2441](https://github.com/keploy/keploy/pull/2441)? I tried reproducing the issue on macOS with different Keploy versions but did not encounter any issues.
cc: @shivamsouravjha

**Comment by shivamsouravjha** [comment]
Yes this has been fixed thus closing the issue
