### ISSUE TITLE
[feature]: exact path for utg

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2331]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

* by giving exact path it can generate correct import paths

### 🎤 Why should this be worked on?

* Helps generate less flaky test cases

### 💻 Repository

keploy

**Comment by Hermione2408** [comment]
Resolved by- https://github.com/keploy/keploy/pull/2330
