### ISSUE TITLE
Create a Django-Mongo sample app

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2335]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

Create a Django-Mongo sample app for [samples-python](https://github.com/keploy/samples-python) repository

### 🎤 Why should this be worked on?

Currently there is no similar sample apps with this tech-stack.

### 💻 Repository

samples-python

**Comment by AryanBakliwal** [comment]
Hey @Swpn0neel, I'd like to work on this

**Comment by Swpn0neel** [comment]
Go ahead, @AryanBakliwal!
