### ISSUE TITLE
Create a Flask-PostgreSQL sample app

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2336]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

Create a Flask-PostgreSQL sample app for the [samples-python](https://github.com/keploy/samples-python) repository.

### 🎤 Why should this be worked on?

Currently there is no similar sample apps with this tech-stack.

### 💻 Repository

samples-python

**Comment by Harshjosh361** [comment]
@Sonichigo can u check it once...
