### ISSUE TITLE
Create a Sanic-Postgres sample app

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2337]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

Create a Sanic-Postgres sample app for the [samples-python](https://github.com/keploy/samples-python) repository.

### 🎤 Why should this be worked on?

Currently there is no similar sample apps with this tech-stack.

### 💻 Repository

samples-python

**Comment by yours-majesty** [comment]
@Swpn0neel I wanna work on this...It's a good first issue and I wanna give it a shot.

**Comment by Swpn0neel** [comment]
Yeah, go ahead @yours-majesty!

**Comment by slashexx** [comment]
@Swpn0neel I have opened a PR for the same, can you please take a look ?
