### ISSUE TITLE
[feature]: optimise update import function of languages for UTG

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2347]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

* In gen.go we have certain functions like updateGoImports,updateJavaImports,updatePythonImports,updateTypeScriptImports,updateJavaScriptImports these functions help us append correct number of new lines so that newly added tests aren't placed at wrong place causing build errors.
* Currently updateJavaImports is the most optimised one as it traverses through the new imports and just adds any additional one and maintain a count, this helps us put new testcases in correct place.

### 🎤 Why should this be worked on?

* Current functions are functional but these would make them more optimised.
* Please also attach screenshot that the optimised functions are functional and work like they workded before.
* refer https://keploy.io/docs/running-keploy/unit-test-generator/#heading to see how to run utg locally.

### 💻 Repository

keploy

**Comment by sup194** [comment]
I'd like to tackle this issue if no one else is working on it

**Comment by sup194** [comment]
can you assign this to me, i would like to work on it

**Comment by shivamsouravjha** [comment]
sure @sup194 feel free to work on it!

**Comment by sup194** [comment]
> sure @sup194 feel free to work on it!

Thank you for assigning the issue to me. I’ve started working on it, but I ran into some difficulty obtaining the Open API key required for debugging. If it’s possible to provide the expected input and output for the updateImport function, I can proceed by writing a unit test to validate my changes directly. Looking forward to your guidance!

**Comment by shivamsouravjha** [comment]
you can use your own GPT  API_KEY for this https://keploy.io/docs/running-keploy/unit-test-generator/#prerequisites.

in updateImport functions of different languages we get the entire code snippet and an array of strings like ~
[ "- import abcd", "-import abc"] for java ..similarly for go and other languages we get output like this

```
new_imports_code: |
    {%- if language == "python" %}
    - "import pytest"
    - "from my_module import my_function"
    {%- elif language == "java" %}
    - "import org.junit.jupiter.api.Test;"
    - "import my.package.MyFunction;"
    {%- elif language == "golang" %}
    - "import \"testing\""
    - "import \"my_module\""
    {%- elif language == "javascript" %}
    - "const assert = require('assert');"
    - "const myFunction = require('my_module').myFunction;"
    {%- elif language == "typescript" %}
    - "import { assert } from 'assert';"
    - "import { myFunction } from 'my_module';"
    {%- endif %}
```

**Comment by sup194** [comment]
> you can use your own GPT API_KEY for this https://keploy.io/docs/running-keploy/unit-test-generator/#prerequisites.
> 
> in updateImport functions of different languages we get the entire code snippet and an array of strings like ~ [ "- import abcd", "-import abc"] for java ..similarly for go and other languages we get output like this
> 
> ```
> new_imports_code: |
>     {%- if language == "python" %}
>     - "import pytest"
>     - "from my_module import my_function"
>     {%- elif language == "java" %}
>     - "import org.junit.jupiter.api.Test;"
>     - "import my.package.MyFunction;"
>     {%- elif language == "golang" %}
>     - "import \"testing\""
>     - "import \"my_module\""
>     {%- elif language == "javascript" %}
>     - "const assert = require('assert');"
>     - "const myFunction = require('my_module').myFunction;"
>     {%- elif language == "typescript" %}
>     - "import { assert } from 'assert';"
>     - "import { myFunction } from 'my_module';"
>     {%- endif %}
> ```
That makes sense, thank you!

**Comment by shivamsouravjha** [comment]
I've updated for Golang (as it was on priority list please check the same)

**Comment by sup194** [comment]
> I've updated for Golang (as it was on priority list please check the same)

Got it, thanks for the update!

**Comment by sup194** [comment]
@shivamsouravjha could you please review this PR when you have a moment?

**Comment by shivamsouravjha** [comment]
have updated  most of those functions and now they seem to be fine.
