### ISSUE TITLE
[feature]: integrate keploy's diff viewer 

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2349]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

* Keploy has recently release a new package for cli diff viewer called jsondiff https://github.com/keploy/jsondiff
* We've to integrate keploy with jsondiff

### 🎤 Why should this be worked on?

* Would remove the burden of maintenance from main keploy repo. 

### 💻 Repository

keploy

**Comment by Harshjosh361** [comment]
fixed: #2350

**Comment by Redidacove** [comment]
@shivamsouravjha If I understand correctly you want to integrate that package and remove the pkgs from this repo and use that pkg as external dep via import right

**Comment by shivamsouravjha** [comment]
i mean if we want to make a changes we will do it in other repo.

**Comment by Redidacove** [comment]
> i mean if we want to make a changes in diff viewer we will do it in other repo and not the main keploy repo.

makes sense new to repo can you give little info about which pkgs are related to this here means like where is jsondiff code now and is used how

**Comment by shivamsouravjha** [comment]
I’ve added in the description already. And it has the readme as well to show whats the use of which function.

**Comment by shivamsouravjha** [comment]
Sure @akshat99812

**Comment by ayush3160** [comment]
Hi @shivamsouravjha , I have raised a pr to fix this issue. Please have a look

**Comment by akshat99812** [comment]
@ayush3160 I was working on the issue and was gonna raise a pr soon

**Comment by akshat99812** [comment]
@shivamsouravjha Is this issue still open I would like to work on it
