### ISSUE TITLE
[bug]: "Copy to Clipboard" button not working on Safari Browser

### ISSUE THREAD

**Issue by trivedi-khushi** [keploy/keploy#2367]
### 👀 Is there an existing issue for this?

- [X] I have searched and didn't find similar issue

### 👍 Current behavior

When the "Copy to Clipboard" button is clicked on Safari (both macOS and iOS), the expected text is not copied to the clipboard. The button appears to function normally, but no text is copied, and the user is unable to paste the text elsewhere. No error message or feedback is provided.

### 👟 Steps to Replicate

1. Open the docs website https://keploy.io/docs/server/installation/ on Safari (macOS or iOS).
2. Click the "Copy to Clipboard" button.
4. Try pasting the text into another location (e.g., Notes or Text Editor).

### 💻 Operating system

MacOS

### 🎲 Version

Version 17.6 (19618.3.11.11.5)

### 💻 Repository

docs

**Comment by akshat99812** [comment]
I would like to work on this issue

**Comment by Nishant732003** [comment]
can you assign this issue to me?

**Comment by Tanishq1604** [comment]
@trivedi-khushi  ma'am, I checked, and it seems to be working fine for me. If the issue has been resolved, that's great! Otherwise, it appears to be functioning as expected. Attaching a video for reference.
https://github.com/user-attachments/assets/fad7ae5f-bc66-43a1-b23e-b449e491aecc

**Comment by nehagup** [comment]
hi @Tanishq1604 we recently fixed this. thanks for testing, closing this issue.
