### ISSUE TITLE
[feature]: the error message be binary decoded in test-export yaml

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#238]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, the error message is stored as base64 encoded binaries in test exported yaml. Instead it should store the readable error message in data field of Objects of yaml file.

### Why should this be worked on?

It will be readable and easy to overwrite.

**Comment by charankamarapu** [comment]
Currently in keploy uber zap is used for logging which will take care of all of these, so this is resolved.
