### ISSUE TITLE
[feature]: Add Attractive sticky for VS Code Extension

### ISSUE THREAD

**Issue by TvisharajiK** [keploy/keploy#2383]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

Create a banner sticky at the bottom similar to https://blackfriday.com/ for the keploy website 
You can use any template online or any design but should be according to the brand guidelines https://github.com/keploy/website

It should have a CTA to the VS Code extension with some lorem ipsum content 

### 🎤 Why should this be worked on?

VS Code extension

### 💻 Repository

keploy

**Comment by Aviral0702** [comment]
@TvisharajiK Can I take up this issue ?

**Comment by wasifkareem** [comment]
Hi @Aviral0702 I think you already have an open issue, @TvisharajiK can I take this one

**Comment by TvisharajiK** [comment]
yes @wasifkareem

**Comment by wasifkareem** [comment]
Hi @TvisharajiK , do we need to show the banner everytime the website is opened or refreshed?

**Comment by TvisharajiK** [comment]
everytime opened

**Comment by ab7022** [comment]
can i work on it

**Comment by ab7022** [comment]
This PR adds a sticky navbar for the VS Code Extension. 

For more details on the sticky navbar implementation, refer to the related PR in the other repository: [keploy/website#118](https://github.com/keploy/website/pull/118).

**Comment by TvisharajiK** [comment]
@ab7022 Can you move the sticky to above the nabvar

**Comment by ab7022** [comment]
yes, i'm on it

**Comment by ab7022** [comment]
@TvisharajiK  i have moved the banner to the top
![scrnli_VzUxJux5Xz8bey](https://github.com/user-attachments/assets/8e439cec-85fd-445b-a477-b11827f632b5)
my PR: [keploy/website#118](https://github.com/keploy/website/pull/118).

**Comment by Hermione2408** [comment]
The PR addressing this issue has been merged https://github.com/keploy/website/pull/118 . Closing this issue as resolved. Thank you to everyone who contributed!
