### ISSUE TITLE
[feature]: Case Studies Page

### ISSUE THREAD

**Issue by TvisharajiK** [keploy/keploy#2385]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

Create a Case studies page that is responsive, based on any template that you choose and adheres to the brand guidelines 
https://github.com/keploy/website

(Just a sample design), you can choose any template online 
https://www.figma.com/design/Smg0JK5FmCkiLY9Qlto0v8/Untitled?node-id=0-1&t=eIBHz4YcVluJELoT-1

Some sample websites : https://pixis.ai/case-studies/

### 🎤 Why should this be worked on?

Case Studies page 

### 💻 Repository

keploy

**Comment by MeenuyD** [comment]
Hello @TvisharajiK could you please assign this task to me?

**Comment by PranavBarthwal** [comment]
Hey @TvisharajiK , I would like to work on this.

**Comment by TvisharajiK** [comment]
@MeenuyD Are you working on this?

**Comment by MeenuyD** [comment]
> @MeenuyD Are you working on this?

Yes

**Comment by MeenuyD** [comment]
Hello @TvisharajiK Could you please assign it to again I will create pr as soon as possible.

**Comment by PranavBarthwal** [comment]
> @MeenuyD Are you working on this?

please assign this to me! @TvisharajiK

**Comment by Varshap2205** [comment]
Hello @TvisharajiK Could you please assign this to me?
