### ISSUE TITLE
[feature]: Better template for Keploy's blog page

### ISSUE THREAD

**Issue by TvisharajiK** [keploy/keploy#2387]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

Would like to redesign Keploy's blog page : 
https://keploy.io/blog/community
Adhere to brand guidelines from https://github.com/keploy/website

Be as creative as you can :)

You can choose any existing templates available online and work on it as well, just ensure it follows a appropriate design theme as per Keploy.io

### 🎤 Why should this be worked on?

Improve design 

### 💻 Repository

keploy

**Comment by TvisharajiK** [comment]
@arup1221 Nope, feel free to pick anything

**Comment by arup1221** [comment]
@TvisharajiK mam, do I need to change the design of both pages Ex-  "keploy.io/blog/community" page and "keploy.io/blog/community/[blog-heading-of-any-blog]"

**Comment by TvisharajiK** [comment]
> @TvisharajiK mam, do I need to change the design of both pages? Ex- "keploy.io/blog/community" page and "keploy.io/blog/community/[blog-heading-of-any-blog]"

That can be up to you as well, ideally better for design fluidity
But again anything works

**Comment by arup1221** [comment]
Ok, Mam I am working on it.

**Comment by arup1221** [comment]
Mam, one last question, keploy/blog-website - it is the repo of Blog website and i need to work on this only?

**Comment by TvisharajiK** [comment]
@arup1221 Yep, that is on the blog website repo

**Comment by arup1221** [comment]
I need a Wordpress api url, How do I get it? Mam

**Comment by arup1221** [comment]
Mam, can I add plugin in my WordPress free plan?

**Comment by arup1221** [comment]
@TvisharajiK  Mam, could you please check it and tell me if there is an error need to solve and need some improvement.

**Comment by TvisharajiK** [comment]
> @TvisharajiK Mam, could you please check it and tell me if there is an error need to solve and need some improvement.

Hey, can you add some screenshots of the changes you made for better reference?

**Comment by arup1221** [comment]
Mam, Is there any rate limit in the the graphql api which is in the .env.example ?
Because currently I can't access it.

**Comment by arup1221** [comment]
@TvisharajiK  could you please check my PR!

**Comment by KunalBamane57** [comment]
@TvisharajiK  could you assign this issue to me.

**Comment by swatified** [comment]
hey @TvisharajiK I see this issue is still not assigned? Can I get this assigned to me? I went to the brand guide and have thought of somethings to improvise in the website. spacing, animations, and a bento layout.

**Comment by TvisharajiK** [comment]
as mentioned prior, anyone can work on the issue
The final PR that will be counted is the one that fits the best (code practice and visually appealing) and will be merged

**Comment by arup1221** [comment]
@TvisharajiK please check my [PR](https://github.com/keploy/blog-website/pull/63) and provide any feedback

**Comment by aashrith-raksh** [comment]
> as mentioned prior, anyone can work on the issue The final PR that will be counted is the one that fits the best (code practice and visually appealing) and will be merged

Sounds good @TvisharajiK. I'd like to work on this issue.

However, the issue description says this issue is related to the main keploy repo. 

But I've found 2 related repositories: "website" and "blog-website" both of which have blogs.

Which one do I contribute to?

**Comment by TejasNasre** [comment]
I want to work on this issue i just read the above discussion i will raise PR asap with the best changes and with good looking ui

**Comment by Hermione2408** [comment]
This issue is no longer required, so we’ll go ahead and close it for now. Appreciate your contribution and support!
