### ISSUE TITLE
[bug]: latest blog not loading on blog site

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#2392]
### 👀 Is there an existing issue for this?

- [X] I have searched and didn't find similar issue

### 👍 Current behavior

* happens because the size is more than 1 mb.

### 👟 Steps to Replicate

* Run it locally and run nom run build

### 💻 Operating system

Linux

### 🎲 Version

I'm using the latest version

### 💻 Repository

blog-website

**Comment by Hermione2408** [comment]
closing with this PR - https://github.com/keploy/blog-website/pull/64
