### ISSUE TITLE
[feature]: Generate test-cases from API schema

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#24]
**Is your feature request related to a problem? Please describe.**
The API schema can be inferred to quickly generate test cases before encountering any traffic. 

**Describe the solution you'd like**
The solution should focus heavily on quality rather than quantity, i.e. it's better to have fewer generated tests than more noisy tests. 

**Describe alternatives you've considered**
Need research

**Additional context**
This can help onboard users faster too!

**Comment by slayerjain** [comment]
Had an interesting discussion on reddit. We need to ensure that we are able to confidently detect API contract drift on new code - https://www.reddit.com/r/softwaretesting/comments/sz9gag/jest_typescript_api_test_framework_example/hy6tlmw/?context=3

**Comment by slayerjain** [comment]
Uber eats had an issue where the Paytm API changed the error code and they interpreted it as success. While assuming success as the default case for unknown errors is definitely a problem. They could have detected the behavior change in the Paytm API if there was a proxy that could alert for changing API behavior.

**Comment by Sarthak160** [comment]
Already implemented in keploy's upcoming features 🤩
