### ISSUE TITLE
[bug]: two buttons at the top in the navbar are not aligned properly

### ISSUE THREAD

**Issue by ab7022** [keploy/keploy#2404]
### 👀 Is there an existing issue for this?

- [X] I have searched and didn't find similar issue

### 👍 Current behavior

![keploy added shadow](https://github.com/user-attachments/assets/f1e54942-25b7-4a14-9dbb-94529686c5aa)

### 👟 Steps to Replicate

signin and producthunt button

### 💻 Operating system

Linux

### 🎲 Version

i am using chrome browser

### 💻 Repository

website

**Comment by ab7022** [comment]
can this issue be assigned to me?

**Comment by rayAritra** [comment]
I  would like to work on this issue !!

**Comment by AravindAkuthota** [comment]
HEY @ab7022 I want to work on the issue.
