### ISSUE TITLE
[feature]: Install and run keploy binary during build to test keploy itself

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#243]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- As Keploy uses a test suite for testing keploy and getting **coverage %** in the github actions workflow .
-  Currently this is being possible by running another instance of keploy (Hosted somewhere in the cloud ) .
- Here `local:6789` keploy acts as client server app and hosted keploy acts as a Keploy server for `E2E test` generation .
- Since we have created **keploy binary** to get installed on linux/mac architecture and have **test export** feature as well 
- We have to make an action which will install the  **_latest_** **keploy binary** and run it on another port lets say `6790`. 
- App Config for keploy is configurable through environment variables , default values are set in `server/server.go` .

### Why should this be worked on?

- This will help contributors to record few tests if they have implemented any new feature for keploy without accessing API key for keploy server .
- Test suites can be managed through version control tools like git and can be stored in a common repository .

**Comment by ShivamTyagi12345** [comment]
Hey @Sarthak160  I am familiar with YAML,and have a basic understanding of creating a github action. Does this issue require us to do something similar where we would be creating new Github action that shall install keploy onto some host machine and then run it on new on a new port?

I would appreciate an initial approach to this good first issue to solve it

**Comment by Sarthak160** [comment]
Yes @ShivamTyagi12345 , we have to create an action to install and run keploy on a port and should give user privilage to set env variables as well
