### ISSUE TITLE
[feature]: Optimize "More Stories" Section to Show Blogs Based on Tags

### ISSUE THREAD

**Issue by Hermione2408** [keploy/keploy#2435]
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

The "More Stories" section currently displays all blogs, which significantly increases the page load time and doesn't provide a personalized experience for the user. Showing related blogs based on the tags associated with the current article to optimize load time and enhance relevance.

<img width="1428" alt="Screenshot 2024-11-20 at 3 44 48 PM" src="https://github.com/user-attachments/assets/d92c600e-8a65-4510-9477-d7147968e397">

**Proposed Solution**

- Fetch blogs with matching tags dynamically when the article is opened.
- Limit the number of blogs displayed in the "More Stories" section to improve load time and avoid clutter.

### 🎤 Why should this be worked on?

Reduces unnecessary load time caused by fetching all blogs.
Improves user experience by showing relevant content based on the article's tags.

### 💻 Repository

blog-website

**Comment by charankamarapu** [comment]
Please review the PR - https://github.com/keploy/blog-website/pull/67

**Comment by Hermione2408** [comment]
Closing this issue as the related PR has been merged
