### ISSUE TITLE
[bug]: Playground API Works Locally but Breaks in Production

### ISSUE THREAD

**Issue by Hermione2408** [keploy/keploy#2440]
### 👀 Is there an existing issue for this?

- [X] I have searched and didn't find similar issue

### 👍 Current behavior

The Playground API works seamlessly in the local environment but fails to function in the production environment. This issue might be related to differences in gitconfig or environment-specific configurations. Debugging and fixing the issue is required to ensure consistent behavior across environments.

<img width="1437" alt="Screenshot 2024-11-20 at 4 22 04 PM" src="https://github.com/user-attachments/assets/4d1f40e8-d510-496e-b612-c5ffd202534e">

### 👟 Steps to Replicate

Navigate to https://keploy.io/playground

### 💻 Operating system

MacOS

### 🎲 Version

latest 

### 💻 Repository

website

**Comment by gouravkrosx** [comment]
Playground is live: https://keploy.io/playground
