### ISSUE TITLE
[bug]: installation broken

### ISSUE THREAD

**Issue by swaroopar** [keploy/keploy#2448]
### 👀 Is there an existing issue for this?

- [X] I have searched and didn't find similar issue

### 👍 Current behavior

installation fails with error `Unsupported architecture: `

Issue occuring form this commit -> https://github.com/keploy/keploy/commit/bb31696df7053a85e957c67500df5190ed9f3c2f

ARCH variable assignment has been removed but it is referenced still in further lines

### 👟 Steps to Replicate

execute https://raw.githubusercontent.com/keploy/keploy/main/keploy.sh

### 💻 Operating system

Linux

### 🎲 Version

Latest version

### 💻 Repository

keploy

**Comment by charankamarapu** [comment]
Hey @swaroopar thanks for notifying us and coming up with RCA. I will raise a PR to fix this issue.

**Comment by charankamarapu** [comment]
The issue has been fixed please try again.
