### ISSUE TITLE
[feature]: Generate extra test cases from existing tests using Fuzz tests

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#25]
**Is your feature request related to a problem? Please describe.**
Fuzz testing can help generate extra test cases which could invoke different code paths. 

**Describe the solution you'd like**
Adding only such tests that invoke a unique different code path will ensure high-quality fuzz tests. 

**Describe alternatives you've considered**
Need research

**Additional context**
go test already supports fuzz testing natively. so it's becoming really popular.

**Comment by charankamarapu** [comment]
Automated test generation which is in the enterprise version already generates test cases in a fuzzy way. Closing this issue as the use case satisfied and proposed not to involve in open source version.
