### ISSUE TITLE
[bug]: Unable to denoise yaml for empty byte array

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to record testcase in yaml file, there is an error denoise request. The log shows: 
```
2022-12-14T14:51:44.355+0530    ERROR   regression/regression.go:387    EOF
go.keploy.io/server/pkg/service/regression.(*Regression).deNoiseYaml
       go-workspace/github.com/keploy/keploy/pkg/service/regression/regression.go:387
```

### Steps to reproduce

1. Run the keploy server. (test-export is true by default)
2. Run any go-sample app on record mode.
3. Make an API call to go-sample app.

### Environment

None

### Version

Local

**Comment by prommZ** [comment]
Hi , sir can i work on this ?

**Comment by nehagup** [comment]
@prommZ sure

**Comment by Octopops2442** [comment]
Hello, I tried recreating the issue but I was not getting the error. Is the issue fixed?

**Comment by charankamarapu** [comment]
Unable to replicated this issue in keploy v2 .
