### ISSUE TITLE
The server version printed during runtime should reflect the actual server version

### ISSUE THREAD

**Issue by thunderboltsid** [keploy/keploy#270]
https://github.com/keploy/keploy/blob/2b1d6a0536d73370f9c59b983f5fd9a94861b95f/cmd/server/main.go#L9

This is currently hardcoded as `v0.1.0-dev`
```
~ server-v0.7.8 run

       ▓██▓▄
    ▓▓▓▓██▓█▓▄
     ████████▓▒
          ▀▓▓███▄      ▄▄   ▄               ▌
         ▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
       ▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
      ▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
       ▓▌                           ▐█▌                   █▌
        ▓

keploy 0.1.0-dev

.2023-01-02T17:31:24.480+0100	INFO	server/server.go:215	keploy started at port 6789
```

This should ideally print `v0.7.8` when running with `v0.7.8`.

**Comment by slayerjain** [comment]
@thunderboltsid Thanks for pointing this out. This was supposed to be set goreleaser - https://goreleaser.com/cookbooks/using-main.version/?h=ldfla

I'm checking why this isn't working as expected.

**Comment by slayerjain** [comment]
@thunderboltsid the issue closed automatically because the PR was merged. Are you able to see the release version with the latest version of keploy?

**Comment by thunderboltsid** [comment]
> @thunderboltsid the issue closed automatically because the PR was merged. Are you able to see the release version with the latest version of keploy?

Nope; still same.
```
~ server-v0.7.9 run

       ▓██▓▄
    ▓▓▓▓██▓█▓▄
     ████████▓▒
          ▀▓▓███▄      ▄▄   ▄               ▌
         ▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
       ▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
      ▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
       ▓▌                           ▐█▌                   █▌
        ▓

keploy 0.1.0-dev

.2023-01-03T10:05:26.182+0100	INFO	server/server.go:214	keploy started at port 6789
```

**Comment by slayerjain** [comment]
how are you installing keploy?

**Comment by thunderboltsid** [comment]
`go install -tags tools "go.keploy.io/server/cmd/server@v0.7.9"`

**Comment by slayerjain** [comment]
Our GitHub pipeline uses `ldflags` to set the version variable. 

Would it be possible for you to set that during your go-install? (eg: `go install -ldflags="-X 'main.version=v0.7.9'" -tags tools go.keploy.io/server/cmd/server@v0.7.9`

**Comment by thunderboltsid** [comment]
> -ldflags="-X 'main.version=v0.7.9'"

For trying it out, sure:
```
go: 'main.version=v0.7.9': all arguments must refer to packages in the same module at the same version (@v0.7.9)
```
But, in general, the version should be populated in the repo itself as part of the release process.

**Comment by slayerjain** [comment]
Using ldflags to set the version during the build process is quite common in go projects. We need to find and implement a different method then.

**Comment by charankamarapu** [comment]
This has been taken care in keploy v2
