### ISSUE TITLE
[feature]: Implement filters for testcase capture

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#28]
**Is your feature request related to a problem? Please describe.**
We need the ability to filter test case capture by various fields such as URL, headers, etc.

**Describe the solution you'd like**
Provide a way to set filters in the SDK. 

**Describe alternatives you've considered**
Provide filters from UI instead. This could be something we do later due to the potential complexities involved. 

**Additional context**
We decided to add this urgently because we needed this to test keploy itself. We are interested in unit testing the keploy API which runs on `/url/*` space.

**Comment by petergeorgas** [comment]
Is this available?

**Comment by slayerjain** [comment]
Hi @petergeorgas, this one is being done here - https://github.com/keploy/go-sdk/issues/56
