### ISSUE TITLE
[bug]: Keploy server installation command failed.

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have tried to install Keploy using the following command
```

curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_darwin_all.tar.gz" | tar xz -C /tmp

sudo mv /tmp/keploy /usr/local/bin && keploy
```
Terminal is throwing :` zsh: command not found: keploy`

This is happening because usr/local/bin is not a directory

### Steps to reproduce

1. Make sure usr/local/bin is not a directory in the laptop else the command will run successfully.
2. run 
```
curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_darwin_all.tar.gz" | tar xz -C /tmp

sudo mv /tmp/keploy /usr/local/bin && keploy
```

### Environment

None

### Version

Local

**Comment by Kumar-Raajeev** [comment]
I would like to work in this issue , please assign me.

**Comment by nehagup** [comment]
@Kumar-Raajeev Sure.

**Comment by Kumar-Raajeev** [comment]
@nehagup can you explain the problem a till bit please.

**Comment by charankamarapu** [comment]
Hey @Kumar-Raajeev , if you observe the command we execute after installing keploy binary that is `sudo mv /tmp/keploy /usr/local/bin && keploy` , we are moving the binary from `/tmp/keploy` to   `/usr/local/bin` . In few systems there may be a possibility that the path `/usr/local/bin` is not present by default . Then it throws an error . We need to fix this . If that path is not present then we have create that folder path.

**Comment by Frey0-0** [comment]
Hello @nehagup I have made a PR for this issue [#154](https://github.com/keploy/docs/pull/154). Please review it and suggest changes :smiley:
