### ISSUE TITLE
[bug]: Keploy generated test cases for different applications are treated as test cases of a single applications according to the name of the tests

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When Keploy server is used with two different applications in record mode, the first application has recorded test-1.yaml , test-2.yaml and then if second application has recorded a test cases the name of the test case is given as test-3.yaml . Although the application is different, server is considering them as one application.

### Steps to reproduce

1. Run the sample applications of [Java-sdk](https://github.com/keploy/samples-java) and [Kelpoy](https://github.com/keploy/keploy#try-sample-application) one after the other keeping APP_NAME as default in Environment Variables.
2. Check the names of test cases generated in both the applications.

### Environment

None

### Version

Cloud

**Comment by re-Tick** [comment]
Hi **@charankamarapu**, did you used same APP_NAME for testing 2 different Apps? Since, Keploy server stores the Last-Index (of yaml test-case files) for different Apps.

One thing we can do is that we could store Last-Index according to the test-case path for yaml so that AppIds shouldn't have to be unique.

**Comment by charankamarapu** [comment]
Yes I have used the same APP_NAME. I think the approach you suggested will work.

**Comment by Frey0-0** [comment]
Hey, @charankamarapu @re-Tick I think I understand the issue, the APP_ID is not unique so there is wrong indexing of the test cases we should add a field like APP_PATH to the config right and the indexing should be done accordingly. I have forked the deploy server repo but I exactly can't find the location where these changes need to be done can you please just give me a hint or point me to the right directory for this? 
And also we will need to make changes to each SDK communicating with the server right?

**Comment by re-Tick** [comment]
Hi @Frey0-0, we are getting testcasePath and mockPath in PostTC handlers and testcasePath is unique for every project. 

Hence, we can use testcasePath field as key for our `tcsCount` map storing the lastIndex for yaml filename. The `tcsCount` map is present in testCase service [here](https://github.com/keploy/keploy/blob/ec2b1ff93b9c8ac9b9600063b281bfea0c5598d2/pkg/service/testCase/testCase.go#L257).

**Comment by Frey0-0** [comment]
@re-Tick I have linked a PR for this issue :) sorry it took a little time as I was trying to understand the codebase a bit. Please review it and suggest changes needed if any.

**Comment by Sarthak160** [comment]
This issue has been resolved in the newer code version , since different `test-sets` are recorded per user `record ` session  .
