### ISSUE TITLE
[chore]: write logger methods to reduce redundancy

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#304]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We can write logger methods to reduce unnecessary lines spend on logging and then return errors. Sanitization can also be done in this logger too. 

### Why should this be worked on?

These redundant lines are reducing our code coverage.

**Comment by rekram1-node** [comment]
Could I work on this?

**Comment by re-Tick** [comment]
Hi **@rekram1-node**, I have made changes for this in a PR. Sorry I have forgotten to assign it to myself.

**Comment by rekram1-node** [comment]
@re-Tick no worries thanks for the reply!

**Comment by slayerjain** [comment]
Hi @rekram1-node, would you be interested in working on a different issue? Maybe this - https://github.com/keploy/keploy/issues/303

**Comment by rekram1-node** [comment]
@slayerjain sure

**Comment by slayerjain** [comment]
@rekram1-node please feel free to discuss any queries :)

**Comment by Swpn0neel** [comment]
Is this still relevant? @slayerjain

**Comment by shivamsouravjha** [comment]
Loggers has been modified after the v2 refactor.
