### ISSUE TITLE
[docs]: TypeScript SDK Redirection Link update

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/keploy#316]
### Clicking on TypeScript SDK

![Screenshot from 2023-02-23 00-26-35](https://user-images.githubusercontent.com/74777863/220732640-183a0b79-59ca-41c0-88e5-3cf91285d761.png)
 
### Leads to 

https://github.com/keploy/keploy/issues/61

### Where is this stated?

- The Typescript SDK under `Resources and guides/SDKs Integration`  in [documentation](https://docs.keploy.io/) leads to an old issue of adding TypeScript SDK, which should rather be replaced with a link directing to [typescript documentation page](https://docs.keploy.io/docs/typescript/installation). 
- TypeScript SDK is now released and is no longer WIP. Therefore, that text need to be removed. 
- Change the order of presentation by putting TypeScript above Python in the list.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Contributor [Guides](https://github.com/keploy/keploy/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/keploy/keploy/blob/main/CODE_OF_CONDUCT.md)

rocketReferences: [Docs Repository](https://github.com/keploy/docs)
🙋🏾🙋🏼 Questions: [Discussion Forum](https://github.com/keploy/keploy/discussions) and [Community Slack](http://slack.keploy.com/)

**Comment by SayantaniDeb** [comment]
Please assign this issue to me

**Comment by SanskritiHarmukh** [comment]
@SayantaniDeb I've assigned you issue #319

**Comment by KrishChopra22** [comment]
Would like to fix this issue

**Comment by SanskritiHarmukh** [comment]
Sure. Assigning it to you @KrishChopra22 .
