### ISSUE TITLE
[docs]: Add new Video Reference for Contributing to Keploy SDK guide

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/keploy#318]
### What do you want to add to the docs? (please state reasons if any)

The [outdated video from contribution guide](https://docs.keploy.io/docs/devtools/sdk-contrib-guide/) need to be replaced by new one.

### Where is this stated?

The Contribution Guide contains `Contribute to Keploy SDK` page, which contains a video that gives a brief about core-concepts of Keploy. But the video is outdated. A [new video](https://youtu.be/Ssm4TnTkbLs) need to be linked that demonstrates Keploy according to latest release.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Contributor [Guides](https://github.com/keploy/keploy/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/keploy/keploy/blob/main/CODE_OF_CONDUCT.md)

🚀References: [Docs Repository](https://github.com/keploy/docs)
🙋🏾🙋🏼 Questions: [Discussion Forum](https://github.com/keploy/keploy/discussions) and [Community Slack](http://slack.keploy.com/)

**Comment by SayantaniDeb** [comment]
Can you assign me this issue?

**Comment by SanskritiHarmukh** [comment]
Sure. Assigning it to you.

**Comment by SayantaniDeb** [comment]
Please kindly review the changes.

**Comment by SanskritiHarmukh** [comment]
@SayantaniDeb closing the issue as the video that is present right now is much more detailed than the new one. Will see you resolving another issue.
