### ISSUE TITLE
[docs]: Add Keploy Student's Blog under Community section

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/keploy#319]
### What do you want to add to the docs? (please state reasons if any)

The ` Join the Keploy Community ` section has all the links that helps contributors understand Keploy and ask queries by joining the community.

![Screenshot from 2023-02-23 01-24-37](https://user-images.githubusercontent.com/74777863/220745256-71559b06-c002-4a79-9e48-1a5842465dda.png)

Blogs can also be a part of this section. 

### Where is this stated?

[Keploy Student's Blogs](https://keploy.hashnode.dev/) has a wide range of blogs that can help beginners understand API, Testing, Mocks and Keploy. The Community section thus should include Hashnode link too.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Contributor [Guides](https://github.com/keploy/keploy/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/keploy/keploy/blob/main/CODE_OF_CONDUCT.md)

References: [Docs Repository](https://github.com/keploy/docs)
🙋🏾🙋🏼 Questions: [Discussion Forum](https://github.com/keploy/keploy/discussions) and [Community Slack](http://slack.keploy.com/)

**Comment by Nayanika-12** [comment]
Please assign me this issue, I want to solve it.

**Comment by SanskritiHarmukh** [comment]
Hi @Nayanika-12, I have assigned you an issue. Let's complete that first.

**Comment by Nayanika-12** [comment]
Sure mam

**Comment by SayantaniDeb** [comment]
Can this task be assigned to me?

**Comment by SanskritiHarmukh** [comment]
Hi @SayantaniDeb , I have suggested an addition to your latest PR, please look into that, then we can proceed with this.

**Comment by SayantaniDeb** [comment]
Please kindly review the PR. 😅
