### ISSUE TITLE
[docs]: Next Button for Integration of Java SDK redirects to Go SDK Integration

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/keploy#321]
### What do you want to add to the docs? (please state reasons if any)

The link to next button for `Java SDK Integartion` in keploy server installation page need to be updated for Java.

### Where is this stated?

Right now, The next button in [Installation page under Java SDK](https://docs.keploy.io/docs/go/installation) redirects to [Go SDK Integration](https://docs.keploy.io/docs/go/integration) page instead of [Java SDK Integration](https://docs.keploy.io/docs/java/integration) page because both the section have same installation doc link.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Contributor [Guides](https://github.com/keploy/keploy/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/keploy/keploy/blob/main/CODE_OF_CONDUCT.md)

🚀References: [Docs Repository](https://github.com/keploy/docs)
🙋🏾🙋🏼 Questions: [Discussion Forum](https://github.com/keploy/keploy/discussions) and [Community Slack](http://slack.keploy.com/)

**Comment by aimbot1526** [comment]
Please Assign this to me.

**Comment by SanskritiHarmukh** [comment]
Sure, assigning it to you.

**Comment by iyear** [comment]
Hello! It looks like assignment has been removed, and I'm willing to work on this:)

**Comment by SanskritiHarmukh** [comment]
Assigning it to you @iyear .
