### ISSUE TITLE
[feature]: Add a link to Blogs at nav bar of keploy's website 

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/keploy#322]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Introduce a link at Nav Bar of [Keploy's Website](https://keploy.io/) for [Blogs](https://keploy.hashnode.dev/).

### Why should this be worked on?

Blogs are one essential part that must be included in Keploy's main website as it curates a list of blogs that can be helpful to beginners quickstart Keploy and concepts around.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Contributor [Guides](https://github.com/keploy/keploy/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/keploy/keploy/blob/main/CODE_OF_CONDUCT.md)

🚀References: [Website Repository](https://github.com/keploy/website)
🙋🏾🙋🏼 Questions: [Discussion Forum](https://github.com/keploy/keploy/discussions) and [Community Slack](http://slack.keploy.com/)

**Comment by Suman373** [comment]
I would like to work on this issue.

**Comment by SanskritiHarmukh** [comment]
Sure, assigning it to you

**Comment by Suman373** [comment]
> Sure, assigning it to you

I have opened a PR in that repo. Thank you !

**Comment by SanjeevSingh08** [comment]
I believe that a more precise and comprehensive explanation of the issue is necessary. @SanskritiHarmukh

**Comment by charankamarapu** [comment]
This issue has been resolved. Currently keploy website does have blog link.
