### ISSUE TITLE
[bug]: Align Home page icon at nav bar in Documentation

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/keploy#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The view box for home page on various documentation pages are not alligned properly, 

![Screenshot from 2023-02-25 22-41-03](https://user-images.githubusercontent.com/74777863/221370363-d206ff09-72ab-4509-92d1-b66a9ba27ca1.png)

### Steps to reproduce

1. Go to [Documentation website](https://docs.keploy.io/).
2. Navigate to any page, like [Contribution guide to keploy SDK](https://docs.keploy.io/docs/devtools/sdk-contrib-guide/).
3. Look at the nav bar.

### Environment

None

### Version

Cloud

**Comment by jeromtom** [comment]
Hi, I would like to work on this issue.

**Comment by chiragkhatri19** [comment]
Hey, Can I work on this Issue ?

**Comment by SanskritiHarmukh** [comment]
I'll assign the issue to @jeromtom. @chiragkhatri19 please have a look into other issues created at different repo.

**Comment by Saikat2407** [comment]
Hey, Can you assign this issue to me!

**Comment by jeromtom** [comment]
Issue solved, [PR ready to be merged ](https://github.com/keploy/docs/pull/142)

**Comment by jeromtom** [comment]
Close this issue as it is solved by #150
