### ISSUE TITLE
[bug]: DynamoDB and SQL driver appear twice under "Integrations/All" in Keploy website 

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/keploy#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we navigate to Integrations on the [website](https://keploy.io/), the DynamoDB and SQL driver supported frameworks are displayed twice, as for both golang and java these integrations are available. We can only show them once under `All` such that they are resopectively visible in Golang and Java too.

### Steps to reproduce

1. Go to [website](https://keploy.io/).
2. Navigate to `Integrations/All`.
3. You'll see the following.

![Integartions](https://user-images.githubusercontent.com/74777863/221373384-bea969a8-19e6-45db-a238-c0ef81cc9883.png)

### Environment

None

### Version

Cloud

**Comment by Ramanjs** [comment]
Hi! I want to work on this issue.

**Comment by aimbot1526** [comment]
@SanskritiHarmukh hello mam i added a new PR for this bug on keploy/website repo. Please let me know if I have to update anything.
