### ISSUE TITLE
[bug]: Warning for unresolved Docs markdown link while starting the development server

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/keploy#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I ran into a warning shown below, while testing commits made for [PR #140](https://github.com/keploy/docs/pull/140) . This might be because the link added is not in right markdown format on the contribution page.

![Screenshot from 2023-02-25 21-18-47](https://user-images.githubusercontent.com/74777863/221396168-4a4b610e-579a-4f6a-93b9-7dcb210fafd7.png)

### Steps to reproduce

1. Navigate to [docs repo](https://github.com/keploy/docs).
2. Fork, Clone and go to docs directory.
3. Start the development server with the necessary dependencies.

### Environment

None

### Version

Self-hosted

**Comment by Ramanjs** [comment]
I would like to work on this issue, please assign it to me.

**Comment by SanskritiHarmukh** [comment]
Sure, Assigning it to you @Ramanjs .
