### ISSUE TITLE
[bug]: 404 error

### ISSUE THREAD

**Issue by JasonDsouza212** [keploy/keploy#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- When we visit the [careers](https://keploy.io/careers) page, it should either show a 404 error or display the career page.
- However, it is currently displaying XML content, which is not an optimal way to handle 404 requests and is not recommended.

![Screenshot from 2023-03-01 18-06-05](https://user-images.githubusercontent.com/74404894/222166821-74b43075-a03a-4df7-a87f-42b4eb085d24.png)

### Steps to reproduce

go to
[careers](https://keploy.io/careers) 
If you try to access other non-existing pages, you will see the same type of result

### Environment

None

### Version

Cloud

**Comment by charankamarapu** [comment]
Issue is relevant as keploy v1 is no longer supported.
