### ISSUE TITLE
[feature]: beautify response diff viewer on CLI   

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#334]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently after running the test-cases the test-result shows the differences of the responses in the failing test cases which looks messy for a long response. This task is to improve that view of showing the differences in the responses on the CLI logs to make more readable. 

It's an open-ended task since differences can be shown in many different representations like git diff checker, diff checker, line by line etc.. 

Here's the current way: 

   
<img width="1132" alt="Screenshot 2023-03-02 at 4 34 36 PM" src="https://user-images.githubusercontent.com/15074229/222411748-f121217d-12fc-433c-ba1c-d80b9fa0ae90.png">

### Why should this be worked on?

To enhance the readability of failing test cases.

**Comment by Sukriti-m** [comment]
Hi @nehagup 
I want to work on this issue.
I'd be grateful if you could assign this issue to me.

**Comment by SanskritiHarmukh** [comment]
Hi @Sukriti-m , since this is a gsoc issue, it will not be assigned to anyone rather you can start working on it directly and raise a PR for the same. After creating a PR, add the PR ID to the task table under [the CLI Refactoring project](https://github.com/keploy/gsoc/tree/main/2023#1-keploy-cli-refactoring) corresponding to the issue.

**Comment by Sukriti-m** [comment]
> Hi @Sukriti-m , since this is a gsoc issue, it will not be assigned to anyone rather you can start working on it directly and raise a PR for the same. After creating a PR, add the PR ID to the task table under [the CLI Refactoring project](https://github.com/keploy/gsoc/tree/main/2023#1-keploy-cli-refactoring) corresponding to the issue.

Thanks for telling. I will start working on this issue then. 😊

**Comment by ADV1K** [comment]
How about putting the expected outcome and actual outcome inside a box?

https://github.com/Delta456/box-cli-maker

**Comment by SanskritiHarmukh** [comment]
@ADV1K totally on you how you wanna style and bring out the creativity.

**Comment by nehagup** [comment]
@achintya-7 we're open for both. However, the diff viewer in output logs is the main task.

**Comment by achintya-7** [comment]
Ok got it

**Comment by Sarthak160** [comment]
#492 has been accepted and merged in the main code base .
