### ISSUE TITLE
[feature]: Update Keploy UI with latest server APIs 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#335]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Keploy UI was not well-maintained recently and due to the increasing interest in UI, the UI needs to be updated (API contracts, schema usage and implementation). The codebase lies on keploy/ui repo. 

### Why should this be worked on?

Easy visualization with keploy console is in demand from users.

**Comment by SayantaniDeb** [comment]
Hey, can you please assign me this issue?

**Comment by SanskritiHarmukh** [comment]
Hey @SayantaniDeb , since this is a gsoc issue, it will not be assigned to anyone rather you can start working on it directly and raise a PR for the same. After creating a PR, add the PR ID to the task table under [the CLI Refactoring project](https://github.com/keploy/gsoc/tree/main/2023#1-keploy-cli-refactoring).

**Comment by SanskritiHarmukh** [comment]
@SayantaniDeb once you raise a PR, please wait for a review before you add the PR ID to the table.

**Comment by AdamJamiu** [comment]
Hello @nehagup. I am a GSoC contributor and i would love work on this issue. I would love to have more insight on it. please how can i get started. Thanks

**Comment by nehagup** [comment]
Hi @AdamJamiu Please let me know if you have any specific questions after running the UI locally with keploy server. The task description is mentioned above. Contribution Guide of the UI is [here](https://docs.keploy.io/docs/devtools/ui-contrib-guide)

**Comment by AdamJamiu** [comment]
after cloning this git clone https://github.com/keploy/keploy.git && cd keploy am i gonna clone https://github.com/keploy/ui.git && cd ui in the sub directory or am going to clone the UI into another dorectory entirely

**Comment by aerowisca** [comment]
@AdamJamiu In a different directory (to avoid polluting your git status).

**Comment by nehagup** [comment]
@AdamJamiu can you please tell me which node version are you using? I'm using `v18.11.0` and it's working fine for me.
