### ISSUE TITLE
[feature]: Shortlist ideas to generate testcases using api schema and response provided

### ISSUE THREAD

**Issue by PranshuSrivastava** [keploy/keploy#338]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

This needs to be a research based PR. This is in reference with [this issue](https://github.com/keploy/keploy/issues/24). You need to go through the various ways in which we can generate new testcases from the api schema and shortlist the best ones. Mention why you decided to choose it, and the limitations(if any) linked to that approach.

### Why should this be worked on?

This will help Keploy generate relevant testcases and improve the test coverage.

**Comment by kartikvirendrar** [comment]
Hello Mentors, I am interested to work on this issue.
Few ways to generate new testcases- 
1. Boundary Values Testing: testing API with inputs that are at boundary of allowed range, may be useful for identifying issues with input validation.
2. Random Testing: generating random inputs and testing over API, can explore unexpected behavior in API.
3. Combinational Testing: generating possible combinations of input parameters.
4. ML model: we can even generate ML model for test cases.

**Comment by nehagup** [comment]
More info on - https://github.com/keploy/keploy/pull/460#issuecomment-1471436224
