### ISSUE TITLE
[feature]: Add support for mocking jwt tokens

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#343]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

By adding support for mocking JWT tokens, It will allow developers to simulate the authentication flow and test their code without the need for actual tokens.

The feature can be subcategorized into the following components:

- A mechanism to capture time-based tokens like JWT and record the time for each token in a YAML file along with the test cases.
- Identify the methods that return the Time object used inside JSON Web Tokens (JWTs) and override them to return the recorded time during test mode.
- The ability to read the recorded time from the YAML file and mock the expired time to simulate the authentication flow during test mode.
- The implementation should use runtime ASM instrumentation libraries like ByteBuddy to minimize changes required in the user API.

### Why should this be worked on?

- By this, We will be able to mock the JWT tokens when recording test cases and will be able to replicate them during the test run.
- This will enhance mocking feature of keploy.

**Comment by reem-atalah** [comment]
If no one working on this, can I be assigned to this issue

**Comment by Sarthak160** [comment]
Yes @reem-atalah you can work on this issue .
