### ISSUE TITLE
[feature]: Add/Increase Test coverage for JAVA-SDK by adding unit tests  

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#348]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently the test coverage of JAVA-SDK is 0. We cannot use Keploy to create end to end test cases for SDK and increase coverage because SDK is a library not a server and SDK calls are invoked as method calls from filter rather than http/https calls. So the only way of increasing test coverage would be by adding unit tests.

Following modules from JAVA-SDK are preferred for Unit test coverage 

- [api](https://github.com/keploy/java-sdk/tree/main/api)
- [integrations](https://github.com/keploy/java-sdk/tree/main/integration)

### Why should this be worked on?

Test coverage is an important metric to calculate the code quality and performance. Test coverage for a code base should always be above 95%.

**Comment by yrs147** [comment]
I would like to work on this issue , please assign this to me

**Comment by charankamarapu** [comment]
This is a GSOC task - https://github.com/keploy/gsoc/tree/main/2023 . You can raise a PR and it will be reviewed, accepted but we cannot assign it to take particular member . At the end we will be selecting the best PR and merge it.

**Comment by yrs147** [comment]
thanks, got that

**Comment by Harsh4902** [comment]
@charankamarapu I am not going to take part in GSOC. Can I work on this issue?

**Comment by charankamarapu** [comment]
@Harsh4902 Yeah sure.
