### ISSUE TITLE
[feature]: Create a github action for publishing sdk to maven central 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#350]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Create a github action pipeline for publishing a multimodule project to maven central .
- Currently every release of java-sdk is performed via local environment .
- Build an action which will first run the `mvn clean install` , upadate the version `mvn versions:set -DnewVersion=N.N.N` and then make necessary changes to release the sdk to [maven central](https://search.maven.org/artifact/io.keploy/keploy-sdk) .

### Why should this be worked on?

To automate the releasing process for java-sdk

**Comment by charankamarapu** [comment]
Issue is relevant as keploy v1 is no more supported.
