### ISSUE TITLE
[feature]: start Keploy server from Typescript-SDK

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#352]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, we need to run Keploy binary and then run our application which is integrated with TS-SDK. 

 We can run the keploy binary from SDK and we don't have to see that whether the keploy binary is running or not.

### Why should this be worked on?

If Keploy binary is not running then,  error will be thrown on making API request on the application.

**Comment by Frey0-0** [comment]
Hey @re-Tick @Sonichigo, so in this issue we would be basically need to execute a bash command `keploy` before starting the node server so the user doesn't need to manually start the keploy server. Looking forward for your suggestions

**Comment by re-Tick** [comment]
@Frey0-0 yes you are correct. We have to start the keploy server from ts-sdk asynchronously along with the user application.

**Comment by Frey0-0** [comment]
For this issue, I am thinking to use spawn function of the child process library to run the `keploy` command before starting the app in the `record` mode checked using a basic if condition. How does this solution sound?

**Comment by Frey0-0** [comment]
I have made a PR [#62](https://github.com/keploy/typescript-sdk/pull/62) @re-Tick please check it out :)

**Comment by re-Tick** [comment]
Yes, you can discuss your changes and make your PR.

**Comment by charankamarapu** [comment]
Issue is irrelevant as keploy v1 is no more supported.
