### ISSUE TITLE
[test]: add unit tests for octokit module

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#354]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, there are no test written in ts-sdk. And since ts-sdk does not have a application server therefore, we need to write unit tests for code coverage. 

 Write a unit test for integrations/octokit module's [wrappedNodeFetch](https://github.com/keploy/typescript-sdk/blob/main/integrations/octokit/require.ts#L89) function. This will increase coverage for this module.

### Why should this be worked on?

There should be unit tests to check the behaviour of modules individually.

**Comment by Vikrant-Khedkar** [comment]
Hey where and how am i supposed to write this tests

**Comment by Hermione2408** [comment]
Hey @re-Tick I was thinking of using jest to write unit test cases for the function also do we need to add it in runtime script or build time script?

**Comment by re-Tick** [comment]
> Hey @re-Tick I was thinking of using jest to write unit test cases for the function also do we need to add it in build time script?

Yes, we can use jest for unit-test and we have to add a test job in github action

**Comment by re-Tick** [comment]
> Hey where and how am i supposed to write this tests

Unit tests have to be added for octokit module. You can use jest or motcha for writing unit tests.

**Comment by re-Tick** [comment]
The issue is open for all. You can propose your changes in a PR and mention this issue

**Comment by re-Tick** [comment]
The issue is open for all. You can propose your changes in a PR and mention this issue

**Comment by Sekhar-Kumar-Dash** [comment]
@re-Tick i have updated new files in typescript sdk please review it .i had to delete the last PR because of some coding mistakes

**Comment by VishalMyla** [comment]
@re-Tick Please review this [PR](https://github.com/keploy/typescript-sdk/pull/83)

**Comment by charankamarapu** [comment]
Closing the issue as we dont support sdks nay more.

**Comment by charankamarapu** [comment]
Closing the issue as we dont support sdks nay more.
