### ISSUE TITLE
[bug]: Unused dependencies should not be imported in application classpath.

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Whenever we add keploy java-sdk dependency in the pom.xml file of the client application, those dependencies which are not in the client's application and used by java-sdk to add support for but are not used internally get imported.

For eg: keploy java-sdk supports the mocking feature for ApacheClient, so it contains the ApacheClient dependency for intercepting. But if the client is not using this dependency, it should not appear in the application classpath but it does.

### Steps to reproduce

1. Clone keploy java-sdk.
2. Add any dependency in any of the its module.
3. Recompile java-sdk using `mvn clean install`.
4. Import it into any application by adding its jar.
5. You will see some dependencies which are not related to your application in your classpath.

### Environment

None

### Version

Local

**Comment by charankamarapu** [comment]
sdk approach is no more supported by keploy v2. Closing the issue as it is relevant.
