### ISSUE TITLE
[bug]: cp cmd in build script not working for windows

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to install the Typescript-SDK on windows, it fails due to unrecognisable "cp" cmd because "copy" is used for copying the files.
 Since there is no universal cmd for copy, We should not use that in build script. [Reference](https://stackoverflow.com/questions/55058002/universal-copy-command-for-windows-and-linux). We can include a common .proto file in the package.json's "files" field.

### Steps to reproduce

1. Try ts-sdk [installation](https://github.com/keploy/typescript-sdk#installation).

### Environment

None

### Version

Self-Hosted

**Comment by G0maa** [comment]
Might be a bit off-topic, but I'm interested in what does this `services.proto` file do?

**Comment by re-Tick** [comment]
hi @G0maa, proto file is used to generate js/ts files for implementing gRPC client calls to Keploy server.

**Comment by charankamarapu** [comment]
Issue is relevant as keploy v1 is no more supported.
