### ISSUE TITLE
[feature]: Convert Test run cards to Table with Filters

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#374]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, test runs can't be filtered by timestamp/app name etc. The goal here will be to convert test run cards to a table with pagination and filters. 

### Why should this be worked on?

The current cards structure is not scalable and filterable. Adding a table would bring consistency to the overall UI as well.

**Comment by karthiknadar1204** [comment]
@nehagup @AnkitKumarvaid If this issue is still up for grabs, I Would like to work on it

**Comment by nehagup** [comment]
@karthiknadar1204 this issue is stale now. Closing. Please pick another one. :)
