### ISSUE TITLE
bug: models.Type backward incompatibility

### ISSUE THREAD

**Issue by jiawchong** [keploy/keploy#379]
**Describe the bug**
In this PR: https://github.com/keploy/go-sdk/pull/148 
A new field: `Type` is used to differentiate between HTTP / GRPC request. 
Usage as shown:
1.  https://github.com/iamskp99/go-sdk/blob/25e6e5d78134f4fee94c4adf620d0481dc93a13c/keploy/utils.go#L228
2. https://github.com/iamskp99/go-sdk/blob/25e6e5d78134f4fee94c4adf620d0481dc93a13c/keploy/keploy.go#L451

This causes backward incompatibility for existing test cases captured and recorded in mongo, as those test cases were previously recorded without the field `Type`, which causes existing test case stored in Mongo retrieved through Keploy Server to contains empty string in Type. 
This result in fail test result caused by empty `bin` in this line https://github.com/iamskp99/go-sdk/blob/25e6e5d78134f4fee94c4adf620d0481dc93a13c/keploy/keploy.go#L492

**To Reproduce**
1. Install Keploy Docker image integrated with go-sdk before [v0.7.9](https://github.com/keploy/go-sdk/releases/tag/v0.7.9)
4. Import go-sdk lib before [v0.7.9](https://github.com/keploy/go-sdk/releases/tag/v0.7.9)
5. Run service integrated with Keploy and record some HTTP test cases
6. Upgrade go-sdk to v0.7.9
7. Run test run
8. Test run fail due to reason mentioned above

**Expected behavior**
Test run should still run successfully for existing test cases.
Existing test case without a `Type` field defined should default to models.HTTP

Reference: https://github.com/keploy/go-sdk/pull/148#discussion_r1097014745

**Comment by charankamarapu** [comment]
Keploy v1 is no more supported. Closing the issue as it is irrelevant now.
