### ISSUE TITLE
feat: need to log the keploy mode 

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#381]
**Is your feature request related to a problem? Please describe.**
Currently, the keploy mode variable is not logged. It can help notify users when keploy is recording, testing, or off and also brief them about the behavior of that mode.

**Describe the solution you'd like**
We need to log the keploy mode variable and also inform the user of the meaning of the mode and other available modes

**Describe alternatives you've considered**
NA

**Additional context**
This became a need because users where incorrectly setting the mode variable and it became difficult to actually understand if keploy was initialized to the right mode. These logs will help understand more about keploy.

**Comment by omgupta1608** [comment]
Has this been picked or I can pick it up (as my first contribution) ?

**Comment by charankamarapu** [comment]
Hi @omgupta1608 this issue has been resolved . You can find some other good first issue and work on it.

**Comment by charankamarapu** [comment]
Hi @omgupta1608 you can work on this [issue ](https://github.com/keploy/keploy/issues/474) if you are interested.
