### ISSUE TITLE
The mock recording feature fails to store mocks if request or response bodies have invalid utf-8 elements

### ISSUE THREAD

**Issue by thunderboltsid** [keploy/keploy#382]
```
2023-01-02T17:54:58.762+0100	ERROR	mock/utils.go:47	Failed to call the putMock method	{"error": "rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"}
```

PutMock fails if the body of the request or response has invalid UTF-8.

**To Reproduce**
Try recording an API response that has non-utf-8 chars (binary encoding, etc.) and you will see `Invoke` method fail due to a protobuf marshalling error.

This happens inside the `Invoke` call stack when `prepareMsg` calls `encode` and the encoding fails due to body having invalid UTF-8 runes.
```go
func (c *regressionServiceClient) PutMock(ctx context.Context, in *PutMockReq, opts ...grpc.CallOption) (*PutMockResp, error) {
	out := new(PutMockResp)
	err := c.cc.Invoke(ctx, "/services.RegressionService/PutMock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
```

**Expected behavior**
I expect Keploy to handle it gracefully instead of throwing a Protobuf marshaling error

**Comment by charankamarapu** [comment]
This has been taken care in keploy v2.
