### ISSUE TITLE
feat: separate go mods for integration packages

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#383]
**Is your feature request related to a problem? Please describe.**
We need to separate integration packages into their own go mod files because unused integrations can be imported into the go.sum files of user projects which can cause potential build failures. 

**Describe the solution you'd like**
We need to have separate go.mod files for integration packages. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by charankamarapu** [comment]
This issue is related to keploy v1 and it is not relevant as keploy v2 as been lanuched,
