### ISSUE TITLE
feat: register sql driver automatically

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#385]
**Is your feature request related to a problem? Please describe.**
Currently, to register the SQL driver the user needs to wrap explicitly the host driver (eg: Postgres) and then register Keploy's driver. I feel this can be automated.  

**Describe the solution you'd like**
Maybe we can use the init block to automatically wrap the drivers instead of making explicitly do so. 

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by Sarthak160** [comment]
This issue is no longer needed since we migrated to V2 which has newer code structure .
