### ISSUE TITLE
Capture code coverage for tests

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#386]
**Is your feature request related to a problem? Please describe.**
Capturing code coverage can be an important metric to understand the effectiveness of tests. 

**Describe the solution you'd like**
Ideally, code coverage should be measured automatically after running a test. 

**Describe alternatives you've considered**
N/A

**Additional context**
This is complementary to the native go test integration feature keploy/go-sdk#29

**Comment by Sarthak160** [comment]
Keploy Go SDK has native go-test support which will log the coverage of the user application .
