### ISSUE TITLE
Make the console more dynamic

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#389]
**Is your feature request related to a problem? Please describe.**
The current console for testing can be made more dynamic. Its plain and boring for now

**Describe the solution you'd like**
We could add progress bars and leaders like https://github.com/gosuri/uiprogress

**Describe alternatives you've considered**
Utilizing features from uber zap to improve the experience.

**Additional context**
NA

**Comment by charankamarapu** [comment]
Closing this issue as we have already integrated with uber.zap with keploy v2 to make logs and cli dynamic.
