### ISSUE TITLE
[feature]: need to log the keploy mode

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#390]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, the keploy mode variable is not logged. It can help notify users when keploy is recording, testing, or off and also brief them about the behavior of that mode.

### Why should this be worked on?

This became a need because users where incorrectly setting the mode variable and it became difficult to actually understand if keploy was initialized to the right mode. These logs will help understand more about keploy.

**Comment by VishalMyla** [comment]
@re-Tick  Please review the PR [#390](https://github.com/keploy/typescript-sdk/pull/85)

**Comment by ashwintelmore** [comment]
should i work on this issue

**Comment by re-Tick** [comment]
Hi @ashwintelmore, people have contributed for this issue. As we have discussed [here](https://keploy.slack.com/archives/C035URHSGDQ/p1689526900437459)

**Comment by charankamarapu** [comment]
This issue has been taken care in keploy v2.
