### ISSUE TITLE
feat: implement the ability to set conf through env variables

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#394]
**Is your feature request related to a problem? Please describe.**
It can become hard to change keploy config in pipelines or other environments unless the host application provides envs to set config. 

**Describe the solution you'd like**
We can provide ability to optimally set config as env variables. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gouravkrosx** [comment]
Closing this issue as SDK's are obsolete now.
