### ISSUE TITLE
[feature]: add a filter for request header fields

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#395]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, when an API request is captured then its authorisation headers are also captured which could be private for users. 
 There should be a way to remove these specified key-value pair from the request-response headers. Recently changes have been made for this in keploy server and go-sdk. In PostTC gRPC call there is a Remove string array which is used to filter the request-response header

### Why should this be worked on?

Since the header fields can contain user specific data so there must be a way to filter them.

**Comment by charankamarapu** [comment]
This has been taken care in keploy v2.
