### ISSUE TITLE
[feature]: integrate a logging framework for more informative logs

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#397]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, console.log is being used for logging errors and info to the terminal. Integrate frameworks like winston for more comprehensive logs to debug easily. Here is a [blog post](https://sematext.com/blog/node-js-logging/).

### Why should this be worked on?

Good logging frameworks will provide with more structured and informative logs to debug easily.

**Comment by charankamarapu** [comment]
Closing the issue because this issue belongs to keploy v1 and stopped supporting keploy v1.
