### ISSUE TITLE
adds support for mongo EstimatedDocumentCount(), Watch(), BulkWrite() methods 

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#398]
**Describe the solution you'd like**
Mock the methods on mongo collection to capture the output of operations.

**Describe alternatives you've considered**
Considered to use other mongo supported method for keploy integerations

**Comment by Sarthak160** [comment]
This issue is outdated as now keploy now supports mocking of mongoDb at the network level rather than overriding the interface methods of different clients . Check out the newly released keploy V2 for seamless integration .
