### ISSUE TITLE
Add Support for gofmt package for formatting!

### ISSUE THREAD

**Issue by khanjasir90** [keploy/keploy#404]
**Is your feature request related to a problem? Please describe.**
The current codebase doesn't have support for formatting of codebase through gofmt package.

**Describe the solution you'd like**
Adding gofmt package will have uniformly formatted codebase

**Describe alternatives you've considered**

**Additional context**

**Comment by gouravkrosx** [comment]
closed by https://github.com/keploy/keploy/issues/1216
