### ISSUE TITLE
Separation can be added to look good

### ISSUE THREAD

**Issue by SoumyadeepOSD** [keploy/keploy#405]
![image](https://user-images.githubusercontent.com/115442240/222470373-c74d21de-9c54-4a2b-98b9-107d433ab52d.png)

### Between the main content and right side content menu bar there can be added different background color so that separation can be understood

**Comment by SoumyadeepOSD** [comment]
@AnkitKumarvaid  Can I work on it?

**Comment by nehagup** [comment]
@SoumyadeepOSD can you please propose a sketch/design first?

**Comment by SoumyadeepOSD** [comment]
> @SoumyadeepOSD can you please propose a sketch/design first?

@nehagup 

I'm talking about like this👇

![keploy_pic](https://user-images.githubusercontent.com/115442240/222922649-d5d52373-02b2-47b2-bb04-205d2261f33b.png)

**Comment by Arpcoder** [comment]
![design](https://user-images.githubusercontent.com/100352419/222938752-90a2e35c-e09f-47b0-b4ee-14b5fd6ce615.png)
@nehagup please have a look at this design.

**Comment by Shaurya-Developer** [comment]
Can I work on this issue?

**Comment by infoparth** [comment]
Can you assign me this issue to work on?

**Comment by nehagup** [comment]
According to an analysis on the anonymous user-traffic sessions captured users are able to navigate through the sidebar as well as the content menu, hence, marking this issue closed.
