### ISSUE TITLE
Duplicate Footer in a single page

### ISSUE THREAD

**Issue by SoumyadeepOSD** [keploy/keploy#406]
![image](https://user-images.githubusercontent.com/115442240/222467854-2b610fbc-08b1-43d1-9ad0-3e929e621a9d.png)

![image](https://user-images.githubusercontent.com/115442240/222467952-9564a145-ef57-4872-a645-fc222a00a3ac.png)

## You can see that two footer section of same type in a single page has been appeared twice. It's need to be fixed, can you please assign me this issue, so that I can work on it?

**Comment by SoumyadeepOSD** [comment]
@AnkitKumarvaid can I work on it?

**Comment by SanskritiHarmukh** [comment]
Hi @SoumyadeepOSD a similar issue already exists [#320](https://github.com/keploy/keploy/issues/320) and it was created before this one. Can you close this issue?
