### ISSUE TITLE
[feature]: CI for prettyfying code 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#407]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Research and add something like this
https://github.com/keploy/docs/blob/6d5a315d184d8c95dfe4da89804466f712a5c595/.github/workflows/autoformat.yml 

### Why should this be worked on?

 https://github.com/keploy/docs/blob/6d5a315d184d8c95dfe4da89804466f712a5c595/.github/workflows/autoformat.yml

**Comment by AkashKumar7902** [comment]
Hey @nehagup
Please close this issue
