### ISSUE TITLE
[bug]: DCO commit message check should apply only for custom commit not for auto down merge from stable branch

### ISSUE THREAD

**Issue by dinesh-07** [keploy/keploy#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When we do changes and try to push, git asks us to down merge from the main branch and this adds a commit which doesn't follow DCO so we get an error after our PRan 

### Steps to reproduce

1. Do changes
2. Commit
3. Push

### Version

Self-hosted

**Comment by charankamarapu** [comment]
Issue has been resolved closing the issue.
