### ISSUE TITLE
[ Documentation request ] : Remove Installation Method from Sample Java Docs  

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#410]
# Brief description

Since Installation Guide is already present here:- https://docs.keploy.io/docs/server/introduction/ . 
Instead of having same steps a link could be added to redirect the users towards the `Installation Method Documentation`

#  Your recommended content

## Current Scenario
![image](https://user-images.githubusercontent.com/53110238/211976543-11e945e4-3a66-4f64-8acb-839c2e9a9004.png)

## Preferred output.

![image](https://user-images.githubusercontent.com/53110238/211740931-3ce8ac35-0628-4683-acb9-6c0e9d1e0cc4.png)

Reference Resource:- 
- https://docs.keploy.io/docs/go/quickstart/run-your-first-app-tutorial

**Comment by mukul314** [comment]
Is the work on this issue done? Or is it still open?

**Comment by Sonichigo** [comment]
Hey @mukul314 this issue is done!!

**Comment by nehagup** [comment]
@Sonichigo @mukul314 the issue has been resolved during the recent refactoring of docs. Example https://docs.keploy.io/docs/java/quickstart/spring-sql

**Comment by nehagup** [comment]
``
