### ISSUE TITLE
[bug]: gitpod.yml run error

### ISSUE THREAD

**Issue by Ananya2001-an** [keploy/keploy#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

**Problem**
So on opening a new workspace for samples-go, the gitpod.yml file builds the app but for some reason the "init" command for 'docker compose up -d' was giving an error. It started the keploy server successfully but was failing at running the docker service. 

**Solution**
I made changes to the file by moving the docker command to "command" section and it worked nicely without any errors. 

**Screenshot**
Initially
![-gitpod-yml-samples-go-Gitpod-Code](https://user-images.githubusercontent.com/55504616/222730063-c5b7b49b-4164-4e96-ab5a-83d5341db43c.png)

after fixing gitpod.yml file
![-gitpod-yml-samples-go-Gitpod-Codegfgg](https://user-images.githubusercontent.com/55504616/222730122-288fb1b0-bc78-45d3-8b01-dede003d1bb9.png)

  

### Steps to reproduce

1. open samples-go in a new workspace in gitpod
2. observe the terminal for "echo-sql-sample-application task"

### Environment

None

### Version

Cloud

**Comment by charankamarapu** [comment]
Issue is irrelevant as keploy v1 is no more supported.
