### ISSUE TITLE
[feature]:  Create a sample application and add go-fuzzing to it.

### ISSUE THREAD

**Issue by PranshuSrivastava** [keploy/keploy#413]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Create a sample go api and integrate Keploy with it. 
Then, go through [Go-fuzzing](https://go.dev/security/fuzz/) and try to implement it in your app.

### Why should this be worked on?

Fuzzing is a very powerful concept in go and can be used to increase the coverage and find bugs. This will improve the level of Keploy's test generation and help it give more valuable information to the user.

**Comment by nehagup** [comment]
@avikkundu since this is a gsoc issue, it will not be assigned to anyone rather you can start working on it directly and raise a PR for the same. After creating a PR, add the PR ID to the task table under your project corresponding to the issue.

FYI @PranshuSrivastava

**Comment by chiggshiggs** [comment]
I coded up a rest api using gin-gonic router and mongo db in backend, i am facing the following error at the time of integrating keploy.
![Screenshot from 2023-03-06 19-58-36](https://user-images.githubusercontent.com/96922117/223139804-6e02c873-f201-46d2-b630-d6d542dc93ab.png)

**Comment by chiggshiggs** [comment]
First and third task listed in the Autogenerate test cases section redirect to the same issue #413, according to task list , first task is simply creating a rest api in go connected to a database. Please clarify!

**Comment by JammUtkarsh** [comment]
I guess this is not going to be merged. So the obvious question is where do I need to create this application, in order to make a PR?

**Comment by PranshuSrivastava** [comment]
Hey @JammUtkarsh you need to create the PR in the samples-go repo. It contains sample go applications with keploy integration.

**Comment by kartikvirendrar** [comment]
Hello @PranshuSrivastava I have created a [PR](https://github.com/keploy/samples-go/pull/49) in samples-go repository for go fuzzing can you please review once

**Comment by tanghaowillow** [comment]
@PranshuSrivastava Hi, would you mind review this? https://github.com/keploy/samples-go/pull/61

**Comment by PranshuSrivastava** [comment]
Sure @tanghaowillow
