### ISSUE TITLE
[docs]: update the sample application readme in reference with docs

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#416]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

the readme of the sample application 'gin-mongo' is outdated - https://github.com/keploy/samples-go/tree/main/gin-mongo

To update - refer the documentation here - https://docs.keploy.io/docs/go/quickstart/gin-mongo-quickstart

### Why should this be worked on?

updation of the readme is required for users.

**Comment by himanshu1221** [comment]
Hey @nehagup the updated link you mentioned above ` https://docs.keploy.io/docs/go/quickstart/gin-mongo-quickstart` is redirecting to the following page if you provide the fix link I will submit a PR regarding the same 

![Screenshot from 2023-03-12 07-52-49](https://user-images.githubusercontent.com/32031706/224520753-a41ad09f-3348-4222-bdfb-9120e04021bf.png)

**Comment by nehagup** [comment]
@himanshu1221 you can use https://docs.keploy.io/docs/go/quickstart/gin-mongo

**Comment by himanshu1221** [comment]
thanks for the URL i will surely make a PR

**Comment by nakulbh** [comment]
@nehagup is this issue still open ? .. I would like to work on it

**Comment by nehagup** [comment]
Hi @nakulbh this has been deprecated now, since the docs website has a new version of docs.
