### ISSUE TITLE
[feature]: add a sample showing ent support

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#417]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Having support for ent could help reach more potential users. https://github.com/ent/ent

### Why should this be worked on?

There's a request to have this example in the discussions forum. 

https://github.com/keploy/keploy/discussions/130

**Comment by Sekhar-Kumar-Dash** [comment]
@slayerjain please review this PR
