### ISSUE TITLE
[docs]: update the sample application readme in reference with docs

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

the readme of the sample application 'echo-sql' is outdated. https://github.com/keploy/samples-go/tree/main/gin-mongo

To update - refer the documentation here - https://docs.keploy.io/docs/go/quickstart/run-your-first-app-tutorial 

### Steps to reproduce

NA

### Environment

Production

### Version

Local

**Comment by Sekhar-Kumar-Dash** [comment]
@nehagup  the link you provided is not working 
this one https://docs.keploy.io/docs/go/quickstart/run-your-first-app-tutorial

**Comment by nehagup** [comment]
@Sekhar-Kumar-Dash thanks for reporting, the updated link is - https://docs.keploy.io/docs/go/quickstart/echo-sql

**Comment by charankamarapu** [comment]
This issue is resolved as readMe of gin-mongo is updated.
