### ISSUE TITLE
[feature]: Add a User Object template  to /users-profile readme

### ISSUE THREAD

**Issue by ShivamTyagi12345** [keploy/keploy#419]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Adding an object template will be helpful for beginners when setting up `[samples-go](https://github.com/keploy/samples-go)/users-profile/` 

![image](https://user-images.githubusercontent.com/60812924/193093727-9d9aff19-2113-4489-bebb-22e036027164.png)

### Why should this be worked on?

Folks new to this repo will have to copy-paste the object and not create the whole object

**Comment by charankamarapu** [comment]
The PR is merged and issue is resolved.
