### ISSUE TITLE
[feature]: add mysql based sample app with fasthttp

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#421]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We should have a sample app that uses MySQL since it's a very popular database. We could also use a different router for this like [fasthttp](https://github.com/valyala/fasthttp). 

### Why should this be worked on?

MySQL is a very popular open-source database. Although keploy has a generic `database/sql` integration, showing more examples apart from just Postgres will help users better understand broader usage of keploy `database/sql` integration.

**Comment by JammUtkarsh** [comment]
Hey @slayerjain, I though of working on this using kfasthttp, but I could not find any documentation regarding the same. Then looked into the [integrations](https://github.com/keploy/go-sdk/tree/main/integrations/kfasthttp) of fasthttp in [go-sdk](https://github.com/keploy/go-sdk/). Here I found a file, I wonder if it's the implementation is compeleted or not?

**Comment by slayerjain** [comment]
@JammUtkarsh were you able to use the `fasthttp` integration?

**Comment by JammUtkarsh** [comment]
Yeah, I was able to integrate with it for now, it seems to be working fine.

**Comment by JammUtkarsh** [comment]
Follow up from this [comment](https://github.com/keploy/samples-go/pull/43#issuecomment-1793359651).

I got to know that there are two things in keploy
1. E2E testing using (language agnostic binary) keploy
2. Generate unit-test stubs using the go-sdk.

So, which method do I need to use?

cc: @nehagup

**Comment by nehagup** [comment]
@JammUtkarsh when you integrate and run keploy v2, you'll be able to generate both tests and stubs by making API calls to your fasthttp application. You simply need to generate some tests n mocks and see if those are working fine with fasthttp and then, document the same.

**Comment by gouravkrosx** [comment]
We have [postgres](https://github.com/keploy/samples-go/tree/main/mux-mysql) example with fasthttp & mysql example with [mux](https://github.com/keploy/samples-go/tree/main/mux-mysql). Contributors can take reference from this to make MySQL example with fasthttp.
