### ISSUE TITLE
[feature]: add an sample showing mocking capability

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#422]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Keploy now has a dedicated library which enables capturing external dependencies (API calls, DB queries..) and replaying during any test suite. We should create a sample which shows how to use it with any other testing framework. 

### Why should this be worked on?

It'll help users who don't want to use keploy' testing capabilities to leverage Keploy only for dependency mocking. Eg: sdk or library developers.

**Comment by Sekhar-Kumar-Dash** [comment]
can someone please review my PR

**Comment by charankamarapu** [comment]
Currently mocking feature examples are present in the readme of all the sdks. Closing the issue.
