### ISSUE TITLE
[feature]: Creating Sample Java Application using JWT Token

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#424]
Knowing how time based tokens like jwt and sessions work . 
And creating sample java application using jwt token authentication can be a good first issue!

**Comment by gouravkrosx** [comment]
Closing this issue as SDK's are obsolete.

**Comment by gouravkrosx** [comment]
@Sonichigo Do we have any JWT Token-based sample java app? or should I close this issue?

**Comment by Sonichigo** [comment]
hey @gouravkrosx no we don't have any JWT token based app yet in samples-java! This can be closed, since no PR was merged. @Swpn0neel can you create a fresh issue for the same ?
