### ISSUE TITLE
[feature]: add a sample Java EE application application to show case keploy integration

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#426]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

As mentioned above we do not have a sample api to demonstrate keploy's ETE and mocking functionality with older java versions and frameworks other than spring .
It would be nice to have with frameworks like Jersey

### Why should this be worked on?

It should be work on so that user experience for non spring applications get better as Keploy java sdk has support for that as well .

**Comment by charankamarapu** [comment]
This sample app is not needed as any java project now can be used with keploy v2. Now sample apps mostly differ with language and databases.
