### ISSUE TITLE
[docs]: Structuring the Installation Methods 

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#427]
### Brief Description

The Installation Process method should be based on the Reader's choice of their OS architecture. The two sections can be converted into ``expand`` mode by using the ``<details></details>`` tags, and also windows option is need to be added as well.

### Acceptable Outputs
1. Adding Methods
![image](https://user-images.githubusercontent.com/53110238/211803532-5c90481e-05d7-4e80-a5d2-9ca59df36b0b.png)

**Comment by sahilrajput18** [comment]
Hey there 
Is this issue still open? i would like to contribute!

**Comment by Sonichigo** [comment]
Hey @sahilrajput18 , unfortunately the PR is already made for this issue and would be merged soon : / 
You can take look at the other [good first issues](https://github.com/keploy/keploy/labels/good%20first%20issue) !!

**Comment by JammUtkarsh** [comment]
Hey, I was wondering why haven’t we implemented a simpler method like 
- For users with Go installed `go install {URI}` 
- using a package manager like `brew`, `apt`, `yum`, etc
- Or add a script like `install.sh`. Like tea uses [here](https://github.com/teaxyz/cli#getting-started).

It will result in a smoother developer experience.
