### ISSUE TITLE
add a sample unit test for mocking/stubbing calls in unit-tests

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#428]
It will be good to have a sample unit-tests for the "mocking/stubbing external calls from unit-tests" feature. 

 Add a directory containing the unit tests integrated with [keploy/typescript-sdk](https://github.com/keploy/typescript-sdk#how-to-use-mock-library) for stubbing and capturing the external calls.

**Comment by re-Tick** [comment]
Hi @kartikvirendrar, keploy can generate mock/stub yamls for the external dependency call triggered from unit-tests. [Reference](https://github.com/keploy/typescript-sdk#how-to-use-mock-library)

 This issue is to add a sample for unit-test which will record/replay those node-fetch mock yamls

**Comment by VishalMyla** [comment]
@re-Tick Can you review my [PR](https://github.com/keploy/samples-typescript/pull/17)

**Comment by VishalMyla** [comment]
I have resolved the issue please review [PR](https://github.com/keploy/samples-typescript/pull/17)

**Comment by gouravkrosx** [comment]
Closing this issue as SDK's are obsolete now.
