### ISSUE TITLE
[feature]: Add support for mocking mongoose operations

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#429]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Please add support for mongoose integration to mock the external dependency calls.

### Why should this be worked on?

mongoose is a popular npm package used for schema validation of MongoDB at application level. This will help mocking the dependency calls from router API handler.

**Comment by Frey0-0** [comment]
Hey @re-Tick is this issue still open? I see a PR linked by you so does that mean it is done?
