### ISSUE TITLE
[bug]: ts-sdk records keploy-testcase even on test mode

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

 When, I run the application on test mode, and do an API call on endpoint then this will record testcases. 

 Ideally it should just return the responses and not record Keploy-testcases on test mode.

### Steps to reproduce

1. Run the self-hosted Keploy server. Follow the [Quick installation](https://github.com/keploy/keploy#quick-installation) guide
2. Integrate ts-sdk or use the [sample-typescript ](https://github.com/keploy/samples-typescript/tree/main/node-fetch)application.
3. Run the application on test mode.
4. Do an API call on the endpoint of running application.
5. A Keploy-testcase is generated

### Environment

None

### Version

Cloud

**Comment by Frey0-0** [comment]
Hey @re-Tick is this still open? If yes I would like to complete it.

**Comment by Frey0-0** [comment]
Hey @re-Tick is this still open? If yes I would like to complete it.

**Comment by re-Tick** [comment]
There is a PR opened for this. You can discuss those changes and can propose your changes.

**Comment by Frey0-0** [comment]
I have linked a PR for this issue. Please review it @re-Tick :sparkles:

**Comment by VishalMyla** [comment]
@re-Tick Please review this [PR](https://github.com/keploy/typescript-sdk/pull/84)
