### ISSUE TITLE
[feature]: add schema checks in keploy assertions logic

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#431]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be great to have schema checks in keploy's assertion logic. This task can be done in 2 parts

1. We can first write logic to detect and log schema changes. 
2. Then we can add schema checks to Keploy's custom assertions. This can enable users to only check a particular fields schema rather than the actual value.  

### Why should this be worked on?

There are many situations where the actual value is irrelevant, but the data type check is important. This can enable keploy to detect such issues.

**Comment by kartikvirendrar** [comment]
Hello Mentors, I am interested to work on this issue can I please get some more details.

**Comment by ItsRoy69** [comment]
Hey @kartikvirendrar, thanks for showing interest in working on this issue. This is an evaluation task for gsoc, it will not be assigned to anyone rather you can start working on it directly and make a PR, just make a README file explaining all the approaches that just talked about, and then link that PR in the table here https://github.com/keploy/gsoc/tree/main/2023. After that, we will evaluate your PR for GSoC.

**Comment by slayerjain** [comment]
Hi @kartikvirendrar, can you please specify which part to clarify?

**Comment by slayerjain** [comment]
Hi @JammUtkarsh , The assertion logic currently is in the test method here: https://github.com/keploy/keploy/blob/37a16a4e1dcbb03a0038625cc6479458e2dab5c1/pkg/service/regression/regression.go#L121

It takes the noisy fields into account and then compares different fields like http headers and body (also handles json bodies separately to handle the keys). We could add additional logic to test schema differences and then maybe hook here. 

The goal is to log if there's a breaking schema change. For eg lets say you were expecting the response of a test case to be:
```json
{
  "foo": "bar"
}
```

and but instead you get: 

```json
{
  "foo": 10
}
```

Then we should highlight that there was a schema change. The field was expected to be a `string` but now we got a `number`

**Comment by JammUtkarsh** [comment]
Hey @slayerjain, just to be clear that I am heading the right direction.

The `pkg.Match()` removes the noisy fields from the bodies(expected and actual) and returns clean bodies here: https://github.com/keploy/keploy/blob/37a16a4e1dcbb03a0038625cc6479458e2dab5c1/pkg/service/regression/regression.go#L194-L203

So, I should be parsing `cleanExp` and `cleanAct` for change in data type. Right?

Also, can you explain what is `pkg.Contains()` doing?

**Comment by aerowisca** [comment]
@JammUtkarsh  `pkg.Contains()` is a simple utility function which checks whether a particular element exists in slice. See [here](https://github.com/keploy/keploy/blob/37a16a4e1dcbb03a0038625cc6479458e2dab5c1/pkg/utils.go#L273). 

From what I could infer, it's checking whether the entire body is labelled as noise. (`tc.Noise` is basically a slice containing the key of all noisy fields). If it's not, and the body is indeed a JSON object, we move on to the next stage).

Detecting schema changes for non noisy fields should be a good starting point for now. (Technically you CAN try to check schema of noisy fields, like timestamp changing to strings, but the first one should be a priority).

**Comment by JammUtkarsh** [comment]
Can this issue be officaly assigned to me?

**Comment by tomtastico** [comment]
This would be great to have! Would make keploy much more useful as a general test system. @JammUtkarsh did you manage to advance on it after all?

**Comment by JammUtkarsh** [comment]
Hello @tomtastico, no, I couldn't work on it. You can work on it if you'd like.
