### ISSUE TITLE
[feature]: Generate OpenAPI schema from API calls/ Testcases

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#432]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be nice to generate OpenAPI schema from API calls. The schema can be used for multiple use cases such as contract testing.  

### Why should this be worked on?

Many developers skip API schema generation to save time. The schema can be very useful to understand the changes and interfaces of an API.

**Comment by kartikvirendrar** [comment]
Hello @slayerjain, I am interested to work on this issue, I am supposed to create a application in GO that generates openAPI schema for API and export this schema in JSON or YAML is this correct?

**Comment by kartikvirendrar** [comment]
Postman has an API for generating OpenAPI schema can we use that

**Comment by nehagup** [comment]
@kartikvirendrar feel free to use any open-source library. 



> Hello @slayerjain, I am interested to work on this issue, I am supposed to create a application in GO that generates openAPI schema for API and export this schema in JSON or YAML is this correct?

Yes the understanding is correct.

**Comment by kartikvirendrar** [comment]
Ok got it

**Comment by kartikvirendrar** [comment]
I wrote a sample code for generating openAPI schema: [openApiSchema.go](https://github.com/kartikvirendrar/keploy/blob/main/generateOpenAPISchema/openApiSchema.go) which returns output: [openapi_schema.yaml](https://github.com/kartikvirendrar/keploy/blob/main/generateOpenAPISchema/openapi_schema.yaml) can you please check once

**Comment by slayerjain** [comment]
@kartikvirendrar Thanks for sharing the sample code and this is a good attempt. This is the schema that was generated when I ran your sample. 

```
openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /India:
    get:
      description: Get universities in India
      responses:
        "200":
          description: Successful response
  /United+States:
    get:
      description: Get universities in United+States
      responses:
        "200":
          description: Successful response
```

1.  The schema doesn't have the field types of the response. 
2. You won't know the data structure of the API request or response. Keploy would have to look at the recorded requests and responses and then figure out the data structure to generate the data structure.

**Comment by kartikvirendrar** [comment]
Ok, will add field types and look how to return data structure from keploy

**Comment by kartikvirendrar** [comment]
I modified my code [openApiSchema.go](https://github.com/kartikvirendrar/keploy/blob/main2/generateOpenAPISchema/openApiSchema.go) to return output as:
```
openapi: 3.0.0
components:
  schemas:
    University:
      type: object
      properties:
        alpha_two_code:
          type: string
          description: Alpha-2 code of the country where the university is located
        country:
          type: string
          description: Country of the university
        name:
          type: string
          description: Name of the university
        state-province:
          type: string
          description: State or province where the university is located
        web_page:
          type: string
          description: Web page of the university
info:
  title: My API
  version: 1.0.0
paths:
  /India:
    get:
      description: Get universities in India
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                description: List of universities
                items:
                  $ref: '#/components/schemas/University'
  /United+States:
    get:
      description: Get universities in United+States
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                description: List of universities
                items:
                  $ref: '#/components/schemas/University'
``` 
Is this output ok, I am still using predefined data structure and working to generate this data structure from API call will update the code as soon as possible

**Comment by charankamarapu** [comment]
Hi @kartikvirendrar . like @JammUtkarsh has pointed out here what will be the case if the API request call doesn't consist of all the fields that are present in the API how do you deal with it . Like for every request for that same API we can produce many OpenAPI schema with your approach how will combine them. Using API calls/TestCases to create OpenAPI is one of the way to think but you are free to explore other options too.

**Comment by kartikvirendrar** [comment]
If the API request call doesn't consist of all the fields that are present in the API response, we can still generate an OpenAPI schema based on the fields that are present in the response. However it may not be as useful in terms of input validation, as the schema won't account for missing or invalid input fields, but generating an OpenAPI schema based on the API response can still have benefits, such as providing documentation to API consumers about the expected response format, including the types and structure of the fields that are returned. This can help API consumers to better understand how to use the API and what to expect in response, which can ultimately lead to more efficient and effective API usage.

If we have multiple OpenAPI schemas generated from different requests of same API calls, we can combine them by merging the schemas together. We can merge the paths, responses, and parameters sections of the different schemas to create a single, comprehensive schema that covers all possible API responses. We may also need to resolve any conflicts that arise when merging the schemas, such as duplicate paths or conflicting response codes. Some approaches to merge schemas:
- Code-first approach: If we use code-first approach where we define the API schema in code to generate OpenAPI schemas, we can define a common interface or contract for our API, and ensure that all implementations of the API conform to this contract. This way, we can generate a single OpenAPI schema that covers all implementations of the API.
- Automated merging: There are some tools and libraries available that can automate the process of merging multiple OpenAPI schemas. For example, the Swagger Codegen tool provides a merge command that can merge multiple OpenAPI schemas into a single schema. Similarly, the OpenAPI Tools project provides a merge utility that can merge multiple OpenAPI schemas in various formats.
- API testing tools: Some API testing tools, such as Postman and Karate, provide features for generating OpenAPI schemas based on API requests and responses. These tools can also merge multiple schemas generated from different requests into a single schema. For example, in Postman, you can use the "Generate Schema" feature to generate a schema for a request, and then use the "Combine Schemas" feature to combine multiple schemas into a single schema.

To generate OpenAPI schema some other approaches which can be taken into consideration are:
- Reverse engineering: This involves analyzing an existing API to generate an OpenAPI schema. There are tools available like Swagger, Postman, APIMatic, Insomnia etc. that can automatically generate a schema by analyzing the API's endpoints, request and response payloads, and other metadata.
- Contract-first approach: This involves defining the API schema in a separate document, such as a YAML or JSON file, before implementing the API. The schema can then be used to generate server and client code, as well as documentation.
- Automated testing: This approach involves using automated tests to generate an OpenAPI schema based on the API's responses. Tools such as Dredd and Prism can automatically generate a schema by testing an API's responses against a pre-defined API specification.
