### ISSUE TITLE
[feature]: Implement an eBPF based program to start and application and capture all http incoming and outgoing traffic  

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#436]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be great to have an eBPF-based program that can start another program (eg: an API server) and then capture all incoming and outgoing HTTP connections. This should not require any changes to the host program. 

### Why should this be worked on?

Keploy currently uses SDKs to capture network traffic. This would enable keploy to capture HTTP traffic without needing to make any code changes in the host program. This would ease the onboarding process and remove the need to reimplement multiple router middlewares in different languages.

**Comment by pk-218** [comment]
Hi @slayerjain,
I am working on this issue as a part of the GSoC task list. Could you clarify in what language/library should the eBPF program be written in? Should it be in C with the user space program in Go using cilium/ebpf? 

I have prior experience in writing eBPF programs (both BPF and user space) in Rust using [Aya](https://github.com/aya-rs/aya) and would like to know if I can use the same here.

**Comment by slayerjain** [comment]
Hi @pk-218 the original idea was to use C and Go. But I think Rust/Aya is also interesting. It looks like we can write both the user space and kernel program using Aya. Would be good to try it as well. 


Please ensure that this integrates with the keploy server (which is written in go).

**Comment by pk-218** [comment]
Great, I will give it a go!
Yes, I have the integration in mind.

**Comment by pk-218** [comment]
Apologies, I had been away due to exams. 

I looked into using either XDP or kernel probes for capturing the network traffic. Since the long-term goal is to capture traffic and analyse it for various protocols, XDP might give be too low-level for the purpose. Hence, I am implementing several kernel probes for the task. And I am able to run the Keploy server from the eBPF program without any code changes.

@slayerjain will the eBPF integration code be a part of this repository or a separate one? So that I can structure the project accordingly.

**Comment by slayerjain** [comment]
@pk-218 I think it would be fine to keep the eBPF code part of this repository. Something I've been told is that we can use system calls like the `connect()` and `getpeername()` to send tcp traffic to/from a user space transparent proxy server (which could be written in go) and then achieve recording outbound dependencies.

**Comment by charankamarapu** [comment]
The keploy v2 is implement using this approach. resolving the issue.
