### ISSUE TITLE
[feature]:  Capture all https incoming and outgoing traffic for an application

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#437]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Extend the previous eBPF program made in #436 to support HTTPS interception. Intercepting HTTPS traffic normally requires installing a self-signed CA so that any proxy is able to decrypt the traffic. 

### Why should this be worked on?

Keploy currently uses SDKs to capture network traffic. This would enable keploy to capture HTTPS traffic without needing to make any code changes in the host program. This would ease the onboarding process and remove the need to reimplement multiple router middleware in different languages.

**Comment by charankamarapu** [comment]
This has implemented in keploy v2.
