### ISSUE TITLE
[feature]: add support for intercepting and parsing Postgres traffic

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#438]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

After capturing HTTP (#436) and HTTPS (#437) we should try to capture and implement them for database traffic. 

### Why should this be worked on?

Capturing database traffic is important because databases are generally used for storing the state of the application.

**Comment by charankamarapu** [comment]
This has been implemented in keploy v2 and postgres is added as an dependency support in v2.
