### ISSUE TITLE
[feature]: create an eBPF based sample from echo-sql demo in sample-go

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#439]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Once we have implemented HTTP (#436), HTTPS(#437) and Postgres (#438), we should create a sample application to demonstrate how the eBPF version would work. We can use the `echo-sql` demo in the samples-go as the base. 

### Why should this be worked on?

The sample application can help demonstrate how keploy would integrate with a particular stack.

**Comment by gouravkrosx** [comment]
eBPF based echo-SQL sample project: https://github.com/keploy/samples-go/tree/main/echo-sql

closing this issue.
