### ISSUE TITLE
[feature]: Add URI and URL in HTTPRequest & HTTPrequestInput schema

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#44]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need both URL and URI for testlist table and test-run side tabs respectively. Currently there's only URI.  

### Why should this be worked on?

Will help user understand the test case better with complete URL

**Comment by madhavsikka** [comment]
Hi, can I take this up ?

**Comment by Sarthak160** [comment]
I think this has been already done refer #45

**Comment by nehagup** [comment]
Thanks for the initiative Madhav. Seems like we missed closing this[ with the PR](https://github.com/keploy/keploy/pull/45). It's covered. 

Thanks for prompt response Sarthak.
