### ISSUE TITLE
[feature]: add configuration to pipe logs to a file

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#444]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently Keploy server logs are logged on CLI which Keploy binary is running. Due to which upon starting Keploy server from SDK asynchronously, the server logs are logged along with sample application logs. 

 We can add a logPath field in our configurations to pipe the logs into the text file instead of CLI. 

### Why should this be worked on?

The server logs are mixed up with the user application logs due to which it becomes to debug.

**Comment by achintya-7** [comment]
Is this issue related to the Keploy GO SDK

**Comment by achintya-7** [comment]
Would like to work on this issue. Can I just directly start with it?

**Comment by slayerjain** [comment]
@achintya-7 yes feel free :)

**Comment by Sarthak160** [comment]
We don't need this feature in the newer keploy version . Since there is no SDK involved and keploy will be running the user application .
