### ISSUE TITLE
[feature]: add support for reading js or go based testcases 

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#447]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Defining a js or go-based test case format alternative to the current keploy YAML would be good. We can take inspiration from `k6.io` or `rest assured`. We can also explore leveraging an existing interpreter for example from k6s and just create a js based interpreter for tests. 

### Why should this be worked on?

JS or Go-based tests would be more flexible than YAML-based tests. It can make adding custom assertions easier.

**Comment by Frey0-0** [comment]
Hello @slayerjain @SanskritiHarmukh  I find this issue interesting and would like to work on it. I have used k6.io once before and I feel the JS-based test cases would be more readable personally. For the approach,h I would prefer to use JS as I have less experience in Go but considering that whole of keploy is in Go what should it be ideally? And also we will need to write a parser right?
I am exploring the code to understand how a yaml file is processed to maybe use the same methods. I would love to hear your opinion on this :)  if there are any resources that can help.

**Comment by charankamarapu** [comment]
Issue is irrelevant as keploy v1 is no more supported.
