### ISSUE TITLE
[feature]: Define basic library interfaces for the JS/Go DSL

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#448]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Once we have a format for the data definitions and are able to read and parse it using the keploy server (#447), we need to define some basic interface to define assertions and other interactions with the keploy server. 

### Why should this be worked on?

This is where we would start seeing the advantages of using a language-based DSL. The library would make various customisations easy and transparent.

**Comment by Arnab7456** [comment]
can i start working on it

**Comment by nehagup** [comment]
@Arnab7456 It's a GSoC task. Anyone can contribute and make a PR.

**Comment by sayantan135** [comment]
can i work on it ?

**Comment by nehagup** [comment]
@sayantan135 It's a GSoC task. Anyone can contribute and make a PR.

**Comment by charankamarapu** [comment]
Issue is irrelevant as keploy v1 is no more supported.
