### ISSUE TITLE
[feature]: Generate tests using the DSL for the echo-sql demo in samples-go

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#450]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Once we are able to read and generate the DSL (#447, #448, #449), we should create test cases for some sample applications like the echo-sql app.  

### Why should this be worked on?

This will help demonstrate the code generation and assertion capability of the keploy DSL module.

**Comment by charankamarapu** [comment]
duplicate.
