### ISSUE TITLE
Add Templates for Issues

### ISSUE THREAD

**Issue by ItsRoy69** [keploy/keploy#453]

**Comment by nehagup** [comment]
@IAmTamal yes this issue is for keploy/website repo, please feel free to make a PR.

**Comment by IAmTamal** [comment]
> @IAmTamal yes this issue is for keploy/website repo, please feel free to make a PR.

So sorry for the delay. The PR has been made [here](https://github.com/keploy/website/pull/37), do let me know if changes needed.
