### ISSUE TITLE
Add Templates for Pull Requests

### ISSUE THREAD

**Issue by ShivamTyagi12345** [keploy/keploy#454]
I will like to create the template for PR as we have in other repositories

**Comment by nehagup** [comment]
@mayankkuamr001 yes this issue is for keploy/website repo, please feel free to make a PR.

**Comment by 9520prashant** [comment]
@nehagup you mean, we need add PR Template for [This](https://github.com/keploy/keploy) right?

**Comment by nehagup** [comment]
@9520prashant this issue has been stale and resolved now. Closing this :)
