### ISSUE TITLE
Sending button text overflow: mobile view

### ISSUE THREAD

**Issue by ashavijit** [keploy/keploy#468]
Ref : subscribe to newsletter (sending message)

**Comment by ashavijit** [comment]
@nehagup can you assign me ?

**Comment by nehagup** [comment]
@ashavijit Done. It'll be great if you can add the screenshot of the issue first.

**Comment by ashavijit** [comment]
sure!

**Comment by karthiknadar1204** [comment]
If this issue is up for grabs,i would like to work on it

**Comment by charankamarapu** [comment]
This has been taken care in the keploy website.
