### ISSUE TITLE
[feature]: Behaviour of Telemetry Events and installationIds when Keploy is used in pipelines

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#474]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Whenever Keploy is run in pipeline 

Current behaviour : new InstallationId is created every time the pipeline is run . This creates wrong data in the telemetry events because new InstallationId is considered as new user.

Required behaviour : InstallationId should be unique per pipeline and should not change and also there should be a variable which lets us know that keploy user is running it in pipeline.

### Why should this be worked on?

This is important to get the correct info regarding the users .

**Comment by haquem1** [comment]
@charankamarapu I'd like to give this issue a shot!

**Comment by charankamarapu** [comment]
sure @haquem1, assigning this issue to you .

**Comment by haquem1** [comment]
I got caught up in a number of things the past couple weeks: but I wanted to point out where I am:

- I have added user field in the telemetry event extracted from this [function](https://github.com/keploy/keploy/blob/560a3b71cebbd692d9fc296e877d0853895e4599/pkg/platform/fs/tele.go#L17-L32)
- I need direction on how to keep the `installationId` persisted from the telemetry service for a pipeline environment. If the service generates a new id every time a pipeline is run that means the embedded files are wiped out for each run per this Slack [post](https://keploy.slack.com/archives/C035URHSGDQ/p1686291227307089?thread_ts=1686080327.456239&cid=C035URHSGDQ) and these [lines](https://github.com/keploy/keploy/blob/560a3b71cebbd692d9fc296e877d0853895e4599/pkg/platform/telemetry/telemetry.go#L61-L81)

**Comment by Swaggermuffin64** [comment]
Hey, I'd like to give this a try.

**Comment by re-Tick** [comment]
Hi @Swaggermuffin64, The issue is open for all. You can discuss your changes here on the issue and open a PR.

**Comment by gouravkrosx** [comment]
@charankamarapu Is this issue still relevant?

**Comment by charankamarapu** [comment]
yes
