### ISSUE TITLE
[feature]: add a sample for express/mongoose app

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#490]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Recently, mongoose support has been added to Typescript-SDK for mocking the outputs. There should be a sample API application which uses express framework.

### Why should this be worked on?

This can describe the integration for express/mongoose frameworks.

**Comment by SumeetMaurya** [comment]
Hey @re-Tick, I'm interested in working on this feature, can you assign this to me please

**Comment by re-Tick** [comment]
> Hey @re-Tick, I'm interested in working on this feature, can you assign this to me please

Hi @SumeetMaurya, the issue are open for all contributors. You can make your change request on the respective repos. And discuss your changes here.

**Comment by SumeetMaurya** [comment]
sure

**Comment by riteshsinghh-coder** [comment]
sure
