### ISSUE TITLE
[bug]:  card look unbalanced.

### ISSUE THREAD

**Issue by Rohitrky2021** [keploy/keploy#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

 I found that this margin was causing too much space between the h5 and the previous element, making the card look unbalanced.

Changed the font size and line height for h2 elements: I increased the font size to make the heading more prominent, and adjusted the line height to improve legibility.

Added padding to the top of the card body: This was done to create some visual space between the heading and the body content.

Changed the font family for p elements: I changed the font family to match that of the h2 element, creating a consistent typography throughout the card.

Adjusted the font size and color for h5 elements: I decreased the font size slightly to make the h5 element less prominent, and adjusted the color to make it more visible against the background.

### Steps to reproduce

Go to ' https://github.com/keploy/ui/edit/main/static/onboardingCss/Card.css'

here is the updated css

/* Remove margin from all heading tags */
h1, h2, h3, h4, h5, h6 {
  margin: 0;
}

.cards-onboard {
  align-items: flex-start;
  justify-content: center;
}

.card-onboard {
  background: #fff;
  width: 24em;
  border-radius: 0.6em;
  margin: 1em;
  overflow: hidden;
  cursor: pointer;
  box-shadow: 0 13px 27px -5px hsla(240, 30.1%, 28%, 0.25), 0 8px 16px -8px hsla(0, 0%, 0%, 0.3), 0 -6px 16px -6px hsla(0, 0%, 0%, 0.03);
  transition: all ease 200ms;
}

.card-onboard:hover {
  transform: scale(1.03);
  box-shadow: 0 13px 40px -5px hsla(240, 30.1%, 28%, 0.12), 0 8px 32px -8px hsla(0, 0%, 0%, 0.14), 0 -6px 32px -6px hsla(0, 0%, 0%, 0.02);
}

.card-onboard img {
  width: 200px;
  height: 200px;
  /* Use "cover" to make sure the image fills the container without distortion */
  object-fit: cover;
}

.card-onboard h2 {
  color: #222;
  margin-top: -0.2em;
  line-height: 1.4;
  font-size: 1.3em;
  font-weight: 500;
  font-family: 'Montserrat', sans-serif;
  transition: all ease-in 100ms;
}

.card-onboard p {
  color: #777;
}

.card-onboard h5 {
  color: #bbb;
  font-weight: 700;
  font-size: 0.7em;
  letter-spacing: 0.04em;
  margin: 1.4em 0 0 0;
  text-transform: uppercase;
}

.card-body-onboard {
  padding: 1.2em;
}

### Environment

None

### Version

Cloud

**Comment by karthiknadar1204** [comment]
If this issue is still available,i would liek to work on it

**Comment by nehagup** [comment]
@karthiknadar1204 since the Ui will soon be deprecated. Will be better if you can put efforts on some other good first issues. :)

**Comment by karthiknadar1204** [comment]
Sure @nehagup ,it's my first time exploring this project,could you suggest some good first issues,i am a full stack web developer.

**Comment by nehagup** [comment]
We've majorly backend-related tasks since we've turned keploy into cli tool. You can explore good-first-issues on the repo and pick one. You can also join Keploy Slack channel to discuss more.

**Comment by Sarthak160** [comment]
This issue has been outdated , Use keploy's CLI experience with latest release .
