### ISSUE TITLE
[feature]: Mutation to normalise multiple test-cases in a test-run

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#5]
**Is your feature request related to a problem? Please describe.**
I have to go into every test case detail for a test-run and accept/normalise each. 

**Describe the solution you'd like**
Add a mutation to normalise multiple test-cases(ids) in a test-run

**Comment by neverbeenthisweeb** [comment]
@nehagup 
I can help with this.

However, can you provide the example of which test cases (in which file) that have the behavior of "_I have to go into every test case detail for a test-run and accept/normalise each._"?

Just in case, there is a misunderstanding.

Thanks.

**Comment by slayerjain** [comment]
Hi @neverbeenthisweeb, currently the normalize mutation only supports a single test-run id. We need to add support for it to take an array of ids. 

here's the mutation - https://github.com/keploy/keploy/blob/1a646eab3d52afbff8ce142bb8ecf197dcde1266/graph/schema.graphqls#L6

and here's the implementation - https://github.com/keploy/keploy/blob/1a646eab3d52afbff8ce142bb8ecf197dcde1266/graph/schema.resolvers.go#L37

**Comment by madhavsikka** [comment]
Hi, is this open ?

**Comment by nehagup** [comment]
@madhavsikka Yes, this is still open. Feel free to take it up 🙂

**Comment by neverbeenthisweeb** [comment]
@madhavsikka 
I haven't make much progress about it. Yes, you can take it up.
Sorry for late resp.
