### ISSUE TITLE
[feature]: Add Java SDK 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#51]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Add the support for Java and popular frameworks that'll enable Java application developers to use Keploy. 

### Why should this be worked on?

Got multiple requests to add Java Support via LinkedIn, Youtube, Reddit. It's one of the most popular languages used by enterprises as well.

**Comment by skant7** [comment]
Hi @nehagup this seems like an interesting feature to work on. Can I work on this?

**Comment by nehagup** [comment]
Hi @skant7 Sure, you can work on this. 

@slayerjain can clear any questions you might have. Please feel free to reach out to us on Slack.

**Comment by slayerjain** [comment]
The Java SDK is available here - https://github.com/keploy/java-sdk

**Comment by Arushisingh23** [comment]
oh yeah i just saw the previous issue
