### ISSUE TITLE
[docs]: Add mux-elastic sample app to docs

### ISSUE THREAD

**Issue by developer-diganta** [keploy/keploy#513]
### What do you want to add to the docs? (please state reasons if any)

The [sample mux-sql](https://github.com/keploy/samples-go/tree/main/mux-sql) should be added to the sample app list on the docs website. Currently only three sample apps under go is there on the docs website.

### Where is this stated?

Adding this sample app would help users get a better idea on how to integrate keploy with mux and sql.

### Repository

docs

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by nehagup** [comment]
@SanjaySinghRajpoot sure, feel free to ask any questions

**Comment by SanjaySinghRajpoot** [comment]
https://github.com/keploy/docs/pull/168

**Comment by Swpn0neel** [comment]
Is this still relevant @Sonichigo ?

**Comment by Sonichigo** [comment]
Not relevant since there are no mux-elastic app anymore! You can create a new issue to create a sample app with elastic @Swpn0neel
