### ISSUE TITLE
[docs]: Add typescript sample app to docs

### ISSUE THREAD

**Issue by developer-diganta** [keploy/keploy#514]
### What do you want to add to the docs? (please state reasons if any)

The [sample typescript](https://github.com/keploy/samples-typescript) should be added to the sample app list on the docs website. Currently there is no sample app which shows how to integrate keploy with typescript.

### Where is this stated?

Adding this sample app would help users get a better idea on how to integrate keploy with a typescript project.

### Repository

docs

**Comment by mukul314** [comment]
Can you tell me where to add the documentation for this particular app? I am having a hard time finding the SAMPLE APP LIST.....

**Comment by nehagup** [comment]
@mukul314 The sample app is mentioned in the issue description. The documentation for this is required to be added in the docs website.  
https://github.com/keploy/samples-typescript/tree/main/node-fetch

**Comment by VishalMyla** [comment]
Anyone working on this issue  ?

**Comment by mukul314** [comment]
> Anyone working on this issue ?

Hey, @VishalMyla I have already made a PR on this issue!
