### ISSUE TITLE
[feature]: Compatibility of Go SDK for Go 1.16

### ISSUE THREAD

**Issue by anirudhjain75** [keploy/keploy#521]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Every time you try to build Go 1.16 program with Keploy Go SDK returns an error due to Zap's incompatibility with Go 1.16

### Why should this be worked on?

To provide compatibility for projects running Go 1.16

### Repository

go-sdk

**Comment by aerowisca** [comment]
@anirudhjain75  Can you share  exactly what errors do you get corresponding to Zap? I was not able to reproduce the issue with Zap with go1.16. 

Please share the environment info, steps to repro and error message.

**Comment by slayerjain** [comment]
More users on other channels have also experienced this. Recently @nikhil-nutanix also faced this issue. I’m able reproduce this, and I’ll share the steps soon.

**Comment by slayerjain** [comment]
@anirudhjain75 and @nikhil-nutanix I think I have fixed the issue. I also needed to enable vendoring to better support classical go projects (non-go mod), else go was pulling more recent versions of libraries leading to incompatibility issues.

**Comment by subtleseeker** [comment]
Thanks Shubham for such a quick turnover. I am able to successfully run keploy.
For my project, I saw this at runtime:
```
panic: /debug/requests is already registered. You may have two independent copies of golang.org/x/net/trace in your binary, trying to maintain separate state. This may involve a vendored copy of golang.org/x/net/trace.

goroutine 1 [running]:
github.com/keploy/go-sdk/vendor/golang.org/x/net/trace.init.0()
        /home/nikhil.mundra/m3/main/.go/src/github.com/keploy/go-sdk/vendor/golang.org/x/net/trace/trace.go:123 +0x191
2023-04-09 01:32:05,522 INFO exited: groups (exit status 2; expected)
```
I deleted net/trace package from vendor and everything worked. Mentioning this for others who face same issue.
