### ISSUE TITLE
[docs]: Support for go-swagger server (go's net/http router)

### ISSUE THREAD

**Issue by nikhil-nutanix** [keploy/keploy#527]
### What do you want to add to the docs? (please state reasons if any)

I am trying to generate UTs with keploy for a go server that is built with go-swagger (openapi v2).
From the [supported list of routers](https://docs.keploy.io/docs/go/integration/), I don’t see how I work with the default net/http package.

### Repository

keploy

**Comment by slayerjain** [comment]
Hi @nikhil-nutanix , We've released the changes in go sdk version `v0.8.5`. Can you please try and confirm. Added an example in README here too - https://github.com/keploy/go-sdk#example-with-goswagger

**Comment by Sarthak160** [comment]
Done in #184
