### ISSUE TITLE
[feature]: sync docs website with Readmes of all SDKs

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#537]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently due to high iterations the readmes are updated but the documentation website becomes outdated soon. Need to add reference links in such a way that both are synced.

### Why should this be worked on?

Users gets confused because of outdated docs

### Repository

docs

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by nehagup** [comment]
@SanjaySinghRajpoot Please go ahead

**Comment by 9520prashant** [comment]
Hi @nehagup I found this issue still open, just want to clear that is there still need to update of READMEs

**Comment by nehagup** [comment]
@9520prashant yes we need to sync and update all the readies, master lies at docs.keploy.io

**Comment by 9520prashant** [comment]
> @9520prashant yes we need to sync and update all the readies, master lies at docs.keploy.io

Got it Thanks For Confirming...

**Comment by AkashKumar7902** [comment]
> @9520prashant yes we need to sync and update all the readies, master lies at docs.keploy.io

@nehagup does this mean the single source of truth lies in docs.keploy.io and we need to sync readme of all repos under keploy with the content of docs.keploy.io ?

**Comment by nehagup** [comment]
@AkashKumar7902 yes, that's right!

**Comment by charankamarapu** [comment]
Issue is irrelevant as keploy v1 is no more supported.
