### ISSUE TITLE
[feature]: add debug log statements to the go sdk

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#543]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We should add debug statements to the go sdk. There's currently only 1 debug statement in the entire sdk codebase. 

### Why should this be worked on?

It can become hard to debug whether the dependency wrapping is working correctly. Debug logs can help with getting better understanding of any issues with integration. 

### Repository

go-sdk

**Comment by charankamarapu** [comment]
Issue is irrelevant as keploy v1 is no more supported.
