### ISSUE TITLE
[bug]: Multiple footer 

### ISSUE THREAD

**Issue by himanshu1221** [keploy/keploy#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we go to the keploy documentation if we choose the quickstart language we see multiple footers 

### Steps to reproduce

[Keploy[BUG].webm](https://user-images.githubusercontent.com/32031706/235117388-754e3f96-6919-41cc-bbb0-12e3088b08a7.webm)

### Environment

Deploy preview

### Version

Cloud

### Repository

keploy

**Comment by nehagup** [comment]
Duplicate. https://github.com/keploy/keploy/issues/545
