### ISSUE TITLE
[bug]: Multiple footer 

### ISSUE THREAD

**Issue by himanshu1221** [keploy/keploy#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we go to the keploy documentation if we choose the quickstart language we see multiple footers 

### Steps to reproduce

[Keploy[BUG].webm](https://user-images.githubusercontent.com/32031706/235117388-754e3f96-6919-41cc-bbb0-12e3088b08a7.webm)

### Environment

Deploy preview

### Version

Cloud

### Repository

docs

**Comment by karthiknadar1204** [comment]
If this issue is up for grabs,i would like to work on it

**Comment by nehagup** [comment]
@karthiknadar1204 please feel free to take this up!

**Comment by karthiknadar1204** [comment]
Sure thank you @nehagup

**Comment by karthiknadar1204** [comment]
<img width="835" alt="Screenshot 2023-05-09 at 8 36 58 PM" src="https://github.com/keploy/keploy/assets/95973644/b82d6024-ad4f-4ea6-a520-c2f80986d89f">


@nehagup I am trying to setup the project on my local machine but it is taking very long time to just execute the second command,is it normal for this to happen sor is there something wrong with the commands that i am using?

**Comment by karthiknadar1204** [comment]
<img width="848" alt="Screenshot 2023-05-12 at 8 51 15 PM" src="https://github.com/keploy/keploy/assets/95973644/614476c6-259f-407f-ab19-adef9bbf48f3">

Could you  please guide me with me

**Comment by KashishLakhara04** [comment]
@karthiknadar1204 run `go mod download github.com/keploy/go-sdk` command and you should be good to go.

**Comment by nehagup** [comment]
@karthiknadar1204 I see you're cloning wrong repo! The multiple footer issue is on the documentation site which is managed here - https://github.com/keploy/docs

**Comment by karthiknadar1204** [comment]
I'm sorry,will get it done correctly

**Comment by karthiknadar1204** [comment]
will try to submit pr today,thank you

**Comment by karthiknadar1204** [comment]
<img width="1451" alt="Screenshot 2023-05-16 at 9 20 25 PM" src="https://github.com/keploy/keploy/assets/95973644/03a3eb2a-daf0-4f28-9143-e903094550e2">

@nehagup how do resolve this error while setting up the project

**Comment by nehagup** [comment]
@karthiknadar1204 have you tried `yarn install`?

Btw @Sonichigo has already made a PR for this, since this issue was becoming most reported and a bit urgent.  https://github.com/keploy/docs/pull/172 Can you please pick up another one?

**Comment by karthiknadar1204** [comment]
I'll try setting up the project again and find a new issue to fix,want to make my first pr with keploy

**Comment by nehagup** [comment]
@karthiknadar1204 can you please tell me the steps you followed, which machine/OS are you using and which project are you trying to setup?
