### ISSUE TITLE
[bug]: broken link

### ISSUE THREAD

**Issue by KashishLakhara04** [keploy/keploy#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There is a broken link in the [readme.md](https://github.com/keploy/website) of `keploy/website`.

## Screenshot

![WhatsApp Image 2023-05-16 at 3 29 24 PM](https://github.com/keploy/keploy/assets/104296574/74f8eb1b-0225-424d-862f-4f589e7fd2da)

### Steps to reproduce

1. Go to [keploy/website](https://github.com/keploy/website)
2. Click on readme.md
3. Scroll down to `Technology Stack`

### Environment

None

### Version

Cloud

### Repository

website

**Comment by gauriimaheshwarii** [comment]
Hi @KashishLakhara04, made the changes and created the [PR](https://github.com/keploy/website/pull/42).
