### ISSUE TITLE
[bug]: Untidy Footer

### ISSUE THREAD

**Issue by kartikmehta8** [keploy/keploy#562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The footer of the [docs](https://docs.keploy.io) website is untidy and doesn't looks good.

![footer](https://github.com/keploy/docs/assets/77505989/d1f1ead7-988e-4dde-85c6-2ed76243c8d8)
There is an extra `|` symbol after Privacy Policy.

### Steps to reproduce

1. Go to [docs](https://docs.keploy.io).
2. Scroll down to the bottom.
3. You can see the footer.

### Environment

None

### Version

Cloud

### Repository

docs

**Comment by nehagup** [comment]
@karthiknadar1204 this issue's PR has been made (https://github.com/keploy/docs/pull/172) . Please pick another one. :)

**Comment by nehagup** [comment]
@karthiknadar1204 assigning it to you. :)

**Comment by karthiknadar1204** [comment]
Will share the procedure i followed to setup the project morning is that fine @nehagup

**Comment by nehagup** [comment]
@karthiknadar1204 My apologies, just noticed, this issue has already been worked on in this PR https://github.com/keploy/docs/pull/173 . Please pick a new one. :)
