### ISSUE TITLE
[docs]: gifs seems grainy/pixelated when switched to dark mode 

### ISSUE THREAD

**Issue by AmalChandru** [keploy/keploy#565]
### What do you want to add to the docs? (please state reasons if any)

I went through the [keploy docs](https://docs.keploy.io/docs/keploy-explained/how-keploy-works/) with dark mode turned on. I was not able to understand what the gif provided on the page. Gifs were grainy and pixelated [refer fig:1]. 

**Note:** This issue is present only in dark mode
![fig:1](https://github.com/keploy/keploy/assets/58633735/e35dd395-3d82-4739-9b81-a175f8552b12)

### Repository

docs

**Comment by AHB102** [comment]
I am new to open source, can I try to solve this ?

**Comment by nehagup** [comment]
@AHB102 Thanks for taking the initiative, assigning this to you! Please feel to ask any questions you may have.

**Comment by AHB102** [comment]
I am currently trying to solve this issue, once I have a breakthrough I would let you know.
