### ISSUE TITLE
[bug]: monthly meetup broken link

### ISSUE THREAD

**Issue by kartikmehta8** [keploy/keploy#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The monthly meetup link is broken on Keploy's website - [https://lu.ma/keploy](https://lu.ma/keploy).

### Steps to reproduce

1. Go to [https://docs.keploy.io](https://docs.keploy.io).
2. In **Join the Keploy community** section, the meetup link is broken.

![link](https://github.com/keploy/keploy/assets/77505989/07d2ec52-d848-4a1b-910b-97903f2c1126)

Clicking on the link where take us to nowhere.
![404](https://github.com/keploy/keploy/assets/77505989/77a69a64-76de-4264-903a-221f97f34f92)

**You can assign the issue to me if we have any link to fix this issue :)**

### Environment

Production

### Version

Cloud

### Repository

website

**Comment by 9520prashant** [comment]
Hey @kartikmehta8 I have checked , but did not find any issue in community section. everything working fine. @nehagup can you please close this issue

**Comment by nehagup** [comment]
This issue is resolved, closing!
