### ISSUE TITLE
[feature]: Add Python SDK

### ISSUE THREAD

**Issue by mahi-official** [keploy/keploy#58]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Add support for python frameworks like Django, flask, and bottle.

You can join `python-sdk` slack channel in order to track progress

### Why should this be worked on?

No solid testing library is present in python right now for API testing.

**Comment by nehagup** [comment]
@mahi-official Thanks for creating this feature request. Would you like to take a chance on adding Python support?

Please feel free to join our Slack channel if you may have any questions.

**Comment by mahi-official** [comment]
Sure I would love to work on it!

**Comment by nehagup** [comment]
@mahi-official Awesome! I'm creating a repo for Python SDK. Assigning this feature request to you, might add more intrested folks later. 🌟

**Comment by slayerjain** [comment]
it's now being built here - https://github.com/keploy/python-sdk

**Comment by anudeepsamaiya** [comment]
Does the python-sdk support django? If it does, cant find any documentation about it, would love to help with the documentation.

**Comment by slayerjain** [comment]
@anudeepsamaiya the python sdk is still WIP. I don’t think Django is supported yet. I’ll keep you posted here. Most mature sdk is go followed by java and typescript/javascript

**Comment by Tanmoy741127** [comment]
@mahi-official @slayerjain 
I like the concepts behind keploy. 
is the python sdk completed ? If not , I like to work on.

**Comment by mahi-official** [comment]
Hi @Tanmoy741127 
The Python SDK is not yet completed. If you like to contribute, we can set up a call to give you an overview of the progress.

**Comment by Tanmoy741127** [comment]
@mahi-official nice ! I will look through the JS library once to understand the logics. Then we can have a meet to resolve the doubts.

**Comment by Tanmoy741127** [comment]
> Hi @Tanmoy741127 The Python SDK is not yet completed. If you like to contribute, we can set up a call to give you an overview of the progress.

@mahi-official Hi, I and my friend @cAmartya will like to work on the python SDK. We have gone through some SDK's codebase and have an overview of working. We can have a meet to get a overview for python-sdk progress. Let us know about your preferred date and time  for the meet.

**Comment by prith-olo** [comment]
Ok

**Comment by cAmartya** [comment]
> > Hi @Tanmoy741127 The Python SDK is not yet completed. If you like to contribute, we can set up a call to give you an overview of the progress.
> 
> @mahi-official Hi, I and my friend @cAmartya will like to work on the python SDK. We have gone through some SDK's codebase and have an overview of working. We can have a meet to get a overview for python-sdk progress. Let us know about your preferred date and time for the meet.

@mahi-official when are we having the meet?

**Comment by nehagup** [comment]
Hi @cAmartya @prith-olo @Tanmoy741127 here is the link of our next meet-up for Python SDK. https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=NzYwNTJxbnA2bWtkcjU4c2dlbzE5YjVrazcgbmVoYUBrZXBsb3kuaW8&tmsrc=neha%40keploy.io

**Comment by Tanmoy741127** [comment]
> Hi @cAmartya @prith-olo @Tanmoy741127 here is the link of our next meet-up for Python SDK. https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=NzYwNTJxbnA2bWtkcjU4c2dlbzE5YjVrazcgbmVoYUBrZXBsb3kuaW8&tmsrc=neha%40keploy.io

I cant open the link. It's saying `Could not found requested event`

**Comment by nehagup** [comment]
@Tanmoy741127 Please try this. 

Python SDK Updates
Friday, January 27 · 3:00 – 4:00pm
Google Meet joining info
Video call link: https://meet.google.com/jrd-thae-cph
Or dial: ‪(US) +1 470-273-8534‬ PIN: ‪523 732 474‬#
More phone numbers: https://tel.meet/jrd-thae-cph?pin=2886076852160

**Comment by Tanmoy741127** [comment]
> @Tanmoy741127 Please try this.
> 
> Python SDK Updates Friday, January 27 · 3:00 – 4:00pm Google Meet joining info Video call link: https://meet.google.com/jrd-thae-cph Or dial: ‪(US) +1 470-273-8534‬ PIN: ‪523 732 474‬# More phone numbers: https://tel.meet/jrd-thae-cph?pin=2886076852160

We will try to join the meet. But from 27th to 30th Jan , me and @cAmartya  will be out of station regarding an hackathon. So if it is possible to reschedule/or any next meeting can be arranged it will be really helpful

**Comment by nehagup** [comment]
Details of next meet : 

Python SDK updates and meet
Saturday, March 18 · 11:00am – 12:00pm
Google Meet joining info
Video call link: https://meet.google.com/zff-eiyf-vjo 
Or dial: ‪(US) +1 561-570-6031‬ PIN: ‪965 113 632‬#
More phone numbers: https://tel.meet/zff-eiyf-vjo?pin=7792079223684

**Comment by nehagup** [comment]
FYI: we're now working on a language agnostic versions of keploy. For SDKs apart from Go/Java/JsTs, it'll be better to spend effort accelerate that project.

**Comment by charankamarapu** [comment]
Closing the issue as we have introduces keploy v2 this issue is no more relevant as version 2 doesn't require sdks and more over libraries no more matter as keploy v2 is capturing calls on network level.
