### ISSUE TITLE
[docs]: Add details of the only unit test case file needed 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#60]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently on the code of the file is mentioned in the README.md 

It'll be easier for the users to follow instructions with more information about unit test case file. For example 
1. Where to add this file (say with main.go)
2. Name of the file(say main_test.go)

### Why should this be worked on?

It'll add more clarity in following the instructions of adding unit testing code.

**Comment by nrmarther** [comment]
could I work on this? Where could I look for more information on this?

**Comment by nehagup** [comment]
> could I work on this? Where could I look for more information on this?
 Yes Sure @nrmarther ! You can refer our docs for this https://docs.keploy.io/docs/go/integration-with-go-test 

> it looks to me like we just need more detail in the README.md, is this correct? 
Yes, in this issue we are looking to add more details to the README.md like at what location should the person add this given unit test file, what should be the name of the unit-test file.

**Comment by SuperAayush** [comment]
@nehagup is this issue still valid and can I work on this.
If yes can you provide more detail on how to get started with this issue?

**Comment by nehagup** [comment]
> @nehagup is this issue still valid and can I work on this.
> If yes can you provide more detail on how to get started with this issue?

Sure @SuperAayush feel free to take this up! This is a documentation issue where you just need to add more about the unit-test file required to run Keploy in test mode. Please read more in the description and comments above and post any specific questions you might have :)

**Comment by ShivamTyagi12345** [comment]
> @nehagup is this issue still valid and can I work on this. If yes can you provide more detail on how to get started with this issue?

Hey @SuperAayush Let us know if your progress :) and any blockers that we can help with

**Comment by Hermione2408** [comment]
Hey @nehagup is this issue still open? Can I pick this up?

**Comment by nehagup** [comment]
@Hermione2408 sure.

**Comment by Hermione2408** [comment]
@nehagup Created the PR please review and let me know if any changes are required
