### ISSUE TITLE
[bug]: seperate dir for different user applicartion 

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I record test cases for 2 different applications from the one running Keploy CLI terminal, then the test cases are mixed together in the same tests dir. 
 This results in false failure in test when we try to run tests.

### Steps to reproduce

1. Record test cases for gin-mongo using keploy-CLI (v2).
2. Record some test cases for another sample app using the same location where test cases for gin-mongo are stored.
3. Now, run the test cmd in Keploy-CLI V2.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by charankamarapu** [comment]
Issue is irrelevant as keploy v1 is no more supported.
