### ISSUE TITLE
[bug]: Update URL name from "keply/example-url-shortener" to "keploy/samples-go"

### ISSUE THREAD

**Issue by KashishLakhara04** [keploy/keploy#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The readme of ![gin-mongo](https://github.com/keploy/samples-go/blob/main/gin-mongo/README.md) sample shows to clone the ![example-url-shortener](https://github.com/keploy/example-url-shortener) repository instead of ![samples-go](https://github.com/keploy/samples-go/tree/main) repository
![WhatsApp Image 2023-07-08 at 1 58 34 PM](https://github.com/keploy/keploy/assets/104296574/368f06d3-4d93-4c88-a873-ba73ebb54d61)

### Steps to reproduce

we can update the repository name in the readme of samples-go

### Environment

None

### Version

Cloud

### Repository

samples-go

**Comment by KashishLakhara04** [comment]
I would like to fix it.

**Comment by nehagup** [comment]
@KashishLakhara04 please go ahead

**Comment by Sarthak160** [comment]
This has been fixed please check the new readme.md
