### ISSUE TITLE
[feature]: Add Javascript/Typescript (SDK) support

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#61]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Add the support for Javascript/Typescript and popular JS frameworks that'll enable JS application developers to use Keploy.

### Why should this be worked on?

Got multiple requests to add JS support via LinkedIn, Reddit. It's one of the most popular languages used by the developers as well.

**Comment by nehagup** [comment]
@madhavsikka Thanks for the initiative! 
This is pretty intensive task! Would to discuss quickly on a meet/slack how we can take it in steps. 😄

**Comment by slayerjain** [comment]
its now being built here - https://github.com/keploy/typescript-sdk

**Comment by slayerjain** [comment]
The typescript SDK now supports record/replay or requests

**Comment by Sarthak160** [comment]
We now have both Java and Js SDK ; Although now keploy V2 has language agnostic approach which doesn't require to integrate sdk .
