### ISSUE TITLE
[feature]: Add docker for mac support to run keploy v2

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#611]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

The goal of this issue is to enhance Keploy v2, which currently supports Linux and Windows (via WSL), to also include support for macOS using Docker for Mac. By adding this support, Keploy v2 will be accessible to macOS users, enabling them to generate tests and mocks for their applications effectively.

### Why should this be worked on?

- Inclusivity: Adding macOS and Docker for Mac support expands Keploy v2's user base, accommodating developers on macOS and promoting inclusivity.

- Seamless integration: Supporting Docker for Mac ensures a smooth integration into existing macOS development workflows, improving efficiency and productivity for macOS users utilizing Keploy v2.

### Repository

keploy

**Comment by gouravkrosx** [comment]
Keploy follows btf (bpf type format) maps in the ebpf program. Right now this is not supported in the docker for mac. You can follow the [open issue](https://github.com/docker/for-mac/issues/6800) here. Enabling btf will automatically add support to run keploy in docker for mac.

**Comment by hp77-creator** [comment]
Hi @gouravkrosx , we can now use keploy with Docker on Mac, so does this mean, this issue is resolved?

**Comment by gouravkrosx** [comment]
Closing as it is already completed.
