### ISSUE TITLE
[feature]: add support for redis protocol in keploy v2

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#618]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to add support for Redis in keploy v2. 

### Why should this be worked on?

It would help redis users use keploy. 

### Repository

keploy

**Comment by shivamsouravjha** [comment]
Keploy now supports Redis protocol with KeployV2. The sample for the same can be found [here](https://keploy.io/docs/quickstart/samples-redis/).
