### ISSUE TITLE
[feature]: add support for using keploy v2 in manually written tests for mocking/stubs

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#623]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We need to add support for adding using keploy's stubbing feature in manually written tests. ref: https://blog.keploy.io/go-mocks-and-stubs-made-easy

### Why should this be worked on?

This would enable keploy v2 to be used beyond just testing APIs. 

### Repository

keploy

**Comment by charankamarapu** [comment]
Mocking feature has been introduced in keploy v2.
