### ISSUE TITLE
[feature]: support http streaming in http clients in keploy v2

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#624]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Keploy V2 should support capturing and replaying clients that are using http streaming. 

### Why should this be worked on?

This will users leveraging http streaming in their applications test their applications via keploy. 

### Repository

keploy

**Comment by divakar54** [comment]
Hello, Can I take up on this issue? I am new to open source and Go. I would like to contribute while learning on this project.

**Comment by re-Tick** [comment]
Hi @divakar54, the issues are open to all. You can open PR for your changes or discuss them here.

**Comment by charankamarapu** [comment]
Keploy v2 currently supports streaming of http.
