### ISSUE TITLE
[feature]: need to add host header in request when running keploy

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#628]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

In Keploy's test mode, when attempting to hit the application API, it uses the URL captured during the record mode. While running Keploy the host header isn't captured as internal http dependency deletes the host header., because of this the host header isn't being captured leading.

### Why should this be worked on?

However, the host header is important in shared hosting environments where multiple websites may reside on the same physical server with the same IP address. The Host header helps the server differentiate between these websites based on the domain name provided in the request, ensuring that the correct content is served to the client. Thus, the Host header is needed when making a request to the application within a Docker environment.

### Repository

keploy

**Comment by shivamsouravjha** [comment]
@gouravkrosx please assign me the issue
