### ISSUE TITLE
[bug]: Hamburger drawer for keploy docs website is too close to the centre

### ISSUE THREAD

**Issue by ArslanYM** [keploy/keploy#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On small screen devices the hamburger menu is too close to the center and should be aligned towards the left to maintain structure in the website.
![ham](https://github.com/keploy/keploy/assets/104521101/954d8195-534f-4671-9d17-ff25b91279e8)

### Steps to reproduce

1. Go to the [website](https://docs.keploy.io/docs/keploy-explained/why-keploy/)
2. Check on mobile devices 

### Environment

Production

### Version

Cloud

### Repository

website

**Comment by nehagup** [comment]
@Sonichigo please correct this in v2.

**Comment by 9520prashant** [comment]
Hey @nehagup I just want to confirm that is that a real issue, if yes kindly assign this issue to me I will fix it.

**Comment by nehagup** [comment]
@9520prashant yes, this issue is open and is replicable on sm screen sizes. 
<img width="465" alt="Screenshot 2023-09-16 at 1 56 55 PM" src="https://github.com/keploy/keploy/assets/15074229/098f1dbc-57e9-4966-b37e-748a13097691">

**Comment by 9520prashant** [comment]
> @9520prashant yes, this issue is open and is replicable on sm screen sizes. <img alt="Screenshot 2023-09-16 at 1 56 55 PM" width="465" src="https://user-images.githubusercontent.com/15074229/268437656-098f1dbc-57e9-4966-b37e-748a13097691.png">

Thank you so much for confirming this issue.

**Comment by 9520prashant** [comment]
Hey @nehagup Just Fixed the issue in my Local can you please check, is that expected ?
[Video](https://drive.google.com/file/d/1xPcd5rqXNRmL-av3rasEc24gUdwyfQ10/view?usp=sharing), will give the access please check :)

**Comment by 9520prashant** [comment]
Hey @AkashKumar7902, Thanks For Creating PR. This Issue Assigned to me but you created a PR That means you fixed it, I am un-assigning this issue. **Appreciate your efforts.**
