### ISSUE TITLE
[bug]:  Custom CA certificate does not get updated in the case of Amazon Linux

### ISSUE THREAD

**Issue by PranshuSrivastava** [keploy/keploy#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The command for updating the ca trust store fails when the name of the distro is Amazon Linux. Ideally it should be updating the ca store depending on what Linux distro Amazon Linux is based on.
Also need to add support for JDK as they have their own trust store ($JAVA_HOME/lib/security/cacerts $JAVA_HOME/lib/security/cacerts.backup) and change the name of the ca to keployCA.
### Steps to reproduce

1. Create an Amazon Linux ec2 instance.
2.  Clone the Keploy repo and switch to the v2 branch
3.  Start the Keploy server by using the command 

```
go run -exec "sudo -E" main.go test --c ~/samples-go/gin-mongo/main --delay 10
```

### Environment

None

### Version

Local

### Repository

keploy

**Comment by charankamarapu** [comment]
This issue is fixed and resolved
