### ISSUE TITLE
[bug]: Keploy V2 is unable to capture events from Python and JavaScript Application

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently when we try to run Python or JavaScript Application along with Keploy , Kelpoy is unable to record the tests. According to the Analysis the EBPF code is not sending any events to Keploy while running Python or JavaScript Application. 

### Steps to reproduce

1. Run a python Application along with Keploy

### Environment

None

### Version

Local

### Repository

keploy

**Comment by slayerjain** [comment]
duplicated of https://github.com/keploy/ebpf/issues/2 and https://github.com/keploy/ebpf/issues/3
