### ISSUE TITLE
[docs]: Add details for 3 different Keploy SDK Modes 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#64]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Add 3 different modes of Keploy SDK in the readme. 

Record: Sets to record mode.
Test: Sets to test mode.
Off: Turns off all the functionality provided by the API

Note: KEPLOY_MODE value is case sensitive.

Take inspiration from https://github.com/keploy/go-sdk#configure 

### Why should this be worked on?

Users will have better undedstanding about different modes and what exactly needs to be set in the env variable since it's currently case sensitive

**Comment by unnati914** [comment]
can i work on this?

**Comment by slayerjain** [comment]
@unnati914 sure :)

**Comment by nehagup** [comment]
@unnati914 are you still working on this? :)

**Comment by unnati914** [comment]
yes, will open a PR soon :)

**Comment by ShivamTyagi12345** [comment]
> Is the issue resolved?

You may go ahead with this @ayushmaanshrotriya
