### ISSUE TITLE
[bug]: When Keploy is ran with application with unsupported dependencies, it encounters an error.

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In the current proxy setup, after establishing both the client and destination connections, we read from the client connection and forward it to the subsequent process. However, we have not accounted for scenarios where a dependency initiates from the server side instead of the client.

### Steps to reproduce

1. Run an application with dependencies like mysql , Keploy breaks as the first buffer that comes after TCP connection is from server not client .

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by re-Tick** [comment]
Merged changes in #731. Closing this issue
