### ISSUE TITLE
[bug]: v0.9.1 shasum has changed

### ISSUE THREAD

**Issue by p-linnane** [keploy/keploy#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. We noticed that the shasum for v0.9.1 of keploy has changed. We wanted to verify this is legitimate before updating it in our repository. Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/139424

### Steps to reproduce

N/A

### Environment

None

### Version

Local

### Repository

keploy

**Comment by re-Tick** [comment]
Hi @p-linnane, thank you for pointing it out. The change in the shasum is indeed legitimate. An object file was accidentally pushed, so we had to remove that specific commit from the git history.

**Comment by p-linnane** [comment]
Thank you!
