### ISSUE TITLE
[bug]: keploy v2 diffs are missing keys in CLI output

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#696]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, the keploy CLI diff only shows the value diff but not the CLI diff. 

<img width="965" alt="Screenshot 2023-08-16 at 5 00 43 PM" src="https://github.com/keploy/keploy/assets/12831254/372f5df3-513a-4d39-a831-923443ceb242">

### Why should this be worked on?

Keys are important for debugging. 

### Repository

keploy

**Comment by shashank-iitbhu** [comment]
@slayerjain is this issue still relevant? Please elaborate this issue a bit more.

**Comment by gouravkrosx** [comment]
@shashank-iitbhu , This issue is already resolved.
