### ISSUE TITLE
[bug]: Mongo Request is getting stored in mocks.yml

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

{ SectionSingle msg: {"ismaster":{"$numberInt":"1"},"$db":"admin"} }' 

This is a config mock request for the mongo in nodejs but it is currently stored in mocks.yml instead of the config.yml

### Steps to reproduce

1. Start the keploy v2 in record mode
2. Make the API calls
3. Go to the Mocks.yml, here the you can search for the query call :- `{ SectionSingle msg: {"ismaster":{"$numberInt":"1"},"$db":"admin"} }'`

### Environment

Deploy preview

### Version

Local

### Repository

keploy

**Comment by Sarthak160** [comment]
@Sonichigo @re-Tick Please mention the PR if this has been merged in main .

**Comment by charankamarapu** [comment]
There is no more config.yaml. Closing this issue as this issue is irrelevant now.
