### ISSUE TITLE
[bug]: docker-compose command doesn't run with keploy v2 wrapping 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the Keploy CLI in either `test` or `record` mode and attempting to run a `docker-compose up`  command, an issue arises where the command fails to execute properly. Interestingly, when the same command is changed to` docker compose up `, it functions as expected. So, need to add support to take `docker-compose ` as a valid run command. 

### Steps to reproduce

1. Install Keploy CLI version 2.
2. Navigate to a project directory containing a Docker Compose file (docker-compose.yml).
3. Run the following Keploy CLI command for test mode: `keploy test -c "docker-compose up --network backend" --containerName "flask-app" --delay 20` -> this will not work 
4. Run the following Keploy CLI command for test mode: `keploy test -c "docker compose up --network backend" --containerName "flask-app" --delay 20` -> this will work 

### Environment

Production

### Version

Local

### Repository

keploy

<details>
<summary>Checklist</summary>

- [ ] `cmd/test.go`
> * Locate the function that handles the 'test' command.
> • Find the part of the code that splits the command string into arguments.
> • Modify this part of the code to split the command string in a way that correctly handles the "docker-compose up" command.

- [ ] `cmd/record.go`
> * Locate the function that handles the 'record' command.
> • Find the part of the code that splits the command string into arguments.
> • Modify this part of the code to split the command string in a way that correctly handles the "docker-compose up" command.

</details>

**Comment by kevinlu1248** [comment]
Hey I'm a developer of Sweep, I'm taking a look at this issue.

**Comment by aerowisca** [comment]
@nehagup  Isn't this expected behaviour? IIRC, `docker-compose` was deprecated, and if you still want to use it, you need to install additional dependencies on your system for the command to work, How about when you run both the commands without keploy, does both of them work?

**Comment by nehagup** [comment]
@aerowisca yes, both of them works locally without Keploy. It was deprecated, however, it's still practically being used. If we can handle that on our end (maybe by handling an alias case), that'd be great!
