### ISSUE TITLE
[bug]: docker containers doesn't stop/get remove after running the application with Keploy 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="1429" alt="Screenshot 2023-08-17 at 7 21 33 PM" src="https://github.com/keploy/keploy/assets/15074229/40568e4a-3313-4d7b-ab7d-0c472a4bd493">

After stopping and re-running application with Keploy in any mode the previous running container for the same application doesn't stop and get removed. `docker-compose down` directly from CLI also doesn't work since it's a different user that started the container.

Temporary solution: docker rm -f <container_name> 

### Steps to reproduce

1. Run https://github.com/keploy/samples-python/tree/main/flask-mongo with `docker-compose up`
2. Record test cases
3. Stop application
4. Try to Re-record/Run test mode with Keploy. 

### Environment

Production

### Version

Local

### Repository

keploy

**Comment by AHB102** [comment]
I am new to open source, can I try to solve this issue?

**Comment by nehagup** [comment]
@AHB102 Thanks for taking the initiative, assigning this to you! Please feel to ask any questions you may have.

**Comment by AHB102** [comment]
I am currently trying to solve this issue, once I have a breakthrough I would let you know.

**Comment by AHB102** [comment]
> @AHB102 Are you still working on this issue ? Do you need any assistance regarding code base or any other blocker you are facing ??

Currently I have an mid sem to go through, it got a bit side tracked. I am having difficulty with replication of the issue. How do you actually record test cases ?

**Comment by Sarthak160** [comment]
Hi @AHB102 , You can try these steps - https://github.com/keploy/samples-go/tree/main/gin-mongo#example-url-shortener .
You will be able to replicate the problem , as soon as you will re run your application with the `keploy` command . It will show an error of container already in use just similar to [this](https://keploy.slack.com/files/U05PQ0BN1KQ/F05R1T417NV/screenshot_2023-09-02_at_1.50.11_am.png)

**Comment by nehagup** [comment]
@AHB102 are you still working on this issue?

**Comment by charankamarapu** [comment]
Hi @nehagup , regarding the issue once Keploy is exited we run a function `loadedHooks.Stop(boolean)` to stop the user application and close everything related to Keploy . This function is majorly focused on Keploy running natively(Linux) but not docker. So we need to modify those functions according to docker,  mainly `h.StopUserApplication()` function to resolve this issue
