### ISSUE TITLE
[bug]: windows binary file not exist!!

### ISSUE THREAD

**Issue by fatemeakbari** [keploy/keploy#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I read the [installation guild](https://docs.keploy.io/docs/go/installation/) path that refers to a Windows binary file. but it does not exist.
https://github.com/keploy/keploy/releases/download/v2.0.0-alpha18/keploy_windows_amd64.tar.gz
Give not found message

### Steps to reproduce

1.  go to this path: https://github.com/keploy/keploy/releases/download/v2.0.0-alpha18/keploy_windows_amd64.tar.gz

2. Show not found message

### Environment

None

### Version

Local

### Repository

keploy

**Comment by Sarthak160** [comment]
keploy v2 no longer works natively on macos (since we have moved from language level sdks to ebpf based instrumentation).
On macos we recommend using via docker and colima
And please follow the keploy Readme , as docs website is not updated yet according to V2 keploy changes .
