### ISSUE TITLE
[docs]: Mac OS download link for Keploy binary is out of date

### ISSUE THREAD

**Issue by lphillips56** [keploy/keploy#766]
### What do you want to add to the docs? (please state reasons if any)

In the Installation instructions for the Mac OS binary here: https://docs.keploy.io/docs/server/server-installation/, the following steps are given:

```
curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_darwin_all.tar.gz" | tar xz -C /tmp

sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin && keploy
```

The issue is that the download link returns a 404 error.

I think that the URL should be changed to: `https://github.com/keploy/keploy/releases/download/v0.9.1/keploy_darwin_all.tar.gz`, as that is what I am seeing as the most up to date version of the project, not including the 2.0.0 pre-release.

### Where is this stated?

This needs to be updated because it makes it more difficult for people to use the project. Instead of just copying and pasting from the documentation, you have to view previous releases to try to find a valid URL.

### Repository

docs

**Comment by Sarthak160** [comment]
keploy v2 no longer works natively on macos (since we have moved from language level sdks to ebpf based instrumentation).
On macos we recommend using via docker and colima
And please follow the keploy Readme , as docs website is not updated yet according to V2 keploy changes .

**Comment by Sarthak160** [comment]
Hey @lphillips56 , If you still want to use Keploy V1 you can download the mac binary from here https://github.com/keploy/keploy/releases/tag/v0.9.1

**Comment by lphillips56** [comment]
@Sarthak160 Thanks for the help!
