### ISSUE TITLE
[feature]:  Add interface to proxy package to make it more extendable

### ISSUE THREAD

**Issue by PranshuSrivastava** [keploy/keploy#770]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We should use interfaces for accessing structs like proxySet in the proxy package to make it more extendable.

### Why should this be worked on?

So that keploy is more extandable, and we can direcly use this interface in the future without requiring to manually write the logic again

### Repository

keploy

**Comment by EraKin575** [comment]
@PranshuSrivastava can I work on this issue?

**Comment by PranshuSrivastava** [comment]
Hey @EraKin575 , this issue was part of a project that was scraped a while back, so this issue does not need to be worked on now. Please find other issues that have been recently opened and not assigned to anyone.
