### ISSUE TITLE
[feature]: rename delay flag to --start-time

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#780]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Based on user feedback, `--delay` flag is not self-understandable and is a common expected parameter from the users. It should be renamed. 

### Why should this be worked on?

Based on user feedback, `--delay` flag is not self-understandable and is a common expected parameter from the users. It should be renamed. 

### Repository

keploy

**Comment by SaumyaBhushan** [comment]
Hi @nehagup ! I would like to work on this one .

**Comment by aerowisca** [comment]
Note that `--start-time` flag is also misleading, since a new user might think of it as an actual time, but it is in fact a duration.

**Comment by nehagup** [comment]
@SaumyaBhushan Yes, please! How about naming it `--startup-time` or `--wait-time`.

**Comment by SaumyaBhushan** [comment]
> @SaumyaBhushan Yes, please! How about naming it `--startup-time` or `--wait-time`.

Got it ! Thankyou @nehagup .

**Comment by gouravkrosx** [comment]
@nehagup are we going with the current flag `--delay` then? or it needs to be changed

**Comment by nehagup** [comment]
@gouravkrosx we can stick delay for now since its been adopted.
