### ISSUE TITLE
[bug]: keploy version missing in docker container

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Via docker, we see the following output: 

```
keploy

       ▓██▓▄
    ▓▓▓▓██▓█▓▄
     ████████▓▒
          ▀▓▓███▄      ▄▄   ▄               ▌
         ▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
       ▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
      ▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
       ▓▌                           ▐█▌                   █▌
        ▓

v0.1.0-dev

Keploy CLI

Usage:
  keploy [command]

...Other output
  ```
  The version is incorrect
  

### Steps to reproduce

1. just start keploy docker container

### Environment

None

### Version

Local

### Repository

keploy

**Comment by charankamarapu** [comment]
Hi @slayerjain normally when we do a release for binary we inject version via `.releaserc.json` into the binary . But In the `Dockerfile` which is present in the current keploy repo doesn't inject any version while build phase . We need to inject version into the Dockerfile and build phase and the bug will be resolved . As this bug is not so crucial right now I would like to mark it as Good first issue for the contributors. Please provide your thoughts

**Comment by SaumyaBhushan** [comment]
Hi @charankamarapu @slayerjain I can take this one .

**Comment by SaumyaBhushan** [comment]
It would be good if you can provide little more detail on this by passing some file references so that I can take a look into it

**Comment by charankamarapu** [comment]
Hi @SaumyaBhushan , Regarding the issue we inject version of Keploy in the Keploy binary in build phase of the binary release. You can observer that in [.releaserc.json](https://github.com/keploy/keploy/blob/main/.releaserc.json) . But if someone uses docker to run keploy they will be using dockerfile to create binary and run a container. We have missed injecting keploy version in the [dockerfile](https://github.com/keploy/keploy/blob/main/Dockerfile) . Using ldflags you need to inject keploy version in the dockerfile.

**Comment by officialasishkumar** [comment]
hey @charankamarapu, Can you please explain how exactly did you injected `.releaserc.json` in build phase?

**Comment by officialasishkumar** [comment]
@charankamarapu Sorry for the late reply. `nextRelease.version` in .releaserc.json returns v0.1.0-dev. Can you please tell me what is the correct version and where I can find it? 

Currently I am updating the `docker-compose.yaml` file with the release-version

**Comment by charankamarapu** [comment]
Hi @officialasishkumar nextRelease.version will provide the release version of next release and inject that into binary . It has no part in versions with -dev suffix, these v0.1.0-dev tags are measured at run time in main.go file and printed in the terminal if you are running keploy as a developer. Please look at [main.go](https://github.com/keploy/keploy/blob/main/main.go) file for better understanding. Rest details I have already mentioned in your PR.

**Comment by charankamarapu** [comment]
Resloved this and the keploy version in dev env shows 2-dev and for released binary it will show the original version.
