### ISSUE TITLE
[feature]: self-update keploy docker image

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#782]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Right now, while setting the alias keploy docker image is used and if there's an already existing docker image it doesn't download the latest one. The goal is to check for the latest keploy docker image and download that during setup. 

### Why should this be worked on?

Since Keploy v2 is iterating very fast, users might not upgrade image by default so it needs to be self-updating for the best user-experience. 

### Repository

keploy

**Comment by SaumyaBhushan** [comment]
Hey I would like to work on this issue but can you please guide me how to get started regarding this one ?

**Comment by aerowisca** [comment]
@SaumyaBhushan  Couple of ways to go about it. Either add `docker pull imageName:latest && oldAliasHere` or use the `--pull` command with docker run, setting `--pull always` so that the new image is pulled everytime.

**Comment by SaumyaBhushan** [comment]
Hi @aerowisca ! what I can understand from your comment is I need to update the documentation here  https://github.com/keploy/keploy#-docker-installation- where we are setting alias .
I think it should be 
`alias keploy='sudo docker run --pull always --name keploy-v2 -p 16789:16789 --network keploy-network --privileged --pid=host -it -v "$(pwd)":/files -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/bpf:/sys/fs/bpf -v /var/run/docker.sock:/var/run/docker.sock --rm ghcr.io/keploy/keploy' `

**Comment by SaumyaBhushan** [comment]
Is my understanding correct @aerowisca ?
