### ISSUE TITLE
[bug]: all test-sets not being executed in Test Mode

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I had 2 test sets in my Gin-Mongo application and during Test mode, Keploy ran 1 test set. 

 
<img width="1437" alt="Screenshot 2023-09-08 at 4 50 14 PM" src="https://github.com/keploy/keploy/assets/15074229/bce9dae0-74e5-43e4-a988-e7f98df54a1a">

### Steps to reproduce

1. Setup Gin-Mongo sample application https://github.com/keploy/samples-go/tree/main/gin-mongo 
2. Run the application in Record and Test Mode.

### Environment

Production

### Version

Local

### Repository

keploy

**Comment by AkashKumar7902** [comment]
@nehagup can you please assign me this issue

**Comment by nehagup** [comment]
@AkashKumar7902 the PR for this issue has been merged, hence closing this issue. :)
