### ISSUE TITLE
[bug]: still waiting for the container to start after tests are executed

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#784]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Once keploy is done executing test cases of an application it closes abruptly finding for containers which has already being shut down. 

<img width="1846" alt="Screenshot 2023-09-08 at 4 55 01 PM" src="https://github.com/keploy/keploy/assets/15074229/f8eedcb1-41e4-4234-a4c7-1b055aa32aa2">

### Why should this be worked on?

Creates confusion for the user for abrupt application behaviour. Needs to be cleaned.

### Repository

keploy

**Comment by gouravkrosx** [comment]
This might happen when there is more than 1 test-set or is there any other case?

**Comment by nehagup** [comment]
In my case there were 2 test-sets.

**Comment by charankamarapu** [comment]
This issue has been resolved.
