### ISSUE TITLE
[bug]: Outdated Keploy example command is mentioned in CLI.

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="1053" alt="image" src="https://github.com/keploy/keploy/assets/53110238/b7052668-b81e-4233-8184-d495d36ad6f9">

When we are using keploy with docker the alias is created with the name of `Keploy`. Therefore, the sample command won't work as instead of the alias created with name Keploy, `KeployV2` is mentioned.

### Steps to reproduce

1. Create a Keploy Alias
2. Type `Keploy` on the terminal and press enter.
3. Scroll down to example section

### Environment

None

### Version

Local

### Repository

keploy

**Comment by Akash-Singh04** [comment]
Hey, is this bug still present? I was unable to reproduce it. Kindly close the issue if it is not. Thank You

**Comment by nehagup** [comment]
@Sonichigo please check and share the url if the issue persists.

**Comment by Sonichigo** [comment]
> Hey, is this bug still present? I was unable to reproduce it. Kindly close the issue if it is not. Thank You

This issue is resolved! closing the issue.
