### ISSUE TITLE
[docs]: add meta-data to keploy-docs

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#803]
### What do you want to add to the docs? (please state reasons if any)

Global metadata needs to be added with twitter-card meta data - https://docusaurus.io/docs/3.0.0-alpha.0/seo#global-metadata.

For reference you can explore multiple card types and validate the card added by following this guide - https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

### Also, declare some json-ld structured data about Keploy

```
module.exports = {
  themeConfig: {
    // Declare some <meta> tags
    metadata: [
      {name: 'keywords', content: 'cooking, blog'},
      {name: 'twitter:card', content: 'summary_large_image'},
    ],
    headTags: [
      // Declare a <link> preconnect tag
      {
        tagName: 'link',
        attributes: {
          rel: 'preconnect',
          href: 'https://example.com',
        },
      },
      // Declare some json-ld structured data
      {
        tagName: 'script',
        attributes: {
          type: 'application/ld+json',
        },
        innerHTML: JSON.stringify({
          '@context': 'https://schema.org/',
          '@type': 'Organization',
          name: 'Meta Open Source',
          url: 'https://opensource.fb.com/',
          logo: 'https://opensource.fb.com/img/logos/Meta-Open-Source.svg',
        }),
      },
    ],
  },
};
```

### Where is this stated?

https://github.com/keploy/docs/blob/main/docusaurus.config.js

### Repository

docs

**Comment by mahfoos** [comment]
Hi, 
Can i work on this
Thanks

**Comment by nehagup** [comment]
@mahfoos sure!

**Comment by mahfoos** [comment]
Hi @nehagup 
I need some exact information for add like twitter user name also in the site once click the twitter icon its linked with on url that also wont work can i create separate issue for that ?

here the code let me know is ok?

`  themeConfig: {
    canonicalBase: 'https://www.docs.keploy.io/',
    metadata: [
      {
        description: '',
      },
      {
        name: 'x-default',
        content: 'en-us',
      },
      { name: 'description', content: 'Keploy - API Test Generator Tool' },
      { name: 'keywords', content: 'cooking, blog' },
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:site', content: '@keployio' },
      { name: 'twitter:title', content: 'Keploy Documentation' },
      { name: 'twitter:description', content: 'API Test Generator Tool' },
      { name: 'twitter:image', content: 'https://docs.keploy.io/img/favicon.png' },
    ],
    headTags: [
      // Declare a <link> preconnect tag
      {
        tagName: 'link',
        attributes: {
          rel: 'preconnect',
          href: 'https://example.com',
        },
      },
      // Declare some json-ld structured data
      {
        tagName: 'script',
        attributes: {
          type: 'application/ld+json',
        },
        innerHTML: JSON.stringify({
          '@context': 'https://schema.org/',
          '@type': 'Organization',
          name: 'Keploy',
          url: 'https://docs.keploy.io',
          description: 'API Test Generator Tool',
          logo: 'https://docs.keploy.io/img/favicon.png',
          sameAs: [
            'https://github.com/keploy/keploy',
            'https://twitter.com/keployio'
          ]
        }),
      },
    ],`


Thanks

**Comment by ganeshrevadi** [comment]
Hey @nehagup !
Created a PR (https://github.com/keploy/docs/pull/194) to solve the issue
This can be my first contribution at Keploy

Thanks!

**Comment by nehagup** [comment]
@mahfoos - @ganeshrevadi has created a PR. Also, going forward, for the review you can just make a PR, reviewing with screenshots sometimes makes it confusing. :)

**Comment by mahfoos** [comment]
@nehagup sure i will create
