### ISSUE TITLE
[feature]: set `mongo_url` as environment variable in `gin-mongo sample app`.

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#810]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

The issue with mongoURL in the gin-mongo. We can have an env variable for changing the Mongo-Host of MongoURL according to running environment. 

Right now, the code change is required from `mongoDb:27017` to `localhost:27017` under the `main.go` file, line 21, if we are running the app using Keploy native.

### Why should this be worked on?

This will help in faster execution of the sample app and would not require any changes in the main codebase by the user.

### Repository

samples-go

**Comment by 9520prashant** [comment]
Hey @Sonichigo I understood the issue, Kindly assign me this issue.

**Comment by shivamsouravjha** [comment]
Seems like a better handling has been done my comments and documents.
