### ISSUE TITLE
[bug]: navigation not working in docs website

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I go to Explanation tab, I am not able to navigate to `2.0.0` by clicking on the version dropdown. From other pages, it works fine.

### Steps to reproduce

1. Go to "docs.keploy.io"
2. Click on Explanation Tab
3. Go to dropdown button and click on the `2.0.0`

<img width="1225" alt="image" src="https://github.com/keploy/keploy/assets/53110238/aabea0f0-88ad-46e7-908d-7e5573c068f1">

### Environment

None

### Version

Cloud

### Repository

docs

**Comment by officialasishkumar** [comment]
Can you please assign this issue to me?

**Comment by nehagup** [comment]
@officialasishkumar sure!

**Comment by officialasishkumar** [comment]
Hi @Sonichigo, I don't think this is a bug. The page is by default on v2.0.0.

**Comment by Sonichigo** [comment]
Hi @officialasishkumar Yes,  by default docs is for v2.0.0 . Navigation issue is from `Explanation` tab. On clicking `2.0.0` from Dropdown, it should go to installation page where the button is linked. Now it works fine with rest pages, except any page from `Explanation` tab.

**Comment by AkashKumar7902** [comment]
Hey @Sonichigo 
Just to confirm, In [docusaurus docs](https://docusaurus.io/docs/api/themes/configuration#navbar-docs-version-dropdown), its written that:
> The user will be able to switch from one version to another, while staying on the same doc

Do you want a behaviour in which irrespective of the current page user is in, the dropdown item will redirect to a specific page ?

Regards
Akash Kumar

**Comment by nehagup** [comment]
@AkashKumar7902 yes we're expecting the drop-down item(2.0.0) to lead to https://docs.keploy.io/docs/server/windows/installation/ even when user is on explanation tab.
