### ISSUE TITLE
[feature]: add CI build workflow for docs

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#812]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

When a new PR is created it, a check should run to build and verify that the everything is working fine. 

### Why should this be worked on?

It is a good practice and would help in reviewing the pr and potentially catching the issue that could arise while deploying the website

### Repository

docs

**Comment by officialasishkumar** [comment]
Can you please assign this to me? @nehagup

**Comment by Sonichigo** [comment]
Have assigned you! 👍
