### ISSUE TITLE
[bug]: keploy crashes on slighly large responses with using node.js app

### ISSUE THREAD

**Issue by anirudhjain75** [keploy/keploy#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My response body is larger than 50KB. I'm getting the following error: 

```
🐰 Keploy: 2023-09-14T23:07:59+05:30 	INFO	hooks/loader.go:367	Exiting keploy program gracefully.
🐰 Keploy: 2023-09-14T23:07:59+05:30 	INFO	hooks/loader.go:416	eBPF resources released successfully...
2023/09/14 23:07:59 runtime error: slice bounds out of range [:24152] with length 16384
panic: runtime error: slice bounds out of range [:24152] with length 16384 [recovered]
	panic: runtime error: slice bounds out of range [:24152] with length 16384

goroutine 35 [running]:
log.Panic({0xc001b33980?, 0x107828c?, 0xe87240?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/log/log.go:432 +0x5a
go.keploy.io/server/pkg/hooks.(*Hook).Recover(0xc0003fdb00, 0x24903c63)
	/home/runner/work/keploy/keploy/pkg/hooks/loader.go:353 +0x2dc
panic({0xfc2ea0?, 0xc0000fc8b8?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f
go.keploy.io/server/pkg/hooks/connection.(*Tracker).AddDataEvent(_, {0x1784d49102b83fe7, {0x52b4, 0x1f, 0x1c7c09184d9}, 0x0, 0x5e58, 0x0, {0x48, 0x54, ...}})
	/home/runner/work/keploy/keploy/pkg/hooks/connection/tracker.go:104 +0x4a5
go.keploy.io/server/pkg/hooks.socketDataEventCallback(0xc0001b8150?, 0xc000e4a420?, 0xc0001b8c40?)
	/home/runner/work/keploy/keploy/pkg/hooks/ringBufReader.go:126 +0x39a
go.keploy.io/server/pkg/hooks.(*Hook).launchSocketDataEvent.func1()
	/home/runner/work/keploy/keploy/pkg/hooks/ringBufReader.go:70 +0x8a
created by go.keploy.io/server/pkg/hooks.(*Hook).launchSocketDataEvent in goroutine 1
	/home/runner/work/keploy/keploy/pkg/hooks/ringBufReader.go:66 +0x265
```

### Steps to reproduce

1. run keploy with node.js server
2. make sure the response is larger than 50kb.
3. keploy crashes

### Environment

None

### Version

Local

### Repository

keploy

**Comment by sarkarshuvojit** [comment]
I have understood the issue, and also located the line which is causing this. There is a hardcoded value called `EventBodyMaxSize` which is set to 16kb, if we can increase that, this issue will be resolved. 

https://github.com/keploy/keploy/blob/c012dcc6358854e45e391b74e9e94268eef94da1/pkg/hooks/structs/structs.go#L51

However how much can this be increased to? If it's too much then we'll be allocating memory we don't need / use for most cases.

In that case, can we maybe make this a more configurable amount for each user? 

I'm interested in taking this up. How should I proceed?

**Comment by gouravkrosx** [comment]
@sarkarshuvojit Thanks for showing interest in this issue. However, it has already been in the testing phase and will be resolved by Monday.
