### ISSUE TITLE
[bug]: same page linked to the next button of pagination navbar 

### ISSUE THREAD

**Issue by AkashKumar7902** [keploy/keploy#832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/keploy/keploy/assets/91385321/e2cbecdc-e944-4801-aa91-cfbfe1e20735)
The next button is showing `introduction` in the introduction page.

### Steps to reproduce

1. Go to https://docs.keploy.io/docs/keploy-explained/introduction/
2. Scroll to the navigation navbar in the bottom.

### Environment

None

### Version

Cloud

### Repository

docs

**Comment by vivekBoii** [comment]
Sir, can you tell me what we have to do
do we have to remove this element 
or link next to an another page

**Comment by 9520prashant** [comment]
> Sir, can you tell me what we have to do do we have to remove this element or link next to an another page

Nope we have to place nav item in correct manner

**Comment by AkashKumar7902** [comment]
Related : https://github.com/keploy/keploy/issues/411
