### ISSUE TITLE
[docs]: 

### ISSUE THREAD

**Issue by sceary-expert** [keploy/keploy#839]
### What do you want to add to the docs? (please state reasons if any)

curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_arm64.tar.gz" | tar xz -C /tmp
It should be replace by
curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp

### Where is this stated?

It is creating issues while setting up keploy locally.

### Repository

keploy

**Comment by nehagup** [comment]
@sceary-expert can you please clarify the issue? 

The ARM section has the `arm` binary and the AMD section should have `amd`.

**Comment by sceary-expert** [comment]
> @sceary-expert can you please clarify the issue?
> 
> The ARM section has the `arm` binary and the AMD section should have `amd`.
the issue was occuring in case of wsl (windows).
![image](https://github.com/keploy/keploy/assets/84634405/bc7adae3-9732-4b5d-9684-3c12fc08283d)

**Comment by gouravkrosx** [comment]
Actually the issue is in the keploy [docs](https://docs.keploy.io/docs/server/windows/installation/). For wsl the binary should be of amd64 and not arm64
<img width="1049" alt="Screenshot 2023-09-17 at 12 28 31 AM" src="https://github.com/keploy/keploy/assets/44055698/b877e6a5-cd30-47be-aa10-07c830476dd5">

**Comment by officialasishkumar** [comment]
```
charon@charon:~$ curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_arm64.tar.gz" | tar xz -C /tmp

sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin && keploy
[sudo] password for charon:     
bash: /usr/local/bin/keploy: cannot execute binary file: Exec format error
```
I'm facing issues while installing keploy in my linux machine. I am following the [docs](https://docs.keploy.io/docs/server/linux/installation/).

**Comment by Sonichigo** [comment]
Marking this issue as solved since the https://github.com/keploy/docs/pull/210 fixes the issue
