### ISSUE TITLE
[bug]: Keploy:Failed to start Proxy at [Port:16789]: <nil>

### ISSUE THREAD

**Issue by fatemeakbari** [keploy/keploy#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, I tried to run Keploy by following the instructions but gave me the error Keploy:Failed to start Proxy at [Port:16789]: <nil>

### Steps to reproduce

1. I install Keply on ubuntu
```
curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp

sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin && keploy
```
this is output of netstat
```
sudo netstat -lp | grep 167

[sudo] password for fateme: 

tcp6       0      0 [::]:16789              [::]:*                  LISTEN      19475/keploy 
```
and Keploy runs correctly
2. I pulled the mongoDB image and run it
```
sudo docker container ls

CONTAINER ID   IMAGE     COMMAND                  CREATED       STATUS       PORTS                                           NAMES

9ef07b36c938   mongo     "docker-entrypoint.s…"   2 hours ago   Up 2 hours   0.0.0.0:27017->27017/tcp, :::27017->27017/tcp   mongoDB

```
4.  I tried to run gin-mongo with different command but it gave me the same error 
my commands:
```
1. ~/Projects/samples-go/gin-mongo$  sudo -E keploy record -c "go run"

2. sudo keploy record -c "docker run -p 8080:8080 --name ginMongoApp  gin-app:1.0"
```

both of them give 
```
Keploy:Failed to start Proxy at [Port:16789]: <nil>
```
this error occurs in the file proxy.go line 398 because port 16789 is busy but this port is used through keploy
please help me
![Screenshot from 2023-09-18 12-42-37](https://github.com/keploy/keploy/assets/16515141/4215984a-dda2-4435-b5be-49559ffe4402)

### Environment

None

### Version

Local

### Repository

keploy

**Comment by slayerjain** [comment]
@fatemeakbari can you please try killing the keploy process with `sudo kill -9 PID`? (please replace the PID with the pid of the running keploy process which has blocked the port.

**Comment by Sarthak160** [comment]
Can you check the process already running on port 16789 ?? You can use ```lsof -i:16789```

**Comment by fatemeakbari** [comment]
> @fatemeakbari can you please try killing the keploy process with `sudo kill -9 PID`? (please replace the PID with the pid of the running keploy process which has blocked the port.

thanks
I started my system again, and my problem was solved.
