### ISSUE TITLE
[bug]: keploy throws slice error that starting of gql app

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I start the application using keploy, it throws `runtime error: slice bounds out of range [:31751] with length 16384 ` , after which the keploy exits the application and release the resources. This happens only in case of graphql api when using with keploy after the system boots up

### Steps to reproduce

`
       ▓██▓▄
    ▓▓▓▓██▓█▓▄
     ████████▓▒
          ▀▓▓███▄      ▄▄   ▄               ▌
         ▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
       ▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
      ▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
       ▓▌                           ▐█▌                   █▌
        ▓
  
v0.1.0-dev

🐰 Keploy: 2023-09-20T06:02:11Z 	INFO	cmd/record.go:110		{"keploy test and mock path": "/files/keploy"}
🐰 Keploy: 2023-09-20T06:02:11Z 	DEBUG	cmd/record.go:121	the ports are	{"ports": []}
🐰 Keploy: 2023-09-20T06:02:13Z 	INFO	hooks/loader.go:748	keploy initialized and probes added to the kernel.
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/loader.go:759		{"Keploy Inode number": 4026531836}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/loader.go:279	Sending keploy pid to kernel	{"pid": 5046}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/loader.go:762	Keploy Pid sent successfully...
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	proxy/proxy.go:277	Java is not installed on the system
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	proxy/proxy.go:448	Proxy IPv4:Port 2886795266:16789
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	proxy/proxy.go:449	Proxy IPV6:Port Addr [0 0 0 1]:16789
🐰 Keploy: 2023-09-20T06:02:13Z 	INFO	proxy/proxy.go:450	Proxy started at port:16789
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:55	Running user application on Docker	{"Docker env": "docker"}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	proxy/proxy.go:571		{"ProxyAddress4": "172.17.0.2"}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	proxy/proxy.go:574		{"ProxyAddress6": "::1"}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	proxy/proxy.go:583	Proxy server is listening on :[::]:16789
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	proxy/proxy.go:584	Proxy will accept both ipv4 and ipv6 connections	{"Ipv4": "172.17.0.2", "Ipv6": "::1"}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:66		{"Parsed container name": "secApp"}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:67		{"Parsed docker network": "keploy-network"}
🐰 Keploy: 2023-09-20T06:02:13Z 	INFO	hooks/launch.go:155	no error found while running user application container
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:369		{"executing cmd": "/usr/bin/docker run -p8080:8080 --net keploy-network --rm --name secApp sql-gql:2.1"}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:217	container created for desired app	{"ID": "a8de43f1cc3dfbaff518d67ef01019b1f7ce000c8baeacff64cae2cfe7d9feb8"}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:235	checking for container pid	{"containerDetails.State.Pid": 0}
app started on https://localhost:8080
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:235	checking for container pid	{"containerDetails.State.Pid": 6127}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:237		{"containerDetails.State.Pid": 6127}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:240	user container:(secApp) found
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:246	the user application container pid: 6127
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:248		{"user inode": 4026532646}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:253	application inode sent to kernel successfully	{"user inode": 4026532646, "time": 1695189733997684774}
🐰 Keploy: 2023-09-20T06:02:13Z 	DEBUG	hooks/launch.go:258	Network details of secApp container:map[keploy-network:0x4002b7bd40]
🐰 Keploy: 2023-09-20T06:02:14Z 	DEBUG	hooks/launch.go:282	Network Name: keploy-network, New Proxy IP: 172.20.0.6

🐰 Keploy: 2023-09-20T06:02:14Z 	DEBUG	hooks/launch.go:299	New proxy ip:2886991878 & proxy port:16789 sent to kernel
🐰 Keploy: 2023-09-20T06:02:14Z 	DEBUG	hooks/launch.go:317	the ip of the docker container: 172.20.0.5
🐰 Keploy: 2023-09-20T06:02:14Z 	DEBUG	hooks/launch.go:170	exiting from goroutine of docker daemon event listener
🐰 Keploy: 2023-09-20T06:02:14Z 	INFO	hooks/launch.go:350	container & network found and processed successfully	{"time": 1695189734137870983}
🐰 Keploy: 2023-09-20T06:02:14Z 	DEBUG	hooks/launch.go:354	processDockerEnv executed successfully
🐰 Keploy: 2023-09-20T06:02:14Z 	INFO	hooks/launch.go:121	User application started successfully
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 1, "current event size": 2016}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 4096}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:136	Got a close event from eBPF	{"TotalReadBytes": 2016, "TotalWrittenBytes": 35854}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:136	Got a close event from eBPF	{"TotalReadBytes": 2016, "TotalWrittenBytes": 35854}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 16384}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	connection/tracker.go:101	Got a data event from eBPF	{"Direction": 0, "current event size": 31751}
🐰 Keploy: 2023-09-20T06:02:34Z 	DEBUG	hooks/loader.go:348	Recover from panic in go routine	{"current routine id": 71434193, "main routine id": 502702033}
🐰 Keploy: 2023-09-20T06:02:34Z 	INFO	hooks/loader.go:365	Exiting keploy program gracefully.
🐰 Keploy: 2023-09-20T06:02:35Z 	INFO	hooks/loader.go:414	eBPF resources released successfully...
2023/09/20 06:02:35 runtime error: slice bounds out of range [:31751] with length 16384
panic: runtime error: slice bounds out of range [:31751] with length 16384 [recovered]
	panic: runtime error: slice bounds out of range [:31751] with length 16384

goroutine 22 [running]:
log.Panic({0x4000741958?, 0xbc39bf?, 0x9d00c0?})
	/usr/local/go/src/log/log.go:432 +0x60
go.keploy.io/server/pkg/hooks.(*Hook).Recover(0x4000371b00, 0x441ffd1)
	/app/pkg/hooks/loader.go:351 +0x214
panic({0xb0e300?, 0x4002c7e450?})
	/usr/local/go/src/runtime/panic.go:914 +0x218
go.keploy.io/server/pkg/hooks/connection.(*Tracker).AddDataEvent(_, {0x178686199633abce, {0x17ef, 0x4, 0xac5a8a235c86}, 0x0, 0x7c07, 0x1000, {0x7b, 0xa, ...}})
	/app/pkg/hooks/connection/tracker.go:104 +0x3c0
go.keploy.io/server/pkg/hooks.socketDataEventCallback(0x4000146230?, 0x4002c558a0?, 0x4000146d20?)
	/app/pkg/hooks/ringBufReader.go:126 +0x3e4
go.keploy.io/server/pkg/hooks.(*Hook).launchSocketDataEvent.func1()
	/app/pkg/hooks/ringBufReader.go:70 +0x7c
created by go.keploy.io/server/pkg/hooks.(*Hook).launchSocketDataEvent in goroutine 1
	/app/pkg/hooks/ringBufReader.go:66 +0x218
`

### Environment

None

### Version

Local

### Repository

keploy

**Comment by re-Tick** [comment]
Hi @Sonichigo, i am able to replicate the error. please assign it to me.
