### ISSUE TITLE
[bug]: `sudo:/app/keploy` command not found when running keploy docker image

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- When attempting to build and run a Docker image created via a Dockerfile, a 'sudo: /app/keploy' command not found error is encountered. This error arises because the Dockerfile runs a binary named 'keploy' and there is also a 'keploy' folder at the same location used to store keploy-generated tests.

### Steps to reproduce

1. Clone the 'keploy' repository and configure it on your local machine.
2. Create a folder named 'keploy' in the same location using `mkdir keploy`
3. Build keploy docker image using `sudo docker build -t keploy .`
4. When you run the 'keploy' image using `sudo docker run keploy`, you will encounter the same error.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by gouravkrosx** [comment]
![image](https://github.com/keploy/keploy/assets/44055698/1f5e2c08-a950-4c4b-87db-82056d6cbecc)

**Comment by kadern0** [comment]
Cannot reproduce it either.

**Comment by AniketNS** [comment]
Hey @gouravkrosx, Can I work on this issue?

**Comment by gouravkrosx** [comment]
Sure @AniketNS.
@kadern0 What problems are you facing while reproducing it?

**Comment by CharvinKhanpara** [comment]
Hello, i and @KrupalUpadhyay are willing to work on it. 
@gouravkrosx, Can we contribute ?

**Comment by gouravkrosx** [comment]
@CharvinKhanpara Anyone can contribute to this good first open-source issue.

**Comment by CharvinKhanpara** [comment]
![Screenshot 2023-12-23 145220](https://github.com/keploy/keploy/assets/154613383/4339b241-cf22-4405-9b29-19b69686c7a7)

@gouravkrosx what kind of output you are expected to come after solving the issue.

**Comment by KrupalUpadhyay** [comment]
@gouravkrosx, I reproduced and run docker image in my local docker engine. I didn't encounter such an error, docker image runs successfully and it creates a container. Can you elaborate by which method you run it so I could understand the bug you mentioned.

**Comment by gouravkrosx** [comment]
@KrupalUpadhyay @CharvinKhanpara  Let me reproduce at my end once again.

**Comment by bablysingh2409** [comment]
Hi @gouravkrosx ,can I work on this issue

**Comment by CharvinKhanpara** [comment]
> @KrupalUpadhyay @CharvinKhanpara Let me reproduce at my end once again.

Okay !

**Comment by slayerjain** [comment]
I think this issue happens when we have keploy folder, and then try to build the docker image. 

A quick fix could be changing the `keploy` binary name to something like `keployBin` here - https://github.com/keploy/keploy/blob/1ceee91e12df5bae4fae078f4ab98688cd47e93a/Dockerfile#L19

And then while copying to the runtime stage changing this back to `keploy` here - https://github.com/keploy/keploy/blob/1ceee91e12df5bae4fae078f4ab98688cd47e93a/Dockerfile#L41

**Comment by Swpn0neel** [comment]
does this issue still persist? @gouravkrosx
