### ISSUE TITLE
[docs]: replace images with local image links

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#877]
### What do you want to add to the docs? (please state reasons if any)

on docs website the https://docs.keploy.io/application-development/ link has images that should refer to the images from local directory in img/os/*

### Where is this stated?

to avoid broken images in case source changes. 

### Repository

docs

**Comment by OmAximani0** [comment]
Hi @nehagup , Do you mean we have to do something like below and link it to `src` ?
```js
import windowsLogo from 'path/to/image';
```

**Comment by ganeshrevadi** [comment]
> Hi @nehagup , Do you mean we have to do something like below and link it to `src` ?
> 
> ```js
> import windowsLogo from 'path/to/image';
> ```

Hey I think it's about creating a new directory named `os` which contains the os logos inside the `img` directory.
Correct me if I am wrong! @nehagup :-)

**Comment by OmAximani0** [comment]
> @OmAximani0 we don't need to import the image but can directly reference relative path in src of img element. 

Ok ok, got it 👍. Can you please assign this to me.

**Comment by charankamarapu** [comment]
this issue has been resolved.
