### ISSUE TITLE
[feature]: Give an option to user to name testcases

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#880]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

There are many situations where user want to give a proper name their testcases like GetEmployeeSuccessful, GetEmployeeValidationError etc which gives them lot of info regarding their tests. Right now keploy has no such option where we allow user to name the tests . User has to rename the test case manually . 

A feature can introduced where user can give the name for tests. This cannot be done at CLI because once record starts there can be n number of tests that user can create and we cannot give an option in CLI to name test in the middle of record command execution. There can be a way at the API level when user will hit a request, user can add an header which says Keploy_Test_Name and we need to handle it where we capture the incoming request and name the test with that Keploy_Test_Name.

### Why should this be worked on?

Its a good user exeperience

### Repository

keploy

**Comment by AkashKumar7902** [comment]
@charankamarapu can you please assign me this issue?

**Comment by charankamarapu** [comment]
ok

**Comment by charankamarapu** [comment]
Please make an issue in the docs to mention this feature and link that issue here so that I can close this issue . Try if you can also complete the doc issue.
