### ISSUE TITLE
[feature]: Add curl section in the testcase yamls

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#881]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Lets say user has hit a requests a testcase is created . Lets say user is trying after quite a few days or lost the curl user was using . To reconstruct the testcase which user has created user wants to hit the request again but he needs to create the curl from scratch looking at the created testcase . This problem can also occur when user has too many curls or testcases. So it will be better if we add a curl section in the testcase where user can use this curl recreate that request in no time.

### Why should this be worked on?

For good user exeperince

### Repository

keploy

**Comment by AkashKumar7902** [comment]
Hey @charankamarapu, what fields will the curl section contain ?

**Comment by charankamarapu** [comment]
Hi @AkashKumar7902 , It will contain the curl command of the test case recorded

**Comment by AkashKumar7902** [comment]
@charankamarapu is this looking good ?
![image](https://github.com/keploy/keploy/assets/91385321/346704cf-2e6a-40c8-8adc-2890318016d2)

**Comment by AkashKumar7902** [comment]
Also, do you want me to remove the headers like Content-Length which are calculated when request is sent ?
Simply copy pasting the above curl is giving "failed to decode req" error because of these headers
![image](https://github.com/keploy/keploy/assets/91385321/b788e216-8445-4abe-ba41-1c82c1743285)

**Comment by charankamarapu** [comment]
Yes you can remove those headers which are calculated at run time because we have saved the request which was sent by the user but we may not be sure that we got everything that user sent majorly headers like the content-length may vary . So you can remove the content length header and Great work!
