### ISSUE TITLE
[bug]: `failed to convert ip string:[] to 32-bit integer` when running keploy in docker environment

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When user runs keploy in docker environment and doesn't provide network name in its docker run command, keploy throws this error:
`"failed to convert ip string:[] to 32-bit integer"`
```shell
$ keploy record -c "sudo docker run --name httpsApp -p8080:8080 --rm  https-app"

       ▓██▓▄
    ▓▓▓▓██▓█▓▄
     ████████▓▒
          ▀▓▓███▄      ▄▄   ▄               ▌
         ▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
       ▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
      ▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
       ▓▌                           ▐█▌                   █▌
        ▓
  
-dev

🐰 Keploy: 2023-09-26T09:08:03Z         INFO    cmd/record.go:110               {"keploy test and mock path": "/files/keploy"}
🐰 Keploy: 2023-09-26T09:08:06Z         INFO    hooks/loader.go:753     keploy initialized and probes added to the kernel.
🐰 Keploy: 2023-09-26T09:08:06Z         INFO    proxy/proxy.go:485      Proxy started at port:16789
🐰 Keploy: 2023-09-26T09:08:06Z         INFO    hooks/launch.go:155     no error found while running user application container
🐰 Keploy: 2023-09-26T09:08:07Z         ERROR   hooks/launch.go:346     failed to process the user application container or network   {"err": "failed to convert ip string:[] to 32-bit integer"}
🐰 Keploy: 2023-09-26T09:08:07Z         ERROR   record/record.go:61     failed to process user application hence stopping keploy      {"error": "failed to convert ip string:[] to 32-bit integer"}
🐰 Keploy: 2023-09-26T09:08:07Z         INFO    hooks/loader.go:370     Exiting keploy program gracefully.
Updating certificates in /etc/ssl/certs...
🐰 Keploy: 2023-09-26T09:08:07Z         INFO    hooks/loader.go:419     eBPF resources released successfully...
🐰 Keploy: 2023-09-26T09:08:07Z         INFO    proxy/proxy.go:1114     proxy stopped...
```
This scenario may arise in applications that rely on external HTTP dependencies, eliminating the need to establish connections between your application and other containers within the same Docker network.

### Steps to reproduce

1. Setup keploy locally.
2. Set alias as `alias keploy='sudo docker run --pull always --name keploy-v2 -p 16789:16789 --privileged --pid=host -it -v "$(pwd)":/files -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/bpf:/sys/fs/bpf -v /var/run/docker.sock:/var/run/docker.sock --rm ghcr.io/keploy/keploy'`
3. Run you application without giving the docker network flag.
`keploy record -c <your docker run command>`

### Environment

None

### Version

Local

### Repository

keploy

**Comment by sajdakabir** [comment]
Hey @gouravkrosx , I would like to work on this issue. can you assign it to me?

**Comment by gouravkrosx** [comment]
Sure @sajdakabir , You can work on this.

**Comment by EraKin575** [comment]
@gouravkrosx is this issue still there?

**Comment by gouravkrosx** [comment]
Aren't you able to replicate it?

**Comment by EraKin575** [comment]
![image](https://github.com/keploy/keploy/assets/100225222/6864c95b-f0f7-4596-baec-1d17c944da66)

**Comment by gouravkrosx** [comment]
Okay, so earlier we were injecting docker network used by the application to the keploy container dynamically. It created some problems in the case where databases don't have retry mechanism. So it is mandatory now to give container name, we have changed the approach of injecting the user defined network to keploy. This issue is now irrelevant, we can now close this issue.
