### ISSUE TITLE
[refactor]: remove the commented code

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#887]
Refactor the redundant commented code from the source code. 
### Why this should be worked on:
This will improve the code quality.

**Comment by VoidVampire** [comment]
I have few questions regarding this.

There are documentation comments as well as code comments, should I assume all commented code is obsolete and ready to delete? I can see some obsolete code comments ready to delete such as in structs.go in pkg/hooks/struct but I am not sure about others.

There are files such as error.go in pkg/hooks/keploy where apart from "package .." everything else is commented, what should be done about that?

**Comment by sajdakabir** [comment]
Hey @re-Tick, I would like to work on this issue . can you assign it to me?

**Comment by re-Tick** [comment]
Hi everyone, the issue is open for all. You can make your changes and make PR or discuss them here.

**Comment by re-Tick** [comment]
Yes @VoidVampire, go files like errors.go can be removed. But we need the comments to exists, only the commented code can be deleted

**Comment by sajdakabir** [comment]
Hey @re-Tick do we just have to remove the commented code or also remove the comment that describes what that function doing?

As example :
```
// Plugins is an interface used to define plugins.
type Plugins interface {
	GetCmd() *cobra.Command
}
```

should I remove this comment too?

**Comment by VoidVampire** [comment]
Hi @re-Tick I have performed few code comments deletions and did a [PR](https://github.com/keploy/keploy/pull/891), please check it out.

**Comment by aditii46** [comment]
Hey, I would like to contribute here. Is this PR closed by any chance since I can see pull request and commits being made. If you can let me know than If comments are still pending, I can start working on it right away.

**Comment by re-Tick** [comment]
Thank you everyone for your contributions and insights on this matter.

After careful consideration, we have decided to close this issue and merge PR #891. It offers a more streamlined approach, with a significant reduction in code and relevant changes.
