### ISSUE TITLE
[bug]: unable to delete keploy containing tests & mocks folder without sudo 

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I recorded some test cases & mocks. When I tried to delete the keploy folder without a sudo user, it displayed permission denied. 

<img width="268" alt="Screenshot 2023-09-27 at 12 26 05 PM" src="https://github.com/keploy/keploy/assets/44055698/8e34b4e5-3e0c-4623-891f-edf5e52b9902">

### Steps to reproduce

1. Set up keploy locally.
2. Record some test cases & mocks.
3. Try deleting the keploy folder without the sudo user.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by AkashKumar7902** [comment]
@gouravkrosx can you please check filemode value in fs.go
![image](https://github.com/keploy/keploy/assets/91385321/ef5a6faa-8380-4785-9d94-c42a266577a4)

**Comment by gouravkrosx** [comment]
Its same.
`ModePerm FileMode = 0777 // Unix permission bits`

**Comment by charankamarapu** [comment]
This has been resolved.
