### ISSUE TITLE
[feature]: add Copy Button for Code Blocks/Commands

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#896]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently, Docusaurus allows for the inclusion of code blocks and commands within documentation pages, which is essential for providing code examples and instructions. However, there is a missing usability feature that would greatly enhance the user experience – the ability to easily copy code or commands from these blocks.

**Feature Request:**

We propose adding a "Copy" button next to code blocks and command examples. When users click on this button, it should automatically copy the content of the block to their clipboard. This feature would significantly improve the ease of using code and commands provided in our documentation.

### Why should this be worked on?

Improved user experience: Users can quickly copy code or commands without having to manually select and copy text.
Reduces errors: Copying directly from the code block reduces the risk of typographical errors when users manually retype code.
Increases code usability: Encourages users to experiment with code examples, ultimately leading to better understanding and adoption of our platform.

### Repository

docs

**Comment by NEMYSESx** [comment]
Hey, I like the idea of adding this feature.  Can I contribute to it?

**Comment by NEMYSESx** [comment]
This is my first time contributing to open source so can you like give me a follow up or guide into this

**Comment by nehagup** [comment]
Hey @NEMYSESx please feel free to open a PR. Please follow https://github.com/keploy/docs for contribution guidelines

**Comment by NEMYSESx** [comment]
Okay I'm onto it👍

**Comment by aditii46** [comment]
Hey, I didn't see a PR being raised on this issue yet. So, can I contribute to this set of task? It is my first time for open source contribution too.

**Comment by 9520prashant** [comment]
Hey @nehagup , can you please assign me this issue, I have started working on this issue.

**Comment by 0xVikasRushi** [comment]
i tried for to implement to copy button in Docusaurus v2

Note : Keploy uses v2.4.1 Docusaurus

## Method 1 : 
Adding custom.css and custom code-block-buttons.js using gist mentioned by  Docusaurus Community but gist fix is for v1 [reference ](https://gist.github.com/yangshun/55db997ed0f8f4e6527571fc3bee4675)
## Method 2: 
I have encountered issue with custom `src/theme/DocItem ` and by upgrading all @Docusaurus packages to v2.4.3 (CodeBlock included) and removing DocItem folder.
```
    "@docusaurus/core": "^2.4.3",
    "@docusaurus/plugin-sitemap": "^2.4.3",
    "@docusaurus/preset-classic": "^2.4.3",
```

By this Method we can achieve copy button but layout for whole website is changed and its not correct approach


![image](https://github.com/keploy/keploy/assets/88543171/6462714e-d1d3-4f84-8d39-ea4189d22c93)

**and we don't have many customization options for DocItem. @nehagup **

**Comment by nehagup** [comment]
Thanks for looking it up @0xVikasRushi ! Closing this for now.
