### ISSUE TITLE
[bug]: in docker, keploy throws error after running the test run.

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am getting this output:-
```
🐰 Keploy: 2023-09-27T09:24:53Z         ERROR   test/test.go:182        failed to run user application hence stopping keploy      {"error": "exited due to command error"}
go.keploy.io/server/pkg/service/test.(*tester).RunTestSet.func2
        /app/pkg/service/test/test.go:182
```

### Steps to reproduce

1. Run the Keploy in TestMode

### Environment

None

### Version

Self-hosted

### Repository

keploy

**Comment by charankamarapu** [comment]
this will be resolved by this pr - https://github.com/keploy/keploy/pull/904
