### ISSUE TITLE
[docs]: add docs for arm arch in Linux installation instruction 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#898]
### What do you want to add to the docs? (please state reasons if any)

Like this https://github.com/keploy/keploy#download-the-keploy-binary installation instructions for arm arc needs to added to linux/Windows installation instruction in docs website.  

### Where is this stated?

Missing info from docs website.

### Repository

docs

**Comment by AkashKumar7902** [comment]
hey @nehagup,
can you please assign me this issue ?

**Comment by charankamarapu** [comment]
this issue has been resolved.
