### ISSUE TITLE
[bug]: in Node.js, `keep-alive` is present by default

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I make the API call using either Postman, Hoppscotch or even cURL command. In response by default `Connection`:`keep-alive` is present. 

Until, the keep-alive is present in the request by user while making the API call itself, it shouldn't be present.

### Steps to reproduce

1. use a Nodejs app.
2. Make a API call by keeping the `Connection`:`keep-alive` off. using postman or https://hoppscotch.io. 
3. Check the Header response and `test-x.yml` generated under keploy folder.
4. You can find `connection:keep-alive` present in the response

### Environment

None

### Version

Local

### Repository

samples-typescript

**Comment by AkashKumar7902** [comment]
@Sonichigo do you have any sample node.js ?

**Comment by Sonichigo** [comment]
@AkashKumar7902 you can find the sample app here :- https://github.com/keploy/samples-typescript/tree/main/express-mongoose

**Comment by gouravkrosx** [comment]
@Sonichigo I think #931 also fixed this issue. Can you please check on your end if you're getting the same behavior after my changes?

**Comment by Sonichigo** [comment]
@gouravkrosx yeah, the issue is fixed with the PR. So closing the issue! @AkashKumar7902 You can try some new good first issues!!
