### ISSUE TITLE
[docs]: add contribution guidelines of docs repo as a page

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#905]
### What do you want to add to the docs? (please state reasons if any)

add the contribution guidelines from docs repo https://github.com/keploy/docs to https://docs.keploy.io/docs/keploy-explained/contribution-guide/ as a separate page! 

### Where is this stated?

For ease of use for contributors.

### Repository

docs

**Comment by sambhavgupta0705** [comment]
@nehagup I can try working on this issue

**Comment by sambhavgupta0705** [comment]
@nehagup just need a clarification of what do we mean by seperate page??

**Comment by sambhavgupta0705** [comment]
And what should be the name of the page ??

**Comment by nehagup** [comment]
@sambhavgupta0705 you can name it Docs Dev Guide

**Comment by AkashKumar7902** [comment]
@nehagup do we need add all the content from [CONTRIBUTING.md](https://github.com/keploy/docs/blob/main/CONTRIBUTING.md) to the docs website ?

**Comment by AkashKumar7902** [comment]
@nehagup please assign me this issue

**Comment by nehagup** [comment]
Hey @AkashKumar7902 the PR has been made for this by @sambhavgupta0705. Please pick another issue.
