### ISSUE TITLE
[feat]: add a new samples app using java & mongo

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#913]
- Create a CRUD application using Java and MongoDB.
- Use the Keploy to test the app and create at least 3 testcases.
- Create a Readme containing the method to run the application with Keploy using Docker and Natively
- Make a PR to [Keploy/Samples-java](https://github.com/keploy/samples-java) repository

**Comment by Siddheshuncodes** [comment]
Interested in contributing to the following issue: Create a CRUD application using Java and MongoDB.

I have experience with Java and MongoDB and I am eager to get started.

**Comment by Sonichigo** [comment]
@Siddheshuncodes assigned the issue to you!

**Comment by Sonichigo** [comment]
Hey @Siddheshuncodes, can you share progress if you are currently working on this issue?

**Comment by Sonichigo** [comment]
> I haven't started yet got ill I will soon start working on it

Hope you are better now!

**Comment by Sonichigo** [comment]
hey @Siddheshuncodes any update regarding the progress?

**Comment by Shubham005x1** [comment]
Hey @Sonichigo  is there any update? Is @Siddheshuncodes still working on it. If he isn't working on it, I can. Assign me if there is no response from his side

**Comment by Sonichigo** [comment]
@Siddheshuncodes Since we haven't back from you for quite a bit on the progress! I'm assign the issue to @Shubham005x1

**Comment by IllTamer** [comment]
Hey @Sonichigo, I'm new here and I'd like to address this as my first PR. I noticed @Shubham005x1 removed his assignment, can you assign it to me ? : )

**Comment by Sonichigo** [comment]
hey @IllTamer !! sure! lmk if you need any help!
