### ISSUE TITLE
[feat]: add a new samples app using typescript & nhost

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#914]
- Create a sample App using Typescript and using nhost.io as Backend as a service.
- Use the Keploy to test the app and create at least 3 testcases.
- Create a Readme containing the method to run the application with Keploy using Docker and Natively
- Make a PR to [Keploy/Samples-typescript](https://github.com/keploy/samples-typescript) repository

**Comment by Anuragwagh** [comment]
I'm interested in contributing to the dd a new samples app using typescript & nhost #914 issue. I have experience with Typescript and nhost.io, and I'm eager to get started.

**Comment by nehagup** [comment]
@Anuragwagh sure. Please take that up.

**Comment by Anuragwagh** [comment]
@nehagup Thanks

**Comment by Sonichigo** [comment]
Hey @Anuragwagh , can you share progress if you are currently working on this issue ?

**Comment by Anuragwagh** [comment]
Hello @Sonichigo I am working on it , stuk in exams

**Comment by Sonichigo** [comment]
Hey @Anuragwagh any progress update ?

**Comment by 0xVikasRushi** [comment]
Hi @Sonichigo

I can take up this issue

**Comment by nehagup** [comment]
@0xVikasRushi please feel free to contribute!

**Comment by CypherpunkSamurai** [comment]
Hi is this issue active? I would like to contribute :)

**Comment by Sonichigo** [comment]
Hey there! yeah this issue is still active !! feel free to reach out on our slack in case you need support : )

_Useful links for you:_
T**ypescrip/JS x Keploy Sample Apps** - https://github.com/keploy/samples-typescript
**Keploy docs** - https://keploy.io/docs

**Comment by sammaji** [comment]
Is this issue still being worked on. If yes, I would like to take it up,

**Comment by Sonichigo** [comment]
Hey @sammaji , yes
