### ISSUE TITLE
[feature]: add support for running a particular test case in the test-set

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#915]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Currently when test mode is run , it loads all the testcases of test-set and run the entire test suite .
- But if someone wants to run a particular testcase of that set it should be able to run that testcase instead of all .
- By adding a flag like : --test-set:0 and --tescase:3 can be used as an input and test run logic can be changed according to this .

### Why should this be worked on?

This feature will be helpful for users having huge set of testcases , and are willing to test a specific feature or module .

### Repository

keploy

**Comment by charankamarapu** [comment]
Hi @Sarthak160 Just a small note that this [issue](https://github.com/keploy/keploy/issues/916) should be resolved before merging the feature you proposed.

**Comment by Sarthak160** [comment]
Since timestamp PR #1023 has been merged , this issue can be picked now !
