### ISSUE TITLE
[bug]: TestCase deletion from test-set causing test run failure

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently In a test-set we include all the tests and one mock file with all the mocks included. Deleting one or two test cases from test-set will cause a mismatch between test case and its respective mock . Please go through Steps to reproduce section to understand the issue clearly.

### Steps to reproduce

1. Run Keploy with a sample app and a database.
2. Make an `insert` api call.
3. Make a `read_all` api call.
4. Make an `insert` api call.
5. Make a `read_all` api call.
6. Test cases and mocks will be recorded.
7. Now delete the first three test cases .
8. Do a testrun 
9. The testrun is going to fail because the mock request call for first `read_all` call and second `read_all` call is same but the response is different . When we go for matching the second `read_all` will be matched with first  `read_all` call and response sent will be different.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by Bhanuteja01** [comment]
i like to work on this issue 
@charankamarapu assign me this issue

**Comment by nehagup** [comment]
@Bhanuteja01 sure.

**Comment by Bhanuteja01** [comment]
@nehagup
Can you explain how to approach this issue

**Comment by charankamarapu** [comment]
hi @Bhanuteja01 Assuming that you have understood the problem that tests and mocks currently doesn't have any parameter that connects them . Firstly you need to come up with a solution that connects them then only we can match the mocks with more info and more precision
