### ISSUE TITLE
[feature]: Allow mockrecord to be used without unit tests as well.

### ISSUE THREAD

**Issue by PranshuSrivastava** [keploy/keploy#925]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently mockrecord can only be used by integrating keploy into unit tests and running the go test command. The task is to make the mockrecord command run like a standalone command, like the record command currently works. The user can just run the mockrecord command whenever he wants to record mocks regardless of the fact whether he has written unit tests or not.

### Why should this be worked on?

This will provide more flexibility to the user who wants to use the mockrecord feature of Keploy.

### Repository

keploy

**Comment by EraKin575** [comment]
I would like to work on this

**Comment by PranshuSrivastava** [comment]
Sure @EraKin575. You can use [this](https://github.com/keploy/go-sdk/pull/194) PR for reference.

**Comment by EraKin575** [comment]
![image](https://github.com/keploy/keploy/assets/100225222/f7ccea29-ec84-40f8-a479-57211889eee1)
 @PranshuSrivastava  is this the error we receive. I am new to this project

**Comment by EraKin575** [comment]
Hi @PranshuSrivastava .. I want to test how mockRecord command works like what should be the actual behavior of the command when its integrated with unit test and when it is not.Will you help me?

**Comment by PranshuSrivastava** [comment]
To see the response of the mockrecord and mocktest command, you can add the unit test that is provided in the previously mentioned PR to the gin-mongo project in the samples-go repo of Keploy. Just add the code to a file called main _test.go. After that, as you can see in the code, a Keploy mode is defined in the configuration, change that more mode to MODE_RECORD and run `go test`. This should create a folder called stubs and a mock inside that folder. To test with that mock, just change the mode to MODE_TEST and run `go test` again. Keploy will automatically start and serve the mock, and the test should pass.

**Comment by PranshuSrivastava** [comment]
Additionally, you can also remove the TestGetURL function from the test file provided in the PR, as Keploy is not integrated into that test.

**Comment by EraKin575** [comment]
thanks  @PranshuSrivastava . I did the steps and was able to get the results. I will submit a PR to this issue soon

**Comment by EraKin575** [comment]
@PranshuSrivastava if we wish to run mockrecord as a standalone command,  should I remove the pid flag and replace it with a default one from os package in go

**Comment by PranshuSrivastava** [comment]
No, we cannot remove the MarkAsRequired for the target application's pid because we need the pid to load our hooks and record the traffic from the user application. You can check how the pid is being used in other services like record. You can go to pkg/service/record/record.go

**Comment by gouravkrosx** [comment]
This feature has been temporarily removed, hence closing this issue.
