### ISSUE TITLE
[feature]: Allow mocktest to be used without unit tests as well.

### ISSUE THREAD

**Issue by PranshuSrivastava** [keploy/keploy#926]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently mocktest can only be used by integrating keploy into unit tests and running the go test command. The task is to make the mocktest command run like a standalone command, like the test command currently works. The user can just run the mocktest command whenever he wants Keploy to serve the mocks that he recorded using mockrecord command regardless of the fact whether he has written unit tests or not.

### Why should this be worked on?

This will provide more flexibility to the user who wants to use the mocktest feature of Keploy.

### Repository

keploy

**Comment by kfayazuddin** [comment]
Can i work on this issue

**Comment by PranshuSrivastava** [comment]
Sure @kfayazuddin go ahead! You can refer to [this](https://github.com/keploy/go-sdk/pull/194) PR for some more context.

**Comment by AkashKumar7902** [comment]
Hey @PranshuSrivastava is there any guide on how to use mocktest in current version ?

**Comment by PranshuSrivastava** [comment]
@AkashKumar7902 You can take a look at this https://github.com/keploy/keploy/issues/925#issuecomment-1742385643

**Comment by PranshuSrivastava** [comment]
@kfayazuddin, have you been able to make any progress on this issue?

**Comment by officialasishkumar** [comment]
Hey @PranshuSrivastava, Can you give an example of the command with all the flags?

**Comment by PranshuSrivastava** [comment]
@officialasishkumar I have given all the steps in detail in the above comments. Could you please try to follow them and let me know if you face any problem.

**Comment by gouravkrosx** [comment]
This feature has been temporarily removed, hence closing this issue.
