### ISSUE TITLE
[bug]: Header diffs sometimes misses the keys

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Headers many times are missing the keys and that makes it hard to understand. 

<img width="902" alt="Screenshot 2023-10-02 at 2 39 52 PM" src="https://github.com/keploy/keploy/assets/12831254/dbde6f11-031b-4799-8f4e-5847444f1792">

### Steps to reproduce

1. Try the gin-mongo sample app. 
2. Change the return address manually. 
3. Header diff should not contain keys. 

### Environment

None

### Version

Local

### Repository

keploy

**Comment by dankomar** [comment]
Hi, can u assigne me to this?

**Comment by AkashKumar7902** [comment]
@slayerjain also if multiple header values mismatch only the last mismatched diff will be displayed.
