### ISSUE TITLE
[docs]: Remove the `--rm` flag from record and test command

### ISSUE THREAD

**Issue by 404fixer** [keploy/keploy#946]
### What do you want to add to the docs? (please state reasons if any)

Remove the `--rm` flag from record and test command from every repository.

### Repository

docs

**Comment by swatichauhan814** [comment]
Hi, 

I would like to work on this. Can you please assign to me ? @404fixer

**Comment by 404fixer** [comment]
Sure @swatichauhan814, assigning it to you.

**Comment by EraKin575** [comment]
@404fixer  can I work on this issue too?
