### ISSUE TITLE
[docs]: Minor fixes in dev-guide

### ISSUE THREAD

**Issue by 404fixer** [keploy/keploy#947]
### What do you want to add to the docs? (please state reasons if any)

Make the following changes in the [dev-guide](https://docs.keploy.io/docs/keploy-explained/contribution-guide/):
1. Add `--pull always` flag in the alias when using the deployed keploy binary image. It is under the **Setup Keploy via Docker** heading.
2. Fix the numbering of the headings. Currently, it is 6 and 6. Make it 6 and 7.
3. Under the heading **Testing Locally Built Docker Image**, fix the build docker image command to `docker build -t <nameOfImage> .`. And add the description to run this command inside the keploy repository and make sure there is no directory by the name of `keploy` inside the main keploy repository while building the image.

### Repository

docs

**Comment by Jaideep1702** [comment]
can you assign me this issue.

**Comment by Sonichigo** [comment]
Hey @Jaideep1702 assigned the issue to you!

**Comment by Jaideep1702** [comment]
Hello there, I have submitted a pull request (PR). Please check and confirm it.
https://github.com/keploy/docs/pull/229

**Comment by Jaideep1702** [comment]
any update @404fixer and @Sonichigo?
