### ISSUE TITLE
[feature]: create a keploy config file for the user specific modifications

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#948]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently keployv2 has improved it's CLI experience, which offers a comprehensive set of commands and flags, we recognize that users may sometimes find it cumbersome to specify numerous flags and parameters repeatedly. This can make executing test scenarios less straightforward, especially when dealing with complex setups.

To simplify the user experience and make Keploy more user-friendly, we're introducing the concept of a Keploy configuration file. This YAML-based file will allow users to define their testing configurations, including container setups, delays, and any other relevant parameters.

**Key Benefits:**

- Reduced Command Complexity: Users can define their configurations in a single, easy-to-read file, reducing the need for extensive command-line arguments.

- Improved Reusability: Configuration files can be reused across multiple testing scenarios, promoting consistency and saving time.

- Enhanced Clarity: Configuration files offer a clear and structured way to document test setups, making it easier to collaborate with team members.

**Example Usage:**
Suppose you have a specific testing environment that involves running a Docker container with specific network settings, delays, and other parameters. Instead of specifying these details on the command line each time, you can define them in a Keploy configuration file, such as keploy-config.yaml:

```
# keploy-config.yaml
containerName: my-container
applicationImage: my-app-image
network: keploy-network
delay: 1

```

### Why should this be worked on?

We're excited to implement this feature and make Keploy even more user-centric. Our plan is to support configuration files, allowing users to define their testing environments efficiently. Additionally, we'll provide detailed documentation on how to create and use these configuration files effectively.

### Repository

keploy

**Comment by AkashKumar7902** [comment]
hey @Sarthak160 Can you please assign me this issue ?

**Comment by AkashKumar7902** [comment]
@Sarthak160 I think there would be a need to create a different config files for test and record commands as there are additional flags in test.
