### ISSUE TITLE
[feature]: add support for running a given test-sets in test cmd

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#952]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Currently on running the test cmd of Keploy CLI, all the test-sets are executed synchronously.
- But there should be a way to run certain test-sets or a test-set.
- There can be a cmd flag for an array of test-sets to be run by test cmd. By default, test command will run all the recorded test-sets.

### Why should this be worked on?

If someone has recorded some test-sets for their current changes, then they can run the newly recorded test-sets using the same test cmd.

### Repository

keploy

**Comment by AkashKumar7902** [comment]
@re-Tick can you please assign me this issue ?

**Comment by re-Tick** [comment]
Hi @AkashKumar7902, thanks for picking this up. The issues is open for all. You can discuss your proposed changes here or can link your PR.
