### ISSUE TITLE
[feature]: update samples java according to v2 compatibility 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#955]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Since now keploy is more focused on keployV2 and it's important to update all our samples according to it .
- It has been already done in go sample apps - https://github.com/keploy/samples-go/tree/main/echo-sql. 
- This has to been done with [samples java](https://github.com/keploy/samples-java) as well .
- Things to do are just to remove Keploy SDK import remove from pom.xml and main class file .
- Then update the readme according to v2 and move the current main branch to another branch as V1 , as done [here](https://github.com/keploy/samples-go/tree/v1) .

### Why should this be worked on?

This should be worked for users who want to try java sample app , along with v2 functionality . 
To experience seamless integration without any code change ; ) .

### Repository

keploy

**Comment by Bhanuteja01** [comment]
@Sarthak160 assign me this issue

**Comment by Bhanuteja01** [comment]
@Sarthak160 i like to work on this issue

**Comment by Sarthak160** [comment]
@Bhanuteja01 , You can just raise the PR Now , If you have completed !

**Comment by Sonichigo** [comment]
@Bhanuteja01 Any update regarding the PR ? Are you working on this ?

**Comment by Bhanuteja01** [comment]
Working

**Comment by charankamarapu** [comment]
This issue is resolved - https://github.com/keploy/samples-java
