### ISSUE TITLE
[feature]: skip the empty curl field for the yaml docs

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#960]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Currently, we get the curl requests in the yaml documents for recorded test cases of user APIs.
- The curls are empty for the mongo mocks.
- The "curl" should not be present if its value is an empty string.

### Why should this be worked on?

This would make the yaml documents more shorter and accurate. And there can be a protocol which is not supported by curl.

### Repository

keploy

**Comment by nikzayn** [comment]
I will take this up.

/assign
