### ISSUE TITLE
[bug]: github action fails on go build

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently we are facing this problem more frequently that go build in the PRs is failing as given below . This needs to be fixed.
<img width="1084" alt="Screenshot 2023-10-06 at 1 27 31 AM" src="https://github.com/keploy/keploy/assets/72094895/06984298-7e74-4949-8184-fa00da43ca93">

### Steps to reproduce

1. Open a PR

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by EraKin575** [comment]
I would like to work on this issue

**Comment by nehagup** [comment]
@EraKin575 sure you can make a PR! :)

**Comment by AkashKumar7902** [comment]
what is the size of your self hosted action runner machine ?

**Comment by charankamarapu** [comment]
Hey @AkashKumar7902 I have actually removed the self-hosted github actions as they are not used anymore . So we can close this task but you can attempt this task https://github.com/keploy/keploy/issues/986 which is also related to current task.
