### ISSUE TITLE
[docs]: Update Folder Path in  Setup application of Express-Mongo

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#965]
### What do you want to add to the docs? (please state reasons if any)

Here `https://docs.keploy.io/docs/quickstart/samples-nodejs/`  in the Setup Application 

Instead of moving to `express-mongo` folder We have to move to the `express-mongoose` folder.

So the command should be changed. Otherwise, it will cause error.

### Where is this stated?

It's stated to move to the `express-mongo folder` but currently the Repo ` https://github.com/keploy/samples-typescript` doesn't have any express-mongo folder. 

![image](https://github.com/keploy/keploy/assets/109217591/5e5151e1-e476-4791-b025-679d1dacc8fd)

And I would like to Work on this.

### Repository

docs

**Comment by rohitkbc** [comment]
I would like to work on this issue. Can you please assign it to me? 😊

**Comment by Arindam200** [comment]
Hey @rohitkbc, As mentioned in the Issue, I will be Working on this Issue. Can you please check the other issues?

**Comment by rohitkbc** [comment]
Sure @Arindam200 😊, I missed out your comment to work on this issue. ✌️
