### ISSUE TITLE
[docs]: update the duplicate title tags

### ISSUE THREAD

**Issue by Shashwat79802** [keploy/keploy#966]
### What do you want to add to the docs?

Example:
v1 - https://github.com/keploy/docs/blob/main/versioned_docs/version-1.0.0/hacktoberfest/code-contribution.md?plain=1
v2 - https://github.com/keploy/docs/blob/main/versioned_docs/version-2.0.0/hacktoberfest/code-contribution.md?plain=1

In the examples given above, the **title** tags in both the pages above have the same data, update the data of all the **title** tags of **Keploy v1 docs** with duplicate values.

### Why is it necessary?

Duplicate <title> tags make it difficult for search engines to determine which of a website's pages is relevant for a specific search query, and which one should be prioritized in search results.

### Repository

docs

**Comment by ayush572** [comment]
Hi @Shashwat79802! I'll like to take up this issue. Can you assign it please?

**Comment by Ritish134** [comment]
Created a pull request for the same : updated the title for version 1 and 2, fixes #966

**Comment by Sonichigo** [comment]
Hi @Ritish134 ! The Titles needs to be updated only for the Version 1 in every page and is not limited to the hacktoberfest guide!

**Comment by officialasishkumar** [comment]
Hey @Shashwat79802, Is this issue still needs to be worked on?

**Comment by nehagup** [comment]
@officialasishkumar yes the title tags are still same, need to be different.
