### ISSUE TITLE
[docs]: Typo in Sample node.js Application setup

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#968]
### What do you want to add to the docs? (please state reasons if any)

In `https://docs.keploy.io/docs/quickstart/samples-nodejs/` While creating MongoDB instances it's mentioned to change that line no 41 of `db/connection.js` It should be changed to line no 4. 

![image](https://github.com/keploy/keploy/assets/109217591/daa1cfff-9254-4470-8d6c-22d986690e68)

### Where is this stated?

 In `db/connection.js`  there's no line 41 in the code,

![image](https://github.com/keploy/keploy/assets/109217591/c536eddb-5971-49c4-91e7-c348c983a42b)

I would like to fix this

### Repository

docs

**Comment by AkashKumar7902** [comment]
Hey @Arindam200 
I just noticed the last statement. I am really sorry for my oversight. you could still open a PR and I would close mine if you would like.

**Comment by Sonichigo** [comment]
Hi @Arindam200 would you still be taking this issue up ?

**Comment by Arindam200** [comment]
Yes! 

I would like to work on this issue!
