### ISSUE TITLE
[bug]: fix broken urls

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Due to changed in endpoint hosting of docs website there are many broken links introduced. For example on https://keploy.io/docs/1.0.0/go/quickstart/ half of the links are broken. 

https://keploy.io/docs/1.0.0/concepts/what-are-keploy-features/ has broken links too!

https://keploy.io/docs/server/ too! 
 
This task is to fix all the broken links on docs website. 

### Steps to reproduce

Try all links on https://keploy.io/docs/1.0.0/go/quickstart/ 

### Environment

Production

### Version

Cloud

### Repository

docs

**Comment by Deveesh-Shetty** [comment]
The Issue should be in this repo, right? (Keploy Docs)[https://github.com/keploy/docs]

**Comment by PranshuSrivastava** [comment]
Hey @jailbreakerVC, thanks for opening a PR for this issue, but you should make sure that you get yourself assigned the issue first before working on the PR, so that everyone has clarity about who is working on this issue.

**Comment by jailbreakerVC** [comment]
> Hey @jailbreakerVC, thanks for opening a PR for this issue, but you should make sure that you get yourself assigned the issue first before working on the PR, so that everyone has clarity about who is working on this issue.

Alright, sorry for that. Can this issue be assigned to me?

**Comment by JavaGirish** [comment]
Hey @jailbreakerVC just wanted to check are you working on this issue...

**Comment by jailbreakerVC** [comment]
> Hey @jailbreakerVC just wanted to check are you working on this issue...

I have created a PR for the same
