### ISSUE TITLE
[docs]: add documentation for the new feature to name testcases

### ISSUE THREAD

**Issue by AkashKumar7902** [keploy/keploy#976]
### What do you want to add to the docs? (please state reasons if any)

A new feature has been added by which one can add a header field to their request to name testcases. refer issue #880 for more details. 

We need to add documentation for this new feature.
 

### Repository

docs

**Comment by AkashKumar7902** [comment]
@nehagup In which section of the docs, should i add ? I am thinking of adding it in the footnote of each installation page.

**Comment by nehagup** [comment]
@AkashKumar7902 great initiative! 

I think we need to add a "Running Keploy" guide to https://keploy.io/docs/server/  - in parallel to Explanation, Resources. Under that dropdown you can add a page that says Rename Testcases and add a crisp documentation on that page. 

WDYT?

**Comment by AkashKumar7902** [comment]
@nehagup seems like a good idea to me. We could use this section to add documentation for config file as well .
