### ISSUE TITLE
[bug]: `tcp_v4_connect` in tracefs: creating probe entry on tracefs: error opening 

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we try to run keploy on kernel version <5.15 , we get the below error:

`2023/10/09 10:36:36 🐰 Keploy:%!(EXTRA string=opening tcp_v4_connect kretprobe: %s, *fmt.wrapError=creating trace event 'tcp_v4_connect' in tracefs: creating probe entry on tracefs: error opening '/sys/kernel/debug/tracing/kprobe_events': open /sys/kernel/debug/tracing/kprobe_events: no such file or directory)`

### Steps to reproduce

1. Make sure you're on kernel version lower than 5.15.
2. Try to run keploy locally.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by gouravkrosx** [comment]
Using the below command the issue was solved.
`sudo mount -t debugfs debugfs /sys/kernel/debug`

**Comment by omgupta1608** [comment]
@gouravkrosx I am facing this error on mac `Ventura 13.5.2`.

On running 
```
sudo mount -t debugfs debugfs /sys/kernel/debug
```
I get this:
```
mount: /sys/kernel/debug: invalid file system.
```

**Comment by gouravkrosx** [comment]
If you're using colima then you can try:
1. `colima ssh`
2. `sudo mount -t debugfs debugfs /sys/kernel/debug`.

**Comment by nehagup** [comment]
@omgupta1608 did this get resolved after using Colima and running above instructions?

**Comment by gouravkrosx** [comment]
@omgupta1608 You're correct about that, this is for Linux file system only. You can try [this](https://github.com/keploy/keploy/issues/984#issuecomment-1871927103) if it fails again, please let us know.

**Comment by omgupta1608** [comment]
@gouravkrosx @nehagup 
Nope. That didn't work either. Will see if I can get back to you with the logs (it's been a while). Unfortunately, had to move away from keploy for now. Might reconsider using it in the future. Liked the product, though some stability issues still needs fixing.

**Comment by gouravkrosx** [comment]
@omgupta1608 
I appreciate your feedback, and it's unfortunate to hear about the challenges you faced with Keploy. I understand your decision to move away for now. However, I'd like to mention that there have been updates, including Docker for Mac support, which might address some of the issues you encountered. Feel free to reconsider Keploy in the future.

**Comment by nehagup** [comment]
Hi @omgupta1608 I'm closing this issue for now since we're not able to replicate this on our end, please feel free to re-open this in future. Happy to jump on a call to deep dive in detail.

**Comment by gouravkrosx** [comment]
Hey @Shivkant-Chauhan, Can you please share your **alias** of keploy. & please share the output of this command also `docker volume inspect debugfs`.
And if there is no volume named `debugfs`, please try to create one using `docker volume create --driver local --opt type=debugfs --opt device=debugfs debugfs` and try running keploy again.

**Comment by Shivkant-Chauhan** [comment]
my alias for `keploy` -- `keploy='sudo docker run --pull always --name keploy-v2 -p 16789:16789 --privileged --pid=host -it -v "$(pwd)":/files -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/bpf:/sys/fs/bpf -v /var/run/docker.sock:/var/run/docker.sock -v /Users/shivkantchauhan/.keploy-config:/root/.keploy-config -v /Users/shivkantchauhan/.keploy:/root/.keploy --rm ghcr.io/keploy/keploy'`

my output for `docker volume inspect debugfs`
```
[
    {
        "CreatedAt": "2024-02-02T11:18:17Z",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/debugfs/_data",
        "Name": "debugfs",
        "Options": {
            "device": "debugfs",
            "type": "debugfs"
        },
        "Scope": "local"
    }
]
```

I remember that I have created `debugfs` volume

**Comment by gouravkrosx** [comment]
@Shivkant-Chauhan We need more discussion around this bug as we are not able to reproduce at our end after following the above-provided solutions. You can reach out to me on the slack channel if you want.

**Comment by Shivkant-Chauhan** [comment]
yes, I am pinging you on Slack for the same. thanks!

**Comment by gouravkrosx** [comment]
@himanshu-wedensday what OS are you using?

**Comment by himanshu-wedensday** [comment]
MacOs Senoma
14.3.1

**Comment by gouravkrosx** [comment]
@himanshu-wedensday Are you still facing that issue or after changing the permissions, it is working?

**Comment by gouravkrosx** [comment]
Above suggested solutions are working hence closing this issue, if anyone comes up with this issue again, we can reopen it.
