### ISSUE TITLE
[docs]: remove `--rm` flag from the record and test-mode in the samples-go

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#987]
### What do you want to add to the docs? (please state reasons if any)

Remove the `--rm` flag mentioned in the Record and Test Mode command while using Docker or Colima in the samples-go repository.

https://github.com/keploy/samples-go/

### Repository

samples-go

**Comment by AkashKumar7902** [comment]
hey @sonichigo, Please assign me this issue

**Comment by VividhPandey003** [comment]
Hey could you please assign me this issue. Also wanted to know what are the prerequisites for this

**Comment by Sonichigo** [comment]
hey @VividhPandey003 ! Sure you can take it up! 

You need to remove `--rm` flag mentioned in the Record and Test Mode command while using Docker or Colima in the samples-go repository.

**Comment by VividhPandey003** [comment]
Hey @Sonichigo just a small doubt. `--rm` flag needs to be removed from all the files right. As I can see there are three files where the changes need to be made.-
'mux-sql/README.md' , 'echo-sql/README.md' , 'gin-mongo/README.md'

**Comment by Sonichigo** [comment]
Yeah, you have to make changes in these three readme's !!

**Comment by VividhPandey003** [comment]
@Sonichigo Could you please review my PR regarding the required changes. Let me know if I misinterpreted something from my end. I'll fix it quickly. 
Thanks

**Comment by VividhPandey003** [comment]
Could you please add hacktoberfest-accepted tag to my Pull Request. 😊
