### ISSUE TITLE
[feature] : Create Sample-apps and integrate Keploy

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#992]
🛠️ Frameworks : -

- [ ] Java
- [ ] GoLang
- [ ] Javascript
- [ ] Python 

💻 Dependencies : - 

- [ ] DyanamoDB
- [ ] S3
- [ ] Azure Blob
- [ ] Redis
- [ ] MySQL
- [ ] Twilio

🚀 Extra's : - 

- [ ] SOAP
- [ ] GRPC
- [ ] REST
- [ ] GraphQL

Chose one of the stack from each to create a something new this Hacktoberfest!! We are looking for the Simple Apps which are using one or more than one dependencies.

**This issue will be open for all for throughout the Hacktoberfest Duration!!!**

Checklist before making a PR: - 

- [ ] Tested the code locally.
- [ ] Have signed the commits.
- [ ] Create the Readme to follow and run the application.

**Comment by Aayushi-Agrwal** [comment]
What kind of apps are we looking for? Also is this issue open to all?

**Comment by Sonichigo** [comment]
Yes, this issue is open to all! We are look for simple CRUD applications!

**Comment by Sonichigo** [comment]
> Hey @Sonichigo! I'm currently working on Javascript + Redis + REST. Is it okay if i replace Javascript with Typescript?

Yeah! It's completely okay

**Comment by rohitkbc** [comment]
Hi @Sonichigo 👋, I would like to work on GoLang + S3 + REST. Can I go ahead?

**Comment by nehagup** [comment]
@rohitkbc sure!

**Comment by rohitkbc** [comment]
@nehagup, Can you please review the PR?
