### ISSUE TITLE
[docs]: Wrong command to Capture test cases

### ISSUE THREAD

**Issue by Arindam200** [keploy/keploy#996]
### What do you want to add to the docs? (please state reasons if any)

To capture the test cases the correct command will be :

```shell
sudo -E env PATH=$PATH keploy record -c 'npm start src/app.js'
``` 

## Part 1
Currently To capture the test cases we are using the following command.

`sudo -E env PATH=$PATH Keploy record -c 'npm run src/app.js'`

But this is not the correct one! 

When installing the keploy binary we have set the alias as "keploy" but here it is Uppercased.
![image](https://github.com/keploy/keploy/assets/109217591/74100826-1f77-41d8-ad10-ee225cdb1498)

## Part 2
Also, we are using `npm run` command but is should be `npm start` as mentioned here:
![image](https://github.com/keploy/keploy/assets/109217591/6f7992a0-4942-4bc9-8d3f-76b849aff12b)

### Repository

docs

**Comment by AniketNS** [comment]
Hey @Arindam200, Can I work on this issue?

**Comment by nehagup** [comment]
@AniketNS please feel free to contribute

**Comment by AniketNS** [comment]
Sure @nehagup.

**Comment by OlibhiaGhosh** [comment]
If anyone is not working , Can I work on this?

**Comment by nehagup** [comment]
@AniketNS are you still working on this?

**Comment by AniketNS** [comment]
Yess @nehagup. Sorry for the delay. I'll be making PR ASAP.

**Comment by AniketNS** [comment]
Hey @Arindam200 can you please tell me where I should make the changes?

because I'm not able to find `sudo -E env PATH=$PATH Keploy record -c 'npm run src/app.js'` written in documents anywhere.

**Comment by officialasishkumar** [comment]
Hey @Arindam200, Looks like this issue is already been fixed by https://github.com/keploy/docs/pull/246 !

**Comment by Arindam200** [comment]
Closing this as it's Resolved by https://github.com/keploy/docs/pull/246
